### ISSUE TITLE
Possible Missing Files

### ISSUE THREAD

**Issue by mchinitz** [quantopian/zipline#1001]
In an earlier version of zipline at https://github.com/ericjohn/zipline, under Transforms, there was a module MovingAverageTransforms (filename = "mavg.py"), which does not appear to be included here. I am trying to learn how to use zipline with a tutorial which relies on this module. I tried downloading the missing source code, but the result is that python is unable to read the classes in transforms.util, which MovingAverage depends on. Is there a workaround using this version? Or is there a way to install the old version?

**Comment by richafrank** [comment]
What tutorial are you using? Can you use the current code and examples ([1] (https://github.com/quantopian/zipline/blob/11465d907d25f517b8f6b88eb6bcf26b4538270f/zipline/examples/olmar.py#L60-L60)) ([2] (https://github.com/quantopian/zipline/blob/283c959cc4bc51a90ee8cd9e805004cad1cc9406/zipline/examples/dual_moving_average.py#L48-L48)) instead?

If you do want to use that exact version, you could pip install zipline from that repo: 
`pip install -e git+git@github.com:ericjohn/zipline.git#egg=zipline-master`.

**Comment by FreddieV4** [comment]
Going to close this due to inactivity/no follow up. Feel free to open a new issue if you still need help.
