### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by chrism2671** [quantopian/zipline#1038]
Can we update the example code as per issue 908:

https://github.com/quantopian/zipline/issues/908

The code in the repository is old and broken, which is particularly confusing for new users as it is the introductory code for zipline. I am using the iPython version.

**Comment by richafrank** [comment]
Thanks @chrism2671.  It looks to me like the [relevant example] (https://github.com/quantopian/zipline/blob/328d449e6066ad7b5fd3aacea511510aa587c67a/zipline/examples/buy_and_hold.py#L44) was already updated to match the suggested code in https://github.com/quantopian/zipline/issues/908#issuecomment-164013074.  Could you be more specific about what's missing or isn't working for you?

**Comment by chrism2671** [comment]
Apologies, I didn't mention. I stumbled into this issue on the iPython notebook:

https://github.com/quantopian/zipline/blob/328d449e6066ad7b5fd3aacea511510aa587c67a/zipline/examples/buyapple.ipynb

**Comment by richafrank** [comment]
Should be fixed by https://github.com/quantopian/zipline/commit/2976280a7674a477b3ab9524846dfcb34d42e958

**Comment by chrism2671** [comment]
Thank you!
