### ISSUE TITLE
zipline for python 3.5 (win32)

### ISSUE THREAD

**Issue by hyunhojo** [quantopian/zipline#1056]
Dear Zipline Maintainers,
Before I tell you about my issue, let me describe my environment:

# Environment
* Operating System: 
Windows 7 (64 bit)

* Python Version: 
Python 3.5.1:: Anaconda 2.5.0 (32-bit)

* Python Bitness: 
31

* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
conda install -c Quantopian zipline

* Python packages: 
I installed Anaconda 2.5.0 using Anaconda3-2.5.0-Windows-x86.exe and I updated packages using 
'conda update -all' command.
Current version of packages are as below:

# packages in environment at C:\Anaconda3:
#
alabaster                 0.7.7                    py35_0  
anaconda                  2.5.0               np110py35_0  
anaconda-client           1.3.1                    py35_0  
argcomplete               1.0.0                    py35_1  
astropy                   1.1.2               np110py35_0  
babel                     2.2.0                    py35_0  
beautifulsoup4            4.4.1                    py35_0  
bitarray                  0.8.1                    py35_1  
blaze-core                0.9.0                    py35_0  
bokeh                     0.11.1                   py35_0  
boto                      2.39.0                   py35_0  
bottleneck                1.0.0               np110py35_0  
bzip2                     1.0.6                    vc14_2  [vc14]
cffi                      1.5.2                    py35_0  
clyent                    1.2.1                    py35_0  
colorama                  0.3.6                    py35_0  
comtypes                  1.1.2                    py35_0  
conda                     4.0.4                    py35_0  
conda-build               1.19.2                   py35_0  
conda-env                 2.4.5                    py35_0  
configobj                 5.0.6                    py35_0  
console_shortcut          0.1.1                    py35_1  
cryptography              1.0.2                    py35_0  
curl                      7.45.0                   vc14_1  [vc14]
cycler                    0.10.0                   py35_0  
cython                    0.23.4                   py35_0  
cytoolz                   0.7.5                    py35_0  
datashape                 0.5.1                    py35_0  
decorator                 4.0.9                    py35_0  
docutils                  0.12                     py35_1  
dynd-python               0.7.1                    py35_0  
et_xmlfile                1.0.1                    py35_0  
fastcache                 1.0.2                    py35_0  
flask                     0.10.1                   py35_1  
freetype                  2.5.5                    vc14_0  [vc14]
futures                   3.0.3                    py35_0  
greenlet                  0.4.9                    py35_0  
h5py                      2.5.0               np110py35_4  
hdf5                      1.8.15.1                 vc14_4  [vc14]
idna                      2.0                      py35_0  
ipykernel                 4.3.1                    py35_0  
ipython                   4.1.2                    py35_0  
ipython-notebook          4.0.4                    py35_3  
ipython-qtconsole         4.0.1                    py35_4  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                4.1.1                    py35_0  
itsdangerous              0.24                     py35_0  
jdcal                     1.2                      py35_0  
jedi                      0.9.0                    py35_0  
jinja2                    2.8                      py35_0  
jpeg                      8d                       vc14_0  [vc14]
jsonschema                2.4.0                    py35_0  
jupyter                   1.0.0                    py35_1  
jupyter_client            4.2.1                    py35_0  
jupyter_console           4.1.1                    py35_0  
jupyter_core              4.1.0                    py35_0  
launcher                  1.0.0                         4  
libdynd                   0.7.1                         0  
libpng                    1.6.17                   vc14_1  [vc14]
libsodium                 1.0.3                         0  
libtiff                   4.0.6                    vc14_1  [vc14]
llvmlite                  0.9.0                    py35_0  
lxml                      3.5.0                    py35_0  
markupsafe                0.23                     py35_0  
matplotlib                1.5.1               np110py35_0  
menuinst                  1.3.2                    py35_0  
mistune                   0.7.2                    py35_0  
mkl                       11.3.1                        0  
mkl-rt                    11.1                         p0  
mkl-service               1.1.2                    py35_0  
mpmath                    0.19                     py35_0  
msvc_runtime              1.0.1                    vc14_0  [vc14]
multipledispatch          0.4.8                    py35_0  
nbconvert                 4.1.0                    py35_0  
nbformat                  4.0.1                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2                      py35_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py35_0  
notebook                  4.1.0                    py35_1  
numba                     0.24.0              np110py35_0  
numexpr                   2.4.6               np110py35_1  
numpy                     1.10.1                  py35_p0  [mkl]
odo                       0.4.2                    py35_0  
openpyxl                  2.3.2                    py35_0  
pandas                    0.18.0              np110py35_0  
patch                     2.5.9                         1  
path.py                   8.1.2                    py35_1  
patsy                     0.4.0               np110py35_0  
pep8                      1.7.0                    py35_0  
pickleshare               0.5                      py35_0  
pillow                    3.1.1                    py35_0  
pip                       8.1.0                    py35_0  
ply                       3.8                      py35_0  
psutil                    4.1.0                    py35_0  
py                        1.4.31                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.1                    py35_0  
pycparser                 2.14                     py35_0  
pycrypto                  2.6.1                    py35_3  
pyflakes                  1.1.0                    py35_0  
pygments                  2.1.1                    py35_0  
pyopenssl                 0.15.1                   py35_1  
pyparsing                 2.0.3                    py35_0  
pyqt                      4.11.4                   py35_5  
pyreadline                2.1                      py35_0  
pytables                  3.2.2               np110py35_1  
pytest                    2.8.5                    py35_0  
python                    3.5.1                         2  
python-dateutil           2.5.0                    py35_0  
pytz                      2016.1                   py35_0  
pywin32                   220                      py35_1  
pyyaml                    3.11                     py35_3  
pyzmq                     15.2.0                   py35_0  
qt                        4.8.7                    vc14_6  [vc14]
qtconsole                 4.1.1                    py35_1  
requests                  2.9.1                    py35_0  
rope                      0.9.4                    py35_1  
scikit-image              0.12.3              np110py35_0  
scikit-learn              0.17.1              np110py35_0  
scipy                     0.16.0             np110py35_p0  [mkl]
setuptools                20.2.2                   py35_0  
simplegeneric             0.8.1                    py35_0  
sip                       4.16.9                   py35_2  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.1                    py35_0  
sphinx                    1.3.5                    py35_0  
sphinx_rtd_theme          0.1.9                    py35_0  
spyder                    2.3.8                    py35_1  
spyder-app                2.3.8                    py35_0  
sqlalchemy                1.0.12                   py35_0  
statsmodels               0.6.1               np110py35_0  
sympy                     1.0                      py35_0  
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.7.4                    py35_0  
tornado                   4.3                      py35_0  
traitlets                 4.1.0                    py35_0  
unicodecsv                0.14.1                   py35_0  
werkzeug                  0.11.4                   py35_0  
wheel                     0.29.0                   py35_0  
xlrd                      0.9.4                    py35_0  
xlsxwriter                0.8.4                    py35_0  
xlwings                   0.7.0                    py35_0  
xlwt                      1.0.0                    py35_0  
zlib                      1.2.8                    vc14_2  [vc14]

# Description of Issue
I cannot install the zipline using conda command. 

Sincerely,
Hyunho

**Comment by llllllllll** [comment]
Zipline does not yet support python 3.5 and we do not yet have windows packages built for conda. We are working on getting the windows packages out but right now they will only be for 2.7 and 3.4

**Comment by richafrank** [comment]
Same as https://github.com/quantopian/zipline/issues/1004 ?

**Comment by hyunhojo** [comment]
Thanks, 
I will refer below link.
https://github.com/quantopian/zipline/issues/650#issuecomment-167050802
