### ISSUE TITLE
history() can not get open and close data

### ISSUE THREAD

**Issue by nanzeng** [quantopian/zipline#1059]
Dear Zipline Maintainers,

I tried to get open and close data from history(), however, the result is NaN.
# Environment
- Operating System: Linux  4.3.3-3-ARCH  x86_64 GNU/Linux
- Python Version: Python 3.5.1
- Python Bitness: 64
- How did you install Zipline: pip
- Python packages: 
  bcolz==0.12.1
  Bottleneck==1.0.0
  click==6.3
  contextlib2==0.5.1
  cycler==0.10.0
  cyordereddict==1.0.0
  Cython==0.23.4
  dbf==0.96.5
  decorator==4.0.9
  funcsigs==0.4
  html2text==2015.11.4
  IbPy==0
  idlex==1.12
  iotop==0.6
  ipykernel==4.3.1
  ipyparallel==4.0.2
  ipython==4.1.2
  ipython-genutils==0.1.0
  ipywidgets==4.1.1
  jedi==0.9.0
  Jinja2==2.8
  jsonschema==2.5.1
  jupyter==1.0.0
  jupyter-client==4.2.2
  jupyter-console==4.0.3
  jupyter-core==4.1.0
  Logbook==0.12.5
  louis==2.6.5
  MarkupSafe==0.23
  matplotlib==1.5.0
  mistune==0.7.1
  mock==1.3.0
  nbconvert==4.1.0
  nbformat==4.0.1
  networkx==1.11
  notebook==4.0.6
  numexpr==2.5
  numpy==1.10.4
  packaging==16.5
  pandas==0.18.0
  pandas-datareader==0.2.1
  path.py==8.1.2
  patsy==0.4.1
  pbr==1.8.1
  pexpect==4.0.1
  pickleshare==0.6
  ply==3.8
  ptyprocess==0.5.1
  PyAlgoTrade==0.17
  pyfolio==0.4.0
  Pygments==2.0.2
  pygobject==3.18.2
  pymssql==2.1.2
  pyodbc==3.0.10
  pyparsing==2.1.0
  python-dateutil==2.5.0
  pytz==2016.1
  pyxdg==0.25
  pyzmq==15.2.0
  qtconsole==4.1.1
  queuelib==1.4.2
  requests==2.9.1
  requests-file==1.4
  rpy2==2.7.7
  scikit-learn==0.17
  scipy==0.17.0
  seaborn==0.6.0
  shadowsocks==2.8.2
  simplegeneric==0.8.1
  six==1.10.0
  spyder==2.3.8
  SQLAlchemy==1.0.12
  statsmodels==0.6.1
  TA-Lib==0.4.9
  team==1.0
  terminado==0.5
  toolz==0.7.4
  tornado==4.3
  traitlets==4.2.1
  Unidecode==0.4.18
  zipline==0.8.4

Now that you know a little about me, let me tell you about the issue I am
having:

While using history under handle_data, I cannot get open and close data:
- What did you expect to happen?

I expect to get open and close data
- What happened instead?

the result I get is NaN

Here is how you can reproduce this issue on your machine:
## Reproduction Steps
1. def handle_data(self, data):
        print(history(10, '1d', 'open_price'))
        print(history(10, '1d', 'close_price'))

...
## What steps have you taken to resolve this already?

Bug report #374 had the same issue. There is no new update on how to solve this problem. I have tried to add_history(10, '1d', 'open_close') in the initialize() function but the result is the same. By the way, I am using daily data downloaded from yahoo.

...

Sincerely,
Nan Zeng

**Comment by nanzeng** [comment]
The problem is solved by adding open and close to history_container.py
[history.txt](https://github.com/quantopian/zipline/files/179000/history.txt)

**Comment by llllllllll** [comment]
Thank you for this report, sorry it took so long to get back to you. I think the patch you proposed is correct. A workaround until this is fixed would be to rename your panel's major axis to use the names `open_price` and `close_price`. This can be done like:

```python
yahoo_data = load_bars_from_yahoo(...).rename(major_axis={'open': 'open_price', 'close': 'close_price'})
```

**Comment by FreddieV4** [comment]
Hi there. I'm going to close this issue as we no longer use `history()` and make calls to `data.history()`. `load_bars_from_yahoo()` is also deprecated 🙂
