### ISSUE TITLE
Open source set_universe feature from quantopian.com

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#109]
quantopian.com provides a `set_universe` function that allows an algorithm to select stocks based on a criterion, e.g. percentile range of dollar volume rankings.

Example algorithm, https://www.quantopian.com/posts/a-very-basic-set-universe-example-to-refer-to-with-a-zipline-issue

The majority of the code that provides `set_universe` is currently within the internal/closed code that runs backtests on Quantopian. (With exception of the `supplemental_data` object within batch transforms, which handles an edge case of `set_universe`)

Besides providing the modules that load the data for a universe, there will need to be some universe "creation" tools developed for standalone Zipline.
i.e. if the dollar volume rankings were to be the universe open sourced, there will need to be a corresponding way to create a local database/file that contains the rankings.

**Comment by ssanderson** [comment]
https://github.com/quantopian/zipline/pull/584 will provide tools for universe creation via Filters.  We need to update Zipline's concept of a DataSource to support Dynamic Universes though.

**Comment by llllllllll** [comment]
unneeded after q2.0
