### ISSUE TITLE
Index out of bounds for history on European equities

### ISSUE THREAD

**Issue by frawgie** [quantopian/zipline#1097]
Operating System: Darwin 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

Python version: Python 2.7.11
Python bitness: 64
Installed Zipline via virtualenv & pip. 
Installed packages: see attached requirements.txt
[requirements.txt](https://github.com/quantopian/zipline/files/198009/requirements.txt)
# Description of Issue

When using the 'history' function on equities from e.g. OMX Stockholm you get index out of bounds instead of the history result.
## Reproduction Steps

```

%%zipline --start 2000-1-1 --end 2014-1-1 --symbols RATO-A.ST -o perf_ipython

from zipline.api import symbol, order, record, history

def initialize(context):
    pass

def handle_data(context, data):
    history(100, '1d', 'price')
    order(symbol('RATO-A.ST'), 10)
    record(AAPL=data[symbol('RATO-A.ST')].price)
```
## What steps have you taken to resolve this already?

Nothing so far except reproducing it on two different computers (both on OSX).
# Anything else?

...

Sincerely,
Jonas Ericsson

**Comment by FreddieV4** [comment]
Hi @frawgie if you try installing a newer version of zipline, e.g. `1.0.2` via Anaconda or `1.1.0` via zipline master, do you still run into this issue?

If you try to use a newer version, keep in mind there have been API changes since then so your algo would now look like:

```
%%zipline --start 2000-1-1 --end 2014-1-1 -o perf_ipython

from zipline.api import symbol, order, record

def initialize(context):
    pass

def handle_data(context, data):
    data.history(100, '1d', 'price')
    order(symbol('RATO-A.ST'), 10)
    record(symbol('RATO-A.ST'), 'price')
```

**Comment by ernestoeperez88** [comment]
I'm gonna go ahead and close this issue. Please feel free to reopen at any time.
