### ISSUE TITLE
Install Error 

### ISSUE THREAD

**Issue by Mikedoh89** [quantopian/zipline#1099]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Operating System: Windows
- Python Version: 2.7
- Python Bitness:  
- How did you install Zipline: conda
- Python packages: 

I am getting an error on the install. 

It says:

Fetching package metadata:........Error: Could not find URL: https://github.com/blampe/IbPy.git/win-64/

I am useing the insall -c Quantopian zipline method

The link it cannot find it a Interactive Brokers library, I am not sure why it is causing Zipline to have a problem. 

Thanks, 
Mike

**Comment by llllllllll** [comment]
Can you post the exact command that you used to try installing zipline? We do not have a dependency on IbPy so I think this may be an issue with another package.

**Comment by Mikedoh89** [comment]
conda install -c Quantopian zipline 

I think the problem may be the install is calling a custom url channel in my .condarc file but I am not sure how to remove it.

**Comment by llllllllll** [comment]
Hmm, Can you post the .condarc? I am almost certain that is the issue because we do not reference that package in our conda recipe.

**Comment by Mikedoh89** [comment]
It is a text file that reads:

binstar_upload: true
channels:
- http://repo.continuum.io/pkgs/free
- http://repo.continuum.io/pkgs/pro
- https://conda.binstar.org/numba

**Comment by llllllllll** [comment]
can you temporarily move that file to something like `.condarc.bak` and then try installing zipline?

**Comment by FreddieV4** [comment]
@Mikedoh89 did you manage to get this working?

**Comment by FreddieV4** [comment]
Going to close this due to inactivity/no follow up. Feel free to open a new issue if you still need helo
