### ISSUE TITLE
Data source that uses a local hdf5 file

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#110]
Analogous to https://github.com/quantopian/zipline/issues/108, provide a wrapper for using a local hdf5 file(s) as a data source.

**Comment by llllllllll** [comment]
@ehebert has this been addressed?

**Comment by ehebert** [comment]
It has not, but we could make a wrapper for `BcolzDailyBarWriter` which reformats an hdf5 file to bcolz. (which is a quick `ctable.fromhdf5(table_path).copy(rootdir=output_path)`.

With incoming changes on lazy-mainline branch the backtest data (not just pipeline) will be sourced from files created by `BcolzDailyBarWriter` and `BcolzMinuteBarWriter` classes.

**Comment by llllllllll** [comment]
I think we have settled on bcolz as the internal format for zipline. With the new data bundle changes we also support the case of caching yahoo data instead of downloading on each run.
