### ISSUE TITLE
'BarData' object has no attribute 'history'

### ISSUE THREAD

**Issue by inakie** [quantopian/zipline#1145]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`) OSX
* Python Version: `$ python --version` Python 2.7.11
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'` 64
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`) pip
* Python packages: `$ pip freeze` or `$ conda list`

appnope==0.1.0
attrs==15.2.0
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
bcolz==1.0.0
Bottleneck==1.0.0
certifi==2016.2.28
cffi==1.5.2
click==6.6
contextlib2==0.5.1
cryptography==1.2.2
cssselect==0.9.1
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.24
decorator==4.0.9
docopt==0.6.2
enum34==1.1.2
functools32==3.2.3.post2
gnureadline==6.3.3
idna==2.0
ipaddress==1.0.16
ipykernel==4.3.1
ipython==4.1.2
ipython-genutils==0.1.0
ipywidgets==4.1.1
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.2.2
jupyter-console==4.1.1
jupyter-core==4.1.0
Logbook==0.12.5
lxml==3.5.0
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.2
nbconvert==4.1.0
nbformat==4.0.1
networkx==1.11
notebook==4.1.0
numexpr==2.5.2
numpy==1.11.0
pandas==0.18.0
pandas-datareader==0.2.1
path.py==8.1.2
patsy==0.4.1
pexpect==4.0.1
pickleshare==0.6
ptyprocess==0.5.1
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
Pygments==2.1.3
pyOpenSSL==0.15.1
pyparsing==2.1.1
python-dateutil==2.5.2
pytz==2016.3
pyzmq==15.2.0
qtconsole==4.2.0
queuelib==1.4.2
requests==2.9.1
requests-file==1.4
scikit-learn==0.17.1
scipy==0.17.0
Scrapy==1.0.5
service-identity==16.0.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
sklearn==0.0
smugpy==0.3.1
SQLAlchemy==1.0.12
statsmodels==0.6.1
terminado==0.6
toolz==0.7.4
tornado==4.3
traitlets==4.2.1
Twisted==15.5.0
vboxapi==1.0
w3lib==1.13.0
zipline==0.9.0
zope.interface==4.1.3

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I can't run some of the examples, because the method data.history() is not found

* What did you expect to happen?
* What happened instead?

```
File "./dual_moving_average.py", line 43, in handle_data  
    short_mavg = data.history(context.sym, 'price', 100, '1d').mean()  
AttributeError: 'BarData' object has no attribute 'history' 
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

```
cd zipline/examples
python dual_moving_average.py
```

## What steps have you taken to resolve this already?

...

# Anything else?

Keep up the great work!!
...

Thanks!
inaki

**Comment by richafrank** [comment]
Hi @inakie !

It sounds like you're running dual_moving_average.py taken from HEAD of master of the zipline repo (i.e. zipline almost-1.0.0), but using zipline 0.9.0.  On 0.9, `history` isn't available on the `data` object passed to `handle_data`.  Instead it's imported from `zipline.api`.  If you like, you can see the differences in the [API migration guide on our test drive environment] (https://testdrive.quantopian.com/quantopian2/migration#data-history) (will eventually be on quantopian.com and in the zipline release notes as well).

You should run an example that uses the API of the version of zipline you've installed.  If you uninstall 0.9, and pip install your git clone of the zipline repo, then you'll be on 1.0 everywhere.  Or you can run [the example from 0.9] (https://github.com/quantopian/zipline/blob/0.9.0/zipline/examples/dual_moving_average.py#L25-L48) using the zipline 0.9 you've already installed.

Hope that helps!
-Rich

**Comment by inakie** [comment]
Hi Rich!

That worked, thanks! I installed from git and now data.history() works.

```
pip uninstall zipline
pip install git+https://github.com/quantopian/zipline.git
```

Thanks!
Iñaki

**Comment by richafrank** [comment]
Great, glad to hear it!
