### ISSUE TITLE
Position's sid instance attribute should contain an int

### ISSUE THREAD

**Issue by anddam** [quantopian/zipline#1175]
While running simulations, the "sid" attribute of Position instance contains an Equity instance.
The same "sid" instance attribute of Asset (of which Equity is a subclass) returns an actual int.

This is confusing naming, either Position should be instantiated using the actual sid in the package or the name of the attribute should be changed to "security" or "equity" or "asset".

The behavior should be consistent throughout the package and "sid" shouldn't return two different types of objects.

See the content of position.sid and position.sid.sid that shows the difference in the following example:

``` python
def initialize(context):
    context.security = sid(24)
    schedule_function(my_handle, date_rules.every_day(), time_rules.market_close(hours=1))


def my_handle(context, data):
    order(context.security, 1)
    for position in context.portfolio.positions.values():
        print("""

        type(position): %s
        position.sid: %s
        type(position.sid): %s
        position.sid.sid: %s
        """
        % (type(position), position.sid, type(position.sid), position.sid.sid))
```

**Comment by llllllllll** [comment]
Thank you for pointing out the inconsistency here. We agree that this is confusing and have been trying to standardize on `sid` being the asset identifier which is an int and `asset`, `equity`, or `future` to mean the `Asset` object. I think the right thing to do here would be to deprecate `position.sid` and add a new `position.asset` instead.

**Comment by FreddieV4** [comment]
x-ref https://github.com/quantopian/zipline/pull/1757
