### ISSUE TITLE
1.0.0 Release Issues

### ISSUE THREAD

**Issue by ssanderson** [quantopian/zipline#1216]
- [x] `import zipline` triggers a warning from `pandas.io.data` (this fires in the CLI)
- [x] `run_algorithm` doesn't set up pipeline machinery.
  - [x] We need an example that uses pipeline that doubles as a regression test.
- [x] Zipline.api stub files not distributed with pip. (https://github.com/quantopian/zipline/issues/1205#issuecomment-220620153)
- [x] `zipline run` should suggest running `ingest` if no data is available.

**Comment by richafrank** [comment]
FWIW I believe the warning isn't new to 1.0.0 - this was true in 0.9 too.

**Comment by llllllllll** [comment]
I need to put a message in the "no data available for bundle on or before ..." message saying, "Maybe you need to download the data" so that users know what to do to fix the problem.

**Comment by llllllllll** [comment]
related to the pipeline example: #911

**Comment by llllllllll** [comment]
#1218
#1219
