### ISSUE TITLE
Add unit test covering intraday performance with AlgorithmSimulator

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#122]
Commit eb42d4bfbd474dc8a07913fde3f6411b2b00841d fixes a bug when
AlgorithmSimulator uses an emission_rate of 'minute'.

The test coverage for emission_rate only covered the use of emission_rate
directly in PerformanceTracker.

There should be a test that runs an AlgorithmSimulator with a 
'minute' emission_rate, so that the integration between PeformanceTracker
and AlgorithmSimulator in that mode is covered.

**Comment by llllllllll** [comment]
@ehebert does this code still need to be tested, I imagine it is fine now

**Comment by dmichalowicz** [comment]
Going to close as outdated.
