### ISSUE TITLE
1.0 Documentation Issues

### ISSUE THREAD

**Issue by fredfortier** [quantopian/zipline#1220]
I found at least these issues here: http://www.zipline.io/bundles.html#quantopian-quandl-wiki-mirror
- Invalid import: from zipline.bundles import register, yahoo_equities => from zipline.data.bundles import register, yahoo_equities
- Missing argument: zipline ingest my-yahoo-equities-bundle => zipline ingest -b my-yahoo-equities-bundle

Also, at least the api.pyi is not there when installing like this: pip install zipline==1.0 (as the release notes would suggest). It is there when installing from the master.

Nice release by the way!

**Comment by llllllllll** [comment]
Thank you for reporting this. I will update the docs right away. We will be releasing a 1.0.1 pretty soon with some small fixes from 1.0.0; getting the .pyi in the sdist is on that list. In the meantime, the .pyi is included in the conda release.

**Comment by llllllllll** [comment]
https://github.com/quantopian/zipline/commit/96ec1fd639cf8310ffe978af441e8053cc796237

**Comment by FreddieV4** [comment]
Looks like this was fixed. Going to close this.
