### ISSUE TITLE
how to inject zipline(1.0.0) executable program into jupyter notebook.

### ISSUE THREAD

**Issue by lajor2010** [quantopian/zipline#1222]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Operating System: (Windows Version or `$ uname --all`)
- Python Version: `$ python --version`
- Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
- How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
- Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:
# Description of Issue
- What did you expect to happen?
- What happened instead?

Here is how you can reproduce this issue on your machine:
## Reproduction Steps

1.
2.
3.
...
## What steps have you taken to resolve this already?

...
# Anything else?

...

Sincerely,
`$ whoami`

**Comment by llllllllll** [comment]
Sorry, I don't really know what you are asking. Can you fill out the description of the issue so I can help with this?

**Comment by lajor2010** [comment]
i have been installed zipline (1.0.1)  and ipython notebook (also called jupyter notebook ) in my computer,  but now,  i want to write same  zipline code  in ipython notebook website,  and  then auto run with zipline in backgroup,  my problem is how to inject zipline into   ipython notebook so that ipython notebook can invoke zipline and send parameters.  thanks you !

**Comment by llllllllll** [comment]
Are you asking about the IPython magic? If so you need to run `%load_ext zipline` in an emty cell. This will make the `%zipline` magic available. If you are asking about importing the code, you need to make sure that you are running jupyter in the same virtual env that you installed zipline in. If this is the case you should be able to just run `import zipline`.

**Comment by llllllllll** [comment]
Should we close this in favor of: https://github.com/quantopian/zipline/issues/1225?

**Comment by FreddieV4** [comment]
Going to close this in favor of the issue Joe referenced above 🙂
