### ISSUE TITLE
find_packages() got an unexpected keyword argument 'include'

### ISSUE THREAD

**Issue by sluo1989** [quantopian/zipline#1278]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Operating System: OSX EI Captain, 10.11.5
- Python Version: 2.7 newly installed
- How did you install Zipline: pip and from source

Now that you know a little about me, let me tell you about the issue I am
having:
# Description of Issue

sudo python setup.py install 

Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    packages=find_packages(include=['zipline', 'zipline.*']),
TypeError: find_packages() got an unexpected keyword argument 'include'

I then try to update both pip and setuptools==3.3, and 23.0.0 as well
all gave me same results...

Sincerely,
Shikai

**Comment by richafrank** [comment]
Hi @sluo1989 ,

Seems like a setuptools version issue?  Locally, setup.py runs for me, and in the repl, I see:
```python
(Pdb) inspect.getargspec(find_packages)
ArgSpec(args=['cls', 'where', 'exclude', 'include'], varargs=None, keywords=None, defaults=('.', (), ('*',)))
(Pdb) find_packages.__module__
'setuptools'
(Pdb) import setuptools
(Pdb) setuptools.__version__
'21.0.0'
```

It also works for me, though, with setuptools 23.0.0.  I have
```python
>>> pip.__version__
'8.1.2'
```
What does the signature of `find_packages` look like for you, and where is it defined?

**Comment by sluo1989** [comment]
Hi Richard,

Thank you so much for your reply:-)
I guess although I have installed the latest version of setuptools package, python still points to the old version setuptools (system python's I guess), however I have set the default python as the one I installed. 

Do you know how to specify the specific setuptools' s version? Many thanks!

Best,
Shikai

**Comment by richafrank** [comment]
> Do you know how to specify the specific setuptools' s version?

My method of choice to install a particular version in my python env is:
```bash
pip install setuptools==<specific version>
```
or (upgrading to the latest):
```bash
pip install -U setuptools
```

but it sounds like you've already done that, so I'm not sure...

**Comment by benjaminsweetnam247** [comment]
couldn't get any of this to work myself but this worked 
curl https://bootstrap.pypa.io/ez_setup.py -o - | sudo python
I added the sudo before python due to a permissions error

**Comment by patrickcat** [comment]
Python 3.4.0 on Mac OS hit this error again.

**Comment by xexiyong** [comment]
> > Do you know how to specify the specific setuptools' s version?
> 
> My method of choice to install a particular version in my python env is:
> 
> ```shell
> pip install setuptools==<specific version>
> ```
> 
> or (upgrading to the latest):
> 
> ```shell
> pip install -U setuptools
> ```
> 
> but it sounds like you've already done that, so I'm not sure...

upgrade the setuptools is the right way for me, Thank you

**Comment by allantargino** [comment]
Upgrating setuptools worked for me too, thanks!

**Comment by ssanderson** [comment]
Looks like this has been resolved as a setuptools version issue.
