### ISSUE TITLE
Cannot import 'add_history'

### ISSUE THREAD

**Issue by jdgd1** [quantopian/zipline#1286]
Clean install of zipline 1.0.1 on windows. After install can import every other module from the example, but when I try to import "add_history" I get the error:

> ImportError: cannot import name 'add_history'

Browsed through the site-package but didn't see this file. Is still being used?

**Comment by richafrank** [comment]
Hi @jdgd1 , 

Nope, it's not used anymore.  Sorry for the confusion.  I just opened a [PR] (https://github.com/quantopian/zipline/pull/1287) which removes mentions of it from the documentation.

**Comment by richafrank** [comment]
Going to close this issue, now that the docs are updated.  Feel free to re-open if there's more to be done here!

**Comment by jmahhh** [comment]
Lots of examples still contain `add_history`. E.g. http://www.zipline.io/beginner-tutorial.html...

**Comment by richafrank** [comment]
Thanks @jmahhh - We've been updating zipline.io from github on each release, and we haven't released since that [PR] (#1287) was merged, so it's not on the docs site yet.  The [source] (https://github.com/quantopian/zipline/blob/master/docs/source/beginner-tutorial.rst#my-first-algorithm) should be fixed now though.  Sorry for the discrepancy.

**Comment by kejintao** [comment]
But is there any function that can replace add_history(), or say, if I want to take history price (formerly realized by add_history() and history() ), how can I achieve it?

**Comment by richafrank** [comment]
Hi @kejintao , `history` is still available and recommended, but you don't need to do any initial setup with `add_history` anymore.  Hopefully the [docs] (http://www.zipline.io/beginner-tutorial.html#access-to-previous-prices-using-history) are correct now...

**Comment by kejintao** [comment]
Thank you for your reply!

I used zipline==1.0.1 in windows and run the example provided by the docs
%---------------------------------
from zipline.api import order_target, record, symbol, history
import matplotlib.pyplot as plt
import numpy as np

def initialize(context):
    context.i = 0


def handle_data(context, data):
    # Skip first 300 days to get full windows
    context.i += 1
    if context.i < 300:
        return

    # Compute averages
    # history() has to be called with the same params
    # from above and returns a pandas dataframe.
    short_mavg = history(100, '1d', 'price').mean()
    long_mavg = history(300, '1d', 'price').mean()

    # Trading logic
    if short_mavg[0] > long_mavg[0]:
        # order_target orders as many shares as needed to
        # achieve the desired number of shares.
        order_target(symbol('AAPL'), 100)
    elif short_mavg[0] < long_mavg[0]:
        order_target(symbol('AAPL'), 0)

    # Save values for later inspection
    record(AAPL=data[symbol('AAPL')].price,
           short_mavg=short_mavg[0],
           long_mavg=long_mavg[0])

def analyze(context, perf):
    fig = plt.figure()
    ax1 = fig.add_subplot(211)
    perf.portfolio_value.plot(ax=ax1)
    ax1.set_ylabel('portfolio value in $')

    ax2 = fig.add_subplot(212)
    perf['AAPL'].plot(ax=ax2)
    perf[['short_mavg', 'long_mavg']].plot(ax=ax2)

    perf_trans = perf.ix[[t != [] for t in perf.transactions]]
    buys = perf_trans.ix[[t[0]['amount'] > 0 for t in perf_trans.transactions]]
    sells = perf_trans.ix[
        [t[0]['amount'] < 0 for t in perf_trans.transactions]]
    ax2.plot(buys.index, perf.short_mavg.ix[buys.index],
             '^', markersize=10, color='m')
    ax2.plot(sells.index, perf.short_mavg.ix[sells.index],
             'v', markersize=10, color='k')
    ax2.set_ylabel('price in $')
    plt.legend(loc=0)
    plt.show()
%-----------------------------
And it comes out an error like this:

Traceback (most recent call last):

  File "<ipython-input-6-9666198999fb>", line 1, in <module>
    runfile('D:/work/ocean team/project1/movingaverage1.0.1.py', wdir='D:/work/ocean team/project1')

  File "D:\software\anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "D:\software\anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/work/ocean team/project1/movingaverage1.0.1.py", line 8, in <module>
    from zipline.api import order_target, record, symbol, history

  File "D:\software\anaconda2\lib\site-packages\zipline\__init__.py", line 19, in <module>
    from . import data

ImportError: cannot import name data

**Comment by richafrank** [comment]
> ```ImportError: cannot import name data```

That usually means a failure to import a C extension because it was compiled against a different version of numpy from the one that's currently installed.  Assuming the numpy you have installed now is the one you want, I'd try reinstalling any libraries with C extensions, such as pandas, scipy, bottleneck, or zipline.

This seems separate from `add_history`, if you want to open a new issue.
