### ISSUE TITLE
Need unit tests that isolate tradesimulation module

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#129]
When implementing d21b500db6b508f5093dfeb61f8ed236845679c5 found it difficult to isolate the results emitted from `tradesimulation.AlgorithmSimulator` and check whether the extra `daily_perf` performance result was emitted.

We should consider adding unit tests for that module where events can be piped through without having to go through an entire algorithm.

**Comment by llllllllll** [comment]
@ehebert does this still need to be tested?

**Comment by llllllllll** [comment]
ping

**Comment by ehebert** [comment]
No longer relevant, since we the paradigm for `test_perf_tracker` has changed with Q2.0.
