### ISSUE TITLE
Issue Using Own Data with Zipline

### ISSUE THREAD

**Issue by jdgd1** [quantopian/zipline#1299]
Hello,

I am new to zipline and want to use my own data instead of the quantopian default data. I have a csv file with the dates and closing prices for a security I want to use for placing orders on that security. So, I put the data into a pandas dataframe

`data=pandas.read_csv("C:\\Users\\sbhadauria\\Documents\\SPYohlcv.csv")
`
and then I run the algorithm using
`zipline.run_algorithm(start=date(2015,5,2),end=date(2016,6,15),initialize=initialize,capital_base=1000000.00,handle_data=handle_data,data_frequency='daily',data=data)
`
described in the manual. However, every time I try this I get:

NameError: name 'zipline' is not defined

Thanks in advance!

**Comment by nathanwolfe** [comment]
You need to import the module using `import zipline` before you use it.

**Comment by FreddieV4** [comment]
@jdgd1 did you end up getting this to work?

**Comment by FreddieV4** [comment]
Hi @jdgd1 I'm going to close this issue as I believe @nathanwolfe has answered it. If you are still experiencing issues feel free to re-open this PR 🙂
