### ISSUE TITLE
write it first

### ISSUE THREAD

**Issue by shidinghong** [quantopian/zipline#1314]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by richafrank** [comment]
Hi @shidinghong !  Given only the title of this issue, it's hard for us to know what to do or fix.  If you could explain a bit more, we'd be happy to look into the question or share our thoughts.  I'm going to close this for now, but feel free to re-open with more information!
