### ISSUE TITLE
EventsLoaderUtilsTestCase takes a very long time

### ISSUE THREAD

**Issue by ssanderson** [quantopian/zipline#1321]
It's 16 seconds on my machine, because we're testing `normalize_timestamp_to_query_time` on every permutation of a length-7 array.  While it's admirable that we've got such complete coverage (and it's somewhat justified as a regression test against a pandas bug that only appears on certain interleavings of EST and DST), this means we're running a non-trivial function 10,000 times.  We probably only need on the order of 1 / 100th of those.

**Comment by ssanderson** [comment]
cc @mtydykov, what are your thoughts on taking a sub-sample of the 10,000 permutations?

**Comment by mtydykov** [comment]
Yeah; we could just manually map out the possible types of interleavings and have tests for each of those rather that generating all possible interleavings, many of which are redundant. We have a separate test for the EST/DST issue.

**Comment by ssanderson** [comment]
@mtydykov I was thinking of something much simpler.

The current implementation does:
```
combos = list(map(np.array, itertools.permutations(np.arange(len(
        boundary_dates + mixed_tz_dates)))))
```

I was thinking we could just take a uniform sample across these by doing something like:

```
    combos = list(map(np.array, itertools.permutations(np.arange(len(
        boundary_dates + mixed_tz_dates)))))[::100]
```

**Comment by mtydykov** [comment]
If we do that, what can we say about the types of cases we're testing?

**Comment by ssanderson** [comment]
> If we do that, what can we say about the types of cases we're testing?

`itertools.permutations` emits cases in lexicographical order, so this would give us a uniform mix of samples from the space of all possible interleavings

<details>
```
In [14]: list(permutations(range(7)))[::100]
Out[14]:
[(0, 1, 2, 3, 4, 5, 6),
 (0, 1, 6, 2, 5, 3, 4),
 (0, 2, 5, 3, 4, 1, 6),
 (0, 3, 4, 5, 1, 2, 6),
 (0, 4, 2, 5, 6, 1, 3),
 (0, 5, 1, 6, 3, 2, 4),
 (0, 6, 1, 2, 3, 4, 5),
 (0, 6, 5, 1, 4, 2, 3),
 (1, 0, 5, 3, 4, 2, 6),
 (1, 2, 4, 5, 0, 3, 6),
 (1, 3, 2, 5, 6, 0, 4),
 (1, 4, 0, 6, 3, 2, 5),
 (1, 5, 0, 2, 3, 4, 6),
 (1, 5, 6, 0, 4, 2, 3),
 (1, 6, 4, 2, 3, 0, 5),
 (2, 0, 4, 5, 1, 3, 6),
 (2, 1, 3, 5, 6, 0, 4),
 (2, 3, 0, 6, 4, 1, 5),
 (2, 4, 0, 1, 3, 5, 6),
 (2, 4, 6, 0, 5, 1, 3),
 (2, 5, 4, 1, 3, 0, 6),
 (2, 6, 3, 4, 0, 1, 5),
 (3, 0, 2, 5, 6, 1, 4),
 (3, 1, 0, 6, 4, 2, 5),
 (3, 2, 0, 1, 4, 5, 6),
 (3, 2, 6, 0, 5, 1, 4),
 (3, 4, 5, 1, 2, 0, 6),
 (3, 5, 2, 4, 0, 1, 6),
 (3, 6, 1, 4, 5, 0, 2),
 (4, 0, 1, 6, 3, 2, 5),
 (4, 1, 0, 2, 3, 5, 6),
 (4, 1, 6, 0, 5, 2, 3),
 (4, 2, 5, 1, 3, 0, 6),
 (4, 3, 2, 5, 0, 1, 6),
 (4, 5, 1, 3, 6, 0, 2),
 (4, 6, 0, 5, 2, 1, 3),
 (5, 0, 1, 2, 3, 4, 6),
 (5, 0, 6, 1, 4, 2, 3),
 (5, 1, 4, 2, 3, 0, 6),
 (5, 2, 3, 4, 0, 1, 6),
 (5, 3, 1, 4, 6, 0, 2),
 (5, 4, 0, 6, 2, 1, 3),
 (5, 6, 0, 1, 2, 3, 4),
 (5, 6, 4, 0, 3, 1, 2),
 (6, 0, 4, 2, 3, 1, 5),
 (6, 1, 3, 4, 0, 2, 5),
 (6, 2, 1, 4, 5, 0, 3),
 (6, 3, 0, 5, 2, 1, 4),
 (6, 4, 0, 1, 2, 3, 5),
 (6, 4, 5, 0, 3, 1, 2),
 (6, 5, 3, 1, 2, 0, 4)]
```

At the very least, this ensures that we test with every relevant date in the first position.  It also still generates a failing case if I remove the current pandas bug workarounds, for whatever that's worth.

**Comment by mtydykov** [comment]
Sure; I didn't word that too clearly. I guess what I meant was more like, what do we want to ensure with this test? If a uniform sample addresses that, then that works. If we want to make sure that we're checking certain combinations of dates, then we could use a method that more explicitly defines those. Or, we could do both.

**Comment by ssanderson** [comment]
> I guess what I meant was more like, what do we want to ensure with this test?

I'm not sure offhand what exactly the conditions are in which pandas triggers the off by one hour issue that we're working around (and which prompted the test to begin with), but it's a function of particular orderings/interleavings. 

I don't have materially less confidence in the correctness of this if we sample 50 interleavings vs trying all of them, especially given that the tests correctly fail if I remove the pandas workaround.

A very minimal alternative would be to so something like all 7 dates, all 7 dates reversed, and the dates in an ordering that causes the tests to fail if we remove the pandas workaround, so that we know we at least have a regression test.  (Though note that the sampling method outlined above hits two out of three of these: it doesn't happen to do a reversed case.)

**Comment by mtydykov** [comment]
Sorry, was looking at the wrong test case in the module! This makes much more sense now.

**Comment by ssanderson** [comment]
Fixed this by sampling from the full parameter space.
