### ISSUE TITLE
BUG: data.history with frequency of "1d" does not work for panel minute data 

### ISSUE THREAD

**Issue by mannau** [quantopian/zipline#1356]
With minute panel data now supported thanks to 9103516 I tried a simple example algo which fetches daily data through data.history.
However, this gives me the following error:

_data_portal.py, line 1094, in _get_daily_window_for_sids_
**AttributeError: 'DataPortal' object has no attribute '_equity_history_loader'**

Below the code to reproduce this issue:

``` python
from zipline import run_algorithm
from datetime import datetime
from pytz import UTC
from zipline.data.loader import load_from_yahoo
from zipline.api import order, symbol, record, sid
import pandas as pd
import numpy as np
from zipline.utils.calendars import get_calendar

# Taken from zipline/tests/test_algorithm
def create_minute_df_for_asset(trading_calendar,
                               start_dt,
                               end_dt,
                               interval=1,
                               start_val=1,
                               minute_blacklist=None):

    asset_minutes = trading_calendar.minutes_for_sessions_in_range(
        start_dt, end_dt
    )
    minutes_count = len(asset_minutes)
    minutes_arr = np.array(range(start_val, start_val + minutes_count))

    df = pd.DataFrame(
        {
            "open": minutes_arr + 1,
            "high": minutes_arr + 2,
            "low": minutes_arr - 1,
            "close": minutes_arr,
            "volume": 100 * minutes_arr,
        },
        index=asset_minutes,
    )

    if interval > 1:
        counter = 0
        while counter < len(minutes_arr):
            df[counter:(counter + interval - 1)] = 0
            counter += interval

    if minute_blacklist is not None:
        for minute in minute_blacklist:
            df.loc[minute] = 0

    return df

def initialize(context):
    context.security = sid(1)

def handle_data(context, data):
    price_history = data.history(context.security, "price", 200, "1d")
    order(sid(1), 10)

if __name__ == '__main__':
    start = datetime(2009, 1, 1, tzinfo=UTC)
    end = datetime(2016, 1, 1, tzinfo=UTC)
    capital_base = 100000

    trading_calendar = get_calendar('NYSE')
    dt_transform = trading_calendar.minute_to_session_label

    data = create_minute_df_for_asset(get_calendar('NYSE'), datetime(1999, 1, 4), datetime(2016, 7, 29))
    dfs = {1 : data }
    panel = pd.Panel(dfs)

    results = run_algorithm(
                  start,
                  end,
                  initialize,
                  capital_base,
                  handle_data=handle_data,
                  data=panel,
                  data_frequency='minute',
                  bundle=None,
                  default_extension=False,
                  )
```

Best,
Mario

**Comment by ssanderson** [comment]
@nathanwolfe this is happening because we're now only passing a minutely reader if the user is running minutely, so daily-frequency history calls don't work.  We either need to have the minutely panel reader able to do daily aggregation on the fly, or we need to take the input data, aggregate it once, and then wrap that up in a daily bar reader so that we can still service daily data queries.

**Comment by nathanwolfe** [comment]
@ssanderson: Which method do you think would be better? Personally I think aggregating it once would be better, since people using Panel data probably pass in data for the few equities that they are interested in, so there would be less loss in doing the aggregation for equities that don't have `data.history` called on them.

**Comment by ssanderson** [comment]
@nathanwolfe I think upfront aggregation makes sense here.

The real win from a performance perspective that we don't end up re-doing the aggregation over any given period more than once. (If we did it on the fly, then we'd end up calculating OHLCV aggregations on the same day over and over if you called history() once per day.)  The challenge is that we need to make sure we're using the user's calendar to bucket minutes into days.  The naive implementation of just taking the date of each day only works for NYSE.

cc @jbredeche I think to support this correctly we need a fast vectorized `minute_to_session_label` that can take an array/datetimeindex of minutes and convert to their session labels.

**Comment by nathanwolfe** [comment]
PR: https://github.com/quantopian/zipline/pull/1407

Just the fast `minute_to_session_label` for large DatetimeIndexes of minutes is done so far.
