### ISSUE TITLE
Cannot install Zipline on Windows 10 machine

### ISSUE THREAD

**Issue by cnimativ** [quantopian/zipline#1389]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10 64bit)
* Python Version: 3.5.2 :: Anaconda 4.1.1 (64-bit)
* Python Bitness: 64
* How did you install Zipline: conda, pip
* Python packages: 
```
# packages in environment at C:\Anaconda3:
#
_nb_ext_conf              0.2.0                    py35_0
alabaster                 0.7.8                    py35_0
anaconda                  4.1.1               np111py35_0
anaconda-client           1.4.0                    py35_0
anaconda-navigator        1.2.1                    py35_0
argcomplete               1.0.0                    py35_1
astropy                   1.2.1               np111py35_0
babel                     2.3.3                    py35_0
backports                 1.0                      py35_0
backtrader                1.8.3.93                  <pip>
beautifulsoup4            4.4.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.0                   py35_0
boto                      2.40.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.6.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.1.11                   py35_0
conda-build               1.21.3                   py35_0
conda-env                 2.5.2                    py35_0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.4                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.24                     py35_0
cytoolz                   0.8.0                    py35_0
dask                      0.10.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.1                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
IbPy                      0                         <pip>
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.3.1                    py35_0
ipyparallel               5.1.1                    py35_0
ipython                   4.2.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                4.1.1                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      8d                       vc14_0  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.3.0                    py35_0
jupyter_console           4.1.1                    py35_0
jupyter_core              4.1.0                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.11.0                   py35_0
locket                    0.2.0                    py35_1
Logbook                   1.0.0                     <pip>
lxml                      3.6.0                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.1               np111py35_0
menuinst                  1.4.1                    py35_0
mistune                   0.7.2                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
nb_anacondacloud          1.1.0                    py35_0
nb_conda                  1.1.0                    py35_0
nb_conda_kernels          1.0.3                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.0.1                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.1                    py35_0
numba                     0.26.0              np111py35_0
numexpr                   2.6.0               np111py35_0
numpy                     1.11.1                   py35_0
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2h                   vc14_0  [vc14]
pandas                    0.17.1                    <pip>
pandas                    0.18.1              np111py35_0
pandas-datareader         0.2.1                     <pip>
partd                     0.3.4                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.2                    py35_0
pillow                    3.2.0                    py35_1
pip                       8.1.2                    py35_0
ply                       3.8                      py35_0
psutil                    4.3.0                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.2.3                    py35_0
pygments                  2.1.3                    py35_0
pyopenssl                 0.16.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      4.11.4                   py35_6
pyreadline                2.1                      py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.4                   py35_0
pywin32                   220                      py35_1
pyyaml                    3.11                     py35_4
pyzmq                     15.2.0                   py35_0
qt                        4.8.7                    vc14_8  [vc14]
qtconsole                 4.2.1                    py35_0
qtpy                      1.0.2                    py35_0
requests                  2.10.0                   py35_0
requests-file             1.4                       <pip>
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.7                   py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.17.1              np111py35_1
setuptools                23.0.0                   py35_0
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.16.9                   py35_2
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.1                    py35_0
sphinx_rtd_theme          0.1.9                    py35_0
spyder                    2.3.9                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.3                      py35_1
traitlets                 4.2.1                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
werkzeug                  0.11.10                  py35_0
wheel                     0.29.0                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.2                    py35_0
xlwings                   0.7.2                    py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

Tried to install zipline using conda, failed.  Tried using pip. Failed as well but expected according to the Installation guide.

Here's the output from 'conda install -c Quantopian zipline'
```
C:\WINDOWS\system32>conda install -c Quantopian zipline
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - python 3.5*
  - zipline
Use "conda info <package>" to see the dependencies for each package.
```
Here's the selective output from 'pip install zipline' 
```
  Failed building wheel for zipline
  Running setup.py clean for zipline
  Running setup.py bdist_wheel for cyordereddict ... error
  Complete output from command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\HAN-CH~1\\AppData\\Local\\Temp\\pip-build-hhyd68sl\\cyordereddict\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\HAN-CH~1\AppData\Local\Temp\tmp1ozp8bzdpip-wheel- --python-tag cp35:
  ----------------------------------------
  Failed building wheel for cyordereddict
  Running setup.py clean for cyordereddict
  Running setup.py bdist_wheel for bcolz ... error
  Complete output from command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\HAN-CH~1\\AppData\\Local\\Temp\\pip-build-hhyd68sl\\bcolz\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\HAN-CH~1\AppData\Local\Temp\tmp5aslb9z_pip-wheel- --python-tag cp35:
  skipping 'bcolz\carray_ext.c' Cython extension (up-to-date)
  building 'bcolz.carray_ext' extension
  error: Unable to find vcvarsall.bat

  ----------------------------------------
  Failed building wheel for bcolz
  Running setup.py clean for bcolz
Failed to build zipline cyordereddict bcolz
Installing collected packages: cyordereddict, bcolz, sortedcontainers, intervaltree, cachetools, zipline
  Running setup.py install for cyordereddict ... error
    Complete output from command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\HAN-CH~1\\AppData\\Local\\Temp\\pip-build-hhyd68sl\\cyordereddict\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\HAN-CH~1\AppData\Local\Temp\pip-3igha0dg-record\install-record.txt --single-version-externally-managed --compile:
    building 'cyordereddict._cyordereddict' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\HAN-CH~1\\AppData\\Local\\Temp\\pip-build-hhyd68sl\\cyordereddict\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\HAN-CH~1\AppData\Local\Temp\pip-3igha0dg-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\HAN-CH~1\AppData\Local\Temp\pip-build-hhyd68sl\cyordereddict\
```

Sincerely,
HCL

**Comment by richafrank** [comment]
Hi @cnimativ !  We haven't tested zipline on, or built conda packages for, python 3.5 yet.  (See #1004.)  

Sorry for the trouble, but can you use a python 3.4 conda environment for now?  Or, PRs for 3.5 support also welcome!  I'm going to close this in favor of #1004.

**Comment by ftnpang** [comment]
Hi @richafrank, this is an old thread and this case was closed almost a year ago. But, I am still experiencing the same issue. The environment settings of my Anaconda is almost exactly as @cnimativ except that my Anaconda is 4.2.0. When I tried to install zipline via conda, I got exactly the same message. I searched for zipline (via channel quantopian) and it seems that zipline 1.1.1 was already released for 3.5.

Can you please advise?

**Comment by richafrank** [comment]
Hi @ftnpang , could you share the output of running `conda info`?

**Comment by ftnpang** [comment]
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Anaconda3-420  (writable)
    default environment : C:\Anaconda3-420
       envs directories : C:\Anaconda3-420\envs
          package cache : C:\Anaconda3-420\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

**Comment by ftnpang** [comment]
Hi @richafrank attached above please find the outputs.

**Comment by richafrank** [comment]
Thanks, and could you also send along the output of `conda list`?

**Comment by ftnpang** [comment]
Hi @richafrank, the followings are from `conda list`:

_license                  1.1                      py35_1  
_nb_ext_conf              0.3.0                    py35_0  
alabaster                 0.7.9                    py35_0  
anaconda                  4.2.0               np111py35_0  
anaconda-clean            1.0.0                    py35_0  
anaconda-client           1.5.1                    py35_0  
anaconda-navigator        1.3.1                    py35_0  
argcomplete               1.0.0                    py35_1  
astroid                   1.4.7                    py35_0  
astropy                   1.2.1               np111py35_0  
babel                     2.3.4                    py35_0  
backports                 1.0                      py35_0  
beautifulsoup4            4.5.1                    py35_0  
bitarray                  0.8.1                    py35_1  
blaze                     0.10.1                   py35_0  
bokeh                     0.12.2                   py35_0  
boto                      2.42.0                   py35_0  
bottleneck                1.1.0               np111py35_0  
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.7.0                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.6                      py35_0  
cloudpickle               0.2.1                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.7                    py35_0  
comtypes                  1.1.2                    py35_0  
conda                     4.2.9                    py35_0  
conda-build               2.0.2                    py35_0  
configobj                 5.0.6                    py35_0  
console_shortcut          0.1.1                    py35_1  
contextlib2               0.5.3                    py35_0  
cryptography              1.5                      py35_0  
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0  
cython                    0.24.1                   py35_0  
cytoolz                   0.8.0                    py35_0  
dask                      0.11.0                   py35_0  
datashape                 0.5.2                    py35_0  
decorator                 4.0.10                   py35_0  
dill                      0.2.5                    py35_0  
docutils                  0.12                     py35_2  
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.2                    py35_0  
et_xmlfile                1.0.1                    py35_0  
fastcache                 1.0.2                    py35_1  
filelock                  2.0.6                    py35_0  
flask                     0.11.1                   py35_0  
flask-cors                2.1.2                    py35_0  
freetype                  2.5.5                    vc14_1  [vc14]
get_terminal_size         1.0.0                    py35_0  
gevent                    1.1.2                    py35_0  
greenlet                  0.4.10                   py35_0  
h5py                      2.6.0               np111py35_2  
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1  
icu                       57.1                     vc14_0  [vc14]
idna                      2.1                      py35_0  
imagesize                 0.7.1                    py35_0  
ipykernel                 4.5.0                    py35_0  
ipython                   5.1.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                5.2.2                    py35_0  
itsdangerous              0.24                     py35_0  
jdcal                     1.2                      py35_1  
jedi                      0.9.0                    py35_1  
jinja2                    2.8                      py35_1  
jpeg                      8d                       vc14_2  [vc14]
jsonschema                2.5.1                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            4.4.0                    py35_0  
jupyter_console           5.0.0                    py35_0  
jupyter_core              4.2.0                    py35_0  
lazy-object-proxy         1.2.1                    py35_0  
libdynd                   0.7.2                         0  
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.13.0                   py35_0  
locket                    0.2.0                    py35_1  
lxml                      3.6.4                    py35_0  
markupsafe                0.23                     py35_2  
matplotlib                1.5.3               np111py35_0  
menuinst                  1.4.1                    py35_0  
mistune                   0.7.3                    py35_0  
mkl                       11.3.3                        1  
mkl-service               1.1.2                    py35_2  
mpmath                    0.19                     py35_1  
multipledispatch          0.4.8                    py35_0  
nb_anacondacloud          1.2.0                    py35_0  
nb_conda                  2.0.0                    py35_0  
nb_conda_kernels          2.0.0                    py35_0  
nbconvert                 4.2.0                    py35_0  
nbformat                  4.1.0                    py35_0  
nbpresent                 3.0.2                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2.1                    py35_0  
nose                      1.3.7                    py35_1  
notebook                  4.2.3                    py35_0  
numba                     0.28.1              np111py35_0  
numexpr                   2.6.1               np111py35_0  
numpy                     1.11.1                   py35_1  
odo                       0.5.0                    py35_1  
openpyxl                  2.3.2                    py35_0  
openssl                   1.0.2j                   vc14_0  [vc14]
pandas                    0.18.1              np111py35_0  
partd                     0.3.6                    py35_0  
path.py                   8.2.1                    py35_0  
pathlib2                  2.1.0                    py35_0  
patsy                     0.4.1                    py35_0  
pep8                      1.7.0                    py35_0  
pickleshare               0.7.4                    py35_0  
pillow                    3.3.1                    py35_0  
pip                       8.1.2                    py35_0  
pkginfo                   1.3.2                    py35_0  
ply                       3.9                      py35_0  
prompt_toolkit            1.0.3                    py35_0  
psutil                    4.3.1                    py35_0  
py                        1.4.31                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.1                    py35_1  
pycparser                 2.14                     py35_1  
pycrypto                  2.6.1                    py35_4  
pycurl                    7.43.0                   py35_0  
pyflakes                  1.3.0                    py35_0  
pygments                  2.1.3                    py35_0  
pylint                    1.5.4                    py35_1  
pyopenssl                 16.0.0                   py35_0  
pyparsing                 2.1.4                    py35_0  
pyqt                      5.6.0                    py35_0  
pytables                  3.2.2               np111py35_4  
pytest                    2.9.2                    py35_0  
python                    3.5.2                         0  
python-dateutil           2.5.3                    py35_0  
pytz                      2016.6.1                 py35_0  
pywin32                   220                      py35_1  
pyyaml                    3.12                     py35_0  
pyzmq                     15.4.0                   py35_0  
qt                        5.6.0                    vc14_0  [vc14]
qtawesome                 0.3.3                    py35_0  
qtconsole                 4.2.1                    py35_2  
qtpy                      1.1.2                    py35_0  
requests                  2.11.1                   py35_0  
rope                      0.9.4                    py35_1  
ruamel_yaml               0.11.14                  py35_0  
scikit-image              0.12.3              np111py35_1  
scikit-learn              0.17.1              np111py35_1  
scipy                     0.18.1              np111py35_0  
setuptools                27.2.0                   py35_1  
simplegeneric             0.8.1                    py35_1  
singledispatch            3.4.0.3                  py35_0  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.4.6                    py35_0  
spyder                    3.0.0                    py35_0  
sqlalchemy                1.0.13                   py35_0  
statsmodels               0.6.1               np111py35_1  
sympy                     1.0                      py35_0  
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0  
tornado                   4.4.1                    py35_0  
traitlets                 4.3.0                    py35_0  
unicodecsv                0.14.1                   py35_0  
vs2015_runtime            14.0.25123                    0  
wcwidth                   0.1.7                    py35_0  
werkzeug                  0.11.11                  py35_0  
wheel                     0.29.0                   py35_0  
widgetsnbextension        1.2.6                    py35_0  
win_unicode_console       0.5                      py35_0  
wrapt                     1.10.6                   py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.3                    py35_0  
xlwings                   0.10.0                   py35_0  
xlwt                      1.1.2                    py35_0  
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by richafrank** [comment]
Hmm, looks like we're missing cachetools packages for py35. We'll have to fix that...

**Comment by richafrank** [comment]
Ah, cachetools isn't necessary anymore, but the rest of our py35 dependencies weren't in the main channel. I updated that. Try again?

**Comment by ftnpang** [comment]
Working like a charm! Thank you very much, @richafrank

**Comment by adalfu** [comment]
I'm having the same issues as ftnpang and OP. tried all methods to install using conda and pip but also getting all those errors that OP has indicated. any tip? 
thanks

**Comment by adalfu** [comment]
my conda list:

#
_license                  1.1                      py35_1
_nb_ext_conf              0.4.0                    py35_1
alabaster                 0.7.10                   py35_0
anaconda                  custom                   py35_0
anaconda-clean            1.1.0                    py35_0
anaconda-client           1.6.3                    py35_0
anaconda-navigator        1.6.2                    py35_0
anaconda-project          0.6.0                    py35_0
argcomplete               1.0.0                    py35_1
asn1crypto                0.22.0                   py35_0
astroid                   1.4.9                    py35_0
astropy                   1.3.2               np112py35_0
babel                     2.4.0                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.6.0                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bleach                    1.5.0                    py35_0
bokeh                     0.12.5                   py35_1
boto                      2.46.1                   py35_0
bottleneck                1.2.1               np112py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.10.0                   py35_0
chardet                   3.0.3                    py35_0
chest                     0.2.3                    py35_0
click                     6.7                      py35_0
cloudpickle               0.2.2                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.9                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.3.25                   py35_0
conda-build               3.0.13           py35h69938a9_0
conda-env                 2.6.0                         0
conda-verify              2.0.0                    py35_0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.5                    py35_0
cryptography              1.8.1                    py35_0
curl                      7.52.1                   vc14_0  [vc14]
cvxopt                    1.1.9                    py35_0
cycler                    0.10.0                   py35_0
cython                    0.25.2                   py35_0
cytoolz                   0.8.2                    py35_0
dask                      0.14.3                   py35_1
datashape                 0.5.4                    py35_0
decorator                 4.0.11                   py35_0
dill                      0.2.6                    py35_0
distributed               1.16.3                   py35_0
docutils                  0.13.1                   py35_0
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_1
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
filelock                  2.0.7                    py35_0
flask                     0.12.2                   py35_0
flask-cors                3.0.2                    py35_0
freetype                  2.5.5                    vc14_2  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.2.1                    py35_0
glob2                     0.5                      py35_0
greenlet                  0.4.12                   py35_0
h5py                      2.7.0               np112py35_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
html5lib                  0.999                    py35_0
icu                       57.1                     vc14_0  [vc14]
idna                      2.5                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.6.1                    py35_0
ipython                   5.3.0                    py35_0
ipython_genutils          0.2.0                    py35_0
ipywidgets                6.0.0                    py35_0
isort                     4.2.5                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.3                      py35_0
jedi                      0.10.2                   py35_2
jinja2                    2.9.6                    py35_0
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.6.0                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            5.0.1                    py35_0
jupyter_console           5.1.0                    py35_0
jupyter_core              4.3.0                    py35_0
lazy-object-proxy         1.2.2                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.27                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_3  [vc14]
llvmlite                  0.18.0                   py35_0
locket                    0.2.0                    py35_1
Logbook                   1.1.0                     <pip>
lxml                      3.7.3                    py35_0
m2w64-dsdp                5.8                           1
m2w64-fftw                3.3.4                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-glpk                4.61                          1
m2w64-gmp                 6.1.0                         2
m2w64-gsl                 2.1                           2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-openblas            0.2.19                        1
markupsafe                0.23                     py35_2
matplotlib                2.0.2               np112py35_0
menuinst                  1.4.7                    py35_0
mistune                   0.7.4                    py35_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py35_3
mpmath                    0.19                     py35_1
msgpack-python            0.4.8                    py35_0
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.9                    py35_0
navigator-updater         0.1.0                    py35_0
nb_anacondacloud          1.4.0                    py35_0
nb_conda                  2.2.0                    py35_0
nb_conda_kernels          2.1.0                    py35_0
nbconvert                 5.1.1                    py35_0
nbformat                  4.3.0                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.3                    py35_0
nose                      1.3.7                    py35_1
notebook                  5.0.0                    py35_0
numba                     0.33.0              np112py35_0
numexpr                   2.6.2               np112py35_0
numpy                     1.12.1                   py35_0
numpydoc                  0.6.0                    py35_0
odo                       0.5.0                    py35_1
olefile                   0.44                     py35_0
openpyxl                  2.4.7                    py35_0
openssl                   1.0.2l                   vc14_0  [vc14]
packaging                 16.8                     py35_0
pandas                    0.18.1                    <pip>
pandas                    0.20.3                   py35_0
pandas-datareader         0.5.0                     <pip>
pandocfilters             1.4.1                    py35_0
partd                     0.3.8                    py35_0
path.py                   10.3.1                   py35_0
pathlib2                  2.2.1                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    4.1.1                    py35_0
pip                       9.0.1                    py35_1
pkginfo                   1.4.1                    py35_0
ply                       3.10                     py35_0
prompt_toolkit            1.0.14                   py35_0
psutil                    5.2.2                    py35_0
py                        1.4.33                   py35_0
pyasn1                    0.2.3                    py35_0
pycodestyle               2.3.1                    py35_0
pycosat                   0.6.2                    py35_0
pycparser                 2.17                     py35_0
pycrypto                  2.6.1                    py35_6
pycurl                    7.43.0                   py35_2
pyflakes                  1.5.0                    py35_0
pygments                  2.2.0                    py35_0
pylint                    1.6.4                    py35_1
pymcef                    0.2.3                     <pip>
pyodbc                    4.0.16                   py35_0
pyopenssl                 17.0.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      5.6.0                    py35_2
pyreadline                2.1                      py35_0
pytables                  3.2.2               np112py35_4
pytest                    3.0.7                    py35_0
python                    3.5.3                         3
python-dateutil           2.6.0                    py35_0
pytz                      2017.2                   py35_0
pywavelets                0.5.2               np112py35_0
pywin32                   220                      py35_2
pyyaml                    3.12                     py35_0
pyzmq                     16.0.2                   py35_0
qt                        5.6.2                    vc14_4  [vc14]
qtawesome                 0.4.4                    py35_0
qtconsole                 4.3.0                    py35_0
qtpy                      1.2.1                    py35_0
requests                  2.14.2                   py35_0
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_1
scikit-image              0.13.0              np112py35_0
scikit-learn              0.18.1              np112py35_1
scipy                     0.19.0              np112py35_0
seaborn                   0.7.1                    py35_0
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sortedcollections         0.5.3                    py35_0
sortedcontainers          1.5.7                    py35_0
sphinx                    1.5.6                    py35_0
spyder                    3.2.1                    py35_0
sqlalchemy                1.1.9                    py35_0
statsmodels               0.8.0               np112py35_0
sympy                     1.0                      py35_0
tblib                     1.3.2                    py35_0
testpath                  0.3                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.2                    py35_0
tornado                   4.5.1                    py35_0
traitlets                 4.3.2                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.12.2                   py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        2.0.0                    py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.10                  py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.6                    py35_0
xlwings                   0.10.4                   py35_0
xlwt                      1.2.0                    py35_0
zict                      0.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by yacinuscrasus** [comment]
A Solution to the problem on installing zipline on windows 10,through any version of anaconda,
(by creating a conda environment running under python 3.4 ,and containing default packages,to avoid 
incompatibility,even though,installing zipline will downgrade some of them):
 conda create -n env_full anaconda python=3.4
 conda activate env_full
 conda install -c Quantopian zipline  

i hope it helps.
