### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by Dessth** [quantopian/zipline#1400]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Operating System: Win32 
- Python Version: Python 2.7 (Spyder)
- How did you install Zipline: pip and a local file (zipline-master) / Conda 

Now that you know a little about me, let me tell you about the issue I am
having:
# Description of Issue

I'm a bit lost...
Impossible to obtain version 1.0.1. I tried Conda method, pip method but the only version i can download is 0.7.0. I'm stuck.

Thanks in advance for your help.

Sincerely,

**Comment by richafrank** [comment]
Hi @Dessth .  Sorry for the trouble.  We're not currently building or testing packages for win-32 conda.  Would you be able to install win-64 conda?

**Comment by FreddieV4** [comment]
@Dessth did you manage to make any progress on this?

**Comment by FreddieV4** [comment]
Going to close this. Feel free to reopen or open a new issue if you still have this problem/can't install zipline.
