### ISSUE TITLE
Can not install from pip

### ISSUE THREAD

**Issue by plavine** [quantopian/zipline#1415]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux ubuntu 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* Python Version: Python 2.7.12

* Python Bitness:  64
* How did you install Zipline: pip
* Python packages: 

backports.shutil-get-terminal-size==1.0.0
boto==2.38.0
cffi==1.5.2
chardet==2.3.0
cryptography==1.2.3
cycler==0.9.0
decorator==4.0.6
duplicity==0.7.6
enum34==1.1.2
ffnet==0.8.3
ffnetui==0.8.3.2
idna==2.0
inflection==0.3.1
ipaddress==1.0.16
ipython==4.2.0
ipython-genutils==0.1.0
lockfile==0.12.2
matplotlib==1.5.1
more-itertools==2.2
msgpack-python==0.4.6
ndg-httpsclient==0.4.0
networkx==1.11
numpy==1.11.0
pandas==0.18.1
pathlib2==2.1.0
pexpect==4.1.0
pickleshare==0.7.2
Pillow==3.1.2
ply==3.7
ptyprocess==0.5.1
pyasn1==0.1.9
pycparser==2.14
pycurl==7.43.0
pyface==5.1.0
Pygments==2.1.3
pygobject==3.20.0
pyOpenSSL==0.15.1
pyparsing==2.0.3
python-apt==1.1.0b1
python-cloudfiles==1.7.10
python-dateutil==1.5
pytz==2014.10
pyxdg==0.25
QSTK==0.2.8
Quandl==3.0.1
requests==2.9.1
scapy==2.2.0
scikit-learn==0.17.1
scikits.statsmodels==0.3.1
scipy==0.17.0
simplegeneric==0.8.1
six==1.10.0
spyder==2.3.9
traitlets==4.2.1
traits==4.5.0
traitsui==5.1.0
unity-lens-photos==1.0
urllib3==1.13.1

I installed compiled cpython and 

# Description of Issue
oot@ubuntu:/home/philip# pip install zipline --no-cache-dir
Collecting zipline
  Downloading zipline-1.0.1.tar.gz (366kB)
    100% |████████████████████████████████| 368kB 4.0MB/s 
Requirement already satisfied (use --upgrade to upgrade): pip>=7.1.0 in /usr/lib/python2.7/dist-packages (from zipline)
Requirement already satisfied (use --upgrade to upgrade): setuptools>18.0 in /usr/lib/python2.7/dist-packages (from zipline)
Collecting Logbook>=0.12.5 (from zipline)
  Downloading Logbook-1.0.0.tar.gz (178kB)
    100% |████████████████████████████████| 184kB 3.9MB/s 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'

Sincerely,
Philip

**Comment by richafrank** [comment]
Hi @plavine , From googling a bit, looks like an issue with newer pip releases?

https://github.com/saltstack/salt/issues/33163
https://github.com/pypa/pip/issues/3687

Does downgrading it help?

**Comment by plavine** [comment]
I saw those articles. I am running pip 8.1.1

**Comment by richafrank** [comment]
Chalk it up to a weird pip issue then?  Not sure what to do within zipline...
