### ISSUE TITLE
"No module named _calendar_helpers"

### ISSUE THREAD

**Issue by fera0013** [quantopian/zipline#1417]
Dear Zipline Maintainers,

I have installed python using 
# Environment
- Operating System: Windows 10
- Python Version:  python --2.7
- Python Bitness: 64 bit
- How did you install Zipline:  conda

Now that you know a little about me, let me tell you about the issue I am
having:
# Description of Issue

I installed zipline using 

```
 "conda install -c Quantopian zipline"
```

I then created a python project in VisualStudio 2015 pytools and tried to run the simple dual moving average algorithm but got the error 

```
 "No module named _calendar_helpers"
```

Here is how you can reproduce this issue on your machine:
## Reproduction Steps
1. Install zipline on windows 10 using conda install
2. create a Visual Studio 2015 python tools project from the existing zipline code
3. run the simple dual moving average algorithm
## What steps have you taken to resolve this already?

...
# Anything else?

...

Sincerely,
 Ralph

**Comment by nborggren** [comment]
I'm getting this same issue with a conda installation on a macOS sierra with python 2.7

**Comment by qinghanmeng** [comment]
I meet the same problem.

**Comment by musiclicn** [comment]
Can someone fix this?

**Comment by FreddieV4** [comment]
Are you still seeing this issue? @fera0013

**Comment by dblN** [comment]
I think I solved this issue by installing from master branch. (MacOS Sierra with anaconda installed)

```
$ git clone git@github.com:quantopian/zipline.git
$ cd zipline
$ pip install -r ext/requirements.txt
$ python setup.py install
$ cd .. (it might cause some issue running zipline here, so move outside of the directory)
```

**Comment by fredfortier** [comment]
Do you understand the root cause of this error? I'm facing the same issue when running nosetests on a modified branch. It can't switch to the latest master branch. I'm just looking for a better clue to troubleshoot. I tried with empyrical 0.2.1 and 0.2.2. Same issue with python 3.6 and 2.7.

**Comment by fredfortier** [comment]
I'm answering my own question here. It turns out that catalyst.utils.calendars._calendar_helpers is a cython module. Rebuilding cython worked for me.

**Comment by freddiev4** [comment]
Going to close this due to inactivity. Feel free to re-open or open a new issue

**Comment by gy8409** [comment]
I got it done by run on Mac OSX High Sierra.
`python setup.py build_ext --inplace`
