### ISSUE TITLE
Documentation Errors

### ISSUE THREAD

**Issue by jmccorriston** [quantopian/zipline#1419]
From Quantopian community member Stephan F:

http://www.zipline.io/bundles.html 
Quandl WIKI Bundle 
QUANDL_API_KEY=<api-key> 
zipline ingest quandl 

should be: 

QUANDL_API_KEY=<api-key> 
zipline ingest -b quandl 

------------------------

http://www.zipline.io/beginner-tutorial.html#my-first-algorithm 

python -m zipline run -f ../../zipline/examples/buyapple.py --start 2000-1-1 --end 2014-1-1 --symbols AAPL -o buyapple_out.pickle 

should remove --symbols AAPL

**Comment by richafrank** [comment]
Thanks @jmccorriston .  I believe the first one was fixed in https://github.com/quantopian/zipline/pull/1303 and the second in https://github.com/quantopian/zipline/pull/1248.  When we release zipline next, the docs site will get updated.
