### ISSUE TITLE
Dual_moving_average.py not working + Pandas PerformanceWarning

### ISSUE THREAD

**Issue by Duvarc** [quantopian/zipline#1485]
# Environment

* Operating System: OSX 10.12
* Python Version: Python 3.5.1
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: pandas, numpy, etc...

# Description of Issue

When I try to run Dual_moving_average.py, one of the sample algorithms in the Quick Start guide
> run -f dual_moving_average.py --start 2011-1-1 --end 2012-1-1 -o dma.pickle

I get:

>/usr/local/lib/python3.5/site-packages/pandas/tseries/index.py:755: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex PerformanceWarning)

four times before getting

> [2016-09-14 07:22:01.556783] INFO: Performance: Simulated 252 trading days out of 252.
> [2016-09-14 07:22:01.564523] INFO: Performance: first open: 2011-01-03 14:31:00+00:00
> [2016-09-14 07:22:01.565202] INFO: Performance: last close: 2011-12-30 21:00:00+00:00

I'd like to know why I'm getting the performance warning and why the algorithm itself isn't working. I checked to see that all my dependencies are up-to-date and even updated python-dateutils to 2.5.3, but nothing changed. Thanks for the help.

pip3 version: 8.1.2
pandas: 0.17.1
zipline: 1.0.2

**Comment by richafrank** [comment]
@ssanderson Do you know if this is a warning that will be fixed with your upgrade to pandas 0.18?

**Comment by Duvarc** [comment]
Hi guys, fixed it by downgrading to 0.17.0. It appears that anything over 0.17.0 will break compatibility.

**Comment by Georgantas** [comment]
I'm getting the same warning. Downgraded to 0.17.0 and that solved it. Maybe keep this issue open?

**Comment by FreddieV4** [comment]
Hi there. We've now released zipline `1.1.0` which has support for pandas 0.18
