### ISSUE TITLE
CLI does not work after pip install

### ISSUE THREAD

**Issue by frabi** [quantopian/zipline#1495]
Sorry for asking such a stupid question, but after installing zipline with pip, I can't run zipline run --help. It says
-bash: zipline: command not found

What am I doing wrong?

**Comment by richafrank** [comment]
What version of zipline does pip say it's installed? e.g. `pip freeze | grep zipline`

**Comment by DexHunter** [comment]
I found an answer [there](https://stackoverflow.com/questions/39584013/zipline-command-line-interface-does-not-work-after-installation)

So maybe you can use

"""
python -m zipline
"""

**Comment by freddiev4** [comment]
Going to close this due to inactivity. Don't hesitate to open another issue if you're still having problems.
