### ISSUE TITLE
Dramatic Memory Usage Increases After Pandas 18 Merge

### ISSUE THREAD

**Issue by ssanderson** [quantopian/zipline#1503]
Prior to the merge of https://github.com/quantopian/zipline/pull/1339, peak memory usage of the test suite was around 800MB.  Post merge, we peak at over 2GB on my machine.

**Comment by ssanderson** [comment]
Root cause appears to be https://github.com/quantopian/zipline/pull/1504.

**Comment by FreddieV4** [comment]
This should be fixed now, right?
