### ISSUE TITLE
how to make zipline support live trading

### ISSUE THREAD

**Issue by wenghb** [quantopian/zipline#1511]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Operating System: debian
- Python Version: 3.5
- Python Bitness: 64
- How did you install Zipline: compile from source
- Python packages: 
  alembic==0.8.8
  bcolz==1.1.0
  Bottleneck==1.1.0
  cachetools==1.1.6
  click==6.6
  contextlib2==0.5.4
  cycler==0.10.0
  decorator==4.0.10
  empyrical==0.2.0
  intervaltree==2.1.0
  Logbook==1.0.0
  lru-dict==1.1.4
  lxml==3.6.4
  Mako==1.0.4
  MarkupSafe==0.23
  matplotlib==1.5.3
  networkx==1.11
  numexpr==2.6.1
  numpy==1.11.1
  pandas==0.18.1
  pandas-datareader==0.2.1
  pyparsing==2.1.9
  python-dateutil==2.5.3
  python-editor==1.0.1
  pytz==2016.6.1
  requests==2.11.1
  requests-file==1.4
  scipy==0.18.1
  six==1.10.0
  sortedcontainers==1.5.3
  SQLAlchemy==1.0.15
  tables==3.3.0
  toolz==0.8.0
  tushare==0.5.0

Now that you know a little about me, let me tell you about the issue I am
having:
# Description of Issue

In the description of zipline, it has capability to support live trading. But it hard to find any tutorial to write code based on live trading. 
On the other words, how can i make zipline support incremental backtest. In detail:
before the TradingAlgorithm run, I can set the positions & orders. 
- What did you expect to happen?

Before the TradingAlgorithm run, I can set the positions & orders.
- What happened instead?

Currently, there is no way to set positions & orders before TradingAlgorithm run.

...

Sincerely,
Haibin

**Comment by lssilva** [comment]
Hi Haibin,

You may better ask this on the mailing list or other support mediums. Don't think you should use Zipline alone on live trading, you need many other components to watch, notify and safe-guard your money.  

Cheers,
Lucas

**Comment by zhangzheng88** [comment]
Hi Lucas,
how can I join the mailing list of zipline?

**Comment by femtotrader** [comment]
https://groups.google.com/forum/#!forum/zipline

**Comment by wenghb** [comment]
@lssilva Thanks~

**Comment by wenghb** [comment]
@femtotrader thanks.

**Comment by richafrank** [comment]
This is in progress [here](https://github.com/zipline-live/zipline).
