### ISSUE TITLE
Conda Install OS X - package missing alembic 0.7.7

### ISSUE THREAD

**Issue by adamluc** [quantopian/zipline#1520]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Mac OS X
* Python Version: python 2.7
* How did you install Zipline: conda

Now that you know a little about me, let me tell you about the issue I am
having:

# When trying to install zipline 1.0.2 with conda, I get the following message:

Fetching package metadata .........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Dependency missing in current osx-64 channels: 
  - zipline 1.0.2* -> alembic >=0.7.7

You can search for packages on anaconda.org with

    anaconda search -t conda alembic

I expected zipline 1.0.2 to install, but got the above error.

Here is how you can reproduce this issue on your machine: use the following command in terminal: conda install -c quantopian zipline=1.0.2

## What steps have you taken to resolve this already?
none
...

# Anything else?
none
...

Sincerely,
Adam

**Comment by richafrank** [comment]
Thanks for the report @adamluc .  I just built and uploaded the OSX alembic packages to our anaconda channel.  Try again?

**Comment by adamluc** [comment]
It works now, thanks!

Adam

**Comment by richafrank** [comment]
Great!

**Comment by jinyiabc** [comment]
Hello, 

This issue is reproducible with Python 3.5.

regards 

Alex

**Comment by richafrank** [comment]
@jinyiabc Thanks for the report - I just uploaded the `osx-64/alembic-0.7.7-py35_0` package, so that should be fixed now.
