### ISSUE TITLE
get_datetime() and using Minute data frequency

### ISSUE THREAD

**Issue by nyxynyx** [quantopian/zipline#1541]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: Python 2.7.12 :: Anaconda custom (64-bit)
* How did you install Zipline: `conda install -c Quantopian zipline`
* Python packages: 

	_license                  1.1                      py27_1
	_nb_ext_conf              0.3.0                    py27_0
	alabaster                 0.7.9                    py27_0
	alembic                   0.7.7                    py27_0    Quantopian
	anaconda                  custom                   py27_0
	anaconda-clean            1.0.0                    py27_0
	anaconda-client           1.5.1                    py27_0
	anaconda-navigator        1.2.3                    py27_0
	argcomplete               1.0.0                    py27_1
	astroid                   1.4.7                    py27_0
	astropy                   1.0.5                np19py27_1
	babel                     2.3.4                    py27_0
	backports                 1.0                      py27_0
	backports_abc             0.4                      py27_0
	bcolz                     0.12.1               np19py27_0    Quantopian
	beautifulsoup4            4.5.1                    py27_0
	bitarray                  0.8.1                    py27_1
	blaze                     0.10.1                   py27_0
	bokeh                     0.12.2                   py27_0
	boto                      2.42.0                   py27_0
	bottleneck                1.0.0                np19py27_0
	bzip2                     1.0.6                     vc9_3  [vc9]
	cachetools                1.1.6                    py27_0    Quantopian
	cdecimal                  2.3                      py27_2
	cffi                      1.7.0                    py27_0
	chest                     0.2.3                    py27_0
	click                     6.6                      py27_0
	cloudpickle               0.2.1                    py27_0
	clyent                    1.2.2                    py27_0
	colorama                  0.3.7                    py27_0
	comtypes                  1.1.2                    py27_0
	configobj                 5.0.6                    py27_0
	configparser              3.5.0                    py27_0
	console_shortcut          0.1.1                    py27_1
	contextlib2               0.5.3                    py27_0
	cryptography              1.5                      py27_0
	curl                      7.49.0                    vc9_0  [vc9]
	cycler                    0.10.0                   py27_0
	cyordereddict             0.2.2                    py27_0    Quantopian
	cython                    0.24.1                   py27_0
	cytoolz                   0.8.0                    py27_0
	dask                      0.11.0                   py27_0
	datashape                 0.5.2                    py27_0
	decorator                 4.0.10                   py27_0
	dill                      0.2.5                    py27_0
	docutils                  0.12                     py27_2
	empyrical                 0.2.1                    py27_0    Quantopian
	entrypoints               0.2.2                    py27_0
	enum34                    1.1.6                    py27_0
	et_xmlfile                1.0.1                    py27_0
	fastcache                 1.0.2                    py27_1
	filelock                  2.0.6                    py27_0
	flask                     0.11.1                   py27_0
	flask-cors                2.1.2                    py27_0
	freetype                  2.5.5                     vc9_1  [vc9]
	funcsigs                  1.0.2                    py27_0
	functools32               3.2.3.2                  py27_0
	futures                   3.0.5                    py27_0
	get_terminal_size         1.0.0                    py27_0
	gevent                    1.1.2                    py27_0
	greenlet                  0.4.10                   py27_0
	grin                      1.2.1                    py27_3
	h5py                      2.5.0                np19py27_2
	hdf5                      1.8.15.1                  vc9_4  [vc9]
	heapdict                  1.0.0                    py27_1
	icu                       57.1                      vc9_0  [vc9]
	idna                      2.1                      py27_0
	imagesize                 0.7.1                    py27_0
	intervaltree              2.1.0                    py27_0    Quantopian
	ipaddress                 1.0.16                   py27_0
	ipykernel                 4.5.0                    py27_0
	ipython                   5.1.0                    py27_0
	ipython_genutils          0.1.0                    py27_0
	ipywidgets                5.2.2                    py27_0
	itsdangerous              0.24                     py27_0
	jdcal                     1.2                      py27_1
	jedi                      0.9.0                    py27_1
	jinja2                    2.8                      py27_1
	jpeg                      8d                        vc9_2  [vc9]
	jsonschema                2.5.1                    py27_0
	jupyter                   1.0.0                    py27_3
	jupyter_client            4.4.0                    py27_0
	jupyter_console           5.0.0                    py27_0
	jupyter_core              4.2.0                    py27_0
	lazy-object-proxy         1.2.1                    py27_0
	libpng                    1.6.22                    vc9_0  [vc9]
	libtiff                   4.0.6                     vc9_2  [vc9]
	llvmlite                  0.13.0                   py27_0
	llvmpy                    0.12.7                   py27_0
	locket                    0.2.0                    py27_1
	Logbook                   1.0.0                     <pip>
	logbook                   0.12.5                   py27_0    Quantopian
	lxml                      3.6.4                    py27_0
	mako                      1.0.4                    py27_0
	markupsafe                0.23                     py27_2
	matplotlib                1.4.3                np19py27_3
	menuinst                  1.4.1                    py27_0
	mistune                   0.7.3                    py27_0
	mkl                       11.3.3                        1
	mkl-service               1.1.2                    py27_2
	mpmath                    0.19                     py27_1
	multipledispatch          0.4.8                    py27_0
	nb_anacondacloud          1.2.0                    py27_0
	nb_conda                  2.0.0                    py27_0
	nb_conda_kernels          2.0.0                    py27_0
	nbconvert                 4.2.0                    py27_0
	nbformat                  4.1.0                    py27_0
	nbpresent                 3.0.2                    py27_0
	networkx                  1.11                     py27_0
	nltk                      3.2.1                    py27_0
	nose                      1.3.7                    py27_1
	notebook                  4.2.3                    py27_0
	numba                     0.15.1               np19py27_0
	numexpr                   2.4.6                np19py27_0    Quantopian
	numpy                     1.9.3                    py27_3
	odo                       0.5.0                    py27_1
	openpyxl                  2.3.2                    py27_0
	openssl                   1.0.2j                    vc9_0  [vc9]
	pandas                    0.17.0               np19py27_0
	pandas                    0.17.1                    <pip>
	pandas-datareader         0.2.1                    py27_0
	pandas-datareader         0.2.1                     <pip>
	partd                     0.3.6                    py27_0
	path.py                   8.2.1                    py27_0
	pathlib2                  2.1.0                    py27_0
	patsy                     0.4.1                    py27_0
	pep8                      1.7.0                    py27_0
	pickleshare               0.7.4                    py27_0
	pillow                    3.3.1                    py27_0
	pip                       8.1.2                    py27_0
	pkginfo                   1.3.2                    py27_0
	ply                       3.9                      py27_0
	prompt_toolkit            1.0.3                    py27_0
	psutil                    4.3.1                    py27_0
	py                        1.4.31                   py27_0
	pyasn1                    0.1.9                    py27_0
	pycosat                   0.6.1                    py27_1
	pycparser                 2.14                     py27_1
	pycrypto                  2.6.1                    py27_4
	pycurl                    7.43.0                   py27_0
	pyflakes                  1.3.0                    py27_0
	pygments                  2.1.3                    py27_0
	pylint                    1.5.4                    py27_1
	pyopenssl                 16.0.0                   py27_0
	pyparsing                 2.1.4                    py27_0
	pyqt                      4.11.4                   py27_6
	pytables                  3.2.2                np19py27_0
	pytest                    2.9.2                    py27_0
	python                    2.7.12                        0
	python-dateutil           2.5.3                    py27_0
	pytz                      2016.6.1                 py27_0
	pywin32                   220                      py27_1
	pyyaml                    3.12                     py27_0
	pyzmq                     15.4.0                   py27_0
	qt                        5.6.0                     vc9_0  [vc9]
	qtawesome                 0.3.3                    py27_0
	qtconsole                 4.2.1                    py27_0
	qtpy                      1.1.2                    py27_0
	requests                  2.11.1                   py27_0
	requests-file             1.4                       <pip>
	requests-file             1.4                      py27_0
	rope                      0.9.4                    py27_1
	scikit-image              0.11.3               np19py27_0
	scikit-learn              0.16.1               np19py27_0
	scipy                     0.16.0               np19py27_0
	setuptools                27.2.0                   py27_1
	simplegeneric             0.8.1                    py27_1
	singledispatch            3.4.0.3                  py27_0
	sip                       4.18                     py27_0
	six                       1.10.0                   py27_0
	snowballstemmer           1.2.1                    py27_0
	sockjs-tornado            1.0.3                    py27_0
	sortedcontainers          1.4.4                    py27_0    Quantopian
	sphinx                    1.4.6                    py27_0
	spyder                    2.3.9                    py27_1
	sqlalchemy                1.0.13                   py27_0
	ssl_match_hostname        3.4.0.2                  py27_1
	statsmodels               0.6.1                np19py27_0
	sympy                     1.0                      py27_0
	tk                        8.5.18                    vc9_0  [vc9]
	toolz                     0.8.0                    py27_0
	tornado                   4.4.1                    py27_0
	traitlets                 4.3.0                    py27_0
	unicodecsv                0.14.1                   py27_0
	vs2008_runtime            9.00.30729.1                  2
	wcwidth                   0.1.7                    py27_0
	werkzeug                  0.11.11                  py27_0
	wheel                     0.29.0                   py27_0
	widgetsnbextension        1.2.6                    py27_0
	win_unicode_console       0.5                      py27_0
	wrapt                     1.10.6                   py27_0
	xlrd                      1.0.0                    py27_0
	xlsxwriter                0.9.3                    py27_0
	xlwings                   0.10.0                   py27_0
	xlwt                      1.1.2                    py27_0
	zipline                   1.0.2                np19py27_0    Quantopian
	zlib                      1.2.8                     vc9_3  [vc9]

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* I am trying to place a trade order for `SPY` at a certain hour of the day
* I get the error `AttributeError: 'NoneType' object has no attribute 'get_datetime'`. Why does `get_datetime` not work?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. `python test.py`

# Anything else?

`load_bars_from_yahoo` does not seem to load minute level data? Because if I comment out the lines that remove the `get_datetime` error, the results appear to be shown in a daily frequency. How can we switch to minute mode?

Here's my `test.py`

	import pandas as pd
	from zipline.api import (
	    history,
	    order_target, order_value,
	    record,
	    symbol,
	    get_datetime
	)
	from zipline.utils.factory import load_bars_from_yahoo
	import zipline

	def initialize(context):
	    pass

	def handle_data(context, data):
	    pass        

	if __name__ == "__main__":
		startDate = pd.Timestamp('2016-01-01 08:00:00+00:00')
		endDate = pd.Timestamp('2016-01-10 08:00:00+00:00')
		data = load_bars_from_yahoo(stocks=['SPY'], start=startDate, end=endDate)  

		if zipline.api.get_datetime() == pd.Timestamp("2016-01-06 12:00:00+00:00"):
			order_value(stocks[0], 5000)

		results = zipline.run_algorithm(initialize=initialize, handle_data=handle_data, capital_base=1000, start=startDate, end=endDate, data=data, data_frequency='minute')
		print results

Sincerely,
Confused Quantopianian

**Comment by richafrank** [comment]
Hi @nyxynyx !  I see the confusion here.  The issue is that the functions in `zipline.api` are available only during the course of a simulation, e.g. `get_datetime()` returns the backtester's current simulation time.  

In your example above, it's being called outside of a simulation being run, i.e. you call it _before_ calling `run_algorithm`, instead of in `handle_data` or in a scheduled function.  This doesn't have much meaning, as there's no current simulation, so we can't ask what simulation time it is.  `handle_data` is called once for each minute of the simulation, so in there you can ask what time it is.

Does that make sense?

**Comment by nyxynyx** [comment]
@richafrank Thanks for the reply, yes I understand now, functions from `zipline.api` need to be called in a function like `handle_data` which is run during the simulation.
