### ISSUE TITLE
No data on or before day error for unknown stock

### ISSUE THREAD

**Issue by RamonBeast** [quantopian/zipline#1566]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Operating System: Mac OS
- Python Version: 2.7.11
- Python Bitness: 64 bit
- How did you install Zipline: pip
- Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

I was ingesting a mixed list of stocks from Russell2000 and SP500, I first incurred in the issue #1241 (hint: _BF_) that was solved after a painful bisection to find the stock that was giving error. Then after all the data was fetched I started to get this:

```
$ zipline ingest -b myindex
Merging daily equity files:  [---#--------------------------------]  2453 100%
Merging daily equity files:  [####################################]
/usr/local/lib/python2.7/site-packages/zipline/assets/asset_writer.py:192: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  row = group.sort('end_date').iloc[-1]
Downloading Yahoo adjustment data:   [####################################]  100%
Traceback (most recent call last):
  File "/usr/local/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/zipline/__main__.py", line 306, in ingest
    show_progress,
  File "/usr/local/lib/python2.7/site-packages/zipline/data/bundles/core.py", line 443, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/usr/local/lib/python2.7/site-packages/zipline/data/bundles/yahoo.py", line 177, in ingest
    adjustment_writer.write(splits=splits, dividends=dividends)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 1150, in write
    self.write_dividend_data(dividends, stock_dividends)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 1062, in write_dividend_data
    dividend_ratios = self.calc_dividend_ratios(dividends)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 985, in calc_dividend_ratios
    sid, prev_close_date, 'close')
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 707, in get_value
    ix = self.sid_day_index(sid, day)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 679, in sid_day_index
    day, sid))
zipline.data.session_bars.NoDataBeforeDate: No data on or before day=1995-05-24 00:00:00+00:00 for sid=1419
```

I cannot pinpoint who is causing that because the whole processing fails after 15 minutes on my computer and I cannot proceed by bisection without getting old in the process.

Is this a known issue, or is there a way to identify it and possibly remove whoever is causing the error? I don't know **sid=1419** to which ticker belongs.

Thank you.

**Comment by scubamut** [comment]
If I could add to this...

Using bundles (especially bundles with hundreds of securities) is very frustrating - ingesting often fails, either because of the sqlalchemy.exc.InvalidRequestError bug (#[1316](https://github.com/quantopian/zipline/issues/1316)), which was reported back in July, or because of indecipherable errors like the one described here.

Please could someone take a look at fixing these problems?

Thanks.

**Comment by lionel75013** [comment]
Hi,

I have to report the same issue. It affects many symbols I try to update, but in this case, I will give the example of MTF.PA.
I work on lubuntu 64 bits, My python version is:
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
when ingesting a package using this Symbol MTF.PA only, i get no error. When logging the result of the call to datareader in yahoo.py with : 
                    path = _cachpath(symbol, 'ohlcv')
                    try:
                        df = cache[path]
                    except KeyError:
                        df = cache[path] = DataReader(
                            symbol,
                            'yahoo',
                            start,
                            end,
                            session=session,
                        ).sort_index()
                        print df
I get:
2016-11-17  215.20  215.20  213.90  213.90     100     213.90
2016-11-18  211.35  213.92  211.23  213.63     700     213.63
2016-11-21  213.34  213.87  212.78  213.61     300     213.61
2016-11-22  215.09  215.14  215.09  215.14       0     215.14
2016-11-23  214.89  214.89  211.99  212.74    2100     212.74
2016-11-25  212.33  213.22  212.33  212.64    1100     212.64

[2121 rows x 6 columns]
  start_date   end_date auto_close_date  symbol
0 2007-07-05 2016-11-25      2016-11-26  MTF.PA

but when using the bundle in backtesting i get :
zipline.data.session_bars.NoDataAfterDate: No data on or after day=2015-12-28 00:00:00+00:00 for sid=Equity(3 [MTF.PA])

please help with this issue.  I invested a lot of time in learning zipline and making it work...

**Comment by FreddieV4** [comment]
This issue should be fixed in the latest release of zipline. You can check out the announcement [here](https://groups.google.com/forum/#!topic/zipline/JbTpM6BJjqQ). If you're still experiencing this issue, feel free to re-open/comment on this issue.

**Comment by jcrichard** [comment]
I have the same issue using local data where one asset does not have returns at the begining of the history. It does not seem fixed. I am under zipline 1.3.0.  If I backfill my prices I do not have the problem anymore..

This is craching here:


> ...\zipline\data\data_portal.py in _get_daily_spot_value(self, asset, column, dt)
>     754                 try:
>     755                     value = reader.get_value(
> --> 756                         asset, found_dt, "close"
>     757                     )
>     758                     if not isnull(value):
> 
> ...\zipline\data\dispatch_bar_reader.py in get_value(self, sid, dt, field)
>      95         asset = self._asset_finder.retrieve_asset(sid)
>      96         r = self._readers[type(asset)]
> ---> 97         return r.get_value(asset, dt, field)
>      98 
>      99     def get_last_traded_dt(self, asset, dt):
> 
> ...\zipline\data\us_equity_pricing.py in get_value(self, sid, dt, field)
>     842             0.
>     843         """
> --> 844         return self.panel.loc[sid, dt, field]
