### ISSUE TITLE
cant get zipline to run on mac --

### ISSUE THREAD

**Issue by modi5** [quantopian/zipline#1570]
hi,

i have python 2.7 with talib and it works fine on mac.  i have the same plus zipline on PC and it all works.

i installed zipline on a mac laptop through conda but it doesnt seem to work:

Minas-MBP:~ Panda_Bear$ conda install -c quantopian zipline
Fetching package metadata .........
Solving package specifications: ..........
# All requested packages already installed.
# packages in environment at /Applications/anaconda:
# 

zipline                   1.0.2               np110py27_0    quantopian

here is what happened when i try to run a basic command:

Minas-MBP:Applications Panda_Bear$ zipline run --help
Traceback (most recent call last):
  File "/Applications/anaconda/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.0.2', 'console_scripts', 'zipline')()
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/**init**.py", line 542, in load_entry_point
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/**init**.py", line 2569, in load_entry_point
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/**init**.py", line 2229, in load
  File "/Ap

any thoughts on how to get zipline running on a mac?

thanks,
modi

Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Operating System: (Windows Version or `$ uname --all`)
- Python Version: `$ python --version`
- Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
- How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
- Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:
# Description of Issue
- What did you expect to happen?
- What happened instead?

Here is how you can reproduce this issue on your machine:
## Reproduction Steps

1.
2.
3.
...
## What steps have you taken to resolve this already?

...
# Anything else?

...

Sincerely,
`$ whoami`

**Comment by FreddieV4** [comment]
Hi @modi5 could you please post the full stack trace for this, and your full list of python packages either using `pip freeze` or `conda list`?

**Comment by FreddieV4** [comment]
Going to close this due to inactivity/no follow up. Feel free to reopen if you still have this issue.
