### ISSUE TITLE
Why does short selling result in a massive short position?

### ISSUE THREAD

**Issue by emitby** [quantopian/zipline#1576]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10     Version or `$ uname --all`)
* Python Version:  2.7     `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: conda     (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Why when i use order_target_percent for a short sale it causes a massive short position? ie, if i use .25 as a target on the long side, the long position is .25 of capital.  but if i use -.25 as a target on the short side, the position turns out being 10 times what i was expecting.

this is also shown in the output file under short positions which dwarf my capital.   if i use order_amount  and target an actual number, ie 25% of capital, then the calculations seem to work but the output in the data file is complete nonsense anyway.

Is this a problem with some kind of leverage setting for short positions?

Also, how do i cancel a stop order if the position closes out?

Thanks,

* What did you expect to happen?   to short the amount in the code
* What happened instead?   the amount shorted is 10 times the amount in the code

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by ernestoeperez88** [comment]
Closing as it has been quite some time. Please feel free to reopen if you still have questions.
