### ISSUE TITLE
is there a way to view the data in a data bundle?

### ISSUE THREAD

**Issue by zhangzheng88** [quantopian/zipline#1579]
I have ingest the data to my customized bundle. Now i want to view the data to insure if it is right. for example, i want to plot the adjusted close price. what should I do？

**Comment by FreddieV4** [comment]
The idea I have for this is that in `zipline.data.bundles.core`, there is a `namedtuple` object called `BundleData`; that can be abstracted away to a class and we can use the `asset_finder`, `adjustments` etc to create some way to view the data more easily (maybe in a DataFrame?)

**Comment by walterkissling** [comment]
I was able to do it like this. My custom bundle name is ETFs and I had already ingested it. I have no idea if this is the 'correct' way, but it worked for me.
```from zipline.data.bundles import load, register
from zipline.data.data_portal import DataPortal
from zipline.utils.calendars import get_calendar
from zipline.data.bundles.ETFs import ETFs
import pandas as pd
symbols = ['VOO','IEF']
register('ETFs', ETFs(symbols))
etfs_bundle = load('ETFs')
start_dt = pd.Timestamp('2014-02-03', tz = 'utc')
end_dt = pd.Timestamp('2017-05-31', tz = 'utc')
etfs_data = DataPortal(etfs_bundle.asset_finder, get_calendar('NYSE'),
                       etfs_bundle.equity_daily_bar_reader.first_trading_day,
                       equity_minute_reader=etfs_bundle.equity_minute_bar_reader,
                       equity_daily_reader=etfs_bundle.equity_daily_bar_reader,
                       adjustment_reader=etfs_bundle.adjustment_reader)
etfs_symbols = []
for ticker in symbols:
    etfs_symbols.append(etfs_data.asset_finder.lookup_symbol(ticker,end_dt))
etfs_pricing = etfs_data.get_history_window(etfs_symbols,end_dt,1000,'1d','close')
etfs_pricing.asfreq('D').dropna().plot()```

**Comment by point049** [comment]
I ingested data from quandl, and I need to check what has been loaded i.e. start and end date as well as the list of symbols. 
the above code shared by @walterkissling looks promising. I tried to adapt it to quandl bundle but failed. 
any idea how I could resolve it?

from zipline.data.bundles import load, register
from zipline.data.data_portal import DataPortal
from zipline.utils.calendars import get_calendar
from zipline.data.bundles.quandl import quandl_bundle
import pandas as pd
symbols = ['AAPL']
register('quandl_bundle', quandl_bundle(symbols))
qd_bundle = load('quandl_bundle')
start_dt = pd.Timestamp('2014-02-03', tz = 'utc')
end_dt = pd.Timestamp('2017-05-31', tz = 'utc')
quandl_data = DataPortal(quandl_bundle.asset_finder, get_calendar('NYSE'),
                                quandl_bundle.equity_daily_bar_reader.first_trading_day,
                                equity_minute_reader=quandl_bundle.equity_minute_bar_reader,
                                equity_daily_reader=quandl_bundle.equity_daily_bar_reader,
                                adjustment_reader=quandl_bundle.adjustment_reader)
quandl_symbols = []
for ticker in symbols:
    quandl_symbols.append(quandl_data.asset_finder.lookup_symbol(ticker,end_dt))
quandl_pricing = quandl_data.get_history_window(quandl_symbols,end_dt,1000,'1d','close')
quandl_pricing.asfreq('D').dropna().plot()

**Comment by pluviosilla** [comment]
Did you ever get this to work?

**Comment by pluviosilla** [comment]
What if you wanted to view a list of equities present in a bundle? The DataPortal forces you to specify the equities you want to view ahead of time, when you instantiate the DataPortal object, so by definition, it can't provide a list of what the bundle contains.

**Comment by pluviosilla** [comment]
Thanks very much for taking time, Joe. Just minutes ago I found the same answer buried in a thread on the Zipline Google group.

import os
from pandas import Timestamp
from zipline.data.bundles import load

now = Timestamp.utcnow()
bundle = load('quantopian-quandl', os.environ, now)
symbols = set(str(asset.symbol) 
              for asset in bundle.asset_finder.retrieve_all(
                           bundle.asset_finder.equities_sids))

**Comment by zhaimac** [comment]
I tried this code on python 3.5 with quandl data bundle. it works. Thanks!

`
import os
import pandas as pd
from pandas import Timestamp
from zipline.data.bundles import load
from zipline.data.bundles.quandl import quandl_bundle
from zipline.data.data_portal import DataPortal
from zipline.utils.calendars import get_calendar

now = Timestamp.utcnow()
bundle = load('quandl', os.environ, now)

all_assets = bundle.asset_finder.retrieve_all(bundle.asset_finder.sids)
symbols = set(
    str(asset.symbol) for asset in bundle.asset_finder.retrieve_all(bundle.asset_finder.equities_sids)
)
print(symbols)

quandl_data = DataPortal(asset_finder= bundle.asset_finder,
                        trading_calendar = get_calendar('NYSE'),
                        first_trading_day = bundle.equity_daily_bar_reader.first_trading_day,
                        equity_minute_reader=bundle.equity_minute_bar_reader,
                        equity_daily_reader=bundle.equity_daily_bar_reader,
                        adjustment_reader=bundle.adjustment_reader)

print(quandl_data)
`

**Comment by life-elixir** [comment]
> I was able to do it like this. My custom bundle name is ETFs and I had already ingested it. I have no idea if this is the 'correct' way, but it worked for me.
> 
> ```
> from zipline.data.bundles import load, register
> from zipline.data.data_portal import DataPortal
> from zipline.utils.calendars import get_calendar
> from zipline.data.bundles.ETFs import ETFs
> import pandas as pd
> symbols = ['VOO','IEF']
> register('ETFs', ETFs(symbols))
> etfs_bundle = load('ETFs')
> start_dt = pd.Timestamp('2014-02-03', tz = 'utc')
> end_dt = pd.Timestamp('2017-05-31', tz = 'utc')
> etfs_data = DataPortal(etfs_bundle.asset_finder, get_calendar('NYSE'),
>                        etfs_bundle.equity_daily_bar_reader.first_trading_day,
>                        equity_minute_reader=etfs_bundle.equity_minute_bar_reader,
>                        equity_daily_reader=etfs_bundle.equity_daily_bar_reader,
>                        adjustment_reader=etfs_bundle.adjustment_reader)
> etfs_symbols = []
> for ticker in symbols:
>     etfs_symbols.append(etfs_data.asset_finder.lookup_symbol(ticker,end_dt))
> etfs_pricing = etfs_data.get_history_window(etfs_symbols,end_dt,1000,'1d','close')
> etfs_pricing.asfreq('D').dropna().plot()
> ```

How did you ingest the ETFs from Quandl? I have access to the paid version and I was wondering how to ingest the ETFs into zipline.

**Comment by walterkissling** [comment]
I don't use Quandl data. I've been using Norgate and they have a zipline package which handles all the ingestion for their data. The link is this: https://pypi.org/project/zipline-norgatedata/

If you read over the source code you can modify the _pricing_iter_equities() function to read in from your own data instaed of their software and use that. They also have ingestion for futures.

**Comment by tstevens02127** [comment]
@walterkissling That's a great idea... where did you find their source code?

**Comment by RichardDale** [comment]
It's down towards the bottom of the page in the section "Books/publications that use Zipline, adapted for Norgate Data use"
