### ISSUE TITLE
zipline-script.py problem on Windows due to missing "" in the path

### ISSUE THREAD

**Issue by PeterCherry** [quantopian/zipline#1591]
Dear Zipline developers,
there should be " " in the path to python.exe
When you run zipline from cmd, there is ,,failed to create process'' due to space in Program Files path.

WRONG:         #!C:/Program Files/Miniconda2\python.exe
SOLUTION:     #!"C:/Program Files/Miniconda2\python.exe"

**Comment by AndreasClenow** [comment]
Hi Peter,

I'm struggling with this issue over here. Do you know of a workaround for it? I tried anything I could think of, but can't get around this "failed to create process".

Thanks

**Comment by PeterCherry** [comment]
Hi,
try to add "" into this file:

C:\Program Files\Miniconda2\Scripts\zipline-script.py 
#!"C:/Program Files/Miniconda2\python.exe"
Peter

Dne 01.02.17, AndreasClenow  <notifications@github.com> napsal:

**Comment by AndreasClenow** [comment]
Thank you, Peter! You have no idea how long time I tried to solve this silly little issue!

That did the trick. You saved me a lot of time!

**Comment by richafrank** [comment]
This is a tough one. It looks like it's an [issue](https://github.com/pypa/setuptools/issues/398) in certain versions of setuptools that's affecting various installers. I tried some of the suggested patches from linked issues but couldn't get them working, so not sure we can do much in zipline.

The workarounds seem to be either editing the -script.py as suggested above, or installing conda in a directory without spaces in the path. Hopefully that helps people who come across this issue.
