### ISSUE TITLE
Zipline tries to downgrade pandas

### ISSUE THREAD

**Issue by MerlinBenj** [quantopian/zipline#1601]
Zipline tries to downgrade my pandas when I try to install on linux. (qgrid I recall, tries to do this also)

> pip install pandas -U
Requirement already up-to-date: pandas in /usr/lib64/python2.7/site-packages
Requirement already up-to-date: pytz>=2011k in /usr/lib/python2.7/site-packages (from pandas)
Requirement already up-to-date: numpy>=1.7.0 in /usr/lib64/python2.7/site-packages (from pandas)
Requirement already up-to-date: python-dateutil in /usr/lib/python2.7/site-packages (from pandas)
Requirement already up-to-date: six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil->pandas)

> pip list
....
pandas (0.19.1)
....

> pip install zipline 
Collecting zipline
  Downloading zipline-1.0.2.tar.gz (392kB)
    100% |████████████████████████████████| 399kB 119kB/s 
Requirement already satisfied (use --upgrade to upgrade): pip>=7.1.0 in /usr/lib/python2.7/site-packages (from zipline)
Requirement already satisfied (use --upgrade to upgrade): setuptools>18.0 in /usr/lib/python2.7/site-packages (from zipline)
Collecting Logbook>=0.12.5 (from zipline)
  Downloading Logbook-1.0.0.tar.gz (178kB)
    100% |████████████████████████████████| 184kB 224kB/s 
Requirement already satisfied (use --upgrade to upgrade): pytz>=2015.4 in /usr/lib/python2.7/site-packages (from zipline)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9.2 in /usr/lib64/python2.7/site-packages (from zipline)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.15.1 in /usr/lib64/python2.7/site-packages (from zipline)
Collecting pandas<0.18,>=0.16.1 (from zipline)
  Downloading pandas-0.17.1.zip (7.7MB)
    2% |▊                               | 184kB 150kB/s eta 0:00:50^C
Operation cancelled by user
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Please advise. On MacOSx, there does not seem to be a problem.

**Comment by ssanderson** [comment]
@SlyOne Zipline doesn't currently support pandas 0.19, so our setup.py file [specifies a dependency of pandas <0.19](https://github.com/quantopian/zipline/blob/master/setup.py#L165), which causes `pip` to downgrade your currently installed version.  The only thing I think we could reasonably do here is raise an error at installation time indicating that your currently installed pandas version is newer than what we support.

As far as getting Zipline to work for you, if you want to continue using the latest pandas somewhere else, I'd recommend installing in a separate virtualenv or conda env to install Zipline.

**Comment by SlyOne** [comment]
@ssanderson ....Why didnt  it download .18 vs 17.1 ? There should really be a dialog before downgrading and upgrading by listing all dependencies then (y/n) to confirm...

**Comment by ssanderson** [comment]
Ah, the version of Zipline currently released on PyPI is only up to pandas 0.17.  The development branch supports 0.18.  @richafrank @llllllllll @ehebert thoughts on cutting a release this week to let people use the newer pandas support?

w/r/t having a prompt before downgrading, agreed that that would be a nice feature, but that's not really in our control, since `pip` (or `conda` if that's how you're installing) is the project actually in control of fetching and installing dependencies.  As mentioned above, I think the "nicest" thing we can do here is fail with a useful error message indicating that Zipline doesn't yet support the latest pandas.

**Comment by ehebert** [comment]
Cutting a release sounds like a good idea to me.
Would the next release be `1.0.3` or `1.1.0`? (i.e. does upgrading one of the core dependencies warrant at least a bump on the minor revision.?)

**Comment by ssanderson** [comment]
@ehebert `1.1.0` makes sense to me.  @llllllllll @richafrank any objections.  We also probably need to take a look at the git log and update the whatsnew.

**Comment by llllllllll** [comment]
+1 from me

**Comment by richafrank** [comment]
👍

**Comment by FreddieV4** [comment]
Version `1.1.0` was released today, which has pandas 0.18 support.

**Comment by FreddieV4** [comment]
Going to close this :)
