### ISSUE TITLE
conflicting CLI flags for `clean`

### ISSUE THREAD

**Issue by pgeez** [quantopian/zipline#1624]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: `OS X 10.12.1`
* Python Version: `2.7`
* Python Bitness: `64`
* How did you install Zipline: `conda`
* Python packages: _default_

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
The CLI command `zipline clean` has conflicting flags for `-b, --bundle` and `-b, --before`. 

```
(zipline-venv) pgeez$ zipline clean --help
Usage: zipline clean [OPTIONS]

  Clean up data downloaded with the ingest command.

Options:
  -b, --bundle BUNDLE-NAME  The data bundle to clean.  [default: quantopian-
                            quandl]
  -b, --before TIMESTAMP    Clear all data before TIMESTAMP. This may not be
                            passed with -k / --keep-last
  -a, --after TIMESTAMP     Clear all data after TIMESTAMP This may not be
                            passed with -k / --keep-last
  -k, --keep-last N         Clear all but the last N downloads. This may not
                            be passed with -b / --before or -a / --after
  --help                    Show this message and exit.
```

* What happened instead?
Because of the conflict, `-b` defaults to `--before`.

Sincerely,
pgeez

**Comment by llllllllll** [comment]
Oops, sorry about that. Thanks for reporting this. Do you have a suggestion for a short-opt for `before`? I am thinking `-f`. Alternativly, if that is not that intuitive we could just remove the short-opt and require users to type `--before`.

**Comment by pgeez** [comment]
`e` or `f` sound good to me; I really don't have an opinion. I do think, though, that you should have a short-opt for `--before` for the sake of consistency with other CLI args.

**Comment by FreddieV4** [comment]
Hey @pgeez this should be fixed now in the latest zipline master thanks to the PR linked above ^^
