### ISSUE TITLE
error in docs for AssetDBWriter.write

### ISSUE THREAD

**Issue by pgeez** [quantopian/zipline#1626]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: `OSX 10.12.2`
* Python Version: `2.7`
* Python Bitness: `64`
* How did you install Zipline: `conda`
* Python packages: _default_

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
The docs for AssetDBWriter.write (http://www.zipline.io/appendix.html#zipline.assets.AssetDBWriter.write) explicitly state that `exchange` is optional for `equities`. It looks like `exchange` is required because `__init__` for `Equity` takes two positional args, `sid` and `exchange`.

See: https://github.com/quantopian/zipline/blob/master/zipline/assets/_assets.pyx#L77

Sincerely,
pgeez

**Comment by llllllllll** [comment]
Thanks for the report, the docs are in fact out of date here.
