### ISSUE TITLE
Installing Zipline on Datalab (running on Google Cloud Virtual Machine)

### ISSUE THREAD

**Issue by richardtbenade** [quantopian/zipline#1647]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Linux datalab 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64)
* Python Version: `default version that comes with Datalab`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`trying to use pip but not working`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Hi There

I'm trying to install Zipline on Datalab which is running on our Google Cloud Virtual Machine. According to http://www.zipline.io/install.html I should run: 
"$ pip install zipline"
but I get "invalid syntax" when I run this. Please advise. 
* What did you expect to happen?
Zipline to install
* What happened instead?
Invalid Syntax error
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Run $ pip install zipline on Datalab 
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by FreddieV4** [comment]
Hi there, thanks for posting this issue. Where are you running `pip install zipline` from? In `bash` of the Docker container? Or within an IPython notebook?

If you're getting an `invalid syntax` error, it then seems like to me that you're running it inside the notebook (?), in which case you would need to run this instead:
```
%%bash
pip install zipline
```

Ultimately this seems like an environment-specific issue and so while I can try to help you out, I can't guarantee that everything is going to work. Also just a note that it looks like Google DataLab is in beta and still has a lot of bugs in regards to the way their Docker containers manage Python packages.
