### ISSUE TITLE
yahoo bundles stopped working after latest Windows 10 update

### ISSUE THREAD

**Issue by modi5** [quantopian/zipline#1648]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
Windows 10 

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

Everything has worked fine for months until the latest windows 10 update the other day.

then zipline stopped working, and although i can ingest the quantopian/quandl bundles any yahoo based bundles dont work.  this is the error i'm getting when i try to ingest a yahoo bundle, which i need for my tickers:

TypeError: DataReader() got an unexpected keyword argument 'session'

any thoughts would be helpful as zipline is basically useless to me if i cant ingest my ticker list, unless there is another way to create a bundle of custom tickers (google, etc).

Thanks,
EM

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by modi5** [comment]
Actually I just reinstalled zipline and now it works again.

apparently the newest zipline install doesnt need a whl file?

**Comment by FreddieV4** [comment]
Hey @modi5 a couple of years ago we built wheels for zipline but we longer do this; if the source file works for you then you should be fine. You'd just need a conda/virtual environment for whatever version of zipline you'd like to use.
