### ISSUE TITLE
CFE was closed in honor of the passing of both Gerald Ford and Ronald Regan

### ISSUE THREAD

**Issue by trical09** [quantopian/zipline#1682]
CBOE and CFE observed the `USNationalDaysofMourning` and `HurricaneSandyClosings`:

`USNationalDaysofMourning`
http://www.mondovisione.com/news/cboe-and-cfe-will-be-closed-on-tuesday-january-2-to-honor-former-president-geral/
https://www.cboe.com/aboutcboe/legal/bulletins/archives/documents/eb062504.pdf

`HurricaneSandyClosings`
http://ir.cboe.com/press-releases/2012/29-oct-2012.aspx
http://www.cboe.com/publish/RegCir/RG12-146.pdf

`exchange_calendar_cfe.CFEExchangeCalendar `

should have the following:

    `@property
     def adhoc_holidays(self):
         return list(chain(
             HurricaneSandyClosings,
             USNationalDaysofMourning,
         ))`

**Comment by FreddieV4** [comment]
Hey @trical09 this looks pretty good to me; feel free to make a pull request 👍

**Comment by FreddieV4** [comment]
PR merged
