### ISSUE TITLE
Development Environment missing commands

### ISSUE THREAD

**Issue by bonesmccoy** [quantopian/zipline#1700]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux bones-alphai 4.8.0-39-generic #42~16.04.1-Ubuntu SMP Mon Feb 20 15:06:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: 2.7 (in a virtualenv)
* Python Bitness: 64
* How did you install Zipline:  from the source code

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I was setting up Zipline on dev environment (based on release 1.0.2 working dir) by following the instruction on the [wiki](https://github.com/quantopian/zipline/wiki/Development-Environment).
After installing everything I ran the`nosetest` command
```
nosetests --with-timer --with-coverage --cover-package=zipline --timer-top-n=1
```
* What did you expect to happen?
Test passing
* What happened instead?
I got two failures
```bash
ImportError: No module named talib
ImportError: No module named blaze
```
## What steps have you taken to resolve this already?
To fix them, I had to execute the following commands:
```bash
pip install -r ./etc/requirements_blaze.txt 
pip install -r ./etc/requirements_talib.txt 
```
It would be nice to have them in the documentation
Regards

Daniele

**Comment by FreddieV4** [comment]
Hey @bonesmccoy thanks for opening up this issue. I was considering moving the dev environment info from the wiki to [zipline.io](http://zipline.io); it'll take some time to do this on my end as I'm looking at some other stuff right now though feel free to submit a PR that fixes this

**Comment by bonesmccoy** [comment]
Sorry for the silly question: how do I submit a PR for updating the wiki ? thanks

**Comment by FreddieV4** [comment]
Oh, sorry if my response was vague. I meant that if you want to move the dev environment info to the zipline docs (on http://zipline.io), you could submit a PR for that (I'd like to move the dev environment docs myself to zipline.io but I'm currently looking at some other issues)

**Comment by bonesmccoy** [comment]
Thanks for the explanation. I'll work on it!
