### ISSUE TITLE
Pipeline error using non us equity

### ISSUE THREAD

**Issue by spyamine** [quantopian/zipline#1744]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

I tried to run the example momentum pipeline in zipline example, using data in form of a panel. When i tried to run the algorithm it give me the following message: "NoEngineRegistered: Attempted to run a pipeline but no pipeline resources were registered.".
I've made sure that I've used the attach_pipeline in the initialize function but still no success.

below the code I used:
`
"""
A simple Pipeline algorithm that longs the top 3 stocks by RSI and shorts
the bottom 3 each day.
"""
from six import viewkeys
from zipline.api import (
    attach_pipeline,
    date_rules,
    order_target_percent,
    pipeline_output,
    record,
    schedule_function,
)
from zipline.pipeline import Pipeline
from zipline.pipeline.factors import RSI

def make_pipeline():
    rsi = RSI()
    return Pipeline(
        columns={
            'longs': rsi.top(3),
            'shorts': rsi.bottom(3),
        },
    )

def rebalance(context, data):

    # Pipeline data will be a dataframe with boolean columns named 'longs' and
    # 'shorts'.
    pipeline_data = context.pipeline_data
    all_assets = pipeline_data.index

    longs = all_assets[pipeline_data.longs]
    shorts = all_assets[pipeline_data.shorts]

    record(universe_size=len(all_assets))

    # Build a 2x-leveraged, equal-weight, long-short portfolio.
    one_third = 1.0 / 3.0
    for asset in longs:
        order_target_percent(asset, one_third)

    for asset in shorts:
        order_target_percent(asset, -one_third)

    # Remove any assets that should no longer be in our portfolio.
    portfolio_assets = longs | shorts
    positions = context.portfolio.positions
    for asset in viewkeys(positions) - set(portfolio_assets):
        # This will fail if the asset was removed from our portfolio because it
        # was delisted.
        if data.can_trade(asset):
            order_target_percent(asset, 0)

def initialize(context):
    attach_pipeline(make_pipeline(), 'my_pipeline')

    # Rebalance each day.  In daily mode, this is equivalent to putting
    # `rebalance` in our handle_data, but in minute mode, it's equivalent to
    # running at the start of the day each day.
    schedule_function(rebalance, date_rules.every_day())

def before_trading_start(context, data):
    context.pipeline_data = pipeline_output('my_pipeline')

start = '2016-01-01'
end = '2017-01-01'

tickers = ["ADH MC Equity","ATW MC Equity","IAM MC Equity"]
data = get_pricing(tickers,"",start, end)
print data.axes

"""

[Index([u'ADH MC Equity', u'ATW MC Equity', u'IAM MC Equity'], dtype='object'), DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
               '2016-01-09', '2016-01-10',
               ...
               '2016-12-23', '2016-12-24', '2016-12-25', '2016-12-26',
               '2016-12-27', '2016-12-28', '2016-12-29', '2016-12-30',
               '2016-12-31', '2017-01-01'],
              dtype='datetime64[ns]', length=367, freq='D'), Index([u'mkt_cap', u'high', u'close', u'low', u'open', u'volume', u'turnover'], dtype='object')]

"""

from zipline.algorithm import TradingAlgorithm

# Create and run the algorithm.
algo = TradingAlgorithm(initialize=initialize,before_trading_start=before_trading_start)

results = algo.run(data)

`

* What did you expect to happen?
* What happened instead?
NoEngineRegistered                        Traceback (most recent call last)
<ipython-input-6-8ad76df152a8> in <module>()
      4 algo = TradingAlgorithm(initialize=initialize,before_trading_start=before_trading_start)
      5 
----> 6 results = algo.run(data)

C:\Program Files\Anaconda2\lib\site-packages\zipline\algorithm.pyc in run(self, data, overwrite_sim_params)
    686         try:
    687             perfs = []
--> 688             for perf in self.get_generator():
    689                 perfs.append(perf)
    690 

C:\Program Files\Anaconda2\lib\site-packages\zipline\gens\tradesimulation.pyc in transform(self)
    233                     self.simulation_dt = dt
    234                     algo.on_dt_changed(dt)
--> 235                     algo.before_trading_start(self.current_data)
    236                 elif action == MINUTE_END:
    237                     handle_benchmark(dt)

C:\Program Files\Anaconda2\lib\site-packages\zipline\algorithm.pyc in before_trading_start(self, data)
    451         with handle_non_market_minutes(data) if \
    452                 self.data_frequency == "minute" else ExitStack():
--> 453             self._before_trading_start(self, data)
    454 
    455         self._in_before_trading_start = False

<ipython-input-1-ed8cb518d3cf> in before_trading_start(context, data)
     66 
     67 def before_trading_start(context, data):
---> 68     context.pipeline_data = pipeline_output('my_pipeline')
     69 

C:\Program Files\Anaconda2\lib\site-packages\zipline\utils\api_support.pyc in wrapped(*args, **kwargs)
     49     def wrapped(*args, **kwargs):
     50         # Get the instance and call the method
---> 51         return getattr(get_algo_instance(), f.__name__)(*args, **kwargs)
     52     # Add functor to zipline.api
     53     setattr(zipline.api, f.__name__, wrapped)

C:\Program Files\Anaconda2\lib\site-packages\zipline\utils\api_support.pyc in wrapped_method(self, *args, **kwargs)
     96             if not self.initialized:
     97                 raise exception
---> 98             return method(self, *args, **kwargs)
     99         return wrapped_method
    100     return decorator

C:\Program Files\Anaconda2\lib\site-packages\zipline\algorithm.pyc in pipeline_output(self, name)
   2322                 valid=list(self._pipelines.keys()),
   2323             )
-> 2324         return self._pipeline_output(p, chunks)
   2325 
   2326     def _pipeline_output(self, pipeline, chunks):

C:\Program Files\Anaconda2\lib\site-packages\zipline\algorithm.pyc in _pipeline_output(self, pipeline, chunks)
   2333         except Expired:
   2334             data, valid_until = self._run_pipeline(
-> 2335                 pipeline, today, next(chunks),
   2336             )
   2337             self._pipeline_cache = CachedObject(data, valid_until)

C:\Program Files\Anaconda2\lib\site-packages\zipline\algorithm.pyc in _run_pipeline(self, pipeline, start_session, chunksize)
   2380 
   2381         return \
-> 2382             self.engine.run_pipeline(pipeline, start_session, end_session), \
   2383             end_session
   2384 

C:\Program Files\Anaconda2\lib\site-packages\zipline\pipeline\engine.pyc in run_pipeline(self, pipeline, start_date, end_date)
     77     def run_pipeline(self, pipeline, start_date, end_date):
     78         raise NoEngineRegistered(
---> 79             "Attempted to run a pipeline but no pipeline "
     80             "resources were registered."
     81         )

NoEngineRegistered: Attempted to run a pipeline but no pipeline resources were registered.

Sincerely,
`$ Amine`

**Comment by FreddieV4** [comment]
Hi @spyamine thanks for opening this issue. Can you provide me with some more information about your environment?

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: run `$ python --version`
* Python Bitness: run `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

I'll see if I can reproduce this issue as well

**Comment by FreddieV4** [comment]
Ah. I also just saw that you're calling `get_pricing` which is only available in the Quantopian research environment, so a call to that would not work in your `before_trading_start` AFAIK

I modified your algo code in this [gist](https://gist.github.com/FreddieV4/054e881dbe0732bdad687c97b3109978) to get it to work.

I ran this on a Windows 10 machine, using conda to create a Python 2.7 env called `zip27`. Ran `zipline ingest` and and then ran `zipline run -f noengineregistered.py --start 2016-01-01 --end 2017-01-01 -o perf.pickle` with no issues.

**Comment by spyamine** [comment]
Hi, thanks for the reply.
Regarding get_pricing it is a function that have the same name of the one in quantopian. my function gives me a panel data with the same structure as the one in Quantopian. For the environment, please find below the details:
$ uname --all
Darwin
$ python --version
Python 2.7.12 :: Anaconda custom (x86_64)
$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'
64
How did you install Zipline: (pip, conda, or other (please explain)):
using conda
$ conda list
# packages in environment at /Users/spyamine/anaconda:
#
_license                  1.1                      py27_1
_nb_ext_conf              0.3.0                    py27_0
alabaster                 0.7.9                    py27_0
alembic                   0.7.7                    py27_0    Quantopian
anaconda                  custom                   py27_0
anaconda-clean            1.0.0                    py27_0
anaconda-client           1.5.1                    py27_0
anaconda-navigator        1.3.1                    py27_0
appdirs                   1.4.3                     <pip>
appnope                   0.1.0                    py27_0
appscript                 1.0.1                    py27_0
arctic                    1.36.0                    <pip>
argcomplete               1.0.0                    py27_1
argparse                  1.4.0                     <pip>
astroid                   1.4.7                    py27_0
astropy                   1.0.4                np19py27_0
babel                     2.3.4                    py27_0
backports                 1.0                      py27_0
backports_abc             0.4                      py27_0
backtrader                1.9.40.116                <pip>
bcolz                     0.12.1               np19py27_0    Quantopian
beautifulsoup4            4.5.1                    py27_0
bitarray                  0.8.1                    py27_0
blaze                     0.10.1                   py27_0
bokeh                     0.12.2                   py27_0
boto                      2.42.0                   py27_0
bottleneck                1.0.0                np19py27_0
cachetools                1.1.6                    py27_0    Quantopian
cdecimal                  2.3                      py27_2
cffi                      1.7.0                    py27_0
chartpy                   0.5                       <pip>
chest                     0.2.3                    py27_0
click                     6.6                      py27_0
cloudpickle               0.2.1                    py27_0
clyent                    1.2.2                    py27_0
colorama                  0.3.7                    py27_0
colorlover                0.2.1                     <pip>
CommonMark                0.5.4                     <pip>
conda                     4.3.16                   py27_0
conda-build               2.0.2                    py27_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py27_0
configparser              3.5.0                    py27_0
contextlib2               0.5.3                    py27_0
cryptography              1.5                      py27_0
cufflinks                 0.8.2                     <pip>
curl                      7.49.0                        1
cvxopt                    1.1.9                     <pip>
cycler                    0.10.0                   py27_0
cyordereddict             0.2.2                    py27_0    Quantopian
cython                    0.24.1                   py27_0
cytoolz                   0.8.0                    py27_0
dask                      0.11.0                   py27_0
datashape                 0.5.2                    py27_0
decorator                 4.0.9                    py27_0
dill                      0.2.5                    py27_0
distribute                0.6.45                   py27_1
docutils                  0.12                     py27_2
dynd-python               0.7.2                    py27_0
empyrical                 0.2.0                    py27_0    Quantopian
entrypoints               0.2.2                    py27_0
enum34                    1.1.6                    py27_0
et_xmlfile                1.0.1                    py27_0
fastcache                 1.0.2                    py27_1
filelock                  2.0.6                    py27_0
flask                     0.11.1                   py27_0
flask-cors                2.1.2                    py27_0
freetype                  2.5.5                         1
funcsigs                  1.0.2                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.0.5                    py27_0
get_terminal_size         1.0.0                    py27_0
gevent                    1.1.2                    py27_0
greenlet                  0.4.10                   py27_0
grin                      1.2.1                    py27_3
h5py                      2.5.0                np19py27_3
hdf5                      1.8.15.1                      2
heapdict                  1.0.0                    py27_1
icu                       54.1                          0
idna                      2.1                      py27_0
imagesize                 0.7.1                    py27_0
inflection                0.3.1                     <pip>
intervaltree              2.1.0                    py27_0    Quantopian
ipaddress                 1.0.16                   py27_0
ipykernel                 4.5.0                    py27_0
ipython                   4.2.0                    py27_1
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.1                    py27_0
itsdangerous              0.24                     py27_0
jbig                      2.1                           0
jdcal                     1.2                      py27_1
jedi                      0.9.0                    py27_1
jinja2                    2.8                      py27_1
joblib                    0.10.3                    <pip>
jpeg                      8d                            2
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.4.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.2.0                    py27_0
Keras                     1.2.2                     <pip>
lazy-object-proxy         1.2.1                    py27_0
libdynd                   0.7.2                         0
libpng                    1.6.17                        0
libtiff                   4.0.6                         2
libxml2                   2.9.2                         0
libxslt                   1.1.28                        2
llvm                      3.3                           0
llvmlite                  0.13.0                   py27_0
llvmpy                    0.12.7                   py27_0
locket                    0.2.0                    py27_1
logbook                   0.12.5                   py27_0    Quantopian
lxml                      3.6.4                    py27_0
lz4                       0.8.2                     <pip>
mako                      1.0.6                    py27_0
markupsafe                0.23                     py27_2
matplotlib                1.4.3                np19py27_2
matplotlib                2.0.0                     <pip>
mistune                   0.7.3                    py27_1
mkl                       11.3.1                        0
mkl-service               1.1.2                    py27_2
mock                      2.0.0                     <pip>
mockextras                1.0.2                     <pip>
more-itertools            2.3                       <pip>
mpmath                    0.19                     py27_1
multipledispatch          0.4.8                    py27_0
multiprocess              0.70.4                    <pip>
munch                     2.1.1                     <pip>
munch                     2.1.0                    py27_0
nb_anacondacloud          1.2.0                    py27_0
nb_conda                  2.0.0                    py27_0
nb_conda_kernels          2.0.0                    py27_0
nbconvert                 4.2.0                    py27_0
nbformat                  4.1.0                    py27_0
nbpresent                 3.0.2                    py27_0
nbsphinx                  0.2.12                    <pip>
ndg-httpsclient           0.4.2                     <pip>
networkx                  1.11                     py27_0
nltk                      3.2.1                    py27_0
nose                      1.3.7                    py27_1
notebook                  4.2.3                    py27_0
numba                     0.15.1               np19py27_0
numexpr                   2.4.6                np19py27_0    Quantopian
numpy                     1.9.3                    py27_1
numpy                     1.12.1                    <pip>
numpydoc                  0.6.0                     <pip>
oauthlib                  2.0.1                     <pip>
odo                       0.5.0                    py27_1
opencv-python             3.2.0.6                   <pip>
openpyxl                  2.3.2                    py27_0
openssl                   1.0.2j                        0
packaging                 16.8                      <pip>
pandas                    0.16.2               np19py27_0
pandas                    0.17.1                    <pip>
pandas-datareader         0.2.1                    py27_0
partd                     0.3.6                    py27_0
path.py                   8.1.2                    py27_1
pathlib2                  2.1.0                    py27_0
patsy                     0.4.1                    py27_0
pbr                       1.10.0                    <pip>
pep8                      1.7.0                    py27_0
pexpect                   4.0.1                    py27_0
pickleshare               0.7.4                    py27_0
pillow                    3.3.1                    py27_0
pip                       9.0.1                     <pip>
pip                       8.1.2                    py27_0
pkginfo                   1.3.2                    py27_0
plotly                    2.0.0                     <pip>
ply                       3.9                      py27_0
prompt_toolkit            1.0.3                    py27_0
protobuf                  3.0.0b2                   <pip>
psutil                    4.3.1                    py27_0
ptyprocess                0.5.1                    py27_0
py                        1.4.31                   py27_0
PyAlgoTrade               0.18                      <pip>
pyasn1                    0.1.9                    py27_0
pyaudio                   0.2.7                    py27_0
Pycaishen                 1.0                       <pip>
pycosat                   0.6.1                    py27_1
pycparser                 2.14                     py27_1
pycrypto                  2.6.1                    py27_4
pycurl                    7.43.0                   py27_0
pydicom                   0.9.9                     <pip>
pyexcel                   0.4.2                     <pip>
pyexcel-io                0.3.0                     <pip>
pyflakes                  1.3.0                    py27_0
pyfolio                   0.6.0                     <pip>
pygments                  2.1.3                    py27_0
pykalman                  0.9.5                     <pip>
pylint                    1.5.4                    py27_1
pylzma                    0.4.8                     <pip>
pymc3                     3.0                       <pip>
pymongo                   3.4.0                     <pip>
pyopenssl                 16.2.0                   py27_0
pyparsing                 2.2.0                     <pip>
pyparsing                 2.0.3                    py27_0
pyqt                      5.6.0                    py27_0
PyScaffold                2.5.7                     <pip>
pytables                  3.2.2                np19py27_0
pytest                    2.9.2                    py27_0
python                    2.7.12                        1
python-dateutil           2.4.2                    py27_0
python.app                1.2                      py27_4
pytz                      2015.7                   py27_0
pyyaml                    3.12                     py27_0
pyzmq                     15.4.0                   py27_0
qstrader                  0.0.1                     <pip>
qt                        5.6.0                         0
qtawesome                 0.3.3                    py27_0
qtconsole                 4.2.1                    py27_1
qtpy                      1.1.2                    py27_0
Quandl                    3.0.1                     <pip>
readline                  6.2                           2
recommonmark              0.4.0                     <pip>
redis                     3.2.0                         0
redis-py                  2.10.5                   py27_0
requests                  2.12.4                   py27_0
requests-file             1.4.1                    py27_0
requests-oauthlib         0.7.0                     <pip>
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_0
scikit-image              0.11.3               np19py27_0
scikit-learn              0.18.1                    <pip>
scikit-learn              0.16.1               np19py27_0
scipy                     0.17.0               np19py27_0
seaborn                   0.7.1                     <pip>
setuptools                34.4.0                    <pip>
setuptools                27.2.0                   py27_0
simplegeneric             0.8.1                    py27_1
simplejson                3.10.0                    <pip>
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                    <pip>
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.3                    py27_0
sortedcontainers          1.4.4                    py27_0    Quantopian
sphinx                    1.4.6                    py27_0
spyder                    3.0.0                    py27_0
sqlalchemy                1.0.13                   py27_0
sqlite                    3.13.0                        0
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.6.1                np19py27_0
subprocess32              3.2.7                     <pip>
sympy                     1.0                      py27_0
ta-lib                    0.4.9                np19py27_0    quantopian
tensorflow                0.8.0                     <pip>
terminado                 0.6                      py27_0
texttable                 0.8.7                     <pip>
Theano                    0.8.2                     <pip>
tk                        8.5.18                        0
toolz                     0.8.0                    py27_0
tornado                   4.4.1                    py27_0
tqdm                      4.11.1                    <pip>
traitlets                 4.1.0                    py27_0
twython                   3.4.0                     <pip>
tzlocal                   1.3                       <pip>
unicodecsv                0.14.1                   py27_0
virtualenv                15.0.3                   py27_0
virtualenv                15.0.3                    <pip>
virtualenv                15.1.0                    <pip>
wcwidth                   0.1.7                    py27_0
werkzeug                  0.11.11                  py27_0
wheel                     0.29.0                   py27_0
widgetsnbextension        1.2.6                    py27_0
wrapt                     1.10.6                   py27_0
xlrd                      1.0.0                    py27_0
xlsxwriter                0.9.3                    py27_0
xlwings                   0.10.0                   py27_0
xlwt                      1.1.2                    py27_0
xz                        5.2.2                         0
yahoo-finance             1.4.0                     <pip>
yaml                      0.1.6                         0
ystockquote               0.2.4                     <pip>
zipline                   1.0.2                np19py27_0    Quantopian
zlib                      1.2.8                         3

**Comment by spyamine** [comment]
Hi, regarding the method you have used using ingesting. I'd rather want to use the get_pricing method and run it in a the ipython notebook environment so I can use it for different stock exchanges and sectors easily. Is there a way how to use it that way and get no error?
because i know that when you ingest data you should metadata about the assets i use and the different stock exchanges i use.

**Comment by FreddieV4** [comment]
Without your `get_pricing()` function:

- In your IPython Notebook, try putting `%load_ext zipline` in a separate cell at the top.

- Then, wherever your algo code exists, instead of called `algo.run()` on an instance of `TradingAlgorithm`, put `%%zipline run --start 2016-01-01 --end 2017-01-01 -o perf.pickle` at the top of the cell
- When you execute the cell the algorithm should then run and give you an output file called `perf.pickle`, which has the performance results of the algo.

I don't know how your `get_pricing` function works but I'm thinking that it would need to provide data in a similar way that data is provided in data bundles, in order for you to be able to run your algo with that data.

You could also create your own custom bundle that includes the tickers of equities you'd like to run your algo on.

**Comment by spyamine** [comment]
Thank you very much for the info. I'll try it and get back to you on that.

**Comment by FreddieV4** [comment]
@spyamine have you made any progress on this?

**Comment by spyamine** [comment]
Hi, I'm sorry I did not have time to try it. I was traveling since. will be back home soon and try it

Thanks for all

Amine

**Comment by FreddieV4** [comment]
Hi @spyamine I'm going to go ahead and close this issue. If you continue work on this and need more help, feel free to re-open this 🙂
