### ISSUE TITLE
Can't Run buyapple.py

### ISSUE THREAD

**Issue by ItsArjun** [quantopian/zipline#1752]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 7 32 bit)
* Python Version: `3.4`(Activated 3.4 from anaconda 3. using this method https://github.com/quantopian/zipline/issues/650#issuecomment-167050802
* IDE: PyCharm
 project interpreter: Python 3.6 Anaconda

Now that you know a little about me, let me tell you about the issue I am
having:

### Description of Issue
When i run the buyapple.py in terminal of Pycharm using the command
zipline run -f ../../zipline/examples/buyapple.py --start 2000-1-1 --end 2014-1-1 -o buyapple_out.pickle

I got the error: Got unexpected extra argument (C:/Github/zipline-1.1.0/zipline/examples/buyapple.py)

and I have no idea what buyapple_out.pickle is, i haven't created any file like that.

Any help would greatly be appreciated.

**Comment by FreddieV4** [comment]
Hi @ItsArjun, are you sure that the example algorithm is being ran in your conda environment and not your PyCharm 3.6 interpreter?

Also `buyapple_out.pickle` is the performance `DataFrame` in the pickle Python file format, which is specified using the `-o` flag and is created once your algo runs.

**Comment by ItsArjun** [comment]
Yes am running in conda environment, which is located in ...\Anaconda3\python.exe(3.6.0). I activated python 3.4 by using the command activate Python34 in Terminal which is my environment. 
This is what i did in terminal.

`D:\Folders\ArJuN\Coding>Activate Python34

(Python34) D:\Folders\ArJuN\Coding>zipline run -f D:\Folders\ArJuN\Coding\buyapple.py --start 2000-1-1 --end 2014-1
-1 -o buyapple_out.pickle
Usage: zipline run [OPTIONS]

Error: Invalid value for "-s" / "--start": 2000-1d is not a valid date
`
I think the issue might be sitting in the installation of Anaconda. I will post you after i install Anaconda using 3.4 instead of 3.6 and then check whether the buyapple.py works then.

**Comment by ItsArjun** [comment]
buyapple.py worked without doing anything to Anaconda. I just reinstalled Pycharm and setup everything clean and it just worked. Thanks for bothering.
