### ISSUE TITLE
run_algorithm keeps returning empty table on minute data

### ISSUE THREAD

**Issue by gijzelaerr** [quantopian/zipline#1756]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: `Python 3.6.0 :: Anaconda custom (32-bit)`
* Python Bitness: `32`
* How did you install Zipline:  `pip`
* Python packages: 
```
alabaster==0.7.9
alembic==0.9.1
anaconda-client==1.6.0
anaconda-navigator==1.5
anaconda-project==0.4.1
appdirs==1.4.3
astroid==1.4.9
astropy==1.3
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
bcolz==0.12.1
beautifulsoup4==4.5.3
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.4
boto==2.45.0
Bottleneck==1.2.0
cachetools==2.0.0
cffi==1.9.1
chardet==2.3.0
chest==0.2.3
click==6.7
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.3.7
comtypes==1.1.2
conda==4.3.16
configobj==5.0.6
contextlib2==0.5.4
coverage==4.3.4
cryptography==1.7.1
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.25.2
cytoolz==0.8.2
dask==0.13.0
datashape==0.5.4
decorator==4.0.11
dill==0.2.5
docutils==0.13.1
empyrical==0.2.2
et-xmlfile==1.0.1
fastcache==1.0.2
Flask==0.12
Flask-Cors==3.0.2
gevent==1.2.1
greenlet==0.4.11
h5py==2.6.0
HeapDict==1.0.0
hiredis==0.2.0
idna==2.2
imagesize==0.7.1
intervaltree==2.1.0
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
isort==4.2.5
itsdangerous==0.24
jdcal==1.3
jedi==0.9.0
Jinja2==2.9.4
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
lazy-object-proxy==1.2.2
llvmlite==0.15.0
locket==0.2.0
Logbook==1.0.0
lru-dict==1.1.6
lxml==3.7.2
Mako==1.0.6
MarkupSafe==1.0
matplotlib==2.0.0
menuinst==1.4.4
mistune==0.7.3
mpmath==0.19
multipledispatch==0.4.9
nbconvert==4.2.0
nbformat==4.2.0
networkx==1.11
nltk==3.2.2
nose==1.3.7
notebook==4.3.1
numba==0.30.1
numexpr==2.6.1
numpy==1.11.3
numpydoc==0.6.0
odo==0.5.0
openpyxl==2.4.1
packaging==16.8
pandas==0.19.2
pandas-datareader==0.3.0.post0
partd==0.3.7
path.py==0.0.0
pathlib2==2.2.0
patsy==0.4.1
pep8==1.7.0
pickleshare==0.7.4
Pillow==4.0.0
ply==3.9
prompt-toolkit==1.0.9
psutil==5.0.1
py==1.4.32
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.5.0
Pygments==2.1.3
pylint==1.6.4
pyOpenSSL==16.2.0
pyparsing==2.2.0
pytest==3.0.5
python-dateutil==2.6.0
python-editor==1.0.3
pythonnet==2.2.2
pytz==2016.10
pywin32==220
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.3
qtconsole==4.2.1
QtPy==1.2.1
redis==2.10.5
requests==2.12.4
requests-file==1.4.1
requests-ftp==0.3.1
rope-py3k==0.9.4.post1
scikit-image==0.12.3
scikit-learn==0.18.1
scipy==0.19.0
seaborn==0.7.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
sortedcontainers==1.5.7
sphinx==1.5.1
spyder==3.1.2
SQLAlchemy==1.1.5
statsmodels==0.6.1
sympy==1.0
tables==3.2.2
toolz==0.8.2
tornado==4.4.2
traitlets==4.3.1
unicodecsv==0.14.1
wcwidth==0.1.7
Werkzeug==0.11.15
widgetsnbextension==1.2.6
win-unicode-console==0.5
wrapt==1.10.8
xlrd==1.0.0
XlsxWriter==0.9.6
xlwings==0.10.2
xlwt==1.2.0
zipline==1.1.0
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?

a  `pd.DataFrame`  with the performance of the algorithm. Or a error that i'm doing something wrong.

* What happened instead?

empty data frame and a warning:

```
C:\Users\gijs\AppData\Local\Continuum\Anaconda3\lib\site-packages\empyrical\stats.py:579: RuntimeWarning: invalid value encountered in greater
  mask = downside_diff > 0
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

I'm trying to run run_algorithm on minute data. My data frame looks like this for a full day:

```
				Open	Close	Low  	High	Volume	Price
2017-03-28 07:01:00+02:00	3270.0	3289.0	3270.0	3289.0	24815.0	3272.903244
2017-03-28 07:02:00+02:00	3286.0	3286.0	3286.0	3286.0	120.0	3286.000000
2017-03-28 07:03:00+02:00	3281.0	3286.0	3281.0	3286.0	7017.0	3281.013539
2017-03-28 07:04:00+02:00	3282.0	3275.0	3275.0	3286.0	34703.0	3283.376250
2017-03-28 07:05:00+02:00	3279.0	3275.0	3263.0	3279.0	15822.0	3273.679054
2017-03-28 07:06:00+02:00	3275.0	3269.0	3264.0	3275.0	72674.0	3273.503550
```

I then put it in a panel and run it:
```
panel = pd.Panel({'MTN': ziplined})
panel.minor_axis = ['Open', 'High', 'Low', 'Close', 'Volume', 'Price']

start = panel.major_axis.min()
end = panel.major_axis.max()
perf = run_algorithm(start=start, end=end, data_frequency='minute', data=panel, initialize=initialize, capital_base=10000)
```
Also just feeding the dataframe as data doesn't do anything. My start and end values look good:

```
Timestamp('2017-03-28 07:01:00+0200', tz='Africa/Johannesburg')
Timestamp('2017-03-28 15:08:00+0200', tz='Africa/Johannesburg')
```
...

## What steps have you taken to resolve this already?

A lot of things. tried a putting data in a Panel and DataFrame, tried older and newer zipline and pandas. Tried to add .to_pydatetime() to the start and end timestamp.  Remove and change TZ data. Also various (example and empty) trading strategies.

Sincerely,
 - Gijs

**Comment by FreddieV4** [comment]
Hi @gijzelaerr thanks for posting about this issue. I noticed that you're using different versions of pandas and numpy that zipline does not currently use (and see that you tried with different versions).

Have you tried creating a Python 3.4 env using **conda create -n zip34 python=3.4** and then running **conda install -c Quantopian zipline**?

**Comment by gijzelaerr** [comment]
So, this is actually an other issue, but when I try to use conda it fails:
```
(zip34) λ conda install -c Quantopian zipline
Fetching package metadata ...............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.4*
  - zipline
Use "conda info <package>" to see the dependencies for each package.
```

This is the reason why I was using pip for zipline.

**Comment by FreddieV4** [comment]
Hmm if you've created a fresh conda env I don't see why you would be getting a conflict like that. We don't include Windows 32-bit in our integration tests so I'm not sure if that has something to do with it.

**Comment by gijzelaerr** [comment]
well, i created a fresh conda environment :)  using the command you supplied.

**Comment by richafrank** [comment]
Regarding the install, that makes sense. As @FreddieV4 said, we're not producing 32-bit packages anymore. We made some a while ago, but looks like only for python 2.7, so you're seeing the conflict between python 3.4 and zipline when installing for win-32.

pip or win-64 conda should install zipline successfully. For pip, you'll need to make sure it can compile zipline's C extensions, whereas the conda packages are already compiled.

**Comment by gijzelaerr** [comment]
i can confirm that the installation works with a 64 bit conda with python 3.4. Still, i'm getting an empty performance table returned by `zipline.run_algorithm()`.

**Comment by dmichalowicz** [comment]
Hi @gijzelaerr sorry for the silence here, is this still an issue for you?

**Comment by gijzelaerr** [comment]
Hehe, no. meanwhile I became a millionaire, lost all my money and became a father of two. I moved on ;) thanks!
