### ISSUE TITLE
run_pipeline equivalent in zipline 

### ISSUE THREAD

**Issue by I-Larsson** [quantopian/zipline#1759]
Hi there, 

I have ingested data from yahoo-finance, and now want to start researching by using pipeline api. The issue I'm having is that there does not seem any way to load ingested data in the following pipeline-format: 

"run_pipeline(my_pipeline(), start_date, end_date)". 

There is a momentum strategy with pipeline in the examples (https://github.com/quantopian/zipline/tree/master/zipline/examples), but this requires to run the whole algorithm. I guess I could print the results along the way, but that seems like a crude way of doing it. 

My question is if there are any alternatives for run_pipeline-format outside run_algorithm for ingested data? 

Relevant posts are: 
* https://github.com/quantopian/zipline/issues/911
* https://www.quantopian.com/posts/possible-to-simulate-inputs-to-pipeline-in-the-research-platform

However these posts seem to deal with custom data, and not ingested data. 

Best,

**Comment by pluviosilla** [comment]
Pity no one ever answered your question! It is actually a pretty good question, imo. If run_algorithm is needed in the research environment, why wouldn't something similar be needed in zipline? ALL the tutorial examples are currently broken. The notebook examples assume you can launch the algorithm with %% magic like this:
%%zipline --start 2016-1-1 --end 2018-1-1 
Who knows what version of Python, iPython, Jupyter and Zipline that worked on. I'm running Python 3.5 for Zipline compatibility, but none of the Zipline samples work for me. Do these samples work on Windows at all? Or do I need to switch to Ubuntu? I'm left wondering. Zipline examples also appear to depend on DataReader, which has undergone some changes lately that break the examples. I know it's a pain to maintain samples, but running the first program is always painful, so basic "Hello, world" tutorials should really be kept current. As for running Zipline from the command line, how about some guidance on how to import Zipline into Pycharm?

**Comment by llllllllll** [comment]
This was discussed in some other issues, and was recently discussed on the mailing list: https://groups.google.com/forum/#!topic/zipline/kOazUWbki6U
Regarding the examples, these are tested automatically with our CI system on both GNU+Linux and Windows. If they are not working that is a bug, would you like to open a new issue for that?
