### ISSUE TITLE
Yahoo Bundle Factories example not working

### ISSUE THREAD

**Issue by DMTSource** [quantopian/zipline#1771]
I am attempting to use the example for the Yahoo Bundle Factories:
http://www.zipline.io/bundles.html#yahoo-bundle-factories

But I get the following errors. Ubuntu 1404, just upgraded to zipline 1.1.0. Using the exact example from the link above. My hope is to, when its working, add the SPY symbol so I can use that price data in zipline.

zipline ingest -b my-yahoo-equities-bundle
Merging daily equity files:  [------------------------------------]  2#]  100%
Merging daily equity files:  [####################################]   
Downloading Yahoo adjustment data:   [####################################]  100%
Traceback (most recent call last):
  File "/usr/local/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.1.0', 'console_scripts', 'zipline')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zipline/__main__.py", line 312, in ingest
    show_progress,
  File "/usr/local/lib/python2.7/dist-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/usr/local/lib/python2.7/dist-packages/zipline/data/bundles/yahoo.py", line 178, in ingest
    adjustment_writer.write(splits=splits, dividends=dividends)
  File "/usr/local/lib/python2.7/dist-packages/zipline/data/us_equity_pricing.py", line 1169, in write
    self.write_frame('splits', splits)
  File "/usr/local/lib/python2.7/dist-packages/zipline/data/us_equity_pricing.py", line 931, in write_frame
    frame,
  File "/usr/local/lib/python2.7/dist-packages/zipline/data/us_equity_pricing.py", line 891, in _write
    frame.columns.tolist(),
ValueError: Unexpected frame columns:
Expected Columns: set(['effective_date', 'ratio', 'sid'])
Received Columns: ['effective_date', 'ratio', 'sid']

**Comment by richafrank** [comment]
Interesting - we have a similar report in https://github.com/quantopian/zipline/issues/1641, but we haven't been able to reproduce it...

Anything you can do to help us repro would be much appreciated. As a start, could you tell us more about your environment?

    Python Version: $ python --version
    Python Bitness: $ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'
    How did you install Zipline: (pip, conda, or other (please explain))
    Python packages: $ pip freeze or $ conda list

**Comment by DMTSource** [comment]
My pleasure,

Python Version:  **Python 2.7.6**

Python Bitness:  **64**

How did you install Zipline: **sudo pip install zipline --upgrade**, I think I already had the 1.1.0 version of zipline from recent work. But I hit this bug, and attempted to upgrade to the newest version in case that was an issue. No change occurred. [Here is the log from that upgrade in case it tells more](https://www.dropbox.com/s/8vh22m3lczyuqbt/upgrade_log.txt?dl=0) about issues(check tables for example I saw an error there) than the below freeze.

Python packages: $ [pip freeze yielded the following](https://www.dropbox.com/s/ztfsadxlhmadtdz/pipfreeze_ybf_bug.txt?dl=0)(kept warning at end just in case):

**Comment by FreddieV4** [comment]
Hi @DMTSource I'm wondering if this is an issue with Python 2.7.6. Would you be able to either upgrade your version of Python to 2.7.13 or create a conda env with Python 2.7.13, and then try running `ingest` again on your custom bundle?

**Comment by FreddieV4** [comment]
Hi there. We've removed Yahoo related code in the latest release so the bundle no longer exists. Going to close this :)

**Comment by tibkiss** [comment]
This issue is also present on Python 2.7.5, but the code works on Python 2.7.10.
It is not yahoo bundle related, custom bundles are also affected by this issue.

Casting the viewkeys(expected_dtypes) to frozenset(viewkeys(expected_dtypes)) solved the problem for me: 
https://github.com/quantopian/zipline/blob/77922ddedced4458fba7d2cb4c2a0826260f82fc/zipline/data/us_equity_pricing.py#L918

Will open a PR.
