### ISSUE TITLE
Ingesting custom futures data in zipline

### ISSUE THREAD

**Issue by mayurbakhai** [quantopian/zipline#1781]
Dear Zipline Maintainers,

Apologies for skipping the usual format, I have a more general question..

I tried out latest version of zipline from github for backtesting futures. I have futures data with roll date and spread info. I was able to ingest dividend and split info for equities by supplying dividends and splits dataframes to `adjustment_writer`. How can I ingest futures data with roll date and spread info in zipline? I'd be curious to see what `ingest` would look like. Also, would you recommend separate data bundles for equities and futures or they can be ingested in the same bundle?

Best,
Mayur

**Comment by mayurbakhai** [comment]
You can close this issue as #603 is open.

**Comment by FreddieV4** [comment]
Hi @mayurbakhai. In regards to the last question you have, in terms of having separate data bundles, I'm not sure which would be best. I suppose it would be dependent on the data you have and if you want to mix futures and equities data in an algo.
