### ISSUE TITLE
Add unit test for FixedSlippage and check possible error when order amount in 0 

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#179]
The following code block in `FixedSlippage.simulate` is under question:

```
if zp_math.tolerant_equals(order.amount, 0):
    return txns
```

It should most likely be a `continue` there, so that the order loop doesn't get short circuited erroneously.

`tests/finance/slippage.py` currently only tests VolumeShareSlippage, so the addition of FixedSlippage to that test suite is needed while testing that fix.

**Comment by richafrank** [comment]
Looks like this is out of date - we [now] (https://github.com/quantopian/zipline/blob/bbb9cc87a9085b55a09afc547d2f62650678691f/zipline/finance/transaction.py#L72-L72) raise an exception in this case.  Feel free to re-open if this is still valid in some new way.
