### ISSUE TITLE
Remove deprecated Yahoo code

### ISSUE THREAD

**Issue by freddiev4** [quantopian/zipline#1805]
As a result of https://github.com/quantopian/zipline/issues/1776, we'll no longer be able to use the Yahoo API to load data for bundles or benchmarks.

Some of the deprecated code can be founder in [loader.py](https://github.com/quantopian/zipline/blob/be8ea7c54c940b3cb3d804db3ec3af7c0fb374f0/zipline/data/loader.py), and also references to `load_bars_from_yahoo` can be removed.

And also the entire data bundle in `zipline.data.bundles` in `yahoo.py`

**Comment by souravsingh** [comment]
I am interested in working on the issue.

**Comment by FreddieV4** [comment]
Hi @souravsingh thanks for offering to work on this issue. I think @mmargenot is working on this currently, because he's been assigned to this issue; if he says he's no longer working on this then feel free to work on it.

Also need to finish up some work on this [branch](https://github.com/quantopian/zipline/tree/google-finance-for-benchmarking) beforehand.

**Comment by FreddieV4** [comment]
x-ref https://github.com/quantopian/zipline/pull/1867

**Comment by Vaibhavdixit02** [comment]
Hey, I would like to work on this issue, can someone help me out?

**Comment by souravsingh** [comment]
The issue can be closed since it is fixed.

**Comment by FreddieV4** [comment]
Hi @Vaibhavdixit02 I actually removed the remaining code in this PR https://github.com/quantopian/zipline/pull/1972 so just waiting to merge that. @souravsingh I'll close this once I merge that PR 🙂

**Comment by freddiev4** [comment]
#2032 should close this

**Comment by ferhatelmas** [comment]
@freddiev4 ping :smile:

**Comment by freddiev4** [comment]
Hi @ferhatelmas this code was removed in the PR linked above so I'll close this issue on the next release 🙂

**Comment by HyperionSounds** [comment]
I'm pretty new to zipline - I've tried writing custom bundles with google to limited success. Is there something comparable that I can use to load_bars_from_yahoo?

**Comment by freddiev4** [comment]
Hi @HyperionSounds the `load_bars_from_yahoo` work was removed a while ago, so the closest thing we have to that now is the ability to [ingest .csv files](http://www.zipline.io/bundles.html#ingesting-data-from-csv-files)
