### ISSUE TITLE
zipline does not work on current Arch linux / installed using pip

### ISSUE THREAD

**Issue by markfink** [quantopian/zipline#1808]
# Environment

$ uname -a
Linux osaka 4.9.28-1-MANJARO #1 SMP PREEMPT Sun May 14 13:32:39 UTC 2017 x86_64 GNU/Linux
$ python --version
Python 2.7.13
$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'
64
$ pip freeze
alembic==0.9.2
appdirs==1.4.3
bcolz==0.12.1
Bottleneck==1.2.1
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.25.2
decorator==4.0.11
empyrical==0.2.2
intervaltree==2.1.0
Logbook==1.0.0
lru-dict==1.1.6
Mako==1.0.6
MarkupSafe==1.0
multipledispatch==0.4.9
networkx==1.11
numexpr==2.6.2
numpy==1.12.1
packaging==16.8
pandas==0.18.1
pandas-datareader==0.4.0
patsy==0.4.1
pyparsing==2.2.0
python-dateutil==2.6.0
python-editor==1.0.3
pytz==2017.2
requests==2.14.2
requests-file==1.4.2
requests-ftp==0.3.1
scipy==0.19.0
six==1.10.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.10
statsmodels==0.8.0
tables==3.4.2
toolz==0.8.2
zipline==1.1.0

# Description of Issue

* What did you expect to happen?
I am working through the zipline beginners tutorial so I expected to see some help.

* What happened instead?
$ zipline run --help
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/home/mark/devel/portfolio/venv/bin/zipline", line 7, in <module>
    from zipline.__main__ import main
  File "/home/mark/devel/portfolio/venv/lib/python2.7/site-packages/zipline/__init__.py", line 38, in <module>
    from . import finance
  File "/home/mark/devel/portfolio/venv/lib/python2.7/site-packages/zipline/finance/__init__.py", line 16, in <module>
    from . import execution, trading
  File "/home/mark/devel/portfolio/venv/lib/python2.7/site-packages/zipline/finance/execution.py", line 22, in <module>
    import zipline.utils.math_utils as zp_math
  File "/home/mark/devel/portfolio/venv/lib/python2.7/site-packages/zipline/utils/math_utils.py", line 52, in <module>
    nanmean = bn.nanmean
AttributeError: 'module' object has no attribute 'nanmean'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. open a terminal 
2. activate virtualenv ('. ./venv/bin/activate')
3. `zipline run --help`

## What steps have you taken to resolve this already?

* I read your installation docu for Arch linux
* reinstalled the os dependencies `sudo pacman -S lapack gcc gcc-fortran pkg-config`
...

# Anything else?

* what is your Linux target environment where I can expect less trouble? if zipline does not work on Arch I could use docker / vagrant to set things up

Best Regards,
Mark

**Comment by ivanlen** [comment]
+1 here. I installed zipline using pip in a venv and I am having the same problem, but in MacOs.

**Comment by ivanlen** [comment]
Hey @markfink I have some news about this issue. I could solve it installing zipline using conda.
Apparently the problem was caused because I needed to downgrade numpy and other packages.

I downloaded conda, then I created a venv using conda (It might take a while because it installs a lot of packages), and the I installed zipline using conda. Whe installing zipline using conda, conda downgraded some packages and now it is working properly.

Hope this helps you.

**Comment by markfink** [comment]
@ivanlen not really a solution to my problem I am using pip not conda.

**Comment by llllllllll** [comment]
It looks like one of the Cython packages was compiled against a different version of numpy than you currently have installed. Did you manually update numpy? To test this, could you create a new empty venv and manually install numpy==1.11.1 then install zipline?

Regarding your question about the a different os: I personally run arch and find it works fine. Would a pkgbuild be helpful for you or would you rather manage the dependencies with pip?

**Comment by liutuo** [comment]
Use a different way of installing numpy works for me. For mac user, install numpy from [numpy 1.13rc2](numpy-1.13.0rc2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl)

**Comment by cgdeboer** [comment]
1.13.0rc2 is working for me. Though, it is incredibly odd that the latest version of `bottleneck` and latest version (non-RC) of `numpy` don't play well together.

**Comment by markfink** [comment]
Thank you for your help guys!
I created a fresh virtualenv using `virtualenv venv`+ activated it
I created a requirements.txt file:
```
numpy==1.13.0rc2
zipline
```

installation:
```
$ pip install -r requirements.txt
```

So now `zipline run --help` gives me a nice output.

@cgdeboer I did not get your remark about `bottleneck`. what am I supposed to do here?

**Comment by cgdeboer** [comment]
@markfink, nothing to do. I was merely bemoaning the notion that the latest release of each package don't seem to be working well with each other. It is mysterious and mildly troubling.

**Comment by markfink** [comment]
@llllllllll I just recently moved to Arch after using Ubuntu (since ~2008). I also use OSX and Amazonlinux (Centos6). I use virtualenv and pip to install my own stuff on these environments so a pkgbuild would not be useful me.
