### ISSUE TITLE
Add Blotter specific tests

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#183]
Add unit tests that isolate the blotter.

When adding those tests, make sure to ensure that the checks for order and transaction alignment in `process_trade` are aligned.

**Comment by richafrank** [comment]
Looks like we added [blotter tests] (https://github.com/quantopian/zipline/blob/b863733953c8a2a268a37ea86a39d8fefc0bb1e1/tests/test_blotter.py#L37-L37).
