### ISSUE TITLE
HTTPError for CSV data

### ISSUE THREAD

**Issue by reMAJ** [quantopian/zipline#1835]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10)
* Python Version: Python 2.7.13 :: Anaconda 4.4.0 (32-bit)
* Python Bitness:  32
* How did you install Zipline: pip install zipline (I tried conda install it failed)
* Python packages: (cse_32_2_7) C:\WINDOWS\system32>conda list
 packages in environment at C:\Anaconda2\envs\cse_32_2_7:

_license                  1.1                      py27_1
alabaster                 0.7.10                   py27_0
alembic                   0.9.2                     <pip>
anaconda                  4.4.0               np112py27_0
anaconda-client           1.6.3                    py27_0
anaconda-navigator        1.6.2                    py27_0
anaconda-project          0.6.0                    py27_0
asn1crypto                0.22.0                   py27_0
astroid                   1.4.9                    py27_0
astropy                   1.3.2               np112py27_0
babel                     2.4.0                    py27_0
backports                 1.0                      py27_0
backports_abc             0.5                      py27_0
bcolz                     0.12.1                    <pip>
beautifulsoup4            4.6.0                    py27_0
bitarray                  0.8.1                    py27_1
blaze                     0.10.1                   py27_0
bleach                    1.5.0                    py27_0
bokeh                     0.12.5                   py27_1
boto                      2.46.1                   py27_0
bottleneck                1.2.1               np112py27_0
bzip2                     1.0.6                     vc9_3  [vc9]
cdecimal                  2.3                      py27_2
cffi                      1.10.0                   py27_0
chardet                   3.0.3                    py27_0
click                     6.7                      py27_0
cloudpickle               0.2.2                    py27_0
clyent                    1.2.2                    py27_0
colorama                  0.3.9                    py27_0
comtypes                  1.1.2                    py27_0
configparser              3.5.0                    py27_0
console_shortcut          0.1.1                    py27_1
contextlib2               0.5.5                    py27_0
cryptography              1.8.1                    py27_0
curl                      7.52.1                    vc9_0  [vc9]
cycler                    0.10.0                   py27_0
cyordereddict             1.0.0                     <pip>
cython                    0.25.2                   py27_0
cytoolz                   0.8.2                    py27_0
dask                      0.14.3                   py27_1
datashape                 0.5.4                    py27_0
decorator                 4.0.11                   py27_0
distributed               1.16.3                   py27_0
docutils                  0.13.1                   py27_0
empyrical                 0.2.2                     <pip>
entrypoints               0.2.2                    py27_1
enum34                    1.1.6                    py27_0
et_xmlfile                1.0.1                    py27_0
fastcache                 1.0.2                    py27_1
flask                     0.12.2                   py27_0
flask-cors                3.0.2                    py27_0
freetype                  2.5.5                     vc9_2  [vc9]
funcsigs                  1.0.2                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.1.1                    py27_0
get_terminal_size         1.0.0                    py27_0
gevent                    1.2.1                    py27_0
greenlet                  0.4.12                   py27_0
grin                      1.2.1                    py27_3
h5py                      2.7.0               np112py27_0
hdf5                      1.8.15.1                  vc9_4  [vc9]
heapdict                  1.0.0                    py27_1
html5lib                  0.999                    py27_0
icu                       57.1                      vc9_0  [vc9]
idna                      2.5                      py27_0
imagesize                 0.7.1                    py27_0
intervaltree              2.1.0                     <pip>
ipaddress                 1.0.18                   py27_0
ipykernel                 4.6.1                    py27_0
ipython                   5.3.0                    py27_0
ipython_genutils          0.2.0                    py27_0
ipywidgets                6.0.0                    py27_0
isort                     4.2.5                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.3                      py27_0
jedi                      0.10.2                   py27_2
jinja2                    2.9.6                    py27_0
jpeg                      9b                        vc9_0  [vc9]
jsonschema                2.6.0                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            5.0.1                    py27_0
jupyter_console           5.1.0                    py27_0
jupyter_core              4.3.0                    py27_0
lazy-object-proxy         1.2.2                    py27_0
libpng                    1.6.27                    vc9_0  [vc9]
libtiff                   4.0.6                     vc9_3  [vc9]
llvmlite                  0.18.0                   py27_0
locket                    0.2.0                    py27_1
Logbook                   1.0.0                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      3.7.3                    py27_0
Mako                      1.0.6                     <pip>
markupsafe                0.23                     py27_2
matplotlib                2.0.2               np112py27_0
menuinst                  1.4.7                    py27_0
mistune                   0.7.4                    py27_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py27_3
mpmath                    0.19                     py27_1
msgpack-python            0.4.8                    py27_0
multipledispatch          0.4.9                    py27_0
navigator-updater         0.1.0                    py27_0
nbconvert                 5.1.1                    py27_0
nbformat                  4.3.0                    py27_0
networkx                  1.11                     py27_0
nltk                      3.2.3                    py27_0
nose                      1.3.7                    py27_1
notebook                  5.0.0                    py27_0
numba                     0.33.0              np112py27_0
numexpr                   2.6.2               np112py27_0
numpy                     1.12.1                   py27_0
numpydoc                  0.6.0                    py27_0
odo                       0.5.0                    py27_1
olefile                   0.44                     py27_0
openpyxl                  2.4.7                    py27_0
openssl                   1.0.2l                    vc9_0  [vc9]
packaging                 16.8                     py27_0
pandas                    0.18.1                    <pip>
pandas                    0.20.1              np112py27_0
pandas-datareader         0.4.0                     <pip>
pandocfilters             1.4.1                    py27_0
partd                     0.3.8                    py27_0
path.py                   10.3.1                   py27_0
pathlib2                  2.2.1                    py27_0
patsy                     0.4.1                    py27_0
pep8                      1.7.0                    py27_0
pickleshare               0.7.4                    py27_0
pillow                    4.1.1                    py27_0
pip                       9.0.1                    py27_1
ply                       3.10                     py27_0
prompt_toolkit            1.0.14                   py27_0
psutil                    5.2.2                    py27_0
py                        1.4.33                   py27_0
pycosat                   0.6.2                    py27_0
pycparser                 2.17                     py27_0
pycrypto                  2.6.1                    py27_6
pycurl                    7.43.0                   py27_2
pyflakes                  1.5.0                    py27_0
pygments                  2.2.0                    py27_0
pylint                    1.6.4                    py27_1
pyodbc                    4.0.16                   py27_0
pyopenssl                 17.0.0                   py27_0
pyparsing                 2.1.4                    py27_0
pyqt                      5.6.0                    py27_2
pytables                  3.2.2               np112py27_4
pytest                    3.0.7                    py27_0
python                    2.7.13                        1
python-dateutil           2.6.0                    py27_0
python-editor             1.0.3                     <pip>
pytz                      2017.2                   py27_0
pywavelets                0.5.2               np112py27_0
pywin32                   220                      py27_2
pyyaml                    3.12                     py27_0
pyzmq                     16.0.2                   py27_0
qt                        5.6.2                     vc9_4  [vc9]
qtawesome                 0.4.4                    py27_0
qtconsole                 4.3.0                    py27_0
qtpy                      1.2.1                    py27_0
requests                  2.14.2                   py27_0
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_1
scandir                   1.5                      py27_0
scikit-image              0.13.0              np112py27_0
scikit-learn              0.18.1              np112py27_1
scipy                     0.19.0              np112py27_0
seaborn                   0.7.1                    py27_0
setuptools                27.2.0                   py27_1
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sortedcollections         0.5.3                    py27_0
sortedcontainers          1.5.7                    py27_0
sphinx                    1.5.6                    py27_0
spyder                    3.1.4                    py27_0
sqlalchemy                1.1.9                    py27_0
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.8.0               np112py27_0
subprocess32              3.2.7                    py27_0
sympy                     1.0                      py27_0
tables                    3.4.2                     <pip>
tblib                     1.3.2                    py27_0
testpath                  0.3                      py27_0
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.2                    py27_0
tornado                   4.5.1                    py27_0
traitlets                 4.3.2                    py27_0
unicodecsv                0.14.1                   py27_0
vs2008_runtime            9.00.30729.5054               0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py27_0
werkzeug                  0.12.2                   py27_0
wheel                     0.29.0                   py27_0
widgetsnbextension        2.0.0                    py27_0
win_unicode_console       0.5                      py27_0
wrapt                     1.10.10                  py27_0
xlrd                      1.0.0                    py27_0
xlsxwriter                0.9.6                    py27_0
xlwings                   0.10.4                   py27_0
xlwt                      1.2.0                    py27_0
zict                      0.1.2                    py27_0
zipline                   1.1.0                     <pip>
zlib                      1.2.8                     vc9_3  [vc9]

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? Run the simple buyapple algorithm on CSV data (The data is not really of AAPL)
* What happened instead?
Traceback (most recent call last):

  File "<ipython-input-17-935ec0a27ac6>", line 1, in <module>
    runfile('D:/Data/CSE/zip_a.py', wdir='D:/Data/CSE')

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/Data/CSE/zip_a.py", line 29, in <module>
    algo_obj = TradingAlgorithm(initialize=initialize, handle_data=handle_data, capital_base = 100000.0)

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\zipline\algorithm.py", line 280, in __init__
    self.trading_environment = TradingEnvironment()

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\zipline\finance\trading.py", line 101, in __init__
    self.bm_symbol,

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\zipline\data\loader.py", line 164, in load_market_data
    trading_day,

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\zipline\data\loader.py", line 247, in ensure_benchmark_data
    last_date,

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\zipline\data\benchmarks.py", line 59, in get_benchmark_returns
    squeeze=True,  # squeeze tells pandas to make this a Series

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\pandas\io\parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\pandas\io\parsers.py", line 301, in _read
    compression=kwds.get('compression', None))

  File "C:\Anaconda2\envs\cse_32_2_7\lib\site-packages\pandas\io\common.py", line 308, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))

  File "C:\Anaconda2\envs\cse_32_2_7\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)

  File "C:\Anaconda2\envs\cse_32_2_7\lib\urllib2.py", line 435, in open
    response = meth(req, response)

  File "C:\Anaconda2\envs\cse_32_2_7\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)

  File "C:\Anaconda2\envs\cse_32_2_7\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)

  File "C:\Anaconda2\envs\cse_32_2_7\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)

  File "C:\Anaconda2\envs\cse_32_2_7\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

HTTPError: Not Found

Here is how you can reproduce this issue on your machine: The following is the code I use. The CSV files are in the working directory. The file name (before .csv) is the symbol name.

from zipline.api import order, record, symbol
import pandas as pd
import glob
import pytz
from collections import OrderedDict

allFiles = glob.glob("*.csv")
datas = OrderedDict()
parser = lambda date: pd.datetime.strptime(date, '%d/%m/%Y')

for file_ in allFiles:
    str_ = file_.split(".")
    df_ = pd.read_csv(file_, header=None, names=["Date","Open","High","Low","Close","Volume"],parse_dates=['Date'],date_parser=parser,index_col='Date')
    df_ = df_[~df_.index.duplicated(keep='first')]
    datas[str_[0]] = df_

pan = pd.Panel(datas)
pan.minor_axis = ['Open', 'High', 'Low', 'Close', 'Volume']
pan.major_axis = pan.major_axis.tz_localize(pytz.utc)

def initialize(context):
    pass

def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data.current(symbol('AAPL'), 'price'))
    
algo_obj = TradingAlgorithm(initialize=initialize, handle_data=handle_data, capital_base = 100000.0)
#run algo
perf_manual = algo_obj.run(pan)

## Reproduction Steps

1. Run the above code with csv OHLCV data for AAPL.

## What steps have you taken to resolve this already?
Checked the panel to see if AAPL symbol is there, and it is.
<class 'pandas.core.panel.Panel'>
Dimensions: 4 (items) x 5039 (major_axis) x 5 (minor_axis)
Items axis: AAPL to TWX
Major_axis axis: 1993-12-19 00:00:00+00:00 to 2017-06-07 00:00:00+00:00
Minor_axis axis: Open to Volume
...

Sincerely,
MAJ

**Comment by FreddieV4** [comment]
Hey @reMAJ thanks for posting. There's a few things going on here so I'll try and address each issue; I'll also need some more information from you.

- Conda install failed because we don't support 32-bit Windows packages. Zipline _might_ work on 32-bit but it's not guaranteed.
- Can you run the buyapple example on it's own? 
- When you ran `zipline run` what did that command look like exactly? 

Thanks!
Freddie

**Comment by FreddieV4** [comment]
@reMAJ ah. I see you have zipline `1.1.0` installed. The latest version does not work currently because of changes Yahoo made to their API. You'll want to use the latest zipline `master`, which now uses Google Finance to get equity data for benchmarks

**Comment by reMAJ** [comment]
@FreddieV4  Thanks a lot. I am very sorry, but I need some info to run with Google.

(1)_Conda install failed because we don't support 32-bit Windows packages. Zipline might work on 32-bit but it's not guaranteed._ : conda install failed with 64bit Anaconda too. There were conflicts with bottleneck. (anyways this is not an issue now in the 32 bit environment)
(2)_Can you run the buyapple example on it's own?_ How do I use "the latest zipline master"
(3)_When you ran zipline run what did that command look like exactly?_ I don't understand the question. I had the above pasted code in the .py file and I ran it in spyder, which means at the IPython console of spyder:  runfile('D:/Data/CSE/zip_a.py', wdir='D:/Data/CSE')

**Comment by FreddieV4** [comment]
To run the latest zipline master, you'll need to have a local copy of zipline, first by forking the repo, and then running `git clone git@github.com:reMAJ/zipline.git`.  You can then run `pip install -e zipline/` assuming you're in a directory that holds the zipline directory.

In regards to the `zipline run` comment, I must have skimmed over the fact that you used `algo.run()` instead. I suggest not using `algo.run()` and using the zipline CLI to run your algorithm. You can find more info in the [Beginner Tutorial](http://www.zipline.io/beginner-tutorial.html)

**Comment by reMAJ** [comment]
@FreddieV4  Thanks again.
I downloaded the zipline master from git and did pip install -e . staying in the zipline-master folder. It uninstalled my current zipline and then installed the master. However, conda list won't show the new zipline. But pip freeze show it as: zipline==0+unknown

Then I put the following code of the buyapple example in zip_a.py file.
```
from zipline.api import order, record, symbol
def initialize(context):
    pass
def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data.current(symbol('AAPL'), 'price'))
```
Then ran it in cmd. Gets the following error.

```
D:\Data>zipline run -f ./zip_a.py --start 2000-1-1 --end 2014-1-1 -o buyapple_out.pickle
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\zipline-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Anaconda2\lib\site-packages\setuptools-23.0.0-py2.7.egg\pkg_resources\__init__.py", line 2927, in <module>
  File "C:\Anaconda2\lib\site-packages\setuptools-23.0.0-py2.7.egg\pkg_resources\__init__.py", line 2913, in _call_aside
  File "C:\Anaconda2\lib\site-packages\setuptools-23.0.0-py2.7.egg\pkg_resources\__init__.py", line 2940, in _initialize_master_working_set
  File "C:\Anaconda2\lib\site-packages\setuptools-23.0.0-py2.7.egg\pkg_resources\__init__.py", line 637, in _build_master
  File "C:\Anaconda2\lib\site-packages\setuptools-23.0.0-py2.7.egg\pkg_resources\__init__.py", line 650, in _build_from_requirements
  File "C:\Anaconda2\lib\site-packages\setuptools-23.0.0-py2.7.egg\pkg_resources\__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'pandas<0.18,>=0.16.1' distribution was not found and is required by zipline
```
Tried to down grade panads and conda fails
```
conda install pandas=0.16.0
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib
  - navigator-updater
  - pandas 0.16.0*
Use "conda info <package>" to see the dependencies for each package.
```
pip succeeded

`pip install -Iv pandas==0.16.0`

Then I ran the algorithm in the cmd, but still get an error. I read a little bit online and it seems like I don't have an ingestion of Google. Please, how do I solve it?

```
D:\Data>zipline run -f ./zip_a.py --start 2000-1-1 --end 2014-1-1 -o buyapple_out.pickle
Traceback (most recent call last):
  File "C:\Anaconda2\envs\cse_32_2_7\Scripts\zipline-script.py", line 11, in <module>
    load_entry_point('zipline', 'console_scripts', 'zipline')()
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\__main__.py", line 97, in _
    return f(*args, **kwargs)
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\__main__.py", line 240, in run
    environ=os.environ,
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\utils\run_algo.py", line 119, in _run
    bundle_timestamp,
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\data\bundles\core.py", line 521, in load
    timestr = most_recent_data(name, timestamp, environ=environ)
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\data\bundles\core.py", line 497, in most_recent_data
    timestamp=timestamp,
ValueError: no data for bundle u'quantopian-quandl' on or before 2017-06-08 19:48:43.522000+00:00
maybe you need to run: $ zipline ingest -b quantopian-quandl
```

**Comment by FreddieV4** [comment]
@reMAJ Ok so just to confirm what you're doing here.

You have a virtualenv, let's say it's called `zipline`, and you are in a directory which has the zipline directory in it, like so:

![image](https://user-images.githubusercontent.com/8339018/26984114-104ed0d4-4d0c-11e7-9e6e-f48198b71dd0.png)

And then you ran `pip install -e zipline`. When you run pip freeze, it should say something like:

![image](https://user-images.githubusercontent.com/8339018/26984343-0cc58ea2-4d0d-11e7-9298-4e3b17c75854.png)

Which says that you have done an editable install of zipline, pinned to a specific commit hash (also just remembering that you don't have to have the `-e` flag for your pip install, but it should work either way here). 

If you did all of that, then the next step is to run `zipline ingest -b quantopian-quandl` in your command prompt, and then run the example code using `zipline run`

**Comment by reMAJ** [comment]
@FreddieV4 Thanks. I have an environment called cse_32_2_7 and I installed the zipline master as you instructed. Then I ran the command `zipline ingest -b quantopian-quandl`, and gots this error.
```
(cse_32_2_7) C:\WINDOWS\system32>zipline ingest -b quantopian-quandl
Traceback (most recent call last):
  File "C:\Anaconda2\envs\cse_32_2_7\Scripts\zipline-script.py", line 11, in <module>
    load_entry_point('zipline', 'console_scripts', 'zipline')()
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\__main__.py", line 312, in ingest
    show_progress,
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\data\bundles\core.py", line 364, in ingest
    calendar = get_calendar(bundle.calendar_name)
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\utils\calendars\calendar_utils.py", line 88, in get_calendar
    calendar = self._calendars[canonical_name] = factory()
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\utils\calendars\trading_calendar.py", line 87, in __init__
    _special_closes = self._calculate_special_closes(start, end)
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\utils\calendars\trading_calendar.py", line 841, in _calculate_special_closes
    end,
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\utils\calendars\trading_calendar.py", line 820, in _special_dates
    for time_, calendar in calendars
  File "c:\users\majesticresearch1\downloads\zipline-master\zipline\utils\calendars\trading_calendar.py", line 892, in holidays_at_time
    calendar.holidays(start, end),
  File "c:\anaconda2\envs\cse_32_2_7\lib\site-packages\pandas\tseries\holiday.py", line 332, in holidays
    if self._cache is None or start < self._cache[0] or end > self._cache[1]:
  File "pandas\tslib.pyx", line 826, in pandas.tslib._Timestamp.__richcmp__ (pandas\tslib.c:15597)
  File "pandas\tslib.pyx", line 858, in pandas.tslib._Timestamp._assert_tzawareness_compat (pandas\tslib.c:15951)
TypeError: Cannot compare tz-naive and tz-aware timestamps
```

**Comment by FreddieV4** [comment]
And you got that error after downgrading pandas? (I don't think we want to downgrade pandas here though)

**Comment by reMAJ** [comment]
@FreddieV4  I down graded it yesterday. But conda list shows me 3 pandas. I don't know which one zipline choose. conda and pip shows difference information
```
(cse_32_2_7) C:\WINDOWS\system32>conda list
# packages in environment at C:\Anaconda2\envs\cse_32_2_7:
pandas                    0.16.0                    <pip>
pandas                    0.18.1                    <pip>
pandas                    0.20.1              np112py27_0

```
pip only shows 1 pandas version. Even though I downgraded using pip.
```
(cse_32_2_7) C:\WINDOWS\system32>pip freeze

pandas==0.18.1
```

**Comment by reMAJ** [comment]
@FreddieV4  I rand the buyapple example on an Ubuntu 16.04.1 LTS machine with 
pandas                    0.18.1              np111py27_0 
zipline                   1.1.0               np111py27_0    Quantopian

The code is from the example:
```
from zipline.api import order, record, symbol
def initialize(context):
    pass
def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data.current(symbol('AAPL'), 'close'))
```
Then I ran it as instructed.
```
$zipline ingest -b quantopian-quandl
$zipline bundles
quandl <no ingestions>
quantopian-quandl 2017-06-10 09:40:26.415661
$zipline run -f ./zip_aapl.py --start 2017-1-1 --end 2017-6-9 -o buyapple_out.pickle
```

Got the error `raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found`

**Comment by FreddieV4** [comment]
Can you try installing the latest version of zipline?

**Comment by freddiev4** [comment]
Hi @reMAJ I'm going to close this due to inactivity but feel free to re-open if you have other issues 🙂
