### ISSUE TITLE
fetch_csv does not handle utf encoding properly

### ISSUE THREAD

**Issue by mx237** [quantopian/zipline#1837]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Win7 Pro SP1
* Python Version: Python 3.6.1
* Python Bitness: 64
* How did you install Zipline: `pip3 install git+https://github.com/quantopian/zipline.git`
* Python packages:
alembic==0.9.2
asn1crypto==0.22.0
bcolz==0.12.1
bleach==2.0.0
Bottleneck==1.2.1
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.3
click==6.7
colorama==0.3.9
contextlib2==0.5.5
cryptography==1.9
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.25.2
decorator==4.0.11
empyrical==0.2.2
entrypoints==0.2.2
html5lib==0.999999999
idna==2.5
inflection==0.3.1
intervaltree==2.1.0
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
Logbook==1.0.0
lru-dict==1.1.6
Mako==1.0.6
MarkupSafe==1.0
matplotlib==2.0.2
mistune==0.7.4
more-itertools==3.1.0
multipledispatch==0.4.9
nbconvert==5.2.1
nbformat==4.3.0
ndg-httpsclient==0.4.2
networkx==1.11
notebook==5.0.0
numexpr==2.6.2
numpy==1.13.0+mkl
pandas==0.18.1
pandas-datareader==0.4.0
pandocfilters==1.4.1
patsy==0.4.1
pickleshare==0.7.4
prompt-toolkit==1.0.14
pyasn1==0.2.3
pycparser==2.17
Pygments==2.2.0
pyOpenSSL==17.0.0
pyparsing==2.2.0
python-dateutil==2.6.0
python-editor==1.0.3
pytz==2017.2
pyzmq==16.0.2
qtconsole==4.3.0
Quandl==3.1.0
requests==2.17.3
requests-file==1.4.2
requests-ftp==0.3.1
scipy==0.19.0
simplegeneric==0.8.1
six==1.10.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.10
statsmodels==0.8.0
tables==3.4.2
testpath==0.3.1
toolz==0.8.2
tornado==4.5.1
traitlets==4.3.2
urllib3==1.21.1
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==2.0.0
zipline==0+unknown

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I was trying to fetch csv from google. The http response has no encoding info. But the returned csv is utf-8 encoded with BOM. fetch_csv() relies on requests.models.Reponse (in requests package) to handle the decoding. Becuase the http response does not contain such info, response.iter_content simply return the raw bytes. It needs to be decoded to string, otherwise I see this error:

  File "c:\python3\lib\site-packages\zipline\utils\api_support.py", line 57, in
wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "c:\python3\lib\site-packages\zipline\algorithm.py", line 1046, in fetch_
csv
    **kwargs
  File "c:\python3\lib\site-packages\zipline\sources\requests_csv.py", line 512,
 in __init__
    self.df = self.load_df()
  File "c:\python3\lib\site-packages\zipline\sources\requests_csv.py", line 285,
 in load_df
    df = self.fetch_data()
  File "c:\python3\lib\site-packages\zipline\sources\requests_csv.py", line 587,
 in fetch_data
    fd.write(chunk)
TypeError: string argument expected, got 'bytes'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

```
from zipline.api import fetch_csv
import pandas

def pre_func(df):
	df["Date"] = pandas.to_datetime(df["Date"], format="%d-%b-%y")
	return df

def initialize(context):
	fetch_csv('http://www.google.com/finance/historical?q=NASDAQ%3AAAPL&startdate=Jun+1%2C+2017&enddate=Jun+2%2C+2017&output=csv', date_column="Date", symbol="AAPL", pre_func=pre_func)
```

## What steps have you taken to resolve this already?

It works for me by changing PandasRequestsCSV.fetch_url in requests_csv.py to the following:

```
    def fetch_url(self, url):
        ......
        ......

        content_length = 0
        logger.info('{} connection established in {:.1f} seconds'.format(
            url, response.elapsed.total_seconds()))

        # use the decode_unicode flag to ensure that the output of this is
        # a string, and not bytes.
        for chunk in response.iter_content(self.CONTENT_CHUNK_SIZE,
                                           decode_unicode=True):
            if content_length > self.MAX_DOCUMENT_SIZE:
                raise Exception('Document size too big.')
            if chunk:
                if isinstance(chunk, bytes):
                    if content_length == 0:
                        import codecs
                        if chunk[:3] == codecs.BOM_UTF8:
                            encoding = 'utf-8-sig'
                        elif chunk[:2] == codecs.BOM_UTF16_LE or chunk[:2] == codecs.BOM_UTF16_BE:
                            encoding = 'utf-16'
                        elif chunk[:4] == codecs.BOM_UTF32_LE or chunk[:4] == codecs.BOM_UTF32_BE:
                            encoding = 'utf-32'
                        else:
                            encoding = 'utf-8'
                        decoder = codecs.getincrementaldecoder(encoding)(errors='replace')
                    chunk = decoder.decode(chunk)
                content_length += len(chunk)
                yield chunk

        return
```

# Anything else?

Even though decode_unicode is set to True, iter_content dows not always return strings. If it returns bytes, the added code will peek the first few bytes to determin the encoding method, and use that for encoding. If no known encoding is found, it will go with default utf-8 decoding.

This solution works for me although python 3.6 is not offically supported at this moment. I did not tested this code on other platforms and I'm not sure if it works on python 2.x

**Comment by richafrank** [comment]
Hi @mx237 ! It looks like the response from that request includes no encoding information for `requests` to use. So the fix either requires inferring the encoding from the data, as you have above, or the server should return the encoding. The idea of zipline being responsible for inferring the encoding, instead of relying on `requests`, doesn't feel ideal to me, but curious what others think. Any chance there's a way to have `requests` do it?

**Comment by mx237** [comment]
Hi @richafrank ! Thanks for your response. I have asked if it can be done in `requests`: [https://github.com/requests/requests/issues/4148](url)
