### ISSUE TITLE
zipline ingest doesn't work

### ISSUE THREAD

**Issue by JackieJin** [quantopian/zipline#1840]
Hi,

I am new to zipline. I just used 'conda install -c Quantopian zipline' to install zipline on my window machine. 

However, when I tried to run zipline ingest, I got error 'failed to create proecess'. Below are  my python versions and modules. Does anyone run into the same issue? 

Python 3.4.3 :: Anaconda 2.2.0 (64-bit)

alembic==0.7.7
argcomplete==0.8.4
asn1crypto==0.22.0
astropy==1.0.1
backports.shutil-get-terminal-size==1.0.0
bcolz==0.12.1
beautifulsoup4==4.3.2
binstar==0.10.1
bitarray==0.8.1
blaze==0.7.3
bleach==2.0.0
blz==0.6.2
bokeh==0.8.1
boto==2.36.0
Bottleneck==1.2.0
certifi==14.5.14
cffi==1.10.0
click==6.7
clyent==0.3.4
colorama==0.3.3
conda==4.3.21
conda-build==1.11.0
configobj==5.0.6
contextlib2==0.5.4
cryptography==1.8.1
cycler==0.10.0
cyordereddict==0.2.2
Cython==0.25.2
cytoolz==0.7.2
DataShape==0.4.4
decorator==4.0.11
docutils==0.12
empyrical==0.2.2
entrypoints==0.2.2
enum34==1.1.6
fastcache==1.0.2
Flask==0.10.1
greenlet==0.4.5
html5lib==0.999999999
idna==2.5
intervaltree==2.1.0
ipykernel==4.6.1
ipython==4.2.0
ipython-genutils==0.1.0
ipywidgets==5.1.5
itsdangerous==0.24
jdcal==1.0
jedi==0.8.1
Jinja2==2.7.3
jsonschema==2.4.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
llvmlite===0.2.2-1-gbcb15be
Logbook==0.12.5
lru-dict==1.1.4
lxml==3.4.2
Mako==1.0.6
MarkupSafe==0.23
matplotlib==1.5.3
menuinst==1.4.7
mistune==0.5.1
mock==1.0.1
multipledispatch==0.4.9
munch==2.0.4
nbconvert==5.1.1
nbformat==4.3.0
networkx==1.11
nltk==3.0.2
nose==1.3.4
notebook==5.0.0
numba==0.17.0
numexpr==2.6.1
numpy==1.11.3
odo==0.3.1
openpyxl==1.8.5
packaging==16.8
pandas==0.18.1
pandas-datareader==0.2.1
pandocfilters==1.4.1
path.py==8.1.2
patsy==0.4.1
pep8==1.6.2
pexpect==4.0.1
pickleshare==0.6
Pillow==2.7.0
ply==3.4
prompt-toolkit==1.0.14
psutil==2.2.1
ptyprocess==0.5.1
py==1.4.26
pyasn1==0.1.7
pycosat==0.6.1
pycparser==2.17
pycrypto==2.6.1
pyflakes==0.8.1
Pygments==2.0.2
pyOpenSSL==17.0.0
pyparsing==2.1.4
pyreadline==2.1
pytest==2.6.4
python-dateutil==2.6.0
pytz==2017.2
pywin32==220
PyYAML==3.11
pyzmq==14.5.0
qstrader==0.0.1
qtconsole==4.3.0
quandl==2.8.8
requests==2.14.2
requests-cache==0.4.12
requests-file==1.4.2
rope-py3k==0.9.4.post1
runipy==0.1.3
scikit-image==0.11.2
scikit-learn==0.15.2
scipy==0.18.1
seaborn==0.7.1
simplegeneric==0.8.1
six==1.10.0
sockjs-tornado==1.0.1
sortedcontainers==1.5.7
Sphinx==1.2.3
spyder==2.3.4
SQLAlchemy==1.1.5
statsmodels==0.6.1
sympy==0.7.6
tables==3.3.0
testpath==0.3
toolz==0.8.2
tornado==4.1
traitlets==4.3.2
ujson==1.33
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.10.1
widgetsnbextension==2.0.0
xlrd==0.9.3
XlsxWriter==0.6.7
xlwings==0.3.4
zipline==1.1.0

**Comment by richafrank** [comment]
Hi @JackieJin ! Looks like maybe you're encountering https://github.com/quantopian/zipline/issues/1591 . Have you installed conda in a directory with spaces in the path? Could you move it? Or you could try editing zipline-script.py, as is mentioned in that issue.

**Comment by JackieJin** [comment]
Thanks @richafrank  . It seems to work now

**Comment by richafrank** [comment]
Great!
