### ISSUE TITLE
question regarding testing best practices 

### ISSUE THREAD

**Issue by markfink** [quantopian/zipline#1841]
I answered all questions about my env (zipline 1.1.0) here: https://github.com/quantopian/zipline/issues/1808

I migrated a function from quantopian 1 to zipline:

```
def can_buy(context, data):
    latest = data.current(context.spy, 'close')
    h = data.history([context.spy], 'close', 200, '1d')
    avg = h[context.spy].mean()
    return latest > avg
```

now I am not so confident any more that this function does what it is supposed to do and I want to add tests. I perfectly well understand that zipline itself is a kind of testing tool but I want more fine grained testing (in SE we call this unit testing).  I personally work with pytest but samples in any other available python test tools would be fine.

```
def test_can_buy():
    
    context.spy = sid(8554)

    data = {} # <==== I understand that this should be BarData but so far I have no clue how to prepare that
    # I would like to use the same data for each test execution
    
    actual = can_buy(context, data)
```

I want to be able to test functions like the above `can_buy` which have [context, data] params and I want to be able to test CustomFactors. Is there some howto or samples on how to do that? I already googled for some time but the only tests I could find so far are the tests for zipline itself.

**Comment by markfink** [comment]
I looked more into this and I am now sure that this is a `valid beginners question`. Consequently I decided to add here what I found out so far:

The necessary tools required for the testing are already there e.g.:
* https://github.com/quantopian/zipline/blob/master/zipline/data/minute_bars.py
* https://github.com/quantopian/zipline/blob/master/zipline/testing/fixtures.py

With this its merely a question of finding some documentation or deciphering the code and data structures to find out how to use all this.

**Comment by markfink** [comment]
the solution I came up with is to load the testdata from csv files and I created a fixture to do exactly that.
details here: https://github.com/finklabs/zipline-testing

**Comment by dmichalowicz** [comment]
@markfink Is this still an issue/open question for you?

**Comment by ssanderson** [comment]
Closing this as stale.
