### ISSUE TITLE
Improve messages when we don't have benchmark data

### ISSUE THREAD

**Issue by freddiev4** [quantopian/zipline#1850]
Because we make requests to Google Finance for benchmark data in `zipline.data.benchmarks` and `zipline.data.loader`, there are two cases where we get:

`KeyError: 'the label [<some timestamp>] is not in the [index]'`

- [ ] The first case is when we don't have benchmark data for the most recent trading day. The logic for us getting day up until `T`, the current trading day minus 2 trading days, can be found [here](https://github.com/quantopian/zipline/blob/master/zipline/data/loader.py#L143). We should do some check in `run_algo.py` before we construct a `TradingAlgorithm` object, that checks the end date that someone passes in to the CLI args via `zipline run`, and check if we have benchmark data up until that day.
  - If we don't have data up until that day, raise an exception and provide a nice message telling the user we only have up until `T-2` days worth of data and that they should change the range for which they're requesting data

- [ ] The second case is when someone passes in a start date to the CLI args that is before `2002`. I'm forgetting why it is that we're only getting data back until `2002` for benchmark data so I'll need to re-investigate.

**Comment by kennell** [comment]
I would like to suggest that perhaps a CLI flag to skip benchmarking should be added.

**Comment by abhilashchowdhary** [comment]
@freddiev4 any updates on this ?

**Comment by freddiev4** [comment]
We recently did a release of zipline; going to close this as this should not be an issue anymore. You can see the release notes [here](http://www.zipline.io/releases.html#release-1-2-0) Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update zipline -c quantopian
```

If there are any problems, please open a new issue 🙂
