### ISSUE TITLE
Fails to import

### ISSUE THREAD

**Issue by richardtbenade** [quantopian/zipline#1859]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Latest Google Datalab Image (linux)
* Python Version:  2.7
* Python Bitness: 64
* How did you install Zipline: pip install
* Python packages: n/a

Now that you know a little about me, let me tell you about the issue I am
having:

Hi There.

I've successfully installed Zipline using:
! apt-get update
! apt-get install libatlas-base-dev python-dev gfortran pkg-config libfreetype6-dev -y
! pip install zipline

When I now try to run
import zipline
I get:
_ImportErrorTraceback (most recent call last)
<ipython-input-11-caeca508216f> in <module>()
----> 1 import zipline
/usr/local/lib/python2.7/dist-packages/zipline/__init__.py in <module>()
     35 # This is *not* a place to dump arbitrary classes/modules for convenience,
     36 # it is a place to expose the public interfaces.
---> 37 from . import data
     38 from . import finance
     39 from . import gens
ImportError: cannot import name data_

* What did you expect to happen? Zipline to import
* What happened instead? Error message as above

Here is how you can reproduce this issue on your machine:

1. Create datalab instance on google cloud platform by running:
datalab create datalab-zipline1 in cloud shell
2. Run installation in notebook as described above
3. Now try to import zipline

## What steps have you taken to resolve this already?
No further steps

# Anything else?
Initially I had the following error while trying to run !pip install zipline:
_Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-UESdqg/bcolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tc_hXp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-UESdqg/bcolz/_

However, running 
!apt-get install -y build-essential libssl-dev libffi-dev python-dev
seemed to have sorted that out. Still stuck with import issue though.

Sincerely,
Richardt

**Comment by FreddieV4** [comment]
Hi @richardtbenade I believe this might be coming from the recent empyrical version `0.3.0`. You'll have to install zipline from the master branch or wait for our next release.

**Comment by FreddieV4** [comment]
Just now seeing https://groups.google.com/forum/#!topic/zipline/rJ2VxWHpDTg

**Comment by FreddieV4** [comment]
So it looks like this issue has been resolved in the mailing list discussion; feel free to re-open if you're having other issues 🙂
