### ISSUE TITLE
Remove position when a stock is delisted

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#188]
When a stock is delisted it should be removed from the portfolio to reflect the impact had on portfolio value.

**Comment by dmichalowicz** [comment]
This is being addressed here: https://github.com/quantopian/zipline/pull/982

**Comment by dmichalowicz** [comment]
@richafrank Can I close this, having merged https://github.com/quantopian/zipline/pull/982?

**Comment by richafrank** [comment]
Yes!
