### ISSUE TITLE
Documentation and Understanding the Simulation Environment

### ISSUE THREAD

**Issue by snth** [quantopian/zipline#19]
Hi,

First off, let me say well done on a great project and for making this Open Source. I'm quite excited about the prospects this opens up and would like to use this for my own work and contribute where possible.

In order to assess whether it can meet my needs in a short enough time period I'm trying to understand how the Trade Simulator works to see if I can use it for my purposes. In particular I'd like to understand the class model and how the classes interact, i.e. who emits which messages and what exactly they contain.

However the documentation in the docs subdirectory still seems quite thin and out of date. For example I found a couple of references to zmq although I don't see it being used anywhere in the code. There are also some references to "QBT" which I can only assume is the previous name of zipline?

I have some experience with Sphinx and I am happy to document as I go along during my explorations. I just want to check that this isn't at odds with any of your own efforts as I noticed that there is a docs branch.

Also what would be the best way to interact with you guys? For example I'm wondering whether any of your developers are available on IRC or G+ for interactive feedback?

**Comment by amostajabi** [comment]
Hi Guys, I've just gotten familiar with this great framework and I've had the same question about zipline architecture which I also really like to get more familiar with. Is the channel you created on freenode still available? How can we have contact with you and get more info about zipline architecture, specially the simulation process?

Thanks for your great help.
@ehebert 
@twiecki

**Comment by FreddieV4** [comment]
Hi @amostajabi we currently don't use a freenode channel, but here in the [README](https://github.com/quantopian/zipline) you can find links to our mailing list and Gitter 😃 

There are also docs at [zipline.io](http://zipline.io) and a [beginner tutorial](https://github.com/quantopian/zipline/blob/master/docs/notebooks/tutorial.ipynb) notebook which you can play around with (although ignore the yahoo mentions as I need to push a change to update that)
