### ISSUE TITLE
Add info about using a virtualenv for installs

### ISSUE THREAD

**Issue by FreddieV4** [quantopian/zipline#1901]
It seems that there have been many attempts to install zipline just by running `pip install` or `conda install`, which results in a bunch of common errors like:

- Downgrading of packages
- Mismatch of package versions in the global `package-list` or `conda packages` with those that Zipline uses
- Conflicting versions with other libraries; i.e. now you can't use another library because Zipline changed the package version or vice versa
- Installing on an unsupported Python version

I was thinking that we should suggest that people use virtualenvs or conda envs for their installs. Any thoughts on this @richafrank?

**Comment by richafrank** [comment]
Environment isolation is a great thing for us to mention, especially for new folks to python. It won't solve the cases where people actually want to use libraries that conflict with zipline, but this education could help to prevent other cases of conflict.

**Comment by z-Runmin** [comment]
Just submitted a PR on this issue.
