### ISSUE TITLE
zipline UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by mongeoroo** [quantopian/zipline#1909]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version
* Python Version:  3.4 (separately download with conda
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: conda install
* Python packages:  conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

first my problem is that my Jupyter QTConsole (version python 3.4) doesn't work. 

i create py34 wiht
conda create -n py34 python=3.4 anaconda

however whenever clicking Jupyter QTConsole, nothing happen. aslo IPython too.

anyway, I perform my coding in anaconda prompt (py34) 

install zipline with
conda install zipline

but, whenever import zipline, I get error like this
[
C:\Users\Administrator\AppData\Local\conda\conda\envs\py34\lib\site-packages\pandas\tseries\index.py:755: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex
  PerformanceWarning)
C:\Users\Administrator\AppData\Local\conda\conda\envs\py34\lib\site-packages\pandas\tseries\index.py:755: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex
  PerformanceWarning)
C:\Users\Administrator\AppData\Local\conda\conda\envs\py34\lib\site-packages\pandas\tseries\index.py:755: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex
  PerformanceWarning)
]

although error, coding can run. so I scrap tutorial code. but I take error

[
Traceback (most recent call last):
  File "E:/workspace/zip.py", line 23, in <module>
    algo = TradingAlgorithm(Iinitialize=initialize, handle_data=handle_data)
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\py34\lib\site-packages\zipline\algorithm.py", line 269, in __init__
    self.trading_environment = TradingEnvironment()
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\py34\lib\site-packages\zipline\finance\trading.py", line 96, in __init__
    self.bm_symbol,
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\py34\lib\site-packages\zipline\data\loader.py", line 165, in load_market_data
    trading_day,
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\py34\lib\site-packages\zipline\data\loader.py", line 253, in ensure_benchmark_data
    if not has_data_for_dates(data, first_date, last_date):
UnboundLocalError: local variable 'data' referenced before assignment
]

my coding is here

[

import pandas_datareader.data as web
from zipline.api import order, record, symbol
from zipline.algorithm import TradingAlgorithm

data = web.DataReader("AAPL", "google")
data = data[['Close']]
data.columns = ["AAPL"]
data = data.tz_localize('UTC')

def initialize(context):
    context.sym = "AAPL"
    context.i = 0

def handle_data(context):
    order(context.sym, 10)
    context.i += 1

algo = TradingAlgorithm(Iinitialize=initialize, handle_data=handle_data)

result = algo.run(data)

print(result)

]

what should I do??

please help me. errors hurting me

Sincerely,
`$ whoami`

**Comment by richafrank** [comment]
Hi @mongeoroo , That error is https://github.com/quantopian/zipline/issues/1506 and is masking failure to download the benchmark. 

The [fix](https://github.com/quantopian/zipline/pull/1513) for the exact error you're seeing was released some months ago, if you want to start by updating to the latest version of zipline. Then you/we might have more information about why the benchmark isn't downloading.

**Comment by ShadoFlameX** [comment]
I'm hitting the same error, but on macOS. Is there any way to install a newer version of zipline (above 1.0.2) using something other than pip, which is giving me trouble? Thanks.

**Comment by richafrank** [comment]
@ShadoFlameX , You could clone the repo locally and [build the c extensions in place manually](http://www.zipline.io/development-guidelines.html#creating-a-development-environment).

**Comment by freddiev4** [comment]
Going to close this due to inactivity/no response from OP. Feel free to re-open if you have further issues 🙂
