### ISSUE TITLE
get started buy apple script fail KeyError: 'the label [2000-01-03 00:00:00+00:00] is not in the [index]'

### ISSUE THREAD

**Issue by WenchenLi** [quantopian/zipline#1911]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System:ubuntu 16.04
* Python Version: `$ python --2.7`
* Python Bitness: 64
* How did you install Zipline:pip
* Python packages: 
adium-theme-ubuntu==0.3.4
alabaster==0.7.9
alembic==0.9.0
appdirs==1.4.3
asciitree==0.3.3
autobahn==0.17.1
Babel==2.3.4
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
backtrader==1.9.29.108
bcolz==0.12.1
beautifulsoup4==4.4.1
bleach==1.5.0
blinker==1.4
boto==2.45.0
Bottleneck==1.2.0
bz2file==0.98
cachetools==2.0.0
certifi==2016.9.26
chainer==1.22.0
chardet==2.3.0
click==6.6
cloudpickle==0.2.2
configparser==3.5.0
constantly==15.1.0
contextlib2==0.5.4
cycler==0.10.0
cymem==1.31.2
cyordereddict==1.0.0
Cython==0.26
cytoolz==0.8.2
dask==0.11.1
decorator==4.0.10
docker-py==1.10.3
docker-pycreds==0.2.1
docutils==0.13.1
dyNET==0.0.0
empyrical==0.2.2
entrypoints==0.2.2
enum34==1.1.6
fastzbarlight==0.0.14
feedparser==5.2.1
filelock==2.0.7
fire==0.1.0
Flask==0.11.1
Flask-Mail==0.9.1
flexmock==0.10.2
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.0.5
gcn==1.0
gensim==0.13.4.1
-e git+https://github.com/openai/go-vncdriver.git@6494c09c74ab91d4357a74eab597667771f3a980#egg=go_vncdriver
googlefinance==0.7
graphviz==0.5.2
grpcio==1.0.0
-e git+https://github.com/openai/gym@c17ac6cc55fda4be60548e2e05b54f22e83e2c1b#egg=gym
h5py==2.6.0
html==1.16
html5lib==0.999
IbPy2==0.8.0
idna==2.5
imagesize==0.7.1
incremental==16.10.1
intervaltree==2.1.0
ipaddress==1.0.18
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
jieba==0.38
Jinja2==2.9.5
joblib==0.9.4
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
Keras==2.0.2
Lasagne==0.1
Logbook==1.0.0
lru-dict==1.1.6
lxml==3.5.0
mail==0.1
Mako==1.0.6
MarkupSafe==0.23
matplotlib==1.5.3
meld==3.14.2
mercurial==3.7.3
mistune==0.7.3
mock==2.0.0
multipledispatch==0.4.9
murmurhash==0.26.4
mxnet==0.9.1
nbconvert==5.0.0
nbformat==4.2.0
networkx==1.11
nltk==3.2.2
nose==1.3.7
notebook==4.3.1
numexpr==2.6.2
numpy==1.12.1
ocropy==1.0
packaging==16.8
panda==0.3.1
pandas==0.18.1
pandas-datareader==0.3.0.post0
pandocfilters==1.4.1
pathlib==1.0.1
pathlib2==2.1.0
patsy==0.4.1
pbr==2.0.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==3.4.2
plac==0.9.6
preshed==0.46.4
progressbar==2.3
prompt-toolkit==1.0.9
protobuf==3.2.0
ptyprocess==0.5.1
pycurl==7.43.0
pyfolio==0.7.0
pyglet==1.2.4
Pygments==2.2.0
pygobject==3.20.0
pyparsing==2.2.0
pypinyin==0.18.1
pytesseract==0.1.6
python-apt==1.1.0b1
python-crontab==2.2.1
python-dateutil==2.6.0
python-editor==1.0.3
pytz==2016.10
PyYAML==3.12
pyzmq==16.0.2
QSTK==0.2.8
qtconsole==4.2.1
recurrentshop==0.0.1
requests==2.13.0
requests-file==1.4.1
requests-ftp==0.3.1
roku==2.0
schedule==0.4.2
scikit-image==0.12.3
scikit-learn==0.18.1
scikits.statsmodels==0.3.1
scipy==0.19.0
seaborn==0.7.1
semver==2.7.5
simplegeneric==0.8.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
sklearn==0.0
smart-open==1.3.5
snowballstemmer==1.2.1
sortedcontainers==1.5.7
spacy==1.6.0
Sphinx==1.5.2
sputnik==0.9.3
SQLAlchemy==1.1.6
statsmodels==0.8.0
TA-Lib==0.4.10
tables==3.3.0
tensorflow==0.11.0rc1
tensorflow-fold==0.0.1
tensorflow-gpu==1.0.1
terminado==0.6
tesserocr==2.1.2
testpath==0.3
Theano==0.9.0
thinc==6.2.0
thrift==0.10.0
thulac==0.1.1
tldextract==2.0.2
toolz==0.8.2
torch==0.1.6.post22
torchtext==0.1.1
torchvision==0.1.7
tornado==4.4.2
tqdm==4.11.2
traitlets==4.3.1
Twisted==16.6.0
txaio==2.6.0
ujson==1.35
unity-lens-photos==1.0
-e git+https://github.com/openai/universe.git@cc31624fc99e59f24ef4f8b80426fbd4ba2c3397#egg=universe
wcwidth==0.1.7
websocket-client==0.40.0
Werkzeug==0.11.10
wget==3.2
widgetsnbextension==1.2.6
wikipedia==1.4.0
yahoo-finance==1.4.0
youtube-dl==2016.12.22
zipline==1.1.1
zope.interface==4.3.3

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
i went through the zipline get started tutorial http://www.zipline.io/beginner-tutorial.html

after ingest data,  zipline run -f zipline_get_started.py --start 2000-1-1 --end 2014-1-1 -o buyapple_out.pickle

but i got:
[2017-08-14 19:57:57.150973] WARNING: Loader: Refusing to download new benchmark data because a download succeeded at 2017-08-14 19:48:28.156401+00:00.
Traceback (most recent call last):
  File "/usr/local/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.1.1', 'console_scripts', 'zipline')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zipline/__main__.py", line 97, in _
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zipline/__main__.py", line 240, in run
    environ=os.environ,
  File "/usr/local/lib/python2.7/dist-packages/zipline/utils/run_algo.py", line 179, in _run
    overwrite_sim_params=False,
  File "/usr/local/lib/python2.7/dist-packages/zipline/algorithm.py", line 709, in run
    for perf in self.get_generator():
  File "/usr/local/lib/python2.7/dist-packages/zipline/gens/tradesimulation.py", line 230, in transform
    handle_benchmark(normalize_date(dt))
  File "/usr/local/lib/python2.7/dist-packages/zipline/gens/tradesimulation.py", line 190, in handle_benchmark
    benchmark_source.get_value(date)
  File "/usr/local/lib/python2.7/dist-packages/zipline/sources/benchmark_source.py", line 75, in get_value
    return self._precalculated_series.loc[dt]
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1296, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1466, in _getitem_axis
    self._has_valid_type(key, axis)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1403, in _has_valid_type
    error()
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1390, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [2000-01-03 00:00:00+00:00] is not in the [index]'

Sincerely,
wenchen

**Comment by FreddieV4** [comment]
Hi @WenchenLi good catch on the tutorial docs. That's a known issue where we can't get data before 2009 (for some reason I have yet to discover). I think we'll want to update that tutorial doc that says some later date, like 2010.

For now you could just use a later date or run through the [Tutorial Notebook])(https://github.com/quantopian/zipline/blob/master/docs/notebooks/tutorial.ipynb)

Also I noticed that several of your Python packages have versions which conflict with the versions that zipline uses. I'd suggest using a `virtualenv` or `conda env` to install zipline.
