### ISSUE TITLE
Cannot install zipline on macOS Sierra using conda 

### ISSUE THREAD

**Issue by jau827** [quantopian/zipline#1912]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: `macOS Sierra 10.12.5`
* Python Version: `Python 3.5.2 :: Anaconda custom (x86_64)`
* Python Bitness: `64`
* How did you install Zipline: `$ conda install -c Quantopian zipline`
* Python packages: Attached
[packages.txt](https://github.com/quantopian/zipline/files/1223807/packages.txt)

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? Install of `zipline` using `conda`
* What happened instead? Received the error: 

`$ conda install -c Quantopian zipline
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.5*
  - zipline -> cachetools >=1.1.5 -> python 3.4*
Use "conda info <package>" to see the dependencies for each package.`

## What steps have you taken to resolve this already?

Searched this forum and found this thread https://github.com/quantopian/zipline/issues/1389, situation looks similar, but person has different operating system. 

Sincerely,
`jau827`

Thanks for the help!!

**Comment by FreddieV4** [comment]
Hi @jau827 thanks for posting. The reason for this is that we have not yet built macOS conda packages for Zipline. The way to install Zipline would be to make a `conda env` (to avoid conflicting package versions for other modules) and then run `pip install zipline`.

**Comment by jau827** [comment]
Hmm ok I will try through pip, I only used anaconda because on the `zipline` github it says that OSX 64 bit is supported for anaconda

**Comment by freddiev4** [comment]
FWIW, there should be Anaconda 3.5 packages for osx now.

Going to close this but feel free to re-open if you have further issues.
