### ISSUE TITLE
ImportError: cannot import name load_from_yahoo

### ISSUE THREAD

**Issue by gustavkkk** [quantopian/zipline#1916]
Hi@quantopian
My OS is ubuntu16.04, python version 2.7.12,
I installed zipline using command "pip install zipline"
then I tried to import load_from_yahoo using "from zipline.utils.factory import load_from_yahoo"
at the moment, I encountered this error.
"ImportError: cannot import name load_from_yahoo"
How can I solve this problem?

**Comment by gustavkkk** [comment]
on windows8.1, conda4.2.0, python3.5
Installed zipline using "conda install -c Quantopian zipline"
but same result("ImportError: cannot import name load_from_yahoo")

**Comment by FreddieV4** [comment]
Hi @gustavkkk. `load_from_yahoo` actually exists in `zipline.data.loader` and needs to be removed (x-ref #1805).

You can see the [Release Notes](http://www.zipline.io/releases.html#release-1-1-10) for why we removed yahoo-related code.

**Comment by gustavkkk** [comment]
Thank you very much, @FreddieV4 .  zipline.data.loader solved the issue.
Btw, when I run the following command
zipline_logging = logbook.NestedSetup([
    logbook.NullHandler(level=logbook.DEBUG, bubble=True),
    logbook.StreamHandler(sys.stdout, level=logbook.INFO),
    logbook.StreamHandler(sys.stderr, level=logbook.ERROR),
])
,I encountered the following error.
TypeError: __init__() got an unexpected keyword argument 'bubble'

I looked into NullHandler. It has bubble argument. Could you help me solve this problem?

**Comment by FreddieV4** [comment]
Hi @gustavkkk in regards to your logging issue, it looks like `logbook.NullHandler()` does not have a `bubble` parameter.

See the docs [here](http://logbook.readthedocs.io/en/stable/api/handlers.html#logbook.NullHandler)

**Comment by gustavkkk** [comment]
@FreddieV4 . Thank you for your answer.

**Comment by FreddieV4** [comment]
Going to go ahead and close this 🙂
