### ISSUE TITLE
Errors after running buyaapl.py example 

### ISSUE THREAD

**Issue by jau827** [quantopian/zipline#1924]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: macOS Sierra 10.12.5 Darwin 16.6.0
* Python Version: `3.5.3`
* Python Bitness: `64`
* How did you install Zipline: `pip install zipline`
* Python packages: attached
[packages.txt](https://github.com/quantopian/zipline/files/1243784/packages.txt)

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? Expected to run through terminal with an output similar to this as seen in the zipline documentation:
`AAPL
[2015-11-04 22:45:32.820166] INFO: Performance: Simulated 3521 trading days out of 3521.
[2015-11-04 22:45:32.820314] INFO: Performance: first open: 2000-01-03 14:31:00+00:00
[2015-11-04 22:45:32.820401] INFO: Performance: last close: 2013-12-31 21:00:00+00:00`

* What happened instead?
Upon running the script
[buyaapl.txt](https://github.com/quantopian/zipline/files/1243790/buyaapl.txt), a figure printed and it seemed like it worked however I received a few errors listed here:
[errors.txt](https://github.com/quantopian/zipline/files/1243789/errors.txt)

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Create virtual environment via conda with python 3.5
2. Install zipline with pip (may have to downgrade pandas version)
3. Run the command shown at the beginning of my error output
...

## What steps have you taken to resolve this already?
Searched other related threads and have seen similar issues but no solutions for my specific problem
...

# Anything else?
Thanks for the help in advance!
...

Sincerely,
`jau827`

**Comment by FreddieV4** [comment]
Hi @jau827 looking at your `errors.txt` those are not error, which would normally stop the execution of your Zipline backtest, but rather it's just info/warnings letting you know that data doesn't exist beyond a certain date. If anything we could update the info in our docs to say that these logs might appear but if the backtest doesn't stop executing then you should be ok.

**Comment by freddiev4** [comment]
Hi @jau827 I'm going to close this due to no response. Feel free to re-open if you have issues again or more questions 🙂
