### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by hatyar** [quantopian/zipline#1928]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 7
* Python Version: `Python 3.5.3 64 bit
* How did you install Zipline: conda
* Python packages: `$ pip freeze` or `$ conda list`
zipline 1.1.1 np111py35_0
-------------------------
file name   : zipline-1.1.1-np111py35_0.tar.bz2
name        : zipline
version     : 1.1.1
build string: np111py35_0
build number: 0
channel     : quantopian
size        : 1.2 MB
arch        : x86_64
has_prefix  : True
license     : Apache Software License
md5         : 9a5a1c13bfaab7bb5649455af66a11e1
noarch      : None
platform    : win32
requires    : ()
subdir      : win-64
url         : https://conda.anaconda.org/quantopian/win-64/ziplin
35_0.tar.bz2
dependencies:
    alembic >=0.7.7
    bcolz >=0.12.1,<1
    bottleneck >=1.0.0
    click >=4.0.0
    contextlib2 >=0.4.0
    cyordereddict >=0.2.2
    cython >=0.25.2
    decorator >=4.0.0
    empyrical >=0.2.2
    intervaltree >=2.1.0
    logbook >=0.12.5
    lru-dict >=1.1.4
    mako >=1.0.1
    markupsafe >=0.23
    multipledispatch >=0.4.8
    networkx >=1.9.1
    numexpr >=2.6.1
    numpy 1.11*
    pandas >=0.18.1,<0.19
    pandas-datareader >=0.2.1
    patsy >=0.4.0
    pip >=7.1.0
    pytables >=3.3.0
    python 3.5*
    python-dateutil >=2.4.2
    pytz >=2016.4
    requests >=2.9.1
    requests-file >=1.4.1
    scipy >=0.17.1
    setuptools >18.0
    six >=1.10.0
    sortedcontainers >=1.4.4
    sqlalchemy >=1.0.8
    statsmodels >=0.6.1
    toolz >=0.8.2

(p35) C:\Users\benr>python --version
Python 3.5.3 :: Anaconda custom (64-bit)

(p35) C:\Users\benr>python -c 'import math, sys;print(int(math.lo
 1, 2) + 1))
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal

(p35) C:\Users\benr>conda list
# packages in environment at C:\ProgramData\Anaconda3\envs\p35:
#
_license                  1.1                      py35_1
alabaster                 0.7.10                   py35_0
anaconda                  custom                   py35_0
anaconda-client           1.6.3                    py35_0
anaconda-navigator        1.6.2                    py35_0
anaconda-project          0.6.0                    py35_0
asn1crypto                0.22.0                   py35_0
astroid                   1.4.9                    py35_0
astropy                   1.3.3               np111py35_0
babel                     2.4.0                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.6.0                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bleach                    1.5.0                    py35_0
bokeh                     0.12.5                   py35_1
boto                      2.46.1                   py35_0
bottleneck                1.2.1               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.10.0                   py35_0
chardet                   3.0.3                    py35_0
click                     6.7                      py35_0
cloudpickle               0.2.2                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.9                    py35_0
comtypes                  1.1.2                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.5                    py35_0
cryptography              1.8.1                    py35_0
curl                      7.52.1                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.25.2                   py35_0
cytoolz                   0.8.2                    py35_0
dask                      0.14.3                   py35_1
datashape                 0.5.4                    py35_0
decorator                 4.0.11                   py35_0
distributed               1.16.3                   py35_0
docutils                  0.13.1                   py35_0
entrypoints               0.2.2                    py35_1
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
flask                     0.12.2                   py35_0
flask-cors                3.0.2                    py35_0
freetype                  2.5.5                    vc14_2  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.2.1                    py35_0
greenlet                  0.4.12                   py35_0
h5py                      2.7.0               np111py35_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
html5lib                  0.999                    py35_0
icu                       57.1                     vc14_0  [vc14]
idna                      2.5                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.6.1                    py35_0
ipython                   5.3.0                    py35_0
ipython_genutils          0.2.0                    py35_0
ipywidgets                6.0.0                    py35_0
isort                     4.2.5                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.3                      py35_0
jedi                      0.10.2                   py35_2
jinja2                    2.9.6                    py35_0
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.6.0                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            5.0.1                    py35_0
jupyter_console           5.1.0                    py35_0
jupyter_core              4.3.0                    py35_0
lazy-object-proxy         1.2.2                    py35_0
libpng                    1.6.27                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_3  [vc14]
llvmlite                  0.18.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.7.3                    py35_0
markupsafe                0.23                     py35_2
matplotlib                2.0.2               np111py35_0
menuinst                  1.4.7                    py35_0
mistune                   0.7.4                    py35_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py35_3
mpmath                    0.19                     py35_1
msgpack-python            0.4.8                    py35_0
multipledispatch          0.4.9                    py35_0
navigator-updater         0.1.0                    py35_0
nbconvert                 5.1.1                    py35_0
nbformat                  4.3.0                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.3                    py35_0
nose                      1.3.7                    py35_1
notebook                  5.0.0                    py35_0
numba                     0.33.0              np111py35_0
numexpr                   2.6.2               np111py35_0
numpy                     1.11.3                   py35_0
numpydoc                  0.6.0                    py35_0
odo                       0.5.0                    py35_1
olefile                   0.44                     py35_0
openpyxl                  2.4.7                    py35_0
openssl                   1.0.2l                   vc14_0  [vc14]
packaging                 16.8                     py35_0
pandas                    0.20.1              np111py35_0
pandas-datareader         0.5.0                     <pip>
pandocfilters             1.4.1                    py35_0
partd                     0.3.8                    py35_0
path.py                   10.3.1                   py35_0
pathlib2                  2.2.1                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    4.1.1                    py35_0
pip                       9.0.1                    py35_1
ply                       3.10                     py35_0
prompt_toolkit            1.0.14                   py35_0
psutil                    5.2.2                    py35_0
py                        1.4.33                   py35_0
pycodestyle               2.3.1                    py35_0
pycosat                   0.6.2                    py35_0
pycparser                 2.17                     py35_0
pycrypto                  2.6.1                    py35_6
pycurl                    7.43.0                   py35_2
pyflakes                  1.5.0                    py35_0
pygments                  2.2.0                    py35_0
pylint                    1.6.4                    py35_1
pymysql                   0.7.9                    py35_0
pyodbc                    4.0.16                   py35_0
pyopenssl                 17.0.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      5.6.0                    py35_2
pytables                  3.2.2               np111py35_4
pytest                    3.0.7                    py35_0
python                    3.5.3                         3
python-dateutil           2.6.0                    py35_0
pytz                      2017.2                   py35_0
pywavelets                0.5.2               np111py35_0
pywin32                   220                      py35_2
pyyaml                    3.12                     py35_0
pyzmq                     16.0.2                   py35_0
qt                        5.6.2                    vc14_6  [vc14]
qtawesome                 0.4.4                    py35_0
qtconsole                 4.3.0                    py35_0
qtpy                      1.2.1                    py35_0
requests                  2.14.2                   py35_0
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_1
scikit-image              0.13.0              np111py35_0
scikit-learn              0.18.1              np111py35_1
scipy                     0.19.0              np111py35_0
seaborn                   0.7.1                    py35_0
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sortedcollections         0.5.3                    py35_0
sortedcontainers          1.5.7                    py35_0
sphinx                    1.5.6                    py35_0
spyder                    3.2.1                    py35_0
sqlalchemy                1.1.9                    py35_0
statsmodels               0.8.0               np111py35_0
sympy                     1.0                      py35_0
ta-lib                    0.4.9               np111py35_0    quan
tblib                     1.3.2                    py35_0
testpath                  0.3                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.2                    py35_0
tornado                   4.5.1                    py35_0
traitlets                 4.3.2                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.12.2                   py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        2.0.0                    py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.10                  py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.6                    py35_0
xlwings                   0.10.4                   py35_0
xlwt                      1.2.0                    py35_0
zict                      0.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

Zipline does not install:

(p35) C:\Users\benr>conda install -c Quantopian zipline
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - blaze
  - python 3.5*
  - zipline
Use "conda info <package>" to see the dependencies for each package.

From reading in Github I understand that you do support python 3.5. Anything I can do to install zipline on 3.5?

Sincerely, 

Ben

**Comment by hatyar** [comment]
not sure why this is not being answered. I tried many things but cannot get it to work with Python 3.5 environment.

**Comment by richafrank** [comment]
Hi @hatyar , Could you share the output of running `conda info`? Thanks.

**Comment by drorlederman** [comment]
I have the same issue:
"
(py35) C:\windows\system32>python --version
Python 3.5.3 :: Anaconda 4.4.0 (64-bit)

(py35) C:\windows\system32>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3\envs\py35
       envs directories : C:\Program Files\Anaconda3\envs
                          C:\Users\dlederma\AppData\Local\conda\conda\envs
                          C:\Users\dlederma\.conda\envs
          package cache : C:\Program Files\Anaconda3\pkgs
                          C:\Users\dlederma\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\dlederma\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.14393
          administrator : True

(py35) C:\windows\system32>
"

**Comment by richafrank** [comment]
@drorlederman I installed miniconda on a new Windows box:
```
(py35) C:\Users\Administrator>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\Administrator\Miniconda3  (writable)
    default environment : C:\Users\Administrator\Miniconda3\envs\py35
       envs directories : C:\Users\Administrator\Miniconda3\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
          package cache : C:\Users\Administrator\Miniconda3\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.14393
          administrator : True
```
I made a new conda env with `conda create -n py35 python=3.5` and then tried `conda install -c quantopian zipline` successfully. Then instead I tried first `conda install blaze` followed by zipline, also successfully. 

Is the error you're seeing from `blaze` incompatibility? Which version of which blaze package do you have installed? Any chance my slightly newer conda version fixed a bug?

**Comment by ernestoeperez88** [comment]
It looks like this thread has gone stale. Please feel free to reopen if you are still having trouble getting zipline to work on conda.
