### ISSUE TITLE
If the clock property is not set, then create one based on frequency.

### ISSUE THREAD

**Issue by llazzaro** [quantopian/zipline#1929]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: 16.7.0 Darwin Kernel Version 16.7.0
* Python Version: `Python 3.6.0`
* Python Bitness: `64`
* How did you install Zipline: pyenv+pip
* Python packages: not required

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

[algorithm.py line 495](https://github.com/quantopian/zipline/blob/master/zipline/algorithm.py#L495) has the comment:

*If the clock property is not set, then create one based on frequency.*

However there is not way to set the clock propery and even if the property is set I can't change the clock provider.
I'm working on a tools that uses zipline and I implemented a different clock.

## What steps have you taken to resolve this already?

I can do a pull request and add another parameter (using pop kwargs) on the __init__ and change the _create_clock function.

I'm not sure if the comment means what I'm reporting in this issue

Sincerely,
Leonardo

**Comment by dmichalowicz** [comment]
Hi @llazzaro, thanks for opening an issue and apologies for the silence here. The simulation clock is derived from the [trading calendar](https://github.com/quantopian/trading_calendars) you are working with. Would it be possible to perhaps run on a (custom) calendar that adheres to the clock you implemented? If that isn't suitable and this is still an issue, also feel free to open a pull request and we will try to further assist in a timely manner.

**Comment by llazzaro** [comment]
We can close this! thanks
