### ISSUE TITLE
Running backtests before 2002

### ISSUE THREAD

**Issue by DavisOwen** [quantopian/zipline#1931]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Ubuntu 16.04
* Python Version: 2.7.12
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: 
adium-theme-ubuntu==0.3.4
alabaster==0.7.10
alembic==0.9.5
algopy==0.5.3
appdirs==1.4.3
argcomplete==0.8.1
argh==0.26.2
Babel==2.3.4
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
bcolz==0.12.1
beautifulsoup4==4.5.3
bleach==1.5.0
blinker==1.3
Bottleneck==1.2.1
bs4==0.0.1
cachetools==2.0.0
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
click==6.7
colorama==0.3.7
CommonMark==0.5.4
ConfigArgParse==0.11.0
configparser==3.5.0
construct==2.5.2
contextlib2==0.5.5
cryptography==1.2.3
cssutils==1.0.2
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.26
decorator==4.1.2
Django==1.8.7
django-extensions==1.7.8
docutils==0.13.1
empyrical==0.3.0
entrypoints==0.2.2
enum34==1.1.6
f.lux-indicator-applet==1.1.8
feedparser==5.1.3
Flask==0.11.1
functools32==3.2.3.post2
h2==2.4.4
h5py==2.6.0
hpack==2.3.0
html2text==2016.9.19
html5lib==0.999
hyperframe==4.0.2
idna==2.5
imageio==2.1.2
imagesize==0.7.1
inflection==0.3.1
intervaltree==2.1.0
ipaddress==1.0.18
ipykernel==4.5.2
ipython==5.4.1
ipython-genutils==0.2.0
ipywidgets==5.2.2
isodate==0.5.4
itsdangerous==0.24
Jinja2==2.9.4
joblib==0.11
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.1.0
jupyter-core==4.2.1
Logbook==1.1.0
lru-dict==1.1.6
lxml==3.5.0
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.0.2
mistune==0.7.3
mitmproxy==0.15
more-itertools==3.2.0
moviepy==0.2.2.13
multipledispatch==0.4.9
nbconvert==5.0.0
nbformat==4.2.0
nbsphinx==0.2.13
netlib==0.15.1
networkx==1.11
notebook==4.3.1
numdifftools==0.9.20
numexpr==2.6.2
numpy==1.13.1
numpydoc==0.6.0
olefile==0.44
packaging==16.8
pandas==0.18.1
pandas-datareader==0.5.0
pandocfilters==1.4.1
passlib==1.6.5
pathlib2==2.3.0
pathtools==0.1.2
patsy==0.4.1
pexpect==4.2.1
pickleshare==0.7.4
Pillow==3.4.2
prompt-toolkit==1.0.14
ptyprocess==0.5.2
pyasn1==0.1.9
pycparser==2.18
pycurl==7.43.0
Pygments==2.2.0
pygobject==3.20.0
pyinotify==0.9.6
pymc3==3.0
PyMySQL==0.7.2
pyOpenSSL==0.15.1
pyparsing==2.2.0
pyperclip==1.5.27
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.2
pyxdg==0.25
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.2.1
Quandl==3.2.0
rdflib==4.1.2
recommonmark==0.4.0
requests==2.17.3
requests-file==1.4.2
requests-ftp==0.3.1
requests-toolbelt==0.7.1
scandir==1.5
scikit-learn==0.19.0
scipy==0.19.1
seaborn==0.7.1
simplegeneric==0.8.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sortedcontainers==1.5.7
SPARQLWrapper==1.6.4
Sphinx==1.5.3
SQLAlchemy==1.1.13
sqlparse==0.1.18
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.10
tables==3.4.2
tabulate==0.7.7
terminado==0.6
testpath==0.3
Theano==0.8.2
toolz==0.8.2
tornado==4.4.2
tqdm==4.11.2
traitlets==4.3.2
unity-lens-photos==1.0
urllib3==1.21.1
urwid==1.3.1
uTidylib==0.2
watchdog==0.8.3
wcwidth==0.1.7
Werkzeug==0.12.2
wget==3.2
widgetsnbextension==1.2.6
yahoo-finance==1.4.0
zipline==1.1.1+60.g147129c.dirty

Now that you know a little about me, let me tell you about the issue I am
having:

I am trying to run a backtest from 1989-01-05 to 2017-8-1, using the quandl data set (also used quantopian quandl) and I keep getting the error

> Traceback (most recent call last):
>   File "./bpj.py", line 107, in <module>
>     results= run_algorithm(start=start,end=end,initialize=initialize,capital_base=10000,bundle='quandl')
>   File "/usr/local/lib/python2.7/dist-packages/zipline/utils/run_algo.py", line 360, in run_algorithm
>     environ=environ,
>   File "/usr/local/lib/python2.7/dist-packages/zipline/utils/run_algo.py", line 179, in _run
>     overwrite_sim_params=False,
>   File "/usr/local/lib/python2.7/dist-packages/zipline/algorithm.py", line 705, in run
>     for perf in self.get_generator():
>   File "/usr/local/lib/python2.7/dist-packages/zipline/gens/tradesimulation.py", line 225, in transform
>     handle_benchmark(normalize_date(dt))
>   File "/usr/local/lib/python2.7/dist-packages/zipline/gens/tradesimulation.py", line 181, in handle_benchmark
>     benchmark_source.get_value(date)
>   File "/usr/local/lib/python2.7/dist-packages/zipline/sources/benchmark_source.py", line 75, in get_value
>     return self._precalculated_series.loc[dt]
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1296, in __getitem__
>     return self._getitem_axis(key, axis=0)
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1466, in _getitem_axis
>     self._has_valid_type(key, axis)
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1403, in _has_valid_type
>     error()
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1390, in error
>     (key, self.obj._get_axis_name(axis)))
> KeyError: 'the label [1990-01-02 00:00:00+00:00] is not in the [index]'

Upon further inspection, it seems that the issue is that the backtester has no benchmark data for SPY before 2002. I tried running from 2002 onward and received no errors, but any date before that is a problem. Is there any way to run without a benchmark? I also tried manually using set_benchmark using google finance data for SPY, but unfortunately that data only returned data from 2001 onward and returned the error here

> Traceback (most recent call last):
>   File "./bpj.py", line 110, in <module>
>     results= run_algorithm(start=start,end=end,initialize=initialize,capital_base=10000,bundle='quandl')
>   File "/usr/local/lib/python2.7/dist-packages/zipline/utils/run_algo.py", line 360, in run_algorithm
>     environ=environ,
>   File "/usr/local/lib/python2.7/dist-packages/zipline/utils/run_algo.py", line 179, in _run
>     overwrite_sim_params=False,
>   File "/usr/local/lib/python2.7/dist-packages/zipline/algorithm.py", line 705, in run
>     for perf in self.get_generator():
>   File "/usr/local/lib/python2.7/dist-packages/zipline/algorithm.py", line 604, in get_generator
>     return self._create_generator(self.sim_params)
>   File "/usr/local/lib/python2.7/dist-packages/zipline/algorithm.py", line 583, in _create_generator
>     self._create_benchmark_source(),
>   File "/usr/local/lib/python2.7/dist-packages/zipline/algorithm.py", line 542, in _create_benchmark_source
>     self.benchmark_sid)
>   File "/usr/local/lib/python2.7/dist-packages/zipline/assets/assets.py", line 433, in retrieve_asset
>     asset = self._asset_cache[sid]
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 806, in __hash__
>     ' hashed'.format(self.__class__.__name__))
> TypeError: 'DataFrame' objects are mutable, thus they cannot be hashed

**Comment by DavisOwen** [comment]
So I think the problem can be fixed by importing google SPY data with benchmarks.py, but even then SPY data only goes back to 1993 when it began. I may be getting greedy here, but in order to run backtests for as long as possible (back to the 1970's), it seems that the only options are to 1. get a new benchmark or 2. run backtest without a benchmark.

Does anyone have any longer running alternative benchmarks that go back that far, and also, how I can change ziplines fundamental functionalities to run without benchmark data and just calculate returns, overall portfolio value, etc.

**Comment by ssanderson** [comment]
@DavisOwen I'm going through and consolidating benchmark-related issues in Zipline. I think the issue here (as you already observed) is that we don't provide a good mechanism for overriding the default benchmark, which has been fetched from various external sources over the years.

I've opened https://github.com/quantopian/zipline/issues/2627 to track that issue. Feel free to reopen this if you think there's something here that's not adequately captured in that issue.
