### ISSUE TITLE
Pipeline output, orders and transactions - lags in daily mode

### ISSUE THREAD

**Issue by I-Larsson** [quantopian/zipline#1934]
![zipline output](https://user-images.githubusercontent.com/27955548/30212754-9960e4d4-94a6-11e7-8dbb-4aeabfdfc615.png)

Hi fellow-zipliners, 

As you guys can see from the outputs attached the pipeline-output gets generated on the first trading day before close, the orders get executed at the end of that trading day, and the transaction happens the next day at close for a given stock.

My concern with this process is the lag between pipeline output and the transaction itself. The last close price which was used in the calculation of RSI was the closing price for the previous trading day, and the transaction price is based on closing price two days later.

Ideally I would like to execute the orders and transactions on the same day, that way I would buy at the first closing price after the pipeline output, instead of two bars later like in this instance. I am aware that instant_fill is in the doc-string for the TradingAlgorithm and may seem appropriate in this case, but it is not implemented as an argument to the init-method. 

Here is the zipline algorithm that is based on the outputs: 

`def make_pipeline():
    
    latest_close = USEquityPricing.close.latest		
    window_length = 3
    inputs = [USEquityPricing.close]

    rsi = RSI(inputs = inputs, window_length = window_length)
    longs = rsi.top(3)   
 
    pipe_columns = columns={"RSI": rsi,  
                           "latest close" : latest_close,
                           "longs": longs}
    
    pipe = Pipeline(columns = pipe_columns, screen = longs)
    
    return pipe

def initialize(context):

    attach_pipeline(make_pipeline(), 'my_pipeline')

     schedule_function(rebalance, date_rules.every_day(), time_rules.market_close())
		    
     set_slippage(slippage.FixedSlippage(spread=0.0))
     set_commission(commission.PerTrade(cost=0))
		
		
def before_trading_start(context, data):
	
     context.output = pipeline_output('my_pipeline').dropna()
     context.all_stocks = context.output.index
     context.longs = context.output[context.output.longs == True].index
     context.pipeline_date = context.blotter.current_dt
	
def handle_data(context, data):
	
	pass

def rebalance(context, data):

	
      for security in context.longs:
	
         if get_open_orders(security):

	      continue

	  elif data.can_trade(security):
    
                order_target_percent(security, 1.0 / len(context.longs))
`
Other info:
-	I am using daily frequency
-	Zipline-version: 1.0.2
-	Python 2.7
-       Bundle ingested with Scandinavian stocks and the correct trading calendar. 

One observation is that scheduling a function based on time_rules does not have any effect on the behavior on the algorithm, which I find a bit strange since both open and close prices are ingested in the bundle used. Another is that before trading start runs around the middle of trading day, and not before the actual trading of the day starts. 

Any suggestions on how I can deal with these issues are much appreciated.

**Comment by I-Larsson** [comment]
Seems like the before_trading_start-function is hardcoded with "US/Eastern"-timezone. Changed this to local timezone.

**Comment by ayxemma** [comment]
does this (changing to local timezone) make sure trades executed onthe same day?

**Comment by SigmaZipline** [comment]
Yes, in my case it did. You can try it out, and see if it works.
