### ISSUE TITLE
Zipline cant find any symbols

### ISSUE THREAD

**Issue by LennyKitty** [quantopian/zipline#1936]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: `$ python --version`
Python 2.7.12
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
64
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
pip
* Python packages: `$ pip freeze` or `$ conda list`
alembic==0.8.2.dev0
attrs==15.2.0
bcolz==0.12.1
BeautifulSoup==3.2.1
blinker==1.3
Bottleneck==1.2.1
certifi==2017.7.27.1
chardet==3.0.4
click==6.2
colorama==0.3.7
configglue==1.1.2
configobj==5.0.6
contextlib2==0.5.5
cryptography==1.2.3
cyordereddict==1.0.0
Cython==0.26.1
debtags==2.0
decorator==4.1.2
defer==1.0.6
dirspec==13.10
duplicity==0.7.6
ecdsa==0.13
empyrical==0.3.2
enum34==1.1.2
feedparser==5.1.3
httplib2==0.9.1
idna==2.6
intervaltree==2.1.0
ipaddress==1.0.16
lockfile==0.12.2
Logbook==1.1.0
lru-dict==1.1.6
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
multipledispatch==0.4.9
nemo-emblems==3.4.1
netifaces==0.10.4
networkx==1.11
numexpr==2.6.2
numpy==1.13.1
oauthlib==1.0.3
oneconf==0.3.9
PAM==0.4.2
pandas==0.18.1
pandas-datareader==0.5.0
paramiko==1.16.0
patsy==0.4.1
pexpect==4.0.1
Pillow==3.1.2
piston-mini-client==0.7.5
protobuf==2.6.1
ptyprocess==0.5
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0
pygobject==3.20.0
pyinotify==0.9.6
PyJWT==1.3.0
pyOpenSSL==0.15.1
pyparted==3.10.7
pyserial==3.0.1
pysmbc==1.0.15.5
python-apt==1.1.0b1
python-dateutil==2.6.1
python-debian==0.1.27
python-xlib==0.14
pytz==2017.2
pyxdg==0.25
reportlab==3.3.0
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scipy==0.19.1
service-identity==16.0.0
setproctitle==1.1.8
six==1.10.0
sortedcontainers==1.5.7
SQLAlchemy==1.0.11
statsmodels==0.8.0
TA-Lib==0.4.9
tables==3.4.2
toolz==0.8.2
Twisted==16.0.0
urllib3==1.22
uTidylib==0.2
wxPython==3.0.2.0
wxPython-common==3.0.2.0
zipline==1.1.1
zope.interface==4.1.3

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Zipline cannot find any symbols or sid
* What did you expect to happen?
to find the symbols
* What happened instead?
cant find any symbol

Here is how you can reproduce this issue on your machine:
from zipline.api import symbol 
then in initatialize or before trading start set a variable to a asset symbol.

EDIT: nevermind, it can find AAPL but it cant find SPY, or USO both of which I have used on quantopian.

**Comment by DavisOwen** [comment]
Zipline uses the quandl WIKI/EOD dataset 

https://www.quandl.com/data/WIKI-Wiki-EOD-Stock-Prices

SPY and USO are not apart of this dataset, as it only has stocks, not etfs. You're gonna have to import both manually if you want to use them. You're gonna have to write your own custom ingest functions and such it's a little bit of a pain.

Zipline also has a SPY_benchmark.csv file that contains SPY data from 2001 automatically downloaded in your ~/.zipline/data directory

**Comment by FreddieV4** [comment]
Hi @LennyKitty I'd like to add to what @DavisOwen said; Zipline does use the Quandl WIKI dataset, which is not the same dataset that is provide by Quantopian (as there are many data sources on there). Zipline uses [Data Bundles](http://www.zipline.io/bundles.html) for ingesting data and using that for backtests.

**Comment by Gillu13** [comment]
Do you think this might be linked with the fact that Google recently stopped providing historical data older than one year?

https://github.com/pydata/pandas-datareader/issues/391

**Comment by ernestoeperez88** [comment]
Closing as the original question has been answered. Please feel free to reopen if any more questions come up.

@Gillu13 loosing historical data from Google turned out to affect the way we used to get benchmark returns, which has since been ported to use IEX. As mentioned above, the data bundle that comes with zipline sources data from quandl WIKI, which does not include ETFs (SPY, USO).
