### ISSUE TITLE
Cant create custom yahoo bundle

### ISSUE THREAD

**Issue by LennyKitty** [quantopian/zipline#1937]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: `$ python --version`
Python 2.7.12
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
64
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
pip
* Python packages: `$ pip freeze` or `$ conda list`
alembic==0.8.2.dev0
attrs==15.2.0
bcolz==0.12.1
BeautifulSoup==3.2.1
blinker==1.3
Bottleneck==1.2.1
certifi==2017.7.27.1
chardet==3.0.4
click==6.2
colorama==0.3.7
configglue==1.1.2
configobj==5.0.6
contextlib2==0.5.5
cryptography==1.2.3
cyordereddict==1.0.0
Cython==0.26.1
debtags==2.0
decorator==4.1.2
defer==1.0.6
dirspec==13.10
duplicity==0.7.6
ecdsa==0.13
empyrical==0.3.2
enum34==1.1.2
feedparser==5.1.3
httplib2==0.9.1
idna==2.6
intervaltree==2.1.0
ipaddress==1.0.16
lockfile==0.12.2
Logbook==1.1.0
lru-dict==1.1.6
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
multipledispatch==0.4.9
nemo-emblems==3.4.1
netifaces==0.10.4
networkx==1.11
numexpr==2.6.2
numpy==1.13.1
oauthlib==1.0.3
oneconf==0.3.9
PAM==0.4.2
pandas==0.18.1
pandas-datareader==0.5.0
paramiko==1.16.0
patsy==0.4.1
pexpect==4.0.1
Pillow==3.1.2
piston-mini-client==0.7.5
protobuf==2.6.1
ptyprocess==0.5
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0
pygobject==3.20.0
pyinotify==0.9.6
PyJWT==1.3.0
pyOpenSSL==0.15.1
pyparted==3.10.7
pyserial==3.0.1
pysmbc==1.0.15.5
python-apt==1.1.0b1
python-dateutil==2.6.1
python-debian==0.1.27
python-xlib==0.14
pytz==2017.2
pyxdg==0.25
reportlab==3.3.0
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scipy==0.19.1
service-identity==16.0.0
setproctitle==1.1.8
six==1.10.0
sortedcontainers==1.5.7
SQLAlchemy==1.0.11
statsmodels==0.8.0
TA-Lib==0.4.9
tables==3.4.2
toolz==0.8.2
Twisted==16.0.0
urllib3==1.22
uTidylib==0.2
wxPython==3.0.2.0
wxPython-common==3.0.2.0
zipline==1.1.1
zope.interface==4.1.3

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
If I try to create a custom yahoo bundle as is discribed in documenation here: http://www.zipline.io/_modules/zipline/data/bundles/yahoo.html
and try to ingest the bundle I get this
```
File "/usr/local/bin/zipline", line 11, in
load_entry_point('zipline-live==1.1.0.1', 'console_scripts', 'zipline')()
File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in call
return self.main(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
return process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
return ctx.invoke(self.callback, *ctx.params)
File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
return callback(args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/zipline/main.py", line 360, in ingest
show_progress,
File "/usr/local/lib/python2.7/dist-packages/zipline/data/bundles/core.py", line 451, in ingest
pth.data_path([name, timestr], environ=environ),
File "/usr/local/lib/python2.7/dist-packages/zipline/data/bundles/yahoo.py", line 152, in ingest
session=session,
File "/usr/local/lib/python2.7/dist-packages/pandas_datareader/data.py", line 126, in DataReader
session=session).read()
File "/usr/local/lib/python2.7/dist-packages/pandas_datareader/yahoo/actions.py", line 35, in read
splits['value'] = splits.apply(lambda x: 1/eval(x['value']), axis=1) # noqa
File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2357, in _setitem__
self.set_item(key, value)
File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2422, in _set_item
self._ensure_valid_index(value)
File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2404, in _ensurevalid_index
raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

```
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. modify your extension.py to:
```
from zipline.data.bundles import register, yahoo_equities

# these are the tickers you would like data for  
symbols = {  
    'USO',    
    'SPY',  
}
register(  
    'my-yahoo-equities-bundle',  # name this whatever you like  
    yahoo_equities(symbols),  
)
```
2.
run zipline ingest -b my_yahoo_equities_bundle

**Comment by DavisOwen** [comment]
yahoo's api is deprecated, I believe.

**Comment by LennyKitty** [comment]
Is there any other way I can obtain this data then?

**Comment by DavisOwen** [comment]
Sure, you can google it and some free sources of SPY data (not sure about USO) but it should be no problem. Google finance is an obvious choice. You could also manually download the csv file from yahoo finance on their website and ingest from that csv.

**Comment by LennyKitty** [comment]
Ok, that works I guess, how would I go about importing minute data?

**Comment by DavisOwen** [comment]
Don't know, you probably have to pay for minute data

**Comment by FreddieV4** [comment]
Hi @LennyKitty we've removed support for Yahoo bundles in Zipline 1.1.1 (you can check the [release notes](http://www.zipline.io/releases.html#release-1-1-1)). Not sure why the Yahoo bundle code is still in the `_modules` directory so I'll have to look into removing that.

In order to get minutely data, you'd have to find some data source that would be able to provide you with that and then create your own custom bundle.

**Comment by LennyKitty** [comment]
I have found sources that provide the last few months of minute data, honestly it is not so important that I have past minute data so much as I can use zipline live to run a algo live and have it trade minutely.

**Comment by freddiev4** [comment]
If you only have daily data, you should be able to run a Zipline backtest

**Comment by freddiev4** [comment]
Going to close due to inactivity. If you still have issue, feel free to re-open or open a new issue.
