### ISSUE TITLE
The latest zipline-1.1.1 is not supported by Python 3.6?

### ISSUE THREAD

**Issue by thomas2004ch** [quantopian/zipline#1938]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows Server 2016
* Python Version: Anaconda 3-4.4
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: conda.exe  install -c Quantopian zipline
* Python packages: The package list is very long. (How can I attach it?)

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?

* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

I use the Anaconda 3-4.4 which contains the Python 3.6. As I try to install the zipline, I got message as follow:
...
C:\ProgramData\Anaconda3\Scripts>conda.exe  install -c Quantopian zipline
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - zipline -> alembic >=0.7.7 -> python 3.5*
Use "conda info <package>" to see the dependencies for each package.

What does this mean? It seems the latest zipline-1.1.1 is not supported by Python 3.6?

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ Thomas`

**Comment by richafrank** [comment]
Hi Thomas,

Sorry for the trouble. Zipline should run on python 3.6, but we don't have conda packages for it. We have 2.7, 3.4, and 3.5. If you have a local compiler toolchain set up properly, you should be able to `pip install zipline` in your 3.6 environment.

**Comment by thomas2004ch** [comment]
Hi richafrank,

Thanks for the reply first.

1.
I just simply tried the pip install zipline. It did a lot. But at the end it is failt. I got:
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

Must I get the MS VC?

2.
How to use the toolchain to do the compilation?

3.
Is it possible to downgrade my Python3.6 to 3.5 so I can install the zipline with Conda?

**Comment by richafrank** [comment]
1. Hmm, I'm not completely sure what's necessary on windows. I'd expect some environment variables need to be set appropriately so that when pip runs, it finds the right binaries on its PATH. 

1. I've heard mingw might work, but yea, I think most folks are using Microsoft tools via Visual Studio.

1. You can make a [new conda environment](https://conda.io/docs/user-guide/getting-started.html) with python 3.5: `conda create --name <my_env> python=3.5 <any other packages>`.

1. I'm not sure it was on the task list previously, but it is now with this issue. I'm not sure when we'll get to it, but consider its priority bumped...

**Comment by limcheekin** [comment]
@richafrank I created python 3.5 environment as per your suggestion and install zipline using following command:
conda install -c Quantopian zipline

But I'm facing the following error:
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - blaze
  - python 3.5*
  - zipline
Use "conda info <package>" to see the dependencies for each package.

This make me curious whether zipline support python 3.5.3. When I launch python shell, I see the following info:
Python 3.5.3 |Anaconda custom (64-bit)| (default, May 15 2017, 10:43:23) [MSC v.1900 64 bit (AMD64)]
 on win32

Please advise. Thank you.

Best regards,
Chee Kin

**Comment by limcheekin** [comment]
I found the solution at https://github.com/quantopian/zipline/issues/1797

The following is the key point of the message:
do not install anaconda, it may limit your pandas and other packages' version

I created the environment with anaconda.

**Comment by thomas2004ch** [comment]
I ahve the same problem as limcheekin at home. At work there is no any problem. Quite strange.

But I fix it in other way as follow:
1.
pip install zipline
2.
But I got error message and I was asked to install the MS VC++ Builder. I download and install it.
3.
Run 1 again. This time it will take very long, more than 5 minutes. But it is successful. The zipline-1.1.1 is installed.

**Comment by FreddieV4** [comment]
Hi @thomas2004ch glad to hear you figured it out :)

**Comment by billtubbs** [comment]
I did as @richafrank suggested and, after trying to install it with Python 3.6, deleted the whole environment and started again from scratch with a Python 3.5 conda environment and it seems to have worked.
