### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by gehongyi** [quantopian/zipline#1940]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 7
* Python Version: `$ python --3.4
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: `conda`,
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

(py34) C:\Users\hongyi>conda install -c Quantopian zipline
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.4*
  - zipline
Use "conda info <package>" to see the dependencies for each package.
...

## What steps have you taken to resolve this already?

...

# Anything else?
this is my environment:
C:\Users\hongyi>conda info -e
# conda environments:
#
py34                     e:\Users\hongyi\Anaconda2\envs\py34
root                  *  e:\Users\hongyi\Anaconda2

Sincerely,
`$ whoami`

**Comment by FreddieV4** [comment]
Hi @gehongyi can you post the output of `conda info`?

And also can you try making a new Python 3.4 `conda env` and then install Zipline?

**Comment by gehongyi** [comment]
@FreddieV4 
C:\Users\hongyi>conda info
Current conda install:

               platform : win-32
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 1.20.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : e:\Users\hongyi\Anaconda2  (writable)
    default environment : e:\Users\hongyi\Anaconda2
       envs directories : e:\Users\hongyi\Anaconda2\envs
                          C:\Users\hongyi\AppData\Local\conda\conda\envs
                          C:\Users\hongyi\.conda\envs
          package cache : e:\Users\hongyi\Anaconda2\pkgs
                          C:\Users\hongyi\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.12.4 CPython/2.7.13 Windows/7
Windows/6.1.7601
          administrator : False

**Comment by gehongyi** [comment]
@FreddieV4 
(py34) C:\Users\hongyi>conda info
Current conda install:

               platform : win-32
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 1.20.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : e:\Users\hongyi\Anaconda2  (writable)
    default environment : e:\Users\hongyi\Anaconda2\envs\py34
       envs directories : e:\Users\hongyi\Anaconda2\envs
                          C:\Users\hongyi\AppData\Local\conda\conda\envs
                          C:\Users\hongyi\.conda\envs
          package cache : e:\Users\hongyi\Anaconda2\pkgs
                          C:\Users\hongyi\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.12.4 CPython/2.7.13 Windows/7
Windows/6.1.7601
          administrator : False

thanks

**Comment by gehongyi** [comment]
@FreddieV4 
I have installed by (conda conda install -c Quantopian zipline ) on another computer , but the same problem arised.
what can i do to resolve the problem?
many thanks!

**Comment by FreddieV4** [comment]
@gehongyi It looks like you're using Windows 32-bit. We don't have conda packages built for 32-bit Windows.

`pip` or win-64 conda should install Zipline successfully. **Note**: for `pip` you'll need to make sure it can compile Zipline's C extensions. The conda packages are already compiled.

**Comment by freddiev4** [comment]
Hi @gehongyi I'm going to close this due to inactivity. Feel free to re-open if you have issues again 🙂
