### ISSUE TITLE
Remove dead code links from _modules on zipline.io

### ISSUE THREAD

**Issue by FreddieV4** [quantopian/zipline#1941]
It appears we still have links to dead code in zipline.io via the `_modules` directory.

e.g. http://www.zipline.io/_modules/zipline/data/bundles/yahoo.html

Noticed this because it was mentioned in #1937

**Comment by richafrank** [comment]
With #1943 merged, I believe we just need to deploy updated docs. If we want to deploy the version from the latest release instead, can just run `make clean` first.

**Comment by richafrank** [comment]
Updated zipline.io after cleaning my output directory
