### ISSUE TITLE
Why the installed zipline can not be shown?

### ISSUE THREAD

**Issue by thomas2004ch** [quantopian/zipline#1944]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 7
* Python Version: 3.5.4
* Python Bitness: 
* How did you install Zipline: conda install -c Quantopian zipline
* Python packages: The list is too long to post here

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I've just created a Python 3.5 environment under Anaconda 4. Then I install the zipline and it tells successful as follow:
zipline-1.1.1- 100% |###############################| Time: 0:00:00   1.48 MB/s

But as I check with 'conda search --full-name zipline', I get the following messages:
...
PackageNotFoundError: Packages missing in current channels:

  - zipline

We have searched for the packages in the following channels:

  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

Why?

* What did you expect to happen?
The installed zipline version should be shown.

* What happened instead?
Zipline not found.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps
conda search --full-name zipline

## What steps have you taken to resolve this already?
No idea.

# Anything else?

...

Sincerely,

Thomas

**Comment by richafrank** [comment]
Hi Thomas, 

I'm not 100% certain, but I believe `conda search` is searching the anconda package index in the default channel(s), and there are no zipline packages in those channels. To add the quantopian channel to your search, you'd run:

```bash
$ conda search --full-name zipline -c quantopian
```

**Comment by richafrank** [comment]
`conda list` should show the packages installed in your current conda environment.

**Comment by thomas2004ch** [comment]
@richafrank 
this works. Many thanks.

$ conda search --full-name zipline -c quantopian

**Comment by richafrank** [comment]
Great!
