### ISSUE TITLE
Got unexpected extra argument (ingest)

### ISSUE THREAD

**Issue by gehongyi** [quantopian/zipline#1955]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 7)
* Python Version: `$ python --3.5`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

When I type "zipline ingest -b quantopian-quandl" in my notebook,it shows the following error:
UsageError                                Traceback (most recent call last)
<ipython-input-14-826c1ccc1356> in <module>()
----> 1 get_ipython().magic('zipline ingest -b quantopian-quandl')

e:\Users\hongyi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

e:\Users\hongyi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

e:\Users\hongyi\Anaconda3\lib\site-packages\zipline\__main__.py in zipline_magic(line, cell)
    273             '%s%%zipline' % ((cell or '') and '%'),
    274             # don't use system exit and propogate errors to the caller
--> 275             standalone_mode=False,
    276         )
    277     except SystemExit as e:

e:\Users\hongyi\Anaconda3\lib\site-packages\click\core.py in main(self, args, prog_name, complete_var, standalone_mode, **extra)
    693         try:
    694             try:
--> 695                 with self.make_context(prog_name, args, **extra) as ctx:
    696                     rv = self.invoke(ctx)
    697                     if not standalone_mode:

e:\Users\hongyi\Anaconda3\lib\site-packages\click\core.py in make_context(self, info_name, args, parent, **extra)
    618         ctx = Context(self, info_name=info_name, parent=parent, **extra)
    619         with ctx.scope(cleanup=False):
--> 620             self.parse_args(ctx, args)
    621         return ctx
    622 

e:\Users\hongyi\Anaconda3\lib\site-packages\click\core.py in parse_args(self, ctx, args)
    877             ctx.fail('Got unexpected extra argument%s (%s)'
    878                      % (len(args) != 1 and 's' or '',
--> 879                         ' '.join(map(make_str, args))))
    880 
    881         ctx.args = args

e:\Users\hongyi\Anaconda3\lib\site-packages\click\core.py in fail(self, message)
    473         :param message: the error message to fail with.
    474         """
--> 475         raise UsageError(message, self)
    476 
    477     def abort(self):

UsageError: Got unexpected extra argument (ingest)

What can I do to resolve the problem?
many thanks!

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by FreddieV4** [comment]
Hi @gehongyi can you:

- Print out the information for `conda info`
- And also tell me how you're running the command? `zipline ingest` is ran via CLI so this should be done in your terminal or command prompt. If you type `! zipline ingest` it will run it as it would with the CLI

**Comment by gehongyi** [comment]
I typed "zipline ingest" in jupyter notebook!
Now I have resolved the problem.
Thank you very much!
