### ISSUE TITLE
DataPortal.get_history_window() ignore ffill parameter

### ISSUE THREAD

**Issue by tibkiss** [quantopian/zipline#1962]
get_history_window() function in DataPortal accepts a boolean flag which should enable forward filling prices: https://github.com/quantopian/zipline/blob/ec94e5aa9f57c30939d18585758d15da352b9dce/zipline/data/data_portal.py#L873

Currently the flag is ignore, the price is always forward filled:
https://github.com/quantopian/zipline/blob/ec94e5aa9f57c30939d18585758d15da352b9dce/zipline/data/data_portal.py#L925

It would be required for zipline-live to disable forward filling in DataPortal to properly present the buffered prices throughout the run.

**Comment by FreddieV4** [comment]
x-ref https://github.com/quantopian/zipline/pull/1963

**Comment by dmichalowicz** [comment]
Looks like the PR for this was closed, so I'm going to close this for now too.
