### ISSUE TITLE
KeyError: 'the label [2011-01-03 00:00:00+00:00] is not in the [index]'

### ISSUE THREAD

**Issue by zxweed** [quantopian/zipline#1968]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux neurox 4.4.0-79-generic #100~14.04.1-Ubuntu SMP Fri May 19 18:36:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Python Version: Python 3.5.4 :: Anaconda custom (64-bit) 
Python 2.7.13 :: Continuum Analytics, Inc.

* How did you install Zipline: pip and conda

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I have to install the zipline (different OSes, python versions and zipline, including the developers), run the default example and get the error KeyError: 'the label [2011-01-03 00:00:00+00:00] is not in the [index]'

There are many anoher unfixed issues about this:
https://www.quantopian.com/posts/running-zipline-algorithm-keyerror-the-label-2000-01-03-00-00-00-plus-00-00-is-not-in-the-index
https://github.com/quantopian/zipline/issues/1911

I have downloaded file SPY_benchmark.csv and replaced it in zipline data folder - error still exists. Please, help.

**Comment by stjordanis** [comment]
I also have this problem, when running even the simplest algos:


class BollingerBands(TradingAlgorithm):   
   
    def initialize(self):
        self.i = 0

        self.invested       = False
       
        self.trade_size=1000
        self.long = False
        self.short = False
        self.closed = False
        self.trading_day_counter = 0  
        self.pct_stop = 0.025
        self.long_stop_price =  0.0
        self.short_stop_price=0.0
        self.target=0.05
        commission_cost = self.trade_size * COMMISSION
        self.set_slippage(FixedSlippage(spread=0.10))  
        self.set_commission(PerTrade(cost=commission_cost))  

    def handle_data(self, data):
        self.i += 1
        if self.i < 300:
                    return
       
        if data['Close'].price >= data['upper'].price and not self.invested:
            self.order('Close', self.trade_size)
            self.long_stop_price =  data['Open'].price - data['Open'].price * float(self.pct_stop) 
            self.short_stop_price =  data['Open'].price + data['Open'].price * float(self.target)
            self.long = True
            self.closed=False
            self.invested = True
            self.trading_day_counter = 0  
        if data['Close'].price <= data['lower'].price and not self.invested:
            self.short_stop_price =  data['Open'].price + data['Open'].price * float(self.pct_stop)
            self.long_stop_price =  data['Open'].price - data['Open'].price * float(self.target) 
            self.order('Close', -self.trade_size)
            self.short = True
            self.closed=False
            self.invested = True
            self.trading_day_counter = 0  
        if self.invested and (data['Close'].price <=  self.long_stop_price or data['Close'].price >=  self.short_stop_price): #or self.trading_day_counter == HOLDTIME):
  
            if self.long: 
                self.order('Close', -self.trade_size)
            if self.short:
                self.order('Close', self.trade_size)
 
            self.closed=True
            self.long=False
            self.short=False
            self.invested=False
           

        self.trading_day_counter =  self.trading_day_counter +1
        self.record(Close=data['Close'].price,
                    upper=data['upper'].price,
                    lower=data['lower'].price,
                    long=self.long,
                    short=self.short,
                    holdtime=self.trading_day_counter,
                    closed_position=self.closed,
                    shares=self.trade_size)






or:

apple=download("AAPL", start, end)
start = datetime(2010, 1, 1, 0, 0, 0, 0, pytz.utc).date()
end = datetime(2017,1,1,0,0,0,0, pytz.utc).date()
apple.to_csv('AAPL', sep=',')


datas['AAPL'] = pd.read_csv('AAPL', index_col=0, parse_dates=['Date'])
datas['AAPL'] = apple
#datas['AAPL'] = pd.read_csv('AAPL' ,names = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'])

#datas['SPY'] = pd.read_csv('/home/priyanka.s/work/algorithms/mac/CHRIS-CME_GC1.csv', index_col=0, parse_dates=['Date'])
#datas['SPY'] = datas['SPY'][::-1]

#converting dataframe data into panel
panel = pd.Panel(datas)
panel.minor_axis = ['open', 'high', 'low', 'close', 'volume', 'price']
panel.major_axis = panel.major_axis.tz_localize(pytz.utc)
                   
csv_data = []
def initialize(context):
    context.i = 0
#    context.__skipping = 10  
    context.security = symbol('AAPL')
#    __skipping = 101  

    csv_data.append(["date","MA1","MA2","Current Price","Buy/Sell","Shares","PnL","Cash","Value"])

def handle_data(context, panel):
    #calculating moving average
    context.i += 1
    if context.i < 300:
#    if context.index < datetime(2011, 1, 1, 0, 0, 0, 0, pytz.utc).date():
       return  
#    if context.__skipping:  
#            context.__skipping -= 1  
#            return
    MA1 = panel[context.security].mavg(50)
    MA2 = panel[context.security].mavg(100)
    date = str(panel[context.security].datetime)[:10]
#    date = panel[context.security].datetime
    #calculating price, pnl, portfolio value
    current_price = panel[context.security].price
    current_positions = context.portfolio.positions[symbol('AAPL')].amount
    cash = context.portfolio.cash
    value = context.portfolio.portfolio_value
    current_pnl = context.portfolio.pnl
    #to buy stock
    if (MA1 > MA2) and current_positions == 0:
        number_of_shares = int(cash/current_price)
        order(context.security, number_of_shares)
        #recording the data
        record(date=date,MA1 = MA1, MA2 = MA2, Price= current_price,status="buy",shares=number_of_shares,\
        PnL=current_pnl,cash=cash,value=value)
        csv_data.append([date,format(MA1, '.2f'),format(MA2, '.2f'),format(current_price, '.2f'),\
        "buy",number_of_shares,format(current_pnl, '.2f'),format(cash, '.2f'),format(value, '.2f')])
    #to sell stocks
    elif (MA1 < MA2) and current_positions != 0:
        order_target(context.security, 0)
        record(date=date,MA1 = MA1, MA2 = MA2, Price= current_price,status="sell",shares="--",\
        PnL=current_pnl,cash=cash,value=value)
        csv_data.append([date,format(MA1, '.2f'),format(MA2, '.2f'),format(current_price, '.2f'),\
        "sell","--",format(current_pnl, '.2f'),format(cash, '.2f'),format(value, '.2f')])
    #do nothing just record the data
    else:
        record(date=date,MA1 = MA1, MA2 = MA2, Price= current_price,status="--",shares="--",\
        PnL=current_pnl,cash=cash,value=value)
        csv_data.append([date,format(MA1, '.2f'),format(MA2, '.2f'),format(current_price, '.2f'),\
        "--","--",format(current_pnl, '.2f'),format(cash, '.2f'),format(value, '.2f')])

#initializing trading enviroment
algo_obj = TradingAlgorithm(initialize=initialize, handle_data=handle_data,  
                                   )

**Comment by stjordanis** [comment]
solution: https://github.com/quantopian/zipline/issues/1953

**Comment by stjordanis** [comment]
https://github.com/minimalgeek/DeepLearning/tree/master/Stock/zipline/other
replace the benchmark.py file and add the csv file found here

**Comment by vighneshbirodkar** [comment]
Can we get an official word on this from the devs ? This issue is seen in many places and is still present in the master branch

**Comment by JoaoAparicio** [comment]
@vighneshbirodkar From what I hear it seems google changed something in their API. Someone suggested changing `google` to `yahoo` on `data/benchmarks.py`, works for me.

**Comment by FreddieV4** [comment]
Hi tehre. The reason for this is because Google has now limited us to about 251 days worth of data, so you can't run backtests over a year. There is a fix currently being worked on.

There are duplicates of this issue so I'm just going to direct everyone to this issue: https://github.com/quantopian/zipline/issues/1965. I'll comment there when there is a fix on master
