### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by thomaslanglois** [quantopian/zipline#1979]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10)
* Python Version: 3.5.3
* Python Bitness: 64
* How did you install Zipline: conda
* Python packages: conda list

_nb_ext_conf              0.3.0                    py35_0  
alabaster                 0.7.10                   py35_0  
anaconda-client           1.6.2                    py35_0  
appdirs                   1.4.2                     <pip>
astroid                   1.4.9                    py35_0  
babel                     2.3.4                    py35_0  
bkcharts                  0.2                      py35_0  
bleach                    1.5.0                    py35_0  
bokeh                     0.12.7                   py35_0  
certifi                   2017.7.27.1               <pip>
chardet                   2.3.0                    py35_0  
chardet                   3.0.4                     <pip>
clyent                    1.2.2                    py35_0  
colorama                  0.3.7                    py35_0  
colorcet                  1.0.0            py35hc27cc94_0    bokeh
cycler                    0.10.0                   py35_0  
decorator                 4.0.11                   py35_0  
docutils                  0.13.1                   py35_0  
duka                      0.2.0                     <pip>
entrypoints               0.2.2                    py35_1  
fix-yahoo-finance         0.0.18                    <pip>
h5py                      2.6.0               np111py35_1  
hdf5                      1.8.16                   vc14_0  [vc14]
html5lib                  0.999                    py35_0  
icu                       57.1                     vc14_0  [vc14]
idna                      2.5                       <pip>
imagesize                 0.7.1                    py35_0  
ipykernel                 4.5.2                    py35_0  
ipython                   5.3.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                5.2.2                    py35_1  
isort                     4.2.5                    py35_0  
jedi                      0.9.0                    py35_1  
jinja2                    2.9.5                    py35_0  
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.5.1                    py35_0  
jupyter_client            5.0.0                    py35_0  
jupyter_core              4.3.0                    py35_0  
Keras                     1.2.2                     <pip>
lazy-object-proxy         1.2.2                    py35_0  
libpng                    1.6.27                   vc14_0  [vc14]
libpython                 2.0                      py35_0  
m2w64-binutils            2.25.1                        5  
m2w64-bzip2               1.0.6                         6  
m2w64-crt-git             5.0.0.4636.2595836               2  
m2w64-gcc                 5.3.0                         6  
m2w64-gcc-ada             5.3.0                         6  
m2w64-gcc-fortran         5.3.0                         6  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gcc-objc            5.3.0                         6  
m2w64-gmp                 6.1.0                         2  
m2w64-headers-git         5.0.0.4636.c0ad18a               2  
m2w64-isl                 0.16.1                        2  
m2w64-libiconv            1.14                          6  
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
m2w64-make                4.1.2351.a80a8b8               2  
m2w64-mpc                 1.0.3                         3  
m2w64-mpfr                3.1.4                         4  
m2w64-pkg-config          0.29.1                        2  
m2w64-toolchain           5.3.0                         7  
m2w64-tools-git           5.0.0.4592.90b8472               2  
m2w64-windows-default-manifest 6.4                           3  
m2w64-winpthreads-git     5.0.0.4634.697f757               2  
m2w64-zlib                1.2.8                        10  
markupsafe                0.23                     py35_2  
matplotlib                2.0.0               np111py35_0  
mingw                     4.7                           1  
mistune                   0.7.3                    py35_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py35_3  
msys2-conda-epoch         20160418                      1  
multitasking              0.0.4                     <pip>
nb_anacondacloud          1.2.0                    py35_0  
nb_conda                  2.0.0                    py35_0  
nb_conda_kernels          2.0.0                    py35_0  
nbconvert                 5.1.1                    py35_0  
nbformat                  4.3.0                    py35_0  
nbpresent                 3.0.2                    py35_0  
nodejs                    6.10.3                        0  
notebook                  4.3.1                    py35_1  
numpy                     1.13.1                    <pip>
numpy                     1.11.3                   py35_0  
numpydoc                  0.6.0                    py35_0  
openssl                   1.0.2k                   vc14_0  [vc14]
packaging                 16.8                      <pip>
pandas                    0.19.2              np111py35_1  
pandas                    0.20.3                    <pip>
pandas-datareader         0.5.0                    py35_0    anaconda
pandocfilters             1.4.1                    py35_0  
path.py                   10.1                     py35_0  
patsy                     0.4.1                    py35_0    anaconda
pep8                      1.7.0                    py35_0  
pickleshare               0.7.4                    py35_0  
pip                       9.0.1                    py35_1  
prompt_toolkit            1.0.9                    py35_0  
protobuf                  3.2.0                     <pip>
psutil                    5.2.0                    py35_0  
pyflakes                  1.5.0                    py35_0  
pygments                  2.2.0                    py35_0  
pylint                    1.6.4                    py35_1  
pyparsing                 2.1.10                    <pip>
pyparsing                 2.1.4                    py35_0  
pyqt                      5.6.0                    py35_2  
python                    3.5.3                         0  
python-dateutil           2.6.1                     <pip>
python-dateutil           2.6.0                    py35_0  
pytz                      2016.10                  py35_0  
pytz                      2017.2                    <pip>
pyyaml                    3.12                     py35_0  
pyzmq                     16.0.2                   py35_0  
qt                        5.6.2                    vc14_3  [vc14]
qtawesome                 0.4.4                    py35_0  
qtconsole                 4.2.1                    py35_2  
qtpy                      1.2.1                    py35_0  
requests                  2.18.3                    <pip>
requests                  2.13.0                   py35_0  
requests-file             1.4.1                    py35_0    anaconda
requests-ftp              0.3.1                    py35_0    anaconda
rope                      0.9.4                    py35_1  
scikit-learn              0.18.1              np111py35_1  
scipy                     0.18.1              np111py35_1  
seaborn                   0.8                      py35_0    anaconda
setuptools                27.2.0                   py35_1  
setuptools                34.3.1                    <pip>
simplegeneric             0.8.1                    py35_1  
sip                       4.18                     py35_0  
six                       1.10.0                    <pip>
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sphinx                    1.5.1                    py35_0  
spyder                    3.1.3                    py35_0  
statsmodels               0.8.0               np111py35_0    anaconda
TA-Lib                    0.4.10                    <pip>
tensorflow-gpu            1.0.0                     <pip>
testpath                  0.3                      py35_0  
theano                    0.8.2                    py35_0  
tk                        8.5.18                   vc14_0  [vc14]
tornado                   4.4.2                    py35_0  
traitlets                 4.3.2                    py35_0  
urllib3                   1.22                      <pip>
vs2015_runtime            14.0.25123                    0  
wcwidth                   0.1.7                    py35_0  
wheel                     0.29.0                    <pip>
wheel                     0.29.0                   py35_0  
widgetsnbextension        1.2.6                    py35_0  
win_unicode_console       0.5                      py35_0  
wrapt                     1.10.8                   py35_0  
zlib                      1.2.8                    vc14_3  [vc14]

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

When I run the below command in my ml35 conda environment, I got the following UnsatisfiableError:

(ml35) C:\Users\thomas>conda install -c Quantopian zipline
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - h5py
  - python 3.5*
  - zipline
Use "conda info <package>" to see the dependencies for each package.

Sincerely,

Thomas

**Comment by richafrank** [comment]
Hi Thomas. This is a difficult one.

First, I can't actually reproduce your environment (even without zipline). I made a new python 3.5.3 conda env, but I can't install the combination of requirements you have:
```bash
(new_oct9) C:\Users\Administrator>conda install hdf5=1.8.16 numpy=1.13.1 h5py=2.6.0
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - h5py 2.6.0* -> numpy 1.10* -> mkl 11.3.1
  - numpy 1.13.1*
Use "conda info <package>" to see the dependencies for each package.
```
which makes sense, since you have an h5py built against numpy 1.11.

With packages built against only numpy=1.11, I _can_ reproduce it, and it looks to be a conflict from zipline 1.1.1 requiring pytables >= 3.3.0 requiring hdf5 1.8.17, but h5py 2.6.0 requires hdf5 1.8.15.1.

There look to be packages of h5py in the conda-forge channel which are compatible with latest zipline. They work for me, at least. Want to try those?

**Comment by thomaslanglois** [comment]
Sorry totally forgot to close this.
I ended up implementing my own backtester and not use zipline!
