### ISSUE TITLE
Replace daily_perf, cumulative_risk_metrics, cumulative_perf, etc. with DataFrames

### ISSUE THREAD

**Issue by benmccann** [quantopian/zipline#198]
These objects are more difficult to work with than the standard pandas DataFrames and they get converted to DataFrames at the end of the day anyway. It might be easier if they started out that way.

As an example, risk.periods_in_range could be replaced by simply calling resample:

```
compound = lambda x: (1+x).prod()-1
returns.resample('1M', how=compound)
```

**Comment by freddiev4** [comment]
I believe there is some work being done in #1933 that addresses this

**Comment by freddiev4** [comment]
Should be addressed in the new [Metrics API](http://www.zipline.io/risk-and-perf-metrics.html)
