### ISSUE TITLE
Error in graph.py when running momentum_pipeline.py example algorithm.  

### ISSUE THREAD

**Issue by VitalyErmilov** [quantopian/zipline#1995]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Ubuntu 16.04
* Python Version: 2.7 
* How did you install Zipline:  pip 
* List of packages:
alembic (0.9.6)
backports.functools-lru-cache (1.4)
bcolz (0.12.1)
Bottleneck (1.2.1)
certifi (2017.7.27.1)
chardet (3.0.4)
click (6.7)
contextlib2 (0.5.5)
cycler (0.10.0)
cyordereddict (1.0.0)
Cython (0.27.2)
decorator (4.1.2)
empyrical (0.3.2)
idna (2.6)
intervaltree (2.1.0)
Logbook (1.1.0)
lru-dict (1.1.6)
Mako (1.0.7)
MarkupSafe (1.0)
matplotlib (2.1.0)
multipledispatch (0.4.9)
networkx (2.0)
numexpr (2.6.4)
numpy (1.13.3)
pandas (0.18.1)
pandas-datareader (0.5.0)
patsy (0.4.1)
pip (9.0.1)
pkg-resources (0.0.0)
pyparsing (2.2.0)
python-dateutil (2.6.1)
python-editor (1.0.3)
pytz (2017.2)
requests (2.18.4)
requests-file (1.4.2)
requests-ftp (0.3.1)
scipy (0.19.1)
setuptools (36.6.0)
six (1.11.0)
sortedcontainers (1.5.7)
SQLAlchemy (1.1.14)
statsmodels (0.8.0)
subprocess32 (3.2.7)
tables (3.4.2)
toolz (0.8.2)
urllib3 (1.22)
v (3.0.0)
wheel (0.30.0)
zipline (1.1.1)

Now that you know a little about me, let me tell you about the issue I am
having:

When I run the momentum_pipeline.py from example algorithms by using the following command: 

**zipline run -f momentum_pipeline.py --start 2017-02-02 --end 2017-10-20 -o results_mom.pickle**

it results in the following error:

Traceback (most recent call last):
  File "/home/ubuntu/venv-zipline/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.1.1', 'console_scripts', 'zipline')()
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/__main__.py", line 97, in _
    return f(*args, **kwargs)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/__main__.py", line 240, in run
    environ=os.environ,
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 179, in _run
    overwrite_sim_params=False,
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/algorithm.py", line 709, in run
    for perf in self.get_generator():
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/gens/tradesimulation.py", line 237, in transform
    algo.before_trading_start(self.current_data)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/algorithm.py", line 453, in before_trading_start
    self._before_trading_start(self, data)
  File "momentum_pipeline.py", line 68, in before_trading_start
    context.pipeline_data = pipeline_output('my_pipeline')
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/utils/api_support.py", line 57, in wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/utils/api_support.py", line 104, in wrapped_method
    return method(self, *args, **kwargs)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/algorithm.py", line 2457, in pipeline_output
    return self._pipeline_output(p, chunks)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/algorithm.py", line 2499, in _pipeline_output
    pipeline, today, next(chunks),
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/algorithm.py", line 2546, in _run_pipeline
    self.engine.run_pipeline(pipeline, start_session, end_session), \
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/pipeline/engine.py", line 311, in run_pipeline
    initial_workspace,
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/pipeline/engine.py", line 471, in compute_chunk
    refcounts = graph.initial_refcounts(workspace)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/pipeline/graph.py", line 147, in initial_refcounts
    refcounts[t] += 1
TypeError: 'OutDegreeView' object does not support item assignment

 
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Run the momentum_pipeline.py example from the environment similar to mine
 

## What steps have you taken to resolve this already?

It looks like the error comes from the file graph.py.  In the function **initial_refcounts** there is a line  
 'refcounts[t] += 1' , but the object doesn't support item assignment.
 I have changed its type to dictionary: 
_before:_
refcounts =   self.graph.out_degree()  
_after:_
**refcounts =  dict(self.graph.out_degree() )**

After this I was able to run the algorithm.   I couldn't find that someone has the similar issue, which is strange cause I just followed the steps to install zipline and there shouldn't be something special in my environment 

 

Sincerely,
Vitaly Ermilov

**Comment by ssanderson** [comment]
@VitalyErmilov the error message here is coming from [networkx](https://networkx.github.io/).  I notice in your pip freeze output that you have networkx 2.0 installed, but our tests are currently running against 1.9.1.  My guess is there are some breaking changes in the newest version of networkx.

**Comment by ssanderson** [comment]
Yup, looks like the behavior of `out_degree` changed in https://networkx.github.io/documentation/stable/release/release_2.0.html#api-changes.

**Comment by VitalyErmilov** [comment]
@ssanderson you're right.  So we need either to make zipline installer to install networkx 1.9.1 by default, which is simpler, or to modify the pipeline code to reflect the changes in api. 
Now this issue impacts zipline's core functionality in all new installations, cause the pipeline algorithms won't run due to the networkx api changes.

**Comment by tamezarnold** [comment]
Thank you @VitalyErmilov  and @ssanderson 
Since I used pip3 to install, i used 
sudo pip3 -uninstall networkx
sudo pip3 -install networkx==1.9.1
now it works like a charm

**Comment by freddiev4** [comment]
Closing this as this should be fixed in the latest release of zipline. Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update zipline -c quantopian
```

**Comment by Floev** [comment]
Hi @ssanderson and @freddiev4 ,

I am seeing exactly the same error using zipline 1.3.0, pip installed in a conda env.
As I am using python 3.6, I cannot downgrade networkx to 1.9.1.
Wrapping `self.graph.out_degree()` with `dict()` as suggested by @VitalyErmilov allows me to get around the issue.

I am good for now, but thought it might be worth looking into,
Thanks, Florian

alembic                   1.0.3                     <pip>
alphalens                 0.3.4                     <pip>
asn1crypto                0.24.0                   py36_0
backcall                  0.1.0                    py36_0
bcolz                     0.12.1                    <pip>
blas                      1.0                         mkl
bleach                    3.0.2                    py36_0
Bottleneck                1.2.1                     <pip>
ca-certificates           2018.03.07                    0
certifi                   2018.10.15               py36_0
cffi                      1.11.5           py36h74b6da3_1
chardet                   3.0.4                    py36_1
Click                     7.0                       <pip>
cloudpickle               0.6.1                    py36_0
colorama                  0.4.0                    py36_0
colour                    0.1.5                    py36_0
contextlib2               0.5.5                     <pip>
cryptography              2.3.1            py36h74b6da3_0
cvxpy                     1.0.10                    <pip>
cycler                    0.10.0           py36h009560c_0
cyordereddict             1.0.0                     <pip>
Cython                    0.29                      <pip>
cytoolz                   0.9.0.1          py36hfa6e2cd_1
dask-core                 1.0.0                    py36_0
decorator                 4.3.0                    py36_0
dill                      0.2.8.2                   <pip>
ecos                      2.0.7.post1               <pip>
empyrical                 0.5.0                     <pip>
entrypoints               0.2.3                    py36_2
fastcache                 1.0.2                     <pip>
freetype                  2.9.1                ha9979f8_1
future                    0.17.1                    <pip>
graphviz                  2.38                 hfd603c8_2
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py36_0
imageio                   2.4.1                    py36_0
intel-openmp              2019.1                      144
intervaltree              2.1.0                     <pip>
ipykernel                 5.1.0            py36h39e3cac_0
ipython                   7.1.1            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.4.2                    py36_0
jedi                      0.13.1                   py36_0
jinja2                    2.10                     py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0                    py36_7
jupyter_client            5.2.3                    py36_0
jupyter_console           6.0.0                    py36_0
jupyter_core              4.4.0                    py36_0
kiwisolver                1.0.1            py36h6538335_0
libpng                    1.6.35               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.0.9                h36446d0_2
Logbook                   1.4.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.2.5                     <pip>
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
Mako                      1.0.7                     <pip>
markupsafe                1.1.0            py36he774522_0
matplotlib                3.0.1            py36hc8f65d3_0
mistune                   0.8.4            py36he774522_0
mkl                       2018.0.3                      1
mkl_fft                   1.0.6            py36hdbbee80_0
mkl_random                1.0.1            py36h77b88f5_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                     <pip>
multiprocess              0.70.6.1                  <pip>
nb_conda                  2.2.1                    py36_0
nb_conda_kernels          2.2.0                    py36_0
nbconvert                 5.3.1                    py36_0
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  2.2                      py36_1
notebook                  5.7.2                    py36_0
numexpr                   2.6.8                     <pip>
numpy                     1.15.4           py36ha559c80_0
numpy-base                1.15.4           py36h8128ebf_0
olefile                   0.46                     py36_0
openssl                   1.0.2p               hfa6e2cd_0
osqp                      0.4.1                     <pip>
pandas                    0.22.0           py36h6538335_0
pandas-datareader         0.7.0                     <pip>
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py36_1
parso                     0.3.1                    py36_0
patsy                     0.5.1                     <pip>
pickleshare               0.7.5                    py36_0
pillow                    5.4.1            py36hdc69c19_0
pip                       18.1                     py36_0
plotly                    2.4.1                     <pip>
prometheus_client         0.4.2                    py36_0
prompt_toolkit            2.0.7                    py36_0
pycparser                 2.19                     py36_0
pygments                  2.2.0            py36hb010967_0
pyhamcrest                1.9.0                    py36_2
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.3.0                    py36_0
pyqt                      5.9.2            py36h6538335_2
pyreadline                2.1                       <pip>
pysocks                   1.6.8                    py36_0
python                    3.6.7                h33f27b4_1
python-dateutil           2.7.5                    py36_0
python-editor             1.0.3                     <pip>
python-graphviz           0.8.4                    py36_1
pytz                      2018.7                   py36_0
pywavelets                1.0.1            py36h8c2d366_0
pywinpty                  0.5.4                    py36_0
pyzmq                     17.1.2           py36hfa6e2cd_0
qt                        5.9.6            vc14h1e9a669_2
qtconsole                 4.4.2                    py36_0
requests                  2.20.1                   py36_0
requests-file             1.4.3                     <pip>
scikit-learn              0.20.0           py36heebcf9a_1
scipy                     1.1.0            py36h4f6bf74_1
scs                       2.0.2                     <pip>
seaborn                   0.9.0                     <pip>
send2trash                1.5.0                    py36_0
setuptools                40.6.2                   py36_0
sip                       4.19.8           py36h6538335_0
six                       1.11.0                   py36_1
sortedcontainers          2.0.5                     <pip>
SQLAlchemy                1.2.14                    <pip>
sqlite                    3.25.3               he774522_0
statsmodels               0.9.0                     <pip>
tables                    3.4.4                     <pip>
terminado                 0.8.1                    py36_1
testpath                  0.4.2                    py36_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                     <pip>
toolz                     0.9.0                    py36_0
tornado                   5.1.1            py36hfa6e2cd_0
tqdm                      4.28.1           py36h28b3542_0
trading-calendars         1.5.1                     <pip>
traitlets                 4.3.2            py36h096827d_0
urllib3                   1.23                     py36_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1                    py36_1
wheel                     0.32.3                   py36_0
widgetsnbextension        3.4.2                    py36_0
win_inet_pton             1.0.1                    py36_1
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4
wrapt                     1.10.11                   <pip>
zeromq                    4.2.5                he025d50_1
zipline                   1.3.0                     <pip>
zlib                      1.2.11               h8395fce_2
