### ISSUE TITLE
Unable to run zipline example with fresh install

### ISSUE THREAD

**Issue by Mandrewoid** [quantopian/zipline#2002]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)
* Python Version: `$ python --version ` 3.5.2
* Python Bitness: `$ 64
* How did you install Zipline: (Tried pip, install completed successfully, then I ran into this issue, so I cloned the git repo and did sudo python3 setup.py install. It reported as completed successfully)
* Python packages: `$ pip freeze` or `$ conda list` 
**Pip freeze of virtualenv**
alembic==0.9.6
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.27.2
decorator==4.1.2
empyrical==0.3.2
idna==2.6
intervaltree==2.1.0
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
multipledispatch==0.4.9
networkx==2.0
numexpr==2.6.4
numpy==1.13.3
pandas==0.18.1
pandas-datareader==0.5.0
patsy==0.4.1
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scipy==1.0.0
six==1.11.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.14
statsmodels==0.8.0
tables==3.4.2
toolz==0.8.2
urllib3==1.22
zipline==1.1.1

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? > I expected the buyapple example to work
* What happened instead? 

**EDIT**
It appears I missed part of the traceback when I pasted here the first time, the originating problem seems to be an SSL Error?:
[2017-10-30 15:20:04.461962] WARNING: Loader: Refusing to download new benchmark data because a download succeed
ed at 2017-10-30 14:47:39.200223+00:00.
[2017-10-30 15:20:04.462134] INFO: Loader: Cache at /home/crews/.zipline/data/treasury_curves.csv does not have 
data from 1990-01-02 00:00:00+00:00 to 2017-10-26 00:00:00+00:00.

[2017-10-30 15:20:04.462206] INFO: Loader: Downloading treasury data for 'SPY'.
[2017-10-30 15:20:04.703224] ERROR: Loader: failed to cache treasury data
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

/usr/local/lib/python3.5/dist-packages/zipline/data/loader.py in has_data_for_dates(series_or_df, first_date, last_date)
     85     last_date?
     86     """
---> 87     dts = series_or_df.index
     88     if not isinstance(dts, pd.DatetimeIndex):
     89         raise TypeError("Expected a DatetimeIndex, but got %s." % type(dts))

AttributeError: 'NoneType' object has no attribute 'index'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. install zipline
2. zipline ingest
3. try to run the buyapple example. Both the notebook and the commandline interface are giving the same error to me. 
...

## What steps have you taken to resolve this already?
From the notebook, I tried to fall back to shell, same error 
Tried running 'zipline ingest' again
Tried pulling zipline from git rather than pip
created a virtualenv, installed zipline from pip hoping it was my dirty pip env. 
updated system time via NTP in case it was an ssl error related to time
...

# Anything else?
I see a few other issues with the same SSLError related to the demise of Yahoo finance, but I judging from the comments, it appeared to me as though those problems had been fixed. 
I may try conda on linux as a workaround, but I'd rather not have to resort to that permanently
...

Sincerely,
Andrew(PS thanks for your time)
PPS, I have downloaded zipline onto my Windows machine with pip and it does seem to work. Any ideas on what in my environment could cause this sort of an error?

**Comment by freddiev4** [comment]
Hi @Mandrewoid can you try running the example with a shorter start date, such as `2017-08-01`?

There's a [PR](https://github.com/quantopian/zipline/pull/1972) open that addresses benchmark data errors.

**Comment by Mandrewoid** [comment]
Thanks for your input @freddiev4. Unfortunately no matter what dates I enter I get the same errors. It appears that whatever code is called after "INFO: Loader: Downloading treasury data for 'SPY'" fails to download that data.

**Comment by alexkojin** [comment]
@Mandrewoid try this solution https://github.com/quantopian/zipline/issues/1965#issuecomment-352715830 . It's works for me.

**Comment by freddiev4** [comment]
Merged that IEX PR above ^^ you (hopefully) should be able to run a backtest up to 5 years from the current date using zipline master

**Comment by freddiev4** [comment]
Closing this as this should be fixed in the latest release of zipline. Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update zipline -c quantopian
```

If you're still experiencing issues, please reopen this or open a new issue 🙂
