### ISSUE TITLE
Mac OSX 10.13 always get installing Zipline stuck 

### ISSUE THREAD

**Issue by burkaslarry** [quantopian/zipline#2016]
Dear Zipline Maintainers,

I  need help on installation
1 Always stuck on 

  Using cached zipline-1.1.1.tar.gz 

pip installed as 8.1.0

**Comment by burkaslarry** [comment]
<img width="1166" alt="screenshot 2017-11-16 22 47 54" src="https://user-images.githubusercontent.com/5709615/32897332-41dd2262-cb20-11e7-8b57-6bba5169bead.png">
<img width="1197" alt="screenshot 2017-11-16 22 48 00" src="https://user-images.githubusercontent.com/5709615/32897333-4214972e-cb20-11e7-9fa7-f50a31bf9d7f.png">

<img width="1158" alt="screenshot 2017-11-16 22 48 47" src="https://user-images.githubusercontent.com/5709615/32897364-581e8aac-cb20-11e7-807c-1b5091f814c5.png">



while   `pip install --verbose zipline`

**Comment by richafrank** [comment]
Hi @burkaslarry , I've definitely seen slowness while setuptools is easy_installing setup dependencies. Maybe it's progressing but slowly? 

Either way, want to try `pip install numpy cython` first, and then try `pip install zipline` after? Then it can avoid the easy_install.

**Comment by burkaslarry** [comment]
Usually how long does it take for setup.py to be finished ? I have tried using verbose, got repeating numpy  warnings 

```
Installing collected packages: zipline
  Running setup.py install for zipline ... /
```

**Comment by burkaslarry** [comment]
like this one. repeatedly 

```
_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    1 warning generated.
    In file included from zipline/assets/_assets.c:526:
    In file included from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:
    /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^

```

**Comment by burkaslarry** [comment]
The module is`     building 'zipline.assets.continuous_futures' extension`

**Comment by richafrank** [comment]
> Usually how long does it take for setup.py to be finished ?

I don't have any broad stats, but on my machine, it took about 2 minutes just now.

**Comment by burkaslarry** [comment]
Maybe we have to tell others installing by these steps : (Mac OSX 10.13.1) 

pip install -upgrade pip
python -m pip
brew update
ram get stable
rvm install 1.9.3
pip install numpy
pip install cython
pip install -U setuptools
pip install h5py
pip install zipline

**Comment by richafrank** [comment]
I buy that - probably a best practice to install numpy and cython before installing zipline. Opened a [PR](https://github.com/quantopian/zipline/pull/2020).

**Comment by oxbits** [comment]
pip install numpy cython

did the trick per @richafrank, thank you!

**Comment by jdricklefs** [comment]
Looks like this one has long since been resolved. Feel free to reopen if you're still having trouble!
