### ISSUE TITLE
zipline ingest of new quandl bundle runs out of memory on 4GB RAM instance

### ISSUE THREAD

**Issue by richafrank** [quantopian/zipline#2022]
See https://github.com/quantopian/zipline/pull/1990#issuecomment-345978820

**Comment by westurner** [comment]
Dask provides a similar API to Pandas and supports datasets larger than can fit into RAM.

From https://dask.pydata.org/en/latest/dataframe.html :

> A Dask DataFrame is a large parallel dataframe composed of many smaller Pandas dataframes, split along the index. These pandas dataframes may live on disk for larger-than-memory computing on a single machine, or on many different machines in a cluster.

- Docs: https://dask.pydata.org/en/latest/
- Src: https://github.com/dask/dask
- Pypi: https://pypi.org/project/dask/
- CondaPkg: ``dask``

**Comment by ernestoeperez88** [comment]
addressed by https://github.com/quantopian/zipline/pull/2053
