### ISSUE TITLE
Error in treasuries

### ISSUE THREAD

**Issue by Andre1208** [quantopian/zipline#2028]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 8.1)
* Python Version: `$ python 2,7`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: ( `conda`)
* Python packages:$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? I had issues with treasuries, with the following error message: ImportError: cannot import name treasuries

* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.from zipline.utils.factory import load_bars_from_yahoo
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by freddiev4** [comment]
Hi @Andre1208 when did you get this error? When running an algorithm? Or trying to use the import you wrote above? `from zipline.utils.factory import load_bars_from_yahoo` is also deprecated and I'm going to remove that soon so I would suggest not using that.

**Comment by Andre1208** [comment]
Hello @freddiev4 , thanks for the tip.

Actually, I got this error also when i tried to run the code below:

from zipline.examples import buyapple

The error is the same: cannot import name treasuries

**Comment by freddiev4** [comment]
Hmm.. I'm not getting that error when I run the same code.

![image](https://user-images.githubusercontent.com/8339018/33447894-8a339098-d5d2-11e7-8d86-34eb3f26246b.png)

![image](https://user-images.githubusercontent.com/8339018/33447915-987888c0-d5d2-11e7-8fd6-fe8076ba43c6.png)

This is in a Py35 environment though. I'll try Py27. Also, out of curiosity, why are you trying to import an example algorithm?

**Comment by freddiev4** [comment]
Just tried to import `from zipline.examples import buyapple` in a Py27 env and it did work.

Can you post the output given to you by running `conda info` @Andre1208?

**Comment by freddiev4** [comment]
Going to close this due to no follow-up. Feel free to re-open or open a new issue.
