### ISSUE TITLE
Default examples is not working

### ISSUE THREAD

**Issue by achempion** [quantopian/zipline#2037]
I've installed zipline within docker environment. I've copied an example from the beginner tutorial.

Here is an error:
```
bot_1  | [2017-12-01 23:03:53.523216] INFO: Loader: Cache at /root/.zipline/data/SPY_benchmark.csv does not have data from 1990-01-02 00:00:00+00:00 to 2017-11-29 00:00:00+00:00.
bot_1  |
bot_1  | [2017-12-01 23:03:53.523617] INFO: Loader: Downloading benchmark data for 'SPY' from 1989-12-29 00:00:00+00:00 to 2017-11-29 00:00:00+00:00
bot_1  | Traceback (most recent call last):

....

bot_1  |   File "/usr/local/lib/python3.5/site-packages/pandas/compat/__init__.py", line 72, in bytes_to_str
bot_1  |     return b.decode(encoding or 'utf-8')
bot_1  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 350: invalid continuation byte
```

I'm using python 3.5
You can reproduce the error just by running `docker-compose up` command.
https://github.com/achempion/zipline-example
Command I'm running is `$ zipline run -f dual_moving_average.py --start 2011-1-1 --end 2012-1-1 -o dma.pickle`

Thank you.

**Comment by freddiev4** [comment]
Hi @achempion there's a PR I've opened #2031 and also some duplicates of this opened already. I'm going to close this in favor of keeping #2036 open. Feel free to read over the discussion there 🙂
