### ISSUE TITLE
Monitor twitter feed 

### ISSUE THREAD

**Issue by gelinger777** [quantopian/zipline#2038]
Sorry for  such trivial question. We are very new to zipline. 
Is it possible in zipline standard environment to monitor twitter feed and in case a new tweet happens buy a specific stock? 
The idea is following 
1) Constant monitor  twitter feed via api of specific account, like once each 3min
2) In case a new tweet appears  purchase the given stock with market price 
3) Immediately put a limit order with purchase price + x%

**Comment by freddiev4** [comment]
Off the top of my head, a naive approach would be in your `handle_data()` function you could monitor the twitter feed every minute and just check if the user tweeted, then if they have recently tweeted, modify a variable attached to `context`, which you create in your `initialize()` function.

And you could then call `order()` with a `limit_price` param passed to it.

**Comment by freddiev4** [comment]
Going to close this due to inactivity. Feel free to re-open 🙂
