### ISSUE TITLE
NameError : name 'true' is not defined

### ISSUE THREAD

**Issue by HwijaeSon** [quantopian/zipline#2039]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Ubuntu 16.04
* Python Version: python 3.6.1 
* Python Bitness: 64bit
* How did you install Zipline: pip install zipline
* Python packages:
_license                  1.1                      py36_1
_nb_ext_conf              0.4.0                    py36_1
alabaster                 0.7.10                   py36_0
anaconda                  custom                   py36_0
anaconda-client           1.6.3                    py36_0
anaconda-navigator        1.6.2                    py36_0
anaconda-project          0.6.0                    py36_0
asn1crypto                0.22.0                   py36_0
astroid                   1.4.9                    py36_0
astropy                   1.3.2               np112py36_0
babel                     2.4.0                    py36_0
backports                 1.0                      py36_0
beautifulsoup4            4.6.0                    py36_0
bitarray                  0.8.1                    py36_0
blaze                     0.10.1                   py36_0
bleach                    1.5.0                    py36_0
bokeh                     0.12.5                   py36_1
boto                      2.48.0                    <pip>
boto                      2.46.1                   py36_0
bottleneck                1.2.1               np112py36_0
bz2file                   0.98                      <pip>
cairo                     1.14.8                        0
certifi                   2017.4.17                 <pip>
cffi                      1.10.0                   py36_0
chardet                   3.0.4                     <pip>
chardet                   3.0.3                    py36_0
click                     6.7                      py36_0
cloudpickle               0.2.2                    py36_0
clyent                    1.2.2                    py36_0
colorama                  0.3.9                    py36_0
conda                     4.3.30           py36h5d9f9f4_0
conda-env                 2.6.0                h36134e3_1
contextlib2               0.5.5                    py36_0
cryptography              1.8.1                    py36_0
cuda80                    1.0                           0    soumith
cudatoolkit               7.5                           0    anaconda
cudnn                     5.1                           0    anaconda
curl                      7.52.1                        0
cycler                    0.10.0                   py36_0
cython                    0.25.2                   py36_0
cytoolz                   0.8.2                    py36_0
dask                      0.14.3                   py36_1
datashape                 0.5.4                    py36_0
dbus                      1.10.10                       0
decorator                 4.0.11                   py36_0
distributed               1.16.3                   py36_0
docutils                  0.13.1                   py36_0
entrypoints               0.2.2                    py36_1
et_xmlfile                1.0.1                    py36_0
expat                     2.1.0                         0
fastcache                 1.0.2                    py36_1
flask                     0.12.2                   py36_0
flask-cors                3.0.2                    py36_0
fontconfig                2.12.1                        3
freetype                  2.5.5                         2
gensim                    2.2.0                     <pip>
get_terminal_size         1.0.0                    py36_0
gevent                    1.2.1                    py36_0
glib                      2.50.2                        1
greenlet                  0.4.12                   py36_0
gst-plugins-base          1.8.0                         0
gstreamer                 1.8.0                         0
h5py                      2.7.0               np112py36_0
harfbuzz                  0.9.39                        2
hdf5                      1.8.17                        1
heapdict                  1.0.0                    py36_1
html5lib                  0.999                    py36_0
icu                       54.1                          0
idna                      2.5                      py36_0
imagesize                 0.7.1                    py36_0
ipykernel                 4.6.1            py36hbf841aa_0
ipython                   5.3.0                    py36_0
ipython_genutils          0.2.0                    py36_0
ipywidgets                6.0.0                    py36_0
isort                     4.2.5                    py36_0
itsdangerous              0.24                     py36_0
jbig                      2.1                           0
jdcal                     1.3                      py36_0
jedi                      0.10.2                   py36_2
jinja2                    2.9.6                    py36_0
jpeg                      9b                            0
jpype1                    0.6.2               np112py36_0    conda-forge
jsonschema                2.6.0                    py36_0
jupyter                   1.0.0                    py36_3
jupyter_client            5.0.1                    py36_0
jupyter_console           5.1.0                    py36_0
jupyter_contrib_core      0.3.1                    py36_0    conda-forge
jupyter_contrib_nbextensions 0.2.8                    py36_1    conda-forge
jupyter_core              4.3.0                    py36_0
jupyter_highlight_selected_word 0.0.11                   py36_0    conda-forge
jupyter_latex_envs        1.3.8.2                  py36_1    conda-forge
jupyter_nbextensions_configurator 0.2.5                    py36_0    conda-forge
konlpy                    0.4.4                     <pip>
lazy-object-proxy         1.2.2                    py36_0
libffi                    3.2.1                         1
libgcc                    5.2.0                         0
libgfortran               3.0.0                         1
libiconv                  1.14                          0
libpng                    1.6.27                        0
libsodium                 1.0.10                        0
libtiff                   4.0.6                         3
libtool                   2.4.2                         0
libtorch-gpu              0.1.12                        0    anaconda
libxcb                    1.12                          1
libxml2                   2.9.4                         0
libxslt                   1.1.29                        0
llvmlite                  0.18.0                   py36_0
locket                    0.2.0                    py36_1
lxml                      3.7.3                    py36_0
markupsafe                0.23                     py36_2
matplotlib                2.0.2               np112py36_0
mistune                   0.7.4                    py36_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_1
msgpack-python            0.4.8                    py36_0
multipledispatch          0.4.9                    py36_0
navigator-updater         0.1.0                    py36_0
nb_anacondacloud          1.4.0                    py36_0
nb_conda                  2.2.1            py36h8118bb2_0
nb_conda_kernels          2.1.0                    py36_0    conda-forge
nbconvert                 5.1.1                    py36_0
nbformat                  4.3.0                    py36_0
nbpresent                 3.0.2            py36h5f95a39_1
nccl                      1.3.4                         0    anaconda
networkx                  1.11                     py36_0
nltk                      3.2.3                    py36_0
nose                      1.3.7                    py36_1
notebook                  5.0.0                    py36_0
numba                     0.33.0              np112py36_0
numexpr                   2.6.2               np112py36_0
numpy                     1.13.1                    <pip>
numpy                     1.12.1                   py36_0
numpydoc                  0.6.0                    py36_0
odo                       0.5.0                    py36_1
olefile                   0.44                     py36_0
openpyxl                  2.4.7                    py36_0
openssl                   1.0.2l                        0
packaging                 16.8                     py36_0
pandas                    0.20.1              np112py36_0
pandocfilters             1.4.1                    py36_0
pango                     1.40.3                        1
partd                     0.3.8                    py36_0
path.py                   10.3.1                   py36_0
pathlib2                  2.2.1                    py36_0
patsy                     0.4.1                    py36_0
pcre                      8.39                          1
pep8                      1.7.0                    py36_0
pexpect                   4.2.1                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.1.1                    py36_0
pip                       9.0.1                    py36_1
pixman                    0.34.0                        0
ply                       3.10                     py36_0
prompt_toolkit            1.0.14                   py36_0
psutil                    5.2.2                    py36_0
ptyprocess                0.5.1                    py36_0
py                        1.4.33                   py36_0
pycosat                   0.6.2                    py36_0
pycparser                 2.17                     py36_0
pycrypto                  2.6.1                    py36_6
pycurl                    7.43.0                   py36_2
pyflakes                  1.5.0                    py36_0
pygments                  2.2.0                    py36_0
pylint                    1.6.4                    py36_1
pyodbc                    4.0.16                   py36_0
pyopenssl                 17.0.0                   py36_0
pyparsing                 2.1.4                    py36_0
pyqt                      5.6.0                    py36_2
pytables                  3.3.0               np112py36_0
pytest                    3.0.7                    py36_0
python                    3.6.1                         2
python-dateutil           2.6.0                    py36_0
pytorch                   0.1.12              py361_2cu80  [cuda80]  soumith
pytz                      2017.2                   py36_0
pywavelets                0.5.2               np112py36_0
pyyaml                    3.12                     py36_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                         4
qtawesome                 0.4.4                    py36_0
qtconsole                 4.3.0                    py36_0
qtpy                      1.2.1                    py36_0
readline                  6.2                           2
requests                  2.14.2                   py36_0
requests                  2.18.1                    <pip>
rope                      0.9.4                    py36_1
ruamel_yaml               0.11.14                  py36_1
scikit-image              0.13.0              np112py36_0
scikit-learn              0.18.1              np112py36_1
scipy                     0.19.1                    <pip>
scipy                     0.19.0              np112py36_0
seaborn                   0.8                      py36_0
setuptools                27.2.0                   py36_0
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
smart-open                1.5.3                     <pip>
snowballstemmer           1.2.1                    py36_0
sortedcollections         0.5.3                    py36_0
sortedcontainers          1.5.7                    py36_0
sphinx                    1.5.6                    py36_0
spyder                    3.1.4                    py36_0
sqlalchemy                1.1.9                    py36_0
sqlite                    3.13.0                        0
statsmodels               0.8.0               np112py36_0
sympy                     1.0                      py36_0
tblib                     1.3.2                    py36_0
terminado                 0.6                      py36_0
testpath                  0.3                      py36_0
tk                        8.5.18                        0
toolz                     0.8.2                    py36_0
torchvision               0.1.8                    py36_2    soumith
tornado                   4.5.1                    py36_0
traitlets                 4.3.2                    py36_0
unicodecsv                0.14.1                   py36_0
Unidecode                 0.04.21                   <pip>
unixodbc                  2.3.4                         0
urllib3                   1.21.1                    <pip>
wcwidth                   0.1.7                    py36_0
werkzeug                  0.12.2                   py36_0
wheel                     0.29.0                   py36_0
widgetsnbextension        2.0.0                    py36_0
wrapt                     1.10.10                  py36_0
xgboost                   0.6a2                     <pip>
xlrd                      1.0.0                    py36_0
xlsxwriter                0.9.6                    py36_0
xlwt                      1.2.0                    py36_0
xz                        5.2.2                         1
yaml                      0.1.6                         0
zeromq                    4.1.5                         0
zict                      0.1.2                    py36_0
zlib                      1.2.8                         3
hwijae@amsquare:~$ source activate trading
(trading) hwijae@amsquare:~$ conda list
# packages in environment at /home/hwijae/anaconda3/envs/trading:
#
_nb_ext_conf              0.4.0                    py27_1
alembic                   0.7.7                    py27_0    Quantopian
anaconda-client           1.6.5            py27hc8169bf_0
asn1crypto                0.23.0           py27h7b0c810_0
backports                 1.0              py27h63c9359_1
backports.shutil_get_terminal_size 1.0.0            py27h5bc021e_2
backports_abc             0.5              py27h7b3c97b_0
bcolz                     0.12.1              np111py27_0    Quantopian
bleach                    2.1.1            py27h655ea9b_0
bottleneck                1.2.1            py27h21b16a3_0
bzip2                     1.0.6                h6d464ef_2
ca-certificates           2017.08.26           h1d4fec5_0
certifi                   2017.11.5        py27h71e7faf_0
cffi                      1.11.2           py27ha7929c6_0
chardet                   3.0.4            py27hfa10054_1
click                     6.7              py27h4225b90_0
clyent                    1.2.2            py27h7276e6c_1
configparser              3.5.0            py27h5117587_0
contextlib2               0.5.5            py27hbf4c468_0
cryptography              2.1.4            py27h6697b16_0
cyordereddict             0.2.2                    py27_0    Quantopian
cython                    0.27.3           py27hc56b35e_0
decorator                 4.1.2            py27h1544723_0
empyrical                 0.3.3                    py27_0    Quantopian
entrypoints               0.2.3            py27h502b47d_2
enum34                    1.1.6            py27h99a27e9_1
functools32               3.2.3.2          py27h4ead58f_1
gmp                       6.1.2                h6c8ec71_1
hdf5                      1.10.1               h9caa474_1
html5lib                  0.999999999      py27hdf15f34_0
idna                      2.6              py27h5722d68_1
intel-openmp              2018.0.0             hc7b2577_8
intervaltree              2.1.0                    py27_0    Quantopian
ipaddress                 1.0.18           py27h337fd85_0
ipykernel                 4.6.1            py27hc93e584_0
ipython                   5.4.1            py27h36c99b6_1
ipython_genutils          0.2.0            py27h89fb69b_0
ipywidgets                7.0.5            py27hfb35cc2_0
jinja2                    2.10             py27h4114e70_0
jsonschema                2.6.0            py27h7ed5aa4_0
jupyter_client            5.1.0            py27hbee1118_0
jupyter_core              4.4.0            py27h345911c_0
libedit                   3.1                  heed3624_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 7.2.0                h7cc24e2_2
libgfortran               3.0.0                         1
libgfortran-ng            7.2.0                h9f7466a_2
libsodium                 1.0.15               hf101ebd_0
libstdcxx-ng              7.2.0                h7a57d05_2
logbook                   0.12.5                   py27_0    Quantopian
lru-dict                  1.1.4                    py27_0    Quantopian
lzo                       2.10                 h49e0be7_2
mako                      1.0.7            py27h3d58d4b_0
markupsafe                1.0              py27h97b2822_1
mistune                   0.8.1            py27h1bd0165_0
mkl                       2017.0.4             h4c4d0af_0
multipledispatch          0.4.9            py27h9b5f95a_0
nb_anacondacloud          1.4.0                    py27_0
nb_conda                  2.2.1            py27hec22543_0
nb_conda_kernels          2.1.0                    py27_0
nbconvert                 5.3.1            py27he041f76_0
nbformat                  4.4.0            py27hed7f2b2_0
nbpresent                 3.0.2            py27hcce4ef4_1
ncurses                   6.0                  h9df7e31_2
networkx                  2.0              py27hfc23926_0
notebook                  5.2.2            py27h6748267_0
numexpr                   2.6.2               np111py27_0
numpy                     1.11.3                   py27_0
openssl                   1.0.2m               h26d622b_1
pandas                    0.18.1              np111py27_0
pandas-datareader         0.5.0                    py27_0
pandoc                    1.19.2.1             hea2e7c5_1
pandocfilters             1.4.2            py27h428e1e5_1
pathlib2                  2.3.0            py27h6e9d198_0
patsy                     0.4.1            py27hd1cf8c0_0
pexpect                   4.3.0            py27hdeba8d9_0
pickleshare               0.7.4            py27h09770e1_0
pip                       9.0.1            py27ha730c48_4
prompt_toolkit            1.0.15           py27h1b593e1_0
ptyprocess                0.5.2            py27h4ccb14c_0
pycparser                 2.18             py27hefa08c5_1
pygments                  2.2.0            py27h4a8b6f5_0
pyopenssl                 17.5.0           py27hcee3be0_0
pysocks                   1.6.7            py27he2db6d2_1
pytables                  3.4.2            py27h1f7bffc_2
python                    2.7.14              hdd48546_24
python-dateutil           2.6.1            py27h4ca5741_1
pytz                      2017.3           py27h001bace_0
pyyaml                    3.12             py27h2d70dd7_1
pyzmq                     16.0.3           py27hc579512_0
readline                  7.0                  ha6073c6_4
requests                  2.18.4           py27hc5b0589_1
requests-file             1.4.1                    py27_0
requests-ftp              0.3.1                    py27_0
scandir                   1.6              py27hf7388dc_0
scipy                     0.19.0              np111py27_0
setuptools                36.5.0           py27h68b189e_0
simplegeneric             0.8.1            py27h19e43cd_0
singledispatch            3.4.0.3          py27h9bcb476_0
six                       1.11.0           py27h5f960f1_1
sortedcontainers          1.4.4                    py27_0    Quantopian
sqlalchemy                1.1.13           py27hb0a01da_0
sqlite                    3.20.1               hb898158_2
ssl_match_hostname        3.5.0.1          py27h4ec10b9_2
statsmodels               0.8.0            py27hc87d62d_0
terminado                 0.6              py27h4be8df9_0
testpath                  0.3.1            py27hc38d2c4_0
tk                        8.6.7                hc745277_3
toolz                     0.8.2            py27hd3b1e7e_0
tornado                   4.5.2            py27h97b179f_0
traitlets                 4.3.2            py27hd6ce930_0
urllib3                   1.22             py27ha55213b_0
wcwidth                   0.1.7            py27h9e3e1ab_0
webencodings              0.5.1            py27hff10b21_1
wheel                     0.30.0           py27h2bc6bb2_1
widgetsnbextension        3.0.8            py27h618a941_0
yaml                      0.1.7                had09818_2
zeromq                    4.2.2                hbedb6e5_2
zipline                   1.1.1                     <pip>
zlib                      1.2.11               ha838bed_2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I'm trying to run a example code in the tutorial.

When I run  zipline run -f /home/user/Trading/first.ipynb --start 2011-1-1 --end 2014-1-1 -o buyapple_out.pickle on terminal, it produce some error like :

[2017-12-04 09:58:39.696850] WARNING: Loader: Refusing to download new benchmark data because a download succeeded at 2017-12-04 09:00:07.772494+00:00.
Traceback (most recent call last):
  File "/home/hwijae/anaconda3/envs/trading/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/zipline/__main__.py", line 97, in _
    return f(*args, **kwargs)
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/zipline/__main__.py", line 240, in run
    environ=os.environ,
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 175, in _run
    'script': algotext,
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/zipline/algorithm.py", line 372, in __init__
    exec_(code, self.namespace)
  File "/home/hwijae/anaconda3/envs/trading/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/home/hwijae/Trading/first.ipynb", line 11, in <module>
    "collapsed": true
NameError: name 'true' is not defined

What is this error? And how to resolve it?

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by richafrank** [comment]
Hi @HwijaeSon ,

Zipline expects that the file to run is a python file, i.e. contains only python code. It looks like you've given it the path to a Jupyter notebook (.ipynb), which includes json (with strings of python embedded) that tells Jupyter all the metadata about what cells you have in your notebook, including whether they're collapsed or not, whether each has output, the type of the input and output, etc. 

I believe the particular error you're seeing is because the json `true` literal is not a valid python literal.

You'll need to extract just the python from your notebook, and give that to zipline.

**Comment by HwijaeSon** [comment]
Thank you! It works!
