### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by mahesh1104** [quantopian/zipline#2042]
i am getting this error , how to slove it

elk@TestELK:~$ elastalert-create-index
Traceback (most recent call last):
  File "/home/elk/.local/bin/elastalert-create-index", line 11, in <module>
    sys.exit(main())
  File "/home/elk/.local/lib/python2.7/site-packages/elastalert/create_index.py", line 77, in main
    username = args.username if args.username else data.get('es_username')
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by richafrank** [comment]
Hi @mahesh1104 ,

That's a tough one. I don't see any zipline code mentioned in that traceback - looks only related to elastalert, so it's especially difficult for us to help.

I'm going to close this, as it doesn't seem like a zipline issue, but if you think there is something that we can help with, please let us know.
