### ISSUE TITLE
Pandas compatibility

### ISSUE THREAD

**Issue by qcho1010** [quantopian/zipline#2043]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

alembic==0.9.6
appdirs==1.4.3
appnope==0.1.0
asn1crypto==0.22.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0.post1
bcolz==0.12.1
beautifulsoup4==4.6.0
bkcharts==0.2
bleach==1.5.0
bokeh==0.12.7
Bottleneck==1.2.1
bs4==0.0.1
certifi==2017.11.5
cffi==1.10.0
chardet==3.0.4
click==6.7
configparser==3.5.0
contextlib2==0.5.5
cryptography==1.8.2
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
dash-core-components==0.3.5
dash-html-components==0.4.1
dash-renderer==0.6.0
dash.ly==0.15.2
decorator==4.1.2
Django==1.11
empyrical==0.3.3
entrypoints==0.2.3
enum34==1.1.6
fairml==0.1.1.5
Flask==0.12.1
Flask-Compress==1.4.0
Flask-SeaSurf==0.2.2
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.1.1
geojson==2.1.0
geopy==1.11.0
gmaps==0.6.0
gmplot==1.1.1
graphviz==0.6
h5py==2.7.0
html5lib==0.9999999
hyperopt==0.1
idna==2.6
image==1.5.5
imbalanced-learn==0.2.1
inflection==0.3.1
intervaltree==2.1.0
ipaddress==1.0.18
ipykernel==4.6.1
ipython==5.4.1
ipython-genutils==0.2.0
ipywidgets==7.0.0
itsdangerous==0.24
Jinja2==2.9.6
joblib==0.11
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-core==4.3.0
jupyterthemes==0.15.4
Keras==2.0.4
lesscpy==0.12.0
lightgbm==0.1
lime==0.1.1.20
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
Markdown==2.6.9
MarkupSafe==1.0
matplotlib==2.0.0
minepy==1.2.0
mistune==0.7.4
ml-insights==0.0.15
mock==2.0.0
more-itertools==3.1.0
multipledispatch==0.4.9
MySQL-python==1.2.3rc1
nbconvert==5.2.1
nbformat==4.4.0
ndg-httpsclient==0.4.2
networkx==1.11
nose==1.3.7
notebook==5.0.0
numexpr==2.6.4
numpy==1.13.3
olefile==0.44
packaging==16.8
pandas==0.18.1
pandas-datareader==0.5.0
pandocfilters==1.4.2
pathlib2==2.3.0
patsy==0.4.1
pbr==3.1.1
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.1.0
pip-autoremove==0.9.0
plotly==2.0.8
ply==3.10
prompt-toolkit==1.0.15
protobuf==3.4.0
ptyprocess==0.5.2
py-earth==0+unknown
PyAlgoTrade==0.18
pyasn1==0.2.3
pycparser==2.17
pydotplus==2.0.2
pyfolio==0.8.0
Pygments==2.2.0
pymc3==3.2
pymongo==3.4.0
pync==1.6.1
pyOpenSSL==17.0.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.3.0
Quandl==3.1.0
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scandir==1.5
scikit-learn==0.18.2
scikit-optimize==0.3
scipy==1.0.0
seaborn==0.7.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sortedcontainers==1.5.7
sphinx-gallery==0.1.10
SQLAlchemy==1.1.15
statsmodels==0.8.0
subprocess32==3.2.7
tables==3.4.2
tensorflow==1.4.0
tensorflow-tensorboard==0.4.0rc2
terminado==0.6
testpath==0.3.1
Theano==0.9.0
toolz==0.8.2
tornado==4.5.2
tqdm==4.19.4
traitlets==4.3.2
treeinterpreter==0.2.1
urllib3==1.22
virtualenv==15.1.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.1
widgetsnbextension==3.0.2
xgbfir==0.2
xgboost==0.6a2
xlrd==1.0.0
XlsxWriter==0.9.6
zipline==1.1.1

# Description of Issue

As I was following the tutorial, at the following jupyter notebook line
`!zipline run -f ../../zipline/examples/buyapple.py --start 2003-1-1 --end 2014-1-1 -o buyapple_out.pickle
`
I get the following error

> 
> [2017-12-05 21:49:09.407988] INFO: Loader: Cache at /home/mimh/.zipline/data/SPY_benchmark.csv does not have data from 1990-01-02 00:00:00+00:00 to 2017-12-01 00:00:00+00:00.
> 
> [2017-12-05 21:49:09.408246] INFO: Loader: Downloading benchmark data for 'SPY' from 1989-12-29 00:00:00+00:00 to 2017-12-01 00:00:00+00:00
> Traceback (most recent call last):
>   File "/usr/local/bin/zipline", line 11, in <module>
>     load_entry_point('zipline==1.1.1', 'console_scripts', 'zipline')()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/zipline/__main__.py", line 97, in _
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/zipline/__main__.py", line 240, in run
>     environ=os.environ,
>   File "/usr/local/lib/python2.7/dist-packages/zipline/utils/run_algo.py", line 132, in _run
>     env = TradingEnvironment(asset_db_path=connstr, environ=environ)
>   File "/usr/local/lib/python2.7/dist-packages/zipline/finance/trading.py", line 99, in __init__
>     self.bm_symbol,
>   File "/usr/local/lib/python2.7/dist-packages/zipline/data/loader.py", line 166, in load_market_data
>     environ,
>   File "/usr/local/lib/python2.7/dist-packages/zipline/data/loader.py", line 230, in ensure_benchmark_data
>     last_date,
>   File "/usr/local/lib/python2.7/dist-packages/zipline/data/benchmarks.py", line 53, in get_benchmark_returns
>     data = data['Close']
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 1997, in __getitem__
>     return self._getitem_column(key)
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2004, in _getitem_column
>     return self._get_item_cache(key)
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 1350, in _get_item_cache
>     values = self._data.get(item)
>   File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3290, in get
>     loc = self.items.get_loc(item)
>   File "/usr/local/lib/python2.7/dist-packages/pandas/indexes/base.py", line 1947, in get_loc
>     return self._engine.get_loc(self._maybe_cast_indexer(key))
>   File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
>   File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
>   File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
>   File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
> KeyError: 'Close'
>

**Comment by renning22** [comment]
+1, my system is Windows 10 x64.

**Comment by nicolasmauhe** [comment]
I have the same issue. Xubuntu 17.04

**Comment by Jerryzhuht** [comment]
Instead I got:
RemoteDataError: Unable to read URL: http://www.google.com/finance/historical?output=csv&enddate=Dec+13%2C+2017&q=SPY&startdate=Dec+29%2C+1989
Mac OS

**Comment by imkoukou** [comment]
When I reinstalled pandas recently to ver0.21.1, I got error even when I execute "zipline run --help"......
Win10+Python 3.6+Pandase 0.21.1

error message:
!zipline run --help
c:\anaconda3\lib\site-packages\zipline\utils\calendars\exchange_calendar_ice.py:10: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import Timestamp
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\zipline.exe\__main__.py", line 5, in <module>
  File "c:\anaconda3\lib\site-packages\zipline\__init__.py", line 21, in <module>
    from . import finance
  File "c:\anaconda3\lib\site-packages\zipline\finance\__init__.py", line 16, in <module>
    from . import execution, trading
  File "c:\anaconda3\lib\site-packages\zipline\finance\trading.py", line 19, in <module>
    from pandas.tslib import normalize_date
ImportError: cannot import name 'normalize_date'

**Comment by renning22** [comment]
FYI: I made github(master) work by installing it in anaconda2/ubuntu 16.04.

**Comment by frosk1** [comment]
some progress going on here?

**Comment by richafrank** [comment]
Sadly, I'm not aware of any. I just corrected the typo in the title.

**Comment by imkoukou** [comment]
I use Python 3.6+Pandase 0.21.1. and encountered  "ImportError: cannot import name 'normalize_date'" as written above.
After enforced to add the following lines in "pandas installing path//pandas/tslib.py" manually, someway I can run zipline without error.
If somebody use the same version, maybe you can try like this.

normalize_date = tslib.normalize_date
iNaT = tslib.iNaT

**Comment by nateGeorge** [comment]
My pandas/tslib.py looked like:

```python
# flake8: noqa

import warnings
warnings.warn("The pandas.tslib module is deprecated and will be "
              "removed in a future version.", FutureWarning, stacklevel=2)
from pandas._libs.tslib import (Timestamp, Timedelta,
                               NaT, NaTType, OutOfBoundsDatetime)
```

So I just added the missing functions to it:

```python
# flake8: noqa

import warnings
warnings.warn("The pandas.tslib module is deprecated and will be "
              "removed in a future version.", FutureWarning, stacklevel=2)
from pandas._libs.tslib import (Timestamp, Timedelta,
                               NaT, NaTType, OutOfBoundsDatetime, normalize_date, iNaT)
```

Then I had to make all these changes as well:

cd /usr/local/lib/python3.5/dist-packages/zipline/finance/performance

edit tracker.py

change the line
`from pandas.tseries.tools import normalize_date`
to
`from pandas._libs.tslib import normalize_date`

cd /usr/local/lib/python3.5/dist-packages/zipline/finance/risk

edit cumulative.py

change the line
`from pandas.tseries.tools import normalize_date`
to
`from pandas._libs.tslib import normalize_date`

cd /usr/local/lib/python3.5/dist-packages/zipline/data

edit benchmarks.py

change

```
    data = pd_reader.DataReader(
        symbol,
        'google',
        first_date,
        last_date
    )
```

to

```
    data = pd_reader.DataReader(
        symbol,
        'yahoo',
        first_date,
        last_date
    )
```

**Comment by groutgauss** [comment]
@nateGeorge when I make the changes you suggest above I get the following:

`Traceback (most recent call last):
  File "/Users/dcalderon/PycharmProjects/Zipline_Equities/Stock_Backtest.py", line 17, in <module>
    from zipline.algorithm import TradingAlgorithm
  File "/Users/dcalderon/anaconda3/lib/python3.6/site-packages/zipline/__init__.py", line 20, in <module>
    from . import data
  File "/Users/dcalderon/anaconda3/lib/python3.6/site-packages/zipline/data/__init__.py", line 1, in <module>
    from . import loader
  File "/Users/dcalderon/anaconda3/lib/python3.6/site-packages/zipline/data/loader.py", line 25, in <module>
    from .benchmarks import get_benchmark_returns
  File "/Users/dcalderon/anaconda3/lib/python3.6/site-packages/zipline/data/benchmarks.py", line 48
    ‘google’,
           ^
SyntaxError: invalid character in identifier`

**Comment by richafrank** [comment]
Closing - See https://github.com/quantopian/zipline/pull/2194 and https://github.com/quantopian/zipline/issues/2243
