### ISSUE TITLE
Fix conda installs on travis

### ISSUE THREAD

**Issue by richafrank** [quantopian/zipline#2054]
and re-enable master branch merges requiring travis passing

**Comment by richafrank** [comment]
See https://travis-ci.org/quantopian/zipline/builds/316621178 for breakage info

**Comment by ssanderson** [comment]
This tentatively appears to have been fixed by https://github.com/quantopian/zipline/commit/b5eaec6bf91b52f6ed2c860a48b20eaf28e97f97

**Comment by richafrank** [comment]
Nice @ssanderson ! Updated branch protection. Closing for now.
