### ISSUE TITLE
Add csvdir usage to bundle docs

### ISSUE THREAD

**Issue by freddiev4** [quantopian/zipline#2060]
Saw some people asking in both the Zipline Google Group and in Gitter about how to use csv data in a bundle. Considering we have the `csvdir` bundle, we should probably add some quick tutorial on how to use that in the [Data Bundles](http://www.zipline.io/bundles.html) docs.

Paste from the Gitter chat: 

![image](https://user-images.githubusercontent.com/8339018/34285293-bef37c00-e6a6-11e7-97de-ce7ba7d830b3.png)

- https://github.com/quantopian/zipline/issues/174
- https://github.com/quantopian/zipline/issues/713

**Comment by ayxemma** [comment]
should the data be in OHLCV format or in OHLCV+dividend+split

**Comment by freddiev4** [comment]
@ayxemma it should also have dividends + splits (I included it in #2073)

**Comment by bboczeng** [comment]
QQ:
what should the "date" col look like in the CSV file, say, we have MINUTE frequency data?
should it still be Y-m-d, or should it be minutes?

**Comment by imkoukou** [comment]
To bboczeng:
Here is the first two lines of my 1 minute data . It works well.
In fact, make sure the volume column is >0 . In some code, the volume value is
checked, sometimes that may stop your order. (If it is 0 or empty, just fill it with some value).

time,open,high,low,close,volume
2013-01-01 17:00:00,86.68,86.682,86.68,86.682,100

**Comment by freddiev4** [comment]
Closing this as this is in the latest release of zipline. You can see the release notes [here](http://www.zipline.io/releases.html#release-1-2-0) Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update zipline -c quantopian
```

If there are any problems, please open a new issue 🙂
