### ISSUE TITLE
ImportError: cannot import name treasuries

### ISSUE THREAD

**Issue by racoon971** [quantopian/zipline#2061]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version 10 )
* Python Version: `$ python --2.7`
* How did you install Zipline: (`pip`,`)
* Python packages: `$ pip freeze` 

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I have installed Zipline on a python 2.7 environement (I am on windows 10)

But I have the error:

    cannot import name treasuries

When I run :

    import zipline

Please let me know if I am missing something.

Sincerely,
`$ whoami`

**Comment by racoon971** [comment]
I have created a virtual environment and check that treasuries.py is in the library dir but it does not change anything.

**Comment by racoon971** [comment]
I had to change my path nin sys.path

**Comment by ayxemma** [comment]
hi, i have the same problem, how do you set your sys.path

**Comment by hrushi397** [comment]
hi, what did you change in sys.path?
