### ISSUE TITLE
RemoteDataError

### ISSUE THREAD

**Issue by ramesh8v** [quantopian/zipline#2070]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
Windows10
* Python Version: `$ python --version`
Python 3.5.4 :: Anaconda, Inc.
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
C:\ProgramData\Anaconda3\envs\py3.5\python35.zip
C:\ProgramData\Anaconda3\envs\py3.5\DLLs
C:\ProgramData\Anaconda3\envs\py3.5\lib
C:\ProgramData\Anaconda3\envs\py3.5
C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages
C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages\Babel-2.5.0-py3.5.egg
C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages\win32
C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages\win32\lib
C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages\Pythonwin
C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages\IPython\extensions
C:\Users\Ramesh\.ipython
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
pip
* Python packages: `$ pip freeze` or `$ conda list`
alabaster                 0.7.10           py35h3a808de_0
alembic                   0.9.6                     <pip>
anaconda                  5.0.0            py35h91a80f2_0
anaconda-client           1.6.5            py35h18499f7_0
anaconda-navigator        1.6.8            py35h84e1151_0
anaconda-project          0.8.0            py35h54b767f_0
asn1crypto                0.22.0           py35he3634b9_1
astroid                   1.5.3            py35h82ecf54_0
astropy                   2.0.2            py35h6e1a5eb_4
babel                     2.5.0            py35hcd66c26_0
backports                 1.0              py35he88aa47_1
backports.shutil_get_terminal_size 1.0.0            py35h9d89c8b_2
bcolz                     0.12.1                    <pip>
beautifulsoup4            4.6.0            py35h61fcdcc_1
bitarray                  0.8.1            py35ha601307_0
bkcharts                  0.2              py35h4704c85_0
blaze                     0.11.3           py35hae12140_0
bleach                    2.0.0            py35he2a2600_0
bokeh                     0.12.7           py35h06303ae_1
boto                      2.48.0           py35ha0bef00_1
bottleneck                1.2.1            py35h8a3671c_0
bzip2                     1.0.6            vc14hdec8e7a_1  [vc14]
ca-certificates           2017.08.26           h94faf87_0
cachecontrol              0.12.3           py35h3f82863_0
certifi                   2017.7.27.1      py35hbab57cd_0
cffi                      1.10.0           py35h4132a7f_1
chardet                   3.0.4            py35h177e1b7_1
click                     6.7              py35h10df73f_0
cloudpickle               0.4.0            py35h754485a_0
clyent                    1.2.2            py35h3cd9751_1
colorama                  0.3.9            py35h32a752f_0
comtypes                  1.1.2            py35hfae9076_0
console_shortcut          0.1.1                haa4cab3_2
contextlib2               0.5.5            py35h0a97e54_0
cryptography              2.0.3            py35h67a4558_1
curl                      7.55.1           vc14hdaba4a4_3  [vc14]
cycler                    0.10.0           py35hcc71164_0
cyordereddict             1.0.0                     <pip>
cython                    0.26.1           py35h91d0724_0
cytoolz                   0.8.2            py35h6a98e29_0
dask                      0.15.2           py35hea826ea_0
dask-core                 0.15.2           py35he1b8ae7_0
datashape                 0.5.4            py35ha38994c_0
decorator                 4.1.2            py35hc7d1f2e_0
distlib                   0.2.5            py35h12c42d7_0
distributed               1.18.3           py35h2fdf97d_0
docutils                  0.14             py35h8ccb97f_0
empyrical                 0.3.3                     <pip>
entrypoints               0.2.3            py35hb91ced9_2
et_xmlfile                1.0.1            py35h2c13def_0
fastcache                 1.0.2            py35h8710e77_0
filelock                  2.0.12           py35h4e16406_0
flask                     0.12.2           py35he898f9a_0
flask-cors                3.0.3            py35h5700fb0_0
freetype                  2.8              vc14h17c9bdf_0  [vc14]
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2            py35hb3d9581_0
glob2                     0.5              py35hb00d93b_1
greenlet                  0.4.12           py35h0b77e5a_0
h5py                      2.7.0            py35h9881aa0_1
hdf5                      1.10.1           vc14hb361328_0  [vc14]
heapdict                  1.0.0            py35h3d1311d_0
html5lib                  0.999999999      py35h79d4e7f_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2             vc14hc45fdbb_0  [vc14]
idna                      2.6              py35h8dcb9ae_1
imageio                   2.2.0            py35hcd4b9a4_0
imagesize                 0.7.1            py35h7f87e83_0
inflection                0.3.1                     <pip>
intel-openmp              2018.0.0             hcd89f80_7
intervaltree              2.1.0                     <pip>
ipykernel                 4.6.1            py35hab2028a_0
ipython                   6.1.0            py35haf90630_1
ipython_genutils          0.2.0            py35ha709e79_0
ipywidgets                7.0.0            py35h9c6a661_0
isort                     4.2.15           py35h0bf7b49_0
itsdangerous              0.24             py35h99d45d4_1
jdcal                     1.3              py35h49a1460_0
jedi                      0.10.2           py35h3350e2d_0
jinja2                    2.9.6            py35hab4de37_1
jpeg                      9b               vc14h4d7706e_1  [vc14]
jsonschema                2.6.0            py35h27d56d3_0
jupyter                   1.0.0            py35hce9caf1_2
jupyter_client            5.1.0            py35hcddec19_0
jupyter_console           5.2.0            py35hf76c22e_1
jupyter_core              4.3.0            py35h93453ca_0
jupyterlab                0.27.0           py35hf0f7bbb_2
jupyterlab_launcher       0.4.0            py35h7c94a28_0
lazy-object-proxy         1.3.1            py35he996729_0
libiconv                  1.15             vc14h29686d3_5  [vc14]
libpng                    1.6.32           vc14hce43e6c_2  [vc14]
libssh2                   1.8.0            vc14hcf584a9_2  [vc14]
libtiff                   4.0.8           vc14h04e2a1e_10  [vc14]
libxml2                   2.9.4            vc14h8fd0f11_5  [vc14]
libxslt                   1.1.29           vc14hf85b8d4_5  [vc14]
llvmlite                  0.20.0                   py35_0
locket                    0.2.0            py35h0dfcdd0_1
lockfile                  0.12.2           py35h667c6d9_0
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      3.8.0            py35h9002f32_0
Mako                      1.0.7                     <pip>
markupsafe                1.0              py35hc253e08_1
matplotlib                2.0.2            py35h9bd10b2_1
mccabe                    0.6.1            py35hcf31250_1
menuinst                  1.4.8            py35h7787ee1_0
mistune                   0.7.4            py35h21381af_0
mkl                       2018.0.0             h36b65af_4
mkl-service               1.1.2            py35h051acba_4
more-itertools            4.0.1                     <pip>
mpmath                    0.19             py35hd324aab_2
msgpack-python            0.4.8            py35hdef45cb_0
multipledispatch          0.4.9            py35hfb38682_0
navigator-updater         0.1.0            py35h1d043e2_0
nbconvert                 5.3.1            py35h98d6c46_0
nbformat                  4.4.0            py35h908c9d9_0
ndg-httpsclient           0.4.3                     <pip>
networkx                  1.11             py35h097edc8_0
nltk                      3.2.4            py35h592734c_0
nose                      1.3.7            py35h0e9586c_2
notebook                  5.0.0            py35hebc375d_1
numba                     0.35.0             np113py35_10
numexpr                   2.6.2            py35h7bc0bb2_1
numpy                     1.13.1           py35h9801081_2
numpydoc                  0.7.0            py35h72ac4f2_0
odo                       0.5.1            py35hc850252_0
olefile                   0.44             py35h7ba86d0_0
openpyxl                  2.4.8            py35h6c05adf_1
openssl                   1.0.2l           vc14hcac20b0_2  [vc14]
packaging                 16.8             py35h5fb721f_1
pandas                    0.20.3           py35he2ce742_2
pandas                    0.18.1                    <pip>
pandas-datareader         0.5.0                     <pip>
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py35h978f723_1
partd                     0.3.8            py35h894d1e4_0
path.py                   10.3.1           py35h111cd61_0
pathlib2                  2.3.0            py35h4f1e8f6_0
patsy                     0.4.1            py35h01e4a18_0
pep8                      1.7.0            py35h15aeeed_0
pickleshare               0.7.4            py35h2f9f535_0
pillow                    4.2.1            py35hd7da350_0
pip                       9.0.1            py35h69293b5_3
pkginfo                   1.4.1            py35hb922f74_1
ply                       3.10             py35hb60f152_0
progress                  1.3              py35ha84af61_0
prompt_toolkit            1.0.15           py35h89c7cb4_0
psutil                    5.2.2            py35hb623197_0
py                        1.4.34           py35hf344529_1
pyasn1                    0.4.2                     <pip>
pycodestyle               2.3.1            py35h35694a3_0
pycosat                   0.6.2            py35h396ce21_1
pycparser                 2.18             py35h15a15da_1
pycrypto                  2.6.1            py35h8890bb5_1
pycurl                    7.43.0           py35hd6f0fee_3
pyflakes                  1.5.0            py35hf25bbea_1
pygments                  2.2.0            py35h24c0941_0
pylint                    1.7.2            py35h573a187_0
pyodbc                    4.0.17           py35he49b0b4_0
pyopenssl                 17.2.0           py35hea705d1_0
pyparsing                 2.2.0            py35hcabcaab_1
pyqt                      5.6.0            py35hd46907b_5
pysocks                   1.6.7            py35hb30ac0d_1
pytables                  3.4.2            py35h90de74f_1
pytest                    3.2.1            py35h656b196_1
python                    3.5.4               hd3c4935_11
python-dateutil           2.6.1            py35h6b299a3_1
python-editor             1.0.3                     <pip>
pytz                      2017.2           py35h3d6be01_1
pywavelets                0.5.2            py35h7c47ace_0
pywin32                   221              py35h14ddfd5_0
pyyaml                    3.12             py35h4bf9689_1
pyzmq                     16.0.2           py35hc237a46_2
qt                        5.6.2           vc14h6f8c307_12  [vc14]
qtawesome                 0.4.4            py35h639d0ff_0
qtconsole                 4.3.1            py35hc47b0dd_0
qtpy                      1.3.1            py35h4918c39_0
Quandl                    3.3.0                     <pip>
requests                  2.18.4           py35h54a615f_1
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
rope                      0.10.5           py35h54a0bee_0
ruamel_yaml               0.11.14          py35h7ef29f8_2
scikit-image              0.13.0           py35h49207bb_1
scikit-learn              0.19.0           py35h3bd3ce1_2
scipy                     0.19.1           py35h1e2829e_3
seaborn                   0.8.0            py35hda3c85b_0
setuptools                36.5.0           py35h21a22e4_0
simplegeneric             0.8.1            py35h6406082_0
singledispatch            3.4.0.3          py35h33f66b4_0
sip                       4.18.1           py35h01cbaa7_2
six                       1.10.0           py35h06cf344_1
snowballstemmer           1.2.1            py35h4c55bfa_0
sortedcollections         0.5.3            py35h4a7ff62_0
sortedcontainers          1.5.7            py35h9857911_0
sphinx                    1.6.3            py35heeac824_0
sphinxcontrib             1.0              py35h45f5ca3_1
sphinxcontrib-websupport  1.0.1            py35ha3690eb_1
spyder                    3.2.3            py35h0c9d003_0
sqlalchemy                1.1.13           py35h5463dee_0
sqlite                    3.20.1           vc14h7ce8c62_1  [vc14]
statsmodels               0.8.0            py35hfa6034c_0
sympy                     1.1.1            py35ha5375ed_0
tblib                     1.3.2            py35hd2cf7e1_0
testpath                  0.3.1            py35h06cf69e_0
tk                        8.6.7            vc14hb68737d_1  [vc14]
toolz                     0.8.2            py35h7afdc4e_0
tornado                   4.5.2            py35h03246f3_0
traitlets                 4.3.2            py35h09b975b_0
typing                    3.6.2            py35h37628ea_0
unicodecsv                0.14.1           py35h0d88516_0
urllib3                   1.22             py35h8cc84eb_0
vc                        14                   h2379b0c_1
vs2015_runtime            14.0.25123           hd4c4e62_1
wcwidth                   0.1.7            py35h6e80d8a_0
webencodings              0.5.1            py35h5d527fb_1
werkzeug                  0.12.2           py35hc854123_0
wheel                     0.29.0           py35hdbcb6e6_1
widgetsnbextension        3.0.2            py35ha8638b2_1
win_inet_pton             1.0.1            py35hbef1270_1
win_unicode_console       0.5              py35h56988b5_0
wincertstore              0.2              py35hfebbdb8_0
wrapt                     1.10.11          py35h54666f7_0
xlrd                      1.1.0            py35h22b952b_1
xlsxwriter                0.9.8            py35hd46c63e_0
xlwings                   0.11.4           py35he637782_0
xlwt                      1.3.0            py35hd04410a_0
yaml                      0.1.7            vc14hb31d195_1  [vc14]
zict                      0.1.2            py35h42e54d5_0
zipline                   1.1.1                     <pip>
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]
Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
Tried to run given basic buyapple example in Jupyter Notebook
* What happened instead?
RemoteDataError: Unable to read URL: http://www.google.com/finance/historical?q=SPY&enddate=Dec+28%2C+2017&startdate=Dec+29%2C+1989&output=csv
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. zipline ingest -b quantopian-quandl (this step successfully downloaded the bundle)
2.  %load_ext zipline
3. (ran this in the next cell)
%%zipline --start 2000-1-1 --end 2014-1-1
from zipline.api import symbol, order, record

def initialize(context):
    pass

def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data[symbol('AAPL')].price)
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$Ramesh`

**Comment by freddiev4** [comment]
Hi @ramesh8v I'm gonna mark this as a duplicate and also refer you to #2072 and #1965 🙂

**Comment by ramesh8v** [comment]
Hi @freddiev4 I installed from Github repo, when I ran `zipline ingest -b quandl` command, I got `zipline ingest -b quandl` error.

**Comment by freddiev4** [comment]
I believe you're seeing that error because you need a Quandl API key, which
you can get by making a free account. Then you can run
QUANDL_API_KEY=yourkey zipline ingest -b quandl

Or you can try zipline ingest -b quantopian-quandl

**Comment by freddiev4** [comment]
FWIW there's a comment in the Zipline bundle docs about this.

**Comment by ramesh8v** [comment]
Thanks, unfortunately `zipline ingest -b quantopian-quandl` produced the same error. 
When I tried `QUANDL_API_KEY=myquandlkey zipline ingest -b quandl`, I got '```
QUANDL_API_KEY' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by freddiev4** [comment]
Sorry, I was answering this from my email, and didn't see the `get_pytables_version` error you mentioned. 

Hmm...considering you're using conda, can you try `conda install -c quantopian/label/ci zipline`? That will install the latest zipline master branch as a conda package.

I'm hoping that cutting a release for Zipline soon-ish will alleviate these issues.

**Comment by ramesh8v** [comment]
Thank you, @freddiev4 . I installed by `conda install -c quantopian/label/ci zipline`, when I tried `zipline ingest -b quantopian-quandl`, I got this error:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py3.5\Scripts\zipline-script.py", line 11, in <module>
    load_entry_point('zipline==1.1.1+133.gaa32252f', 'console_scripts', 'zipline')()
  File "C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages\pkg_resources\__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages\pkg_resources\__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
    return self.resolve()
  File "C:\ProgramData\Anaconda3\envs\py3.5\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\programdata\anaconda3\envs\py3.5\lib\site-packages\zipline\__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm
  File "c:\programdata\anaconda3\envs\py3.5\lib\site-packages\zipline\utils\run_algo.py", line 18, in <module>
    from zipline.data.bundles.core import load
  File "c:\programdata\anaconda3\envs\py3.5\lib\site-packages\zipline\data\bundles\__init__.py", line 2, in <module>
    from . import quandl  # noqa
  File "c:\programdata\anaconda3\envs\py3.5\lib\site-packages\zipline\data\bundles\quandl.py", line 18, in <module>
    from . import core as bundles
  File "c:\programdata\anaconda3\envs\py3.5\lib\site-packages\zipline\data\bundles\core.py", line 23, in <module>
    from zipline.assets.asset_db_migrations import downgrade
  File "c:\programdata\anaconda3\envs\py3.5\lib\site-packages\zipline\assets\asset_db_migrations.py", line 1, in <module>
    from alembic.migration import MigrationContext
  File "c:\programdata\anaconda3\envs\py3.5\lib\site-packages\alembic\__init__.py", line 8, in <module>
    from . import op  # noqa
  File "c:\programdata\anaconda3\envs\py3.5\lib\site-packages\alembic\op.py", line 6, in <module>
    util.create_module_class_proxy(Operations, globals(), locals())
AttributeError: module 'alembic.util' has no attribute 'create_module_class_proxy'
```

**Comment by freddiev4** [comment]
Closing this as you should be able to do this in the latest release of zipline. You can see the release notes [here](http://www.zipline.io/releases.html#release-1-2-0) Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update zipline -c quantopian
```

If there are any problems, please open a new issue 🙂

**Comment by roywoodhead2** [comment]
Hi freddiev,
    I have lost 2 days trying to get zipline to run in a jupyter notebook.

    I used the following code (commented out some other attempts):
!conda search --full-name zipline -c quantopian
#!conda install --yes -c Quantopian zipline
#!conda install --yes -c https://conda.anaconda.org/Quantopian/label/ci -c Quantopian zipline
!conda install --yes -c https://conda.anaconda.org/Quantopian/label/ci -c Quantopian zipline==1.2.0
!conda list  # list to check zipline is in site-packages

    I see zipline in the list - packages in environment at /home/nbuser/anaconda3_420:
zipline                   1.2.0               np111py35_0    Quantopian

However, when I use %load_ext zipline I get the error:
"module 'alembic.util' has no attribute 'create_module_class_proxy'"

    I've also tried:
!pip install zipline
    and
import sys
!{sys.executable} -m pip install zipline

Is there a way to get zipline up and running in a Azure / Jupyter notebook?

Any advice will be greatly appreciated
