### ISSUE TITLE
Zipline install errors - specifications in conflict

### ISSUE THREAD

**Issue by iisai1821** [quantopian/zipline#2075]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: Python 2.7.13 :: Anaconda 4.4.0 (64-bit)
* How did you install Zipline:  `conda` (I also tried pip)
* Python packages: conda install -c Quantopian zipline

I'm getting error messages similar to those mentioned in other issues when trying to install zipline.  Based on some other suggestions, I've already run conda --update all.

My error after running conda install -c Quantopian zipline:

> Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - astropy
>   - zipline -> numpy=1.9 -> mkl==11.3.3
> Use "conda info <package>" to see the dependencies for each package.

Thanks for your help!

**Comment by freddiev4** [comment]
Hi @iisai1821 can you post the output of `conda info` and also try installing zipline in it's own `conda env`?

**Comment by iisai1821** [comment]
Thanks for your response.  Here's conda info: 

> conda info
> 
>      active environment : None
>        user config file : C:\Users\E\.condarc
>  populated config files : C:\Users\E\.condarc
>           conda version : 4.4.6
>     conda-build version : not installed
>          python version : 2.7.13.final.0
>        base environment : C:\Users\E\Anaconda2  (writable)
>            channel URLs : https://repo.continuum.io/pkgs/main/win-64
>                           https://repo.continuum.io/pkgs/main/noarch
>                           https://repo.continuum.io/pkgs/free/win-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/win-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/win-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-64
>                           https://repo.continuum.io/pkgs/msys2/noarch
>           package cache : C:\Users\E\Anaconda2\pkgs
>                           C:\Users\E\AppData\Local\conda\conda\pkgs
>        envs directories : C:\Users\E\Anaconda2\envs
>                           C:\Users\E\AppData\Local\conda\conda\envs
>                           C:\Users\E\.conda\envs
>                platform : win-64
>              user-agent : conda/4.4.6 requests/2.14.2 CPython/2.7.13 Windows/10 Windows/10.0.16299
>           administrator : False
>              netrc file : None
>            offline mo

de : False

Trying with a new environment, and with the latest master branch give me missing packages errors: 

>conda create -n quanto zipline
>Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - zipline
> 
> Current channels:
> 
>   - https://repo.continuum.io/pkgs/main/win-64
>   - https://repo.continuum.io/pkgs/main/noarch
>   - https://repo.continuum.io/pkgs/free/win-64
>   - https://repo.continuum.io/pkgs/free/noarch
>   - https://repo.continuum.io/pkgs/r/win-64
>   - https://repo.continuum.io/pkgs/r/noarch
>   - https://repo.continuum.io/pkgs/pro/win-64
>   - https://repo.continuum.io/pkgs/pro/noarch
>   - https://repo.continuum.io/pkgs/msys2/win-64
>   - https://repo.continuum.io/pkgs/msys2/noarch
> 
>

**Comment by freddiev4** [comment]
@iisai1821 you'll want to create a new `conda env` using

```
conda create -n <env_name>
```

And then install latest zipline master using `conda install -c quantopian/label/ci zipline`. The reason it failed is because you tried to create a `conda env` with just `zipline` without specifying that it comes from the quantopian channel.

**Comment by iisai1821** [comment]
Thanks for your help.  There are even more missing packages when I do that, though: 

> C:\Users\E> conda create -n quanto
> Solving environment: done
> C:\Users\E>activate quanto
> 
> (quanto) C:\Users\E>conda install -c quantopian/label/ci zipline
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - zipline
>   - lru-dict[version='>=1.1.4']
>   - zipline
>   - cyordereddict[version='>=0.2.2']
>   - zipline
>   - bcolz[version='>=0.12.1,<1']
>   - zipline
>   - intervaltree[version='>=2.1.0']
>   - zipline
>   - logbook[version='>=0.12.5']
>   - zipline
>   - empyrical[version='>=0.2.2']
>   - zipline
>   - cachetools[version='>=1.1.5']
> 
> Current channels:
> 
>   - https://conda.anaconda.org/quantopian/label/ci/win-64
>   - https://conda.anaconda.org/quantopian/label/ci/noarch
>   - https://repo.continuum.io/pkgs/main/win-64
>   - https://repo.continuum.io/pkgs/main/noarch
>   - https://repo.continuum.io/pkgs/free/win-64
>   - https://repo.continuum.io/pkgs/free/noarch
>   - https://repo.continuum.io/pkgs/r/win-64
>   - https://repo.continuum.io/pkgs/r/noarch
>   - https://repo.continuum.io/pkgs/pro/win-64
>   - https://repo.continuum.io/pkgs/pro/noarch
>   - https://repo.continuum.io/pkgs/msys2/win-64
>   - https://repo.continuum.io/pkgs/msys2/noarch

**Comment by iisai1821** [comment]
Hmm, I think I made progress.  I updated to conda 4.4.7, then tried 'conda install -c Quantopian zipline' again.  It installed a massive list of new packages and then zipline successfully.  I'm not sure everything is working though, since the very first line of code from the [beginner's tutorial](http://www.zipline.io/beginner-tutorial.html#basics) produces a no-such-module error, but maybe that's a separate issue?  'from zipline.api import order' worked.


> (quanto) C:\Users\E>conda install -c Quantopian zipline
> Solving environment: done
> 
> ## Package Plan ##
> 
>   environment location: C:\Users\E\Anaconda2\envs\quanto
> 
>   added / updated specs:
>     - zipline
> 
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     click-6.7                  |   py27hb6defca_0         103 KB
>     vc-9                       |       h7299396_1           3 KB
>     python-dateutil-2.6.1      |   py27hbdcc174_1         237 KB
>     cyordereddict-0.2.2        |           py27_0          36 KB  Quantopian
>     numexpr-2.6.4              |   py27h20dc147_0         133 KB
>     toolz-0.9.0                |           py27_0          91 KB
>     lzo-2.10                   |       h0bb7fe3_2         150 KB
>     requests-file-1.4.1        |           py27_0           6 KB
>     chardet-3.0.4              |   py27h56c3b73_1         192 KB
>     logbook-0.12.5             |           py27_0         114 KB  Quantopian
>     markupsafe-1.0             |   py27h9d4480d_1          25 KB
>     decorator-4.1.2            |   py27h383e199_0          15 KB
>     six-1.11.0                 |   py27ha5e1701_1          21 KB
>     sortedcontainers-1.4.4     |           py27_0          61 KB  Quantopian
>     intervaltree-2.1.0         |           py27_0          45 KB  Quantopian
>     zlib-1.2.11                |       hbc2faf4_2         117 KB
>     lru-dict-1.1.4             |           py27_0          10 KB  Quantopian
>     scipy-1.0.0                |   py27h7cd1477_0        13.1 MB
>     alembic-0.7.7              |           py27_0         197 KB  Quantopian
>     cython-0.27.3              |   py27h566c365_0         2.4 MB
>     mako-1.0.7                 |   py27h650e302_0         132 KB
>     patsy-0.5.0                |           py27_0         307 KB
>     contextlib2-0.5.5          |   py27h42efda5_0          15 KB
>     sqlalchemy-1.2.0           |   py27h0c8e037_0         1.5 MB
>     pyopenssl-17.5.0           |   py27h59156d7_0          77 KB
>     enum34-1.1.6               |   py27h2aa175b_1          57 KB
>     idna-2.6                   |   py27h1ea29d3_1         122 KB
>     urllib3-1.22               |   py27hb9f5a07_0         153 KB
>     hdf5-1.10.1                |       h08c2580_1        17.6 MB
>     empyrical-0.3.2            |           py27_0          53 KB  Quantopian
>     python-2.7.14              |      h8c3f1cb_23        20.6 MB
>     cryptography-2.1.4         |   py27h0628b04_0         502 KB
>     bcolz-0.12.1               |      np111py27_0         324 KB  Quantopian
>     pytables-3.4.2             |   py27h583b7c0_2         3.3 MB
>     win_inet_pton-1.0.1        |   py27hf41312a_1           5 KB
>     cffi-1.11.2                |   py27hba5d71c_0         206 KB
>     networkx-2.0               |   py27h42253ca_0         1.7 MB
>     requests-ftp-0.3.1         |           py27_0          13 KB
>     vs2008_runtime-9.00.30729.1|       hfaea7d5_1        1017 KB
>     pip-9.0.1                  |   py27hdaa76b4_4         2.4 MB
>     pandas-0.18.1              |      np111py27_0         7.0 MB
>     zipline-1.1.1              |      np111py27_0         1.3 MB  Quantopian
>     statsmodels-0.8.0          |   py27hc77c1fc_0         6.2 MB
>     mkl-2018.0.1               |       h2108138_4       155.2 MB
>     asn1crypto-0.24.0          |           py27_0         154 KB
>     intel-openmp-2018.0.0      |       hd92c6cd_8         1.4 MB
>     wheel-0.30.0               |   py27ha643586_1          84 KB
>     icc_rt-2017.0.4            |       h97af966_0         8.0 MB
>     bottleneck-1.2.1           |   py27hde90680_0         104 KB
>     pycparser-2.18             |   py27hb43d16c_1         167 KB
>     requests-2.18.4            |   py27h3159eba_1          91 KB
>     bzip2-1.0.6                |       h69b88ca_2         111 KB
>     pandas-datareader-0.5.0    |           py27_0         100 KB
>     ipaddress-1.0.19           |           py27_0          33 KB
>     numpy-1.11.3               |   py27hab9e983_3         3.2 MB
>     pytz-2017.3                |   py27hca431c1_0         209 KB
>     pysocks-1.6.7              |   py27h59bdd1e_1          22 KB
>     multipledispatch-0.4.9     |   py27h8ebb51e_0          15 KB
>     ------------------------------------------------------------
>                                            Total:       250.3 MB
> 
> The following NEW packages will be INSTALLED:
> 
>     alembic:           0.7.7-py27_0             Quantopian
>     asn1crypto:        0.24.0-py27_0
>     bcolz:             0.12.1-np111py27_0       Quantopian
>     bottleneck:        1.2.1-py27hde90680_0
>     bzip2:             1.0.6-h69b88ca_2
>     ca-certificates:   2017.08.26-h94faf87_0
>     certifi:           2017.11.5-py27h03b45e1_0
>     cffi:              1.11.2-py27hba5d71c_0
>     chardet:           3.0.4-py27h56c3b73_1
>     click:             6.7-py27hb6defca_0
>     contextlib2:       0.5.5-py27h42efda5_0
>     cryptography:      2.1.4-py27h0628b04_0
>     cyordereddict:     0.2.2-py27_0             Quantopian
>     cython:            0.27.3-py27h566c365_0
>     decorator:         4.1.2-py27h383e199_0
>     empyrical:         0.3.2-py27_0             Quantopian
>     enum34:            1.1.6-py27h2aa175b_1
>     hdf5:              1.10.1-h08c2580_1
>     icc_rt:            2017.0.4-h97af966_0
>     idna:              2.6-py27h1ea29d3_1
>     intel-openmp:      2018.0.0-hd92c6cd_8
>     intervaltree:      2.1.0-py27_0             Quantopian
>     ipaddress:         1.0.19-py27_0
>     logbook:           0.12.5-py27_0            Quantopian
>     lru-dict:          1.1.4-py27_0             Quantopian
>     lzo:               2.10-h0bb7fe3_2
>     mako:              1.0.7-py27h650e302_0
>     markupsafe:        1.0-py27h9d4480d_1
>     mkl:               2018.0.1-h2108138_4
>     multipledispatch:  0.4.9-py27h8ebb51e_0
>     networkx:          2.0-py27h42253ca_0
>     numexpr:           2.6.4-py27h20dc147_0
>     numpy:             1.11.3-py27hab9e983_3
>     openssl:           1.0.2n-hc64555f_0
>     pandas:            0.18.1-np111py27_0
>     pandas-datareader: 0.5.0-py27_0
>     patsy:             0.5.0-py27_0
>     pip:               9.0.1-py27hdaa76b4_4
>     pycparser:         2.18-py27hb43d16c_1
>     pyopenssl:         17.5.0-py27h59156d7_0
>     pysocks:           1.6.7-py27h59bdd1e_1
>     pytables:          3.4.2-py27h583b7c0_2
>     python:            2.7.14-h8c3f1cb_23
>     python-dateutil:   2.6.1-py27hbdcc174_1
>     pytz:              2017.3-py27hca431c1_0
>     requests:          2.18.4-py27h3159eba_1
>     requests-file:     1.4.1-py27_0
>     requests-ftp:      0.3.1-py27_0
>     scipy:             1.0.0-py27h7cd1477_0
>     setuptools:        38.4.0-py27_0
>     six:               1.11.0-py27ha5e1701_1
>     sortedcontainers:  1.4.4-py27_0             Quantopian
>     sqlalchemy:        1.2.0-py27h0c8e037_0
>     statsmodels:       0.8.0-py27hc77c1fc_0
>     toolz:             0.9.0-py27_0
>     urllib3:           1.22-py27hb9f5a07_0
>     vc:                9-h7299396_1
>     vs2008_runtime:    9.00.30729.1-hfaea7d5_1
>     wheel:             0.30.0-py27ha643586_1
>     win_inet_pton:     1.0.1-py27hf41312a_1
>     wincertstore:      0.2-py27hf04cefb_0
>     zipline:           1.1.1-np111py27_0        Quantopian
>     zlib:              1.2.11-hbc2faf4_2
> 
> Proceed ([y]/n)? y
> 
> 
> Downloading and Extracting Packages
> click 6.7: ############################################################ | 100%
> vc 9: ################################################################# | 100%
> python-dateutil 2.6.1: ################################################ | 100%
> cyordereddict 0.2.2: ################################################## | 100%
> numexpr 2.6.4: ######################################################## | 100%
> toolz 0.9.0: ########################################################## | 100%
> lzo 2.10: ############################################################# | 100%
> requests-file 1.4.1: ################################################## | 100%
> chardet 3.0.4: ######################################################## | 100%
> logbook 0.12.5: ####################################################### | 100%
> markupsafe 1.0: ####################################################### | 100%
> decorator 4.1.2: ###################################################### | 100%
> six 1.11.0: ########################################################### | 100%
> sortedcontainers 1.4.4: ############################################### | 100%
> intervaltree 2.1.0: ################################################### | 100%
> zlib 1.2.11: ########################################################## | 100%
> lru-dict 1.1.4: ####################################################### | 100%
> scipy 1.0.0: ########################################################## | 100%
> alembic 0.7.7: ######################################################## | 100%
> cython 0.27.3: ######################################################## | 100%
> mako 1.0.7: ########################################################### | 100%
> patsy 0.5.0: ########################################################## | 100%
> contextlib2 0.5.5: #################################################### | 100%
> sqlalchemy 1.2.0: ##################################################### | 100%
> pyopenssl 17.5.0: ##################################################### | 100%
> enum34 1.1.6: ######################################################### | 100%
> idna 2.6: ############################################################# | 100%
> urllib3 1.22: ######################################################### | 100%
> hdf5 1.10.1: ########################################################## | 100%
> empyrical 0.3.2: ###################################################### | 100%
> python 2.7.14: ######################################################## | 100%
> cryptography 2.1.4: ################################################### | 100%
> bcolz 0.12.1: ######################################################### | 100%
> pytables 3.4.2: ####################################################### | 100%
> win_inet_pton 1.0.1: ################################################## | 100%
> cffi 1.11.2: ########################################################## | 100%
> networkx 2.0: ######################################################### | 100%
> requests-ftp 0.3.1: ################################################### | 100%
> vs2008_runtime 9.00.30729.1: ########################################## | 100%
> pip 9.0.1: ############################################################ | 100%
> pandas 0.18.1: ######################################################## | 100%
> zipline 1.1.1: ######################################################## | 100%
> statsmodels 0.8.0: #################################################### | 100%
> mkl 2018.0.1: ######################################################### | 100%
> asn1crypto 0.24.0: #################################################### | 100%
> intel-openmp 2018.0.0: ################################################ | 100%
> wheel 0.30.0: ######################################################### | 100%
> icc_rt 2017.0.4: ###################################################### | 100%
> bottleneck 1.2.1: ##################################################### | 100%
> pycparser 2.18: ####################################################### | 100%
> requests 2.18.4: ###################################################### | 100%
> bzip2 1.0.6: ########################################################## | 100%
> pandas-datareader 0.5.0: ############################################## | 100%
> ipaddress 1.0.19: ##################################################### | 100%
> numpy 1.11.3: ######################################################### | 100%
> pytz 2017.3: ########################################################## | 100%
> pysocks 1.6.7: ######################################################## | 100%
> multipledispatch 0.4.9: ############################################### | 100%
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> 
> (quanto) C:\Users\E>python
> Python 2.7.14 |Anaconda, Inc.| (default, Nov  8 2017, 13:40:45) [MSC v.1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from zipline.examples import buyapple
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\Elisabeth\Anaconda2\envs\quanto\lib\site-packages\zipline\examples\__init__.py", line 17, in <module>
>     mod = import_module('.' + modname, package=__name__)
>   File "C:\Users\E\Anaconda2\envs\quanto\lib\importlib\__init__.py", line 37, in import_module
>     __import__(name)
>   File "C:\Users\E\Anaconda2\envs\quanto\lib\site-packages\zipline\examples\dual_ema_talib.py", line 29, in <module>
>     from talib import EMA
> ImportError: No module named talib
> >>> from zipline.api import order
> >>>

**Comment by freddiev4** [comment]
We also recently did a release of zipline. You can see the release notes [here](http://www.zipline.io/releases.html#release-1-2-0) Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update -c quantopian/label/main zipline
```

If there are any problems, please open a new issue 🙂
