### ISSUE TITLE
Fix test_flip_algo

### ISSUE THREAD

**Issue by freddiev4** [quantopian/zipline#2079]
Currently `test_flip_algo` fails in `test_algorithm.py` but we skip that test. Would be cool to fix this at some point as it's been skipped for quite a while. Added a `Help Wanted` here in case anyone wants to give this a shot and contribute 🙂

**Comment by richafrank** [comment]
Removed in https://github.com/quantopian/zipline/commit/10cea4c3abefca3990cbae85294fb3bda57e661b#diff-ed39c40cbbb5cf7fd3d34d39ac5da6a2L3236
