### ISSUE TITLE
Cannot conda install

### ISSUE THREAD

**Issue by raffam** [quantopian/zipline#2083]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)

> Linux raffaele-GL753VD 4.14.13-041413-generic #201801101001 SMP Wed Jan 10 10:02:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Python Version: `$ python --version`

> Python 3.6.3 :: Anaconda, Inc.

* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`

> 64

* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
I tried with `conda`, but it doesn't work. So zipline is not installed.

* Python packages: `$ pip freeze` or `$ conda list`
Output of `pip freeze` in virtual environment is empty.
Output of `conda list` follows:
> \# packages in environment at /home/raffaele/anaconda3:
> \#
> _ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0  
> alabaster                 0.7.10           py36h306e16b_0  
> alembic                   0.9.7                     <pip>
> anaconda                  custom           py36hbbc8b67_0  
> anaconda-client           1.6.5            py36h19c0dcd_0  
> anaconda-navigator        1.6.9            py36h11ddaaa_0  
> anaconda-project          0.8.0            py36h29abdf5_0  
> asn1crypto                0.22.0           py36h265ca7c_1  
> astroid                   1.5.3            py36hbdb9df2_0  
> astropy                   2.0.2            py36ha51211e_4  
> babel                     2.5.0            py36h7d14adf_0  
> backports                 1.0              py36hfa02d7e_1  
> backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
> bcolz                     0.12.1                    <pip>
> beautifulsoup4            4.6.0            py36h49b8c8c_1  
> bitarray                  0.8.1            py36h5834eb8_0  
> bkcharts                  0.2              py36h735825a_0  
> blaze                     0.11.3           py36h4e06776_0  
> bleach                    2.0.0            py36h688b259_0  
> bleach                    1.5.0                     <pip>
> bokeh                     0.12.10          py36hbb0e44a_0  
> boto                      2.48.0           py36h6e4cd66_1  
> bottleneck                1.2.1            py36haac1ea0_0  
> bzip2                     1.0.6                h0376d23_1  
> ca-certificates           2017.08.26           h1d4fec5_0  
> cairo                     1.14.10              haa5651f_5  
> certifi                   2017.7.27.1      py36h8b7b77e_0  
> cffi                      1.10.0           py36had8d393_1  
> chardet                   3.0.4            py36h0f667ec_1  
> click                     6.7              py36h5253387_0  
> cloudpickle               0.4.0            py36h30f8c20_0  
> clyent                    1.2.2            py36h7e57e65_1  
> colorama                  0.3.9            py36h489cec4_0  
> conda                     4.4.7                    py36_0  
> conda-build               3.0.27           py36h940a66d_0  
> conda-env                 2.6.0                h36134e3_1  
> conda-verify              2.0.0            py36h98955d8_0  
> contextlib2               0.5.5            py36h6c84a62_0  
> cryptography              2.0.3            py36ha225213_1  
> curl                      7.55.1               hcb0b314_2  
> cycler                    0.10.0           py36h93f1223_0  
> cyordereddict             1.0.0                     <pip>
> cython                    0.26.1           py36h21c49d0_0  
> cytoolz                   0.8.2            py36h708bfd4_0  
> dask                      0.15.3           py36hdc2c8aa_0  
> dask-core                 0.15.3           py36h10e6167_0  
> datashape                 0.5.4            py36h3ad6b5c_0  
> dbus                      1.10.22              h3b5a359_0  
> decorator                 4.1.2            py36hd076ac8_0  
> distributed               1.19.1           py36h25f3894_0  
> docutils                  0.14             py36hb0f60f5_0  
> empyrical                 0.3.3                     <pip>
> entrypoints               0.2.3            py36h1aec115_2  
> enum34                    1.1.6                     <pip>
> et_xmlfile                1.0.1            py36hd6bccc3_0  
> expat                     2.2.4                hc00ebd1_1  
> fastcache                 1.0.2            py36h5b0c431_0  
> filelock                  2.0.12           py36hacfa1f5_0  
> flask                     0.12.2           py36hb24657c_0  
> flask-cors                3.0.3            py36h2d857d3_0  
> fontconfig                2.12.4               h88586e7_1  
> freetype                  2.8                  h52ed37b_0  
> get_terminal_size         1.0.0                haa9412d_0  
> gevent                    1.2.2            py36h2fe25dc_0  
> glib                      2.53.6               hc861d11_1  
> glob2                     0.5              py36h2c1b292_1  
> gmp                       6.1.2                hb3b607b_0  
> gmpy2                     2.0.8            py36h55090d7_1  
> graphite2                 1.3.10               hc526e54_0  
> greenlet                  0.4.12           py36h2d503a6_0  
> gst-plugins-base          1.12.2               he3457e5_0  
> gstreamer                 1.12.2               h4f93127_0  
> h5py                      2.7.0            py36he81ebca_1  
> harfbuzz                  1.5.0                h2545bd6_0  
> hdf5                      1.10.1               hb0523eb_0  
> heapdict                  1.0.0            py36h79797d7_0  
> html5lib                  0.9999999                 <pip>
> html5lib                  0.999999999      py36h2cfc398_0  
> icu                       58.2                 h211956c_0  
> idna                      2.6              py36h82fb2a8_1  
> imageio                   2.2.0            py36he555465_0  
> imagesize                 0.7.1            py36h52d8127_0  
> intel-openmp              2018.0.0             h15fc484_7  
> intervaltree              2.1.0                     <pip>
> ipykernel                 4.6.1            py36hbf841aa_0  
> ipython                   6.1.0            py36hc72a948_1  
> ipython_genutils          0.2.0            py36hb52b0d5_0  
> ipywidgets                7.0.0            py36h7b55c3a_0  
> isort                     4.2.15           py36had401c0_0  
> itsdangerous              0.24             py36h93cc618_1  
> jbig                      2.1                  hdba287a_0  
> jdcal                     1.3              py36h4c697fb_0  
> jedi                      0.10.2           py36h552def0_0  
> jinja2                    2.9.6            py36h489bce4_1  
> jpeg                      9b                   habf39ab_1  
> jsonschema                2.6.0            py36h006f8b5_0  
> jupyter                   1.0.0            py36h9896ce5_0  
> jupyter_client            5.1.0            py36h614e9ea_0  
> jupyter_console           5.2.0            py36he59e554_1  
> jupyter_core              4.3.0            py36h357a921_0  
> jupyterlab                0.27.0           py36h86377d0_2  
> jupyterlab_launcher       0.4.0            py36h4d8058d_0  
> lazy-object-proxy         1.3.1            py36h10fcdad_0  
> libedit                   3.1                  heed3624_0  
> libffi                    3.2.1                h4deb6c0_3  
> libgcc-ng                 7.2.0                h7cc24e2_2  
> libgfortran-ng            7.2.0                h9f7466a_2  
> libpng                    1.6.32               hda9c8bc_2  
> libsodium                 1.0.13               h31c71d8_2  
> libssh2                   1.8.0                h8c220ad_2  
> libstdcxx-ng              7.2.0                h7a57d05_2  
> libtiff                   4.0.8                h90200ff_9  
> libtool                   2.4.6                hd50d1a6_0  
> libxcb                    1.12                 h84ff03f_3  
> libxml2                   2.9.4                h6b072ca_5  
> libxslt                   1.1.29               hcf9102b_5  
> llvmlite                  0.20.0                   py36_0  
> locket                    0.2.0            py36h787c0ad_1  
> Logbook                   1.1.0                     <pip>
> lru-dict                  1.1.6                     <pip>
> lxml                      4.1.0            py36h5b66e50_0  
> lzo                       2.10                 h1bfc0ba_1  
> Mako                      1.0.7                     <pip>
> Markdown                  2.6.11                    <pip>
> markupsafe                1.0              py36hd9260cd_1  
> matplotlib                2.1.0            py36hba5de38_0  
> mccabe                    0.6.1            py36h5ad9710_1  
> mistune                   0.7.4            py36hbab8784_0  
> mkl                       2018.0.0             hb491cac_4  
> mkl-service               1.1.2            py36h17a0993_4  
> mpc                       1.0.3                hf803216_4  
> mpfr                      3.1.5                h12ff648_1  
> mpmath                    0.19             py36h8cc018b_2  
> msgpack-python            0.4.8            py36hec4c5d1_0  
> multipledispatch          0.4.9            py36h41da3fb_0  
> navigator-updater         0.1.0            py36h14770f7_0  
> nbconvert                 5.3.1            py36hb41ffb7_0  
> nbformat                  4.4.0            py36h31c9010_0  
> ncurses                   6.0                  h06874d7_1  
> networkx                  2.0              py36h7e96fb8_0  
> nltk                      3.2.4            py36h1a0979f_0  
> nose                      1.3.7            py36hcdf7029_2  
> notebook                  5.0.0            py36h0b20546_2  
> numba                     0.35.0             np113py36_10  
> numexpr                   2.6.2            py36hdd3393f_1  
> numpy                     1.14.0                    <pip>
> numpy                     1.13.3           py36ha12f23b_0  
> numpydoc                  0.7.0            py36h18f165f_0  
> odo                       0.5.1            py36h90ed295_0  
> olefile                   0.44             py36h79f9f78_0  
> openpyxl                  2.4.8            py36h41dd2a8_1  
> openssl                   1.0.2l               h077ae2c_5  
> packaging                 16.8             py36ha668100_1  
> pandas                    0.22.0                    <pip>
> pandas                    0.20.3           py36h842e28d_2  
> pandas-datareader         0.5.0                     <pip>
> pandoc                    1.19.2.1             hea2e7c5_1  
> pandocfilters             1.4.2            py36ha6701b7_1  
> pango                     1.40.11              h8191d47_0  
> partd                     0.3.8            py36h36fd896_0  
> patchelf                  0.9                  hf79760b_2  
> path.py                   10.3.1           py36he0c6f6d_0  
> pathlib2                  2.3.0            py36h49efa8e_0  
> patsy                     0.4.1            py36ha3be15e_0  
> pcre                      8.41                 hc71a17e_0  
> pep8                      1.7.0            py36h26ade29_0  
> pexpect                   4.2.1            py36h3b9d41b_0  
> pickleshare               0.7.4            py36h63277f8_0  
> pillow                    4.2.1            py36h9119f52_0  
> pip                       9.0.1            py36h8ec8b28_3  
> pixman                    0.34.0               h83dc358_2  
> pkginfo                   1.4.1            py36h215d178_1  
> ply                       3.10             py36hed35086_0  
> prompt_toolkit            1.0.15           py36h17d85b1_0  
> protobuf                  3.5.1                     <pip>
> psutil                    5.4.0            py36h84c53db_0  
> ptyprocess                0.5.2            py36h69acd42_0  
> py                        1.4.34           py36h0712aa3_1  
> pycodestyle               2.3.1            py36hf609f19_0  
> pycosat                   0.6.3            py36h0a5515d_0  
> pycparser                 2.18             py36hf9f622e_1  
> pycrypto                  2.6.1            py36h6998063_1  
> pycurl                    7.43.0           py36h5e72054_3  
> pyflakes                  1.6.0            py36h7bd6a15_0  
> pygments                  2.2.0            py36h0d3125c_0  
> pylint                    1.7.4            py36hb9d4533_0  
> pyodbc                    4.0.17           py36h999153c_0  
> pyopenssl                 17.2.0           py36h5cc804b_0  
> pyparsing                 2.2.0            py36hee85983_1  
> pyqt                      5.6.0            py36h0386399_5  
> pysocks                   1.6.7            py36hd97a5b1_1  
> pytables                  3.4.2            py36h3b5282a_2  
> pytest                    3.2.1            py36h11ad3bb_1  
> python                    3.6.3                hc9025b9_1  
> python-dateutil           2.6.1            py36h88d3b88_1  
> python-editor             1.0.3                     <pip>
> pytz                      2017.2           py36hc2ccc2a_1  
> pytz                      2017.3                    <pip>
> pywavelets                0.5.2            py36he602eb0_0  
> pyyaml                    3.12             py36hafb9ca4_1  
> pyzmq                     16.0.2           py36h3b0cf96_2  
> qt                        5.6.2               h974d657_12  
> qtawesome                 0.4.4            py36h609ed8c_0  
> qtconsole                 4.3.1            py36h8f73b5b_0  
> qtpy                      1.3.1            py36h3691cc8_0  
> readline                  7.0                  hac23ff0_3  
> requests                  2.18.4           py36he2e5f8d_1  
> requests-file             1.4.3                     <pip>
> requests-ftp              0.3.1                     <pip>
> rope                      0.10.5           py36h1f8c17e_0  
> ruamel_yaml               0.11.14          py36ha2fb22d_2  
> scikit-image              0.13.0           py36had3c07a_1  
> scikit-learn              0.19.1           py36h7aa7ec6_0  
> scipy                     0.19.1           py36h9976243_3  
> seaborn                   0.8.0            py36h197244f_0  
> setuptools                36.5.0           py36he42e2e1_0  
> simplegeneric             0.8.1            py36h2cb9092_0  
> singledispatch            3.4.0.3          py36h7a266c3_0  
> sip                       4.18.1           py36h51ed4ed_2  
> six                       1.11.0           py36h372c433_1  
> snowballstemmer           1.2.1            py36h6febd40_0  
> sortedcollections         0.5.3            py36h3c761f9_0  
> sortedcontainers          1.5.7            py36hdf89491_0  
> sphinx                    1.6.3            py36he5f0bdb_0  
> sphinxcontrib             1.0              py36h6d0f590_1  
> sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
> spyder                    3.2.4            py36hbe6152b_0  
> sqlalchemy                1.1.13           py36hfb5efd7_0  
> sqlite                    3.20.1               h6d8b0f3_1  
> statsmodels               0.8.0            py36h8533d0b_0  
> sympy                     1.1.1            py36hc6d1c1c_0  
> tblib                     1.3.2            py36h34cf8b6_0  
> tensorflow                1.4.1                     <pip>
> tensorflow-tensorboard    0.4.0rc3                  <pip>
> terminado                 0.6              py36ha25a19f_0  
> testpath                  0.3.1            py36h8cadb63_0  
> tk                        8.6.7                h5979e9b_1  
> toolz                     0.8.2            py36h81f2dff_0  
> tornado                   4.5.2            py36h1283b2a_0  
> traitlets                 4.3.2            py36h674d592_0  
> typing                    3.6.2            py36h7da032a_0  
> unicodecsv                0.14.1           py36ha668878_0  
> unixodbc                  2.3.4                hc36303a_1  
> urllib3                   1.22             py36hbe7ace6_0  
> virtualenv                15.1.0                   py36_0  
> wcwidth                   0.1.7            py36hdf4376a_0  
> webencodings              0.5.1            py36h800622e_1  
> werkzeug                  0.12.2           py36hc703753_0  
> wheel                     0.29.0           py36he7f4e38_1  
> widgetsnbextension        3.0.2            py36hd01bb71_1  
> wrapt                     1.10.11          py36h28b7045_0  
> xlrd                      1.1.0            py36h1db9f0c_1  
> xlsxwriter                1.0.2            py36h3de1aca_0  
> xlwt                      1.3.0            py36h7b00a1f_0  
> xz                        5.2.3                h2bcbf08_1  
> yaml                      0.1.7                h96e3832_1  
> zeromq                    4.2.2                hb0b69da_1  
> zict                      0.1.3            py36h3a3bf81_0  
> zlib                      1.2.11               hfbfcf68_1  

* Bonus: conda version
`$ conda --version`

> conda 4.4.7

* Bonus: conda info
`$ conda info`

>      active environment : None
>             shell level : 0
>        user config file : /home/raffaele/.condarc
>  populated config files : 
>           conda version : 4.4.7
>     conda-build version : 3.0.27
>          python version : 3.6.3.final.0
>        base environment : /home/raffaele/anaconda3  (writable)
>            channel URLs : https://repo.continuum.io/pkgs/main/linux-64
>                           https://repo.continuum.io/pkgs/main/noarch
>                           https://repo.continuum.io/pkgs/free/linux-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/linux-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/linux-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>           package cache : /home/raffaele/anaconda3/pkgs
>                           /home/raffaele/.conda/pkgs
>        envs directories : /home/raffaele/anaconda3/envs
>                           /home/raffaele/.conda/envs
>                platform : linux-64
>              user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.3 Linux/4.14.13-041413-generic ubuntu/17.10 glibc/2.26
>                 UID:GID : 1000:1000
>              netrc file : None
>            offline mode : False

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I cannot install zipline using `conda install`

* What did you expect to happen?
For zipline to install

* What happened instead?

The following error message shows up:
> $ conda install -c Quantopian zipline
> Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - conda
>   - zipline
> Use "conda info <package>" to see the dependencies for each package.

## Reproduction Steps

1. `virtualenv zipline_conda`
2. `cd zipline_conda`
3. `source ./bin/activate`
4. `conda install zipline`

## What steps have you taken to resolve this already?
Nothing

# Anything else?
No

Sincerely,
`$ whoami`
Raffaele

**Comment by freddiev4** [comment]
Hi @raffam we don't yet have packages built for Python 3.6. Can you try installing the latest zipline master in a Python 3.5 env?

```
conda install -c quantopian/label/ci -c quantopian zipline
```

**Comment by raffam** [comment]
Hi @freddiev4 ,
[there are three ways](https://docs.anaconda.com/anaconda/faq#how-do-i-get-the-latest-anaconda-with-python-3-5) I can get an Anaconda distribution with Python 3.5. Which one should I use?

**Comment by freddiev4** [comment]
Hi @raffam I recommend making a new conda env using:

```
conda create -n py35 python=3.5
```

Then run

```
conda install -c quantopian/label/ci -c quantopian zipline
```
