### ISSUE TITLE
Cannot compile from source: xlocale.h was renamed upstream

### ISSUE THREAD

**Issue by raffam** [quantopian/zipline#2084]
Dear Zipline Maintainers,

well this is my third post. Hope you appreciate my efforts to have a zipline up and running ^.^

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)

> Linux raffaele-GL753VD 4.14.13-041413-generic #201801101001 SMP Wed Jan 10 10:02:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Python Version: `$ python --version`
Python 3.6.3 :: Anaconda, Inc.
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`

> 64

* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)

I am trying to do so

* Python packages: `$ pip freeze` or `$ conda list`
`pip freeze` (base installation, no virtual env)
> alembic==0.9.7
> bcolz==0.12.1
> Bottleneck==1.2.1
> certifi==2017.11.5
> chardet==3.0.4
> click==6.7
> contextlib2==0.5.5
> cyordereddict==1.0.0
> Cython==0.27.3
> DateTime==4.2
> decorator==4.2.1
> empyrical==0.3.3
> idna==2.6
> intervaltree==2.1.0
> Logbook==1.1.0
> lru-dict==1.1.6
> Mako==1.0.7
> MarkupSafe==1.0
> multipledispatch==0.4.9
> networkx==2.0
> numexpr==2.6.4
> numpy==1.14.0
> pandas==0.18.1
> pandas-datareader==0.5.0
> patsy==0.5.0
> python-dateutil==2.6.1
> python-editor==1.0.3
> pytz==2017.3
> requests==2.18.4
> requests-file==1.4.3
> requests-ftp==0.3.1
> scipy==1.0.0
> six==1.11.0
> sortedcontainers==1.5.9
> SQLAlchemy==1.2.1
> statsmodels==0.8.0
> tables==3.4.2
> toolz==0.9.0
> urllib3==1.22
> zipline==1.1.1
> zope.interface==4.4.3

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I cannot compile from source files

* What did you expect to happen?
For the compilation to go fine

* What happened instead?
numpy 1.11.1 (the requirements.txt force this exact version) doesn't compile anymore because a [header file](https://sourceware.org/git/?p=glibc.git;a=commit;h=f0be25b6336db7492e47d2e8e72eb8af53b5506d) was renamed upstream in glibc

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

Follow the instructions [here](https://virtualenvwrapper.readthedocs.io/en/latest/)

1. `git clone git@github.com:your-github-username/zipline.git`
2. `mkvirtualenv zipline`
3. `./etc/ordered_pip.sh ./etc/requirements.txt`

## What steps have you taken to resolve this already?
None

# Anything else?
Here is the relevant part of the compilation log:

> gcc: numpy/core/src/multiarray/iterators.c
>     gcc: build/src.linux-x86_64-3.6/numpy/core/src/multiarray/lowlevel_strided_loops.c
>     gcc: numpy/core/src/multiarray/mapping.c
>     gcc: numpy/core/src/multiarray/methods.c
>     gcc: numpy/core/src/multiarray/multiarraymodule.c
>     gcc: build/src.linux-x86_64-3.6/numpy/core/src/multiarray/nditer_templ.c
>     gcc: numpy/core/src/multiarray/nditer_api.c
>     gcc: numpy/core/src/multiarray/nditer_constr.c
>     gcc: numpy/core/src/multiarray/nditer_pywrap.c
>     gcc: numpy/core/src/multiarray/number.c
>     gcc: numpy/core/src/multiarray/numpymemoryview.c
>     gcc: numpy/core/src/multiarray/numpyos.c
>     numpy/core/src/multiarray/numpyos.c:18:10: fatal error: xlocale.h: No such file or directory
>      #include <xlocale.h>
>               ^~~~~~~~~~~
>     compilation terminated.
>     numpy/core/src/multiarray/numpyos.c:18:10: fatal error: xlocale.h: No such file or directory
>      #include <xlocale.h>
>               ^~~~~~~~~~~
>     compilation terminated.
>     error: Command "gcc -pthread -B /home/raffaele/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -DNO_ATLAS_INFO=-1 -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-3.6/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/raffaele/anaconda3/include/python3.6m -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -c numpy/core/src/multiarray/numpyos.c -o build/temp.linux-x86_64-3.6/numpy/core/src/multiarray/numpyos.o" failed with exit status 1
>     
>     ----------------------------------------
> Command "/media/raffaele/DATA/data/progetti_miei/virtualenvs/zipline/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qigjgwp4/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-le2e41b6-record/install-record.txt --single-version-externally-managed --compile --install-headers /media/raffaele/DATA/data/progetti_miei/virtualenvs/zipline/include/site/python3.6/numpy" failed with error code 1 in /tmp/pip-build-qigjgwp4/numpy/
> 

Sincerely,
`$ whoami`
Raffaele

**Comment by raffam** [comment]
I made a PR that makes ziplien compile against the latest version of pandas (0.22) and numpy (1.14). This is PR #2086.
It's highly experimental and 10/891 tests fail.

(also the developer documentation needs to be updated, since `nosetests` without arguments don't run any test at all for me)

**Comment by raffam** [comment]
What do you think of the PR? You said PR were welcomed no?

**Comment by freddiev4** [comment]
Hi @raffam thanks for opening the PR! I don't currently have time to review it in detail but I think the next step would be to get the tests to pass. Would you be able to work on that?

**Comment by richafrank** [comment]
@raffam I'm going to close this, since https://github.com/quantopian/zipline/pull/2194 was merged. Feel free to reopen if that wasn't enough.

**Comment by tan981211** [comment]
Have you found a solution? I met this, too
