### ISSUE TITLE
date_rules does not work

### ISSUE THREAD

**Issue by xiaoxiaoyaozi** [quantopian/zipline#2090]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10)
* Python Version: `$ python 3.5
* How did you install Zipline: (`pip`,)

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I want to re-balance my portfolio with dual-average strategy at each month beginning. So I use schedule_function(handle_data, date_rules.month_start) to achieve it. But it didn't come true. It still invokes handle_data() every time. However, It invokes handle_data() twice at every month beginning.

My code is attached below.

def initialize(context):
    context.sym = symbol('AAPL')
    context.i = 0
    context.set_commission(commission.PerDollar(cost=0.0030))
    schedule_function(handle_data, date_rules.month_start())

def handle_data(context, data):
    context.i += 1
    if context.i < 300:  
        return
    print(get_datetime())
    if not get_open_orders():
        short_mavg = data.history(context.sym, 'close', 100, '1d').mean()
        long_mavg = data.history(context.sym, 'close', 300, '1d').mean()
        if short_mavg > long_mavg:    
            order_target_percent(context.sym, 1.0)
            print('buy')
        elif short_mavg < long_mavg:
            order_target_percent(context.sym, 0.0)
            print('sell')

 And I post a part of my output:
2016-10-18 20:00:00+00:00
sell
2016-10-19 20:00:00+00:00
sell
2016-10-20 20:00:00+00:00
sell
2016-10-21 20:00:00+00:00
buy
2016-10-24 20:00:00+00:00
buy
2016-10-25 20:00:00+00:00
buy
2016-10-26 20:00:00+00:00
buy
2016-10-27 20:00:00+00:00
buy
2016-10-28 20:00:00+00:00
buy
2016-10-31 20:00:00+00:00
buy
2016-11-01 20:00:00+00:00
buy
2016-11-01 20:00:00+00:00
buy
2016-11-02 20:00:00+00:00
buy
2016-11-03 20:00:00+00:00
buy

as you can see, the strategy re-balance at 2016-10-21, which is not the beginning of a month. And it invokes the strategy twice at the beginning of Nov. 2016. I don't know why.

Sincerely,
Brian

**Comment by freddiev4** [comment]
Hi Brian. handle_data is called every day, regardless of whether or not you use it in your call to schedule_function. 

You should make your own function, called rebalance, which takes in context and data, and then you should be able to use your rebalance in schedule_function.

**Comment by xiaoxiaoyaozi** [comment]
Hi freddiev. I add my own function callled `rebalance` and use it in the `schedule_function`, but it has the same outcome.

**Comment by xiaoxiaoyaozi** [comment]
I have solute it. Freddiev's method is right. Thanks
