### ISSUE TITLE
zipline cli errors due to pandas-datareader conflict

### ISSUE THREAD

**Issue by ybryan** [quantopian/zipline#2102]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment 

* Operating System: (Windows Version or `$ uname --all`) 
**1. MacOS 10.13.3**
**2. Linux 0af9b3940091 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 GNU/Linux**

* Python Version: **Python 3.5.4**
* Python Bitness: **64**
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
>1. docker from 70f8d14
>2. virtualenv + `pip install zipline` (from latest master 70f8d14)
* Python packages: `$ pip freeze` or `$ conda list` 
*Mac OS virtualenv 3.5.4*
```alembic==0.9.7
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.2.1
empyrical==0.3.4
idna==2.6
intervaltree==2.1.0
Logbook==1.2.1
lru-dict==1.1.6
lxml==4.1.1
Mako==1.0.7
MarkupSafe==1.0
multipledispatch==0.4.9
networkx==1.11
numexpr==2.6.4
numpy==1.14.0
pandas==0.18.1
pandas-datareader==0.6.0
patsy==0.5.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
scipy==1.0.0
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
tables==3.4.2
toolz==0.9.0
urllib3==1.22
wrapt==1.10.11
zipline==1.1.1+240.g70f8d147
```
Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

`zipline ingest ` and all zipline cli commands fail due to pandas version conflict. Really due to pandas-datareader dependency on pandas 0.19.2

* What did you expect to happen?
Progress bar on zipline ingest and bcolz data input
* What happened instead?
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pandas 0.18.1 (/usr/local/lib/python3.5/site-packages), Requirement.parse('pandas>=0.19.2'), {'pandas-datareader'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zipline", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pandas 0.18.1 (/usr/local/lib/python3.5/site-packages), Requirement.parse('pandas>=0.19.2'), {'pandas-datareader'})
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. `zipline ingest -b quantopian-quandl` or `zipline ingest -c custom-csv` on both Docker containers and virtualenv pip install zipline git master
2. All zipline CLI commands fail this exact way

## What steps have you taken to resolve this already?
Trying different git commits
...

# Anything else?
I had the `zipline ingest -b quantopain-quandl` and `zipline run *` working on my Docker container on 2018-01-23
...

Sincerely,
`ybryan`

**Comment by ybryan** [comment]
Just tested this on a fresh centos instance and the issue is still present. I believe this is not related to environment.

**Comment by ybryan** [comment]
Looks like a library dependency issue but I don't see any changes in /etc/requirements.txt 
`$ pipdeptree`
>Warning!!! Possibly conflicting dependencies found:
>* pandas-datareader==0.6.0
> - pandas [required: >=0.19.2, installed: 0.18.1]

**Comment by richafrank** [comment]
Looks like the latest pandas-datareader [now requires](https://github.com/pydata/pandas-datareader/compare/v0.5.0...v0.6.0#diff-2eeaed663bd0d25b7e608891384b7298L28) a newer pandas version than zipline supports.

**Comment by ybryan** [comment]
Closing
