### ISSUE TITLE
Really simple: broken-link of Dockerfile, ta-lib's source

### ISSUE THREAD

**Issue by dougpagani** [quantopian/zipline#2109]
_Sourceforge changed the base-url format:_
**OLD:** 
https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz
**NEW:**
https://kent.dl.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz

**Comment by freddiev4** [comment]
Hmm I suppose I'll have to run the Dockerfile myself to check, but I just opened the original link and was still able to download the `ta-lib` tar file.

**Comment by ssanderson** [comment]
FWIW, sourceforge is currently in maintenance mode, so this may just be temporary. https://twitter.com/sfnet_ops/status/963565756851081216

**Comment by freddiev4** [comment]
ah @ssanderson that's probably the issue

**Comment by dougpagani** [comment]
The master-build (without cache of course) was still failing ~1 hour ago with the old URL, so maybe something funny is/was going on with `curl -L` for redirection. 

As a temporary workaround, just swapping those two URL's should do just fine. It did indeed work just fine for me and two others, whereas the old failed for all.

**Comment by freddiev4** [comment]
Looks like this turned out to only be temporary. Going to close this and will re-open or revisit this if this becomes an issue in the future.
