### ISSUE TITLE
quandl bundle does not have recent data after ingestion

### ISSUE THREAD

**Issue by VitalyErmilov** [quantopian/zipline#2118]
Dear Zipline Maintainers,
 
Today (2nd March 2018) I discovered a problem with ingesting the quandl bundle while yesterday everything worked ok.  The process of ingestion goes as usual (has normal textual output  ) but in result the last price data in the bundle appears to be for 28th February 2018.

Because of this it's not possible to run backtests with the end date set to yesterday.

I suppose the following url doesn't work as before anymore  :
 'https://www.quandl.com/api/v3/datatables/WIKI/PRICES.csv?'
 
To reproduce the issue, please, try to make ingestion of the quandl bundle and make a backtest with benchmark set to some stock like MSFT, GOOGL,AAPL etc. You are supposed to get the error message that benchmark stopped trading at 28th February 2018
 
Sincerely,
`$ whoami`

**Comment by VitalyErmilov** [comment]
Update: I manually downloaded today's WIKI prices csv file and some searching showed there is actually no data for yesterday. So look like the url is working, probably this is an issue on the quandl's side.

**Comment by h55nick** [comment]
Yeah. I can confirm that I am seeing the most recent data in the quandl bundle. Note that over the weekend they can be delayed.

@richafrank I think this can be closed :-)

**Comment by richafrank** [comment]
Ok, great to hear 😄
