### ISSUE TITLE
Why the same algo in quantopian and local zipline has a big gap in the consuming time of backtest?

### ISSUE THREAD

**Issue by tonywangcn** [quantopian/zipline#2122]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
Linux 9d729c44795c 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: `$ python --version`
Python 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:10:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
64
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
pip
* Python packages: `$ pip freeze` or `$ conda list`
alembic==0.9.8
alphalens==0.2.1
asn1crypto==0.22.0
backports.weakref==1.0rc1
bcolz==0.12.1
beautifulsoup4==4.5.3
bleach==1.5.0
bokeh==0.12.13
Bottleneck==1.2.1
certifi==2018.1.18
cffi==1.11.2
chardet==3.0.4
click==6.7
cloudpickle==0.2.2
conda==4.3.34
contextlib2==0.5.5
cryptography==2.1.4
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
dask==0.17.0
decorator==4.2.1
dill==0.2.7.1
distributed==1.21.0
empyrical==0.3.4
entrypoints==0.2.3
fastcache==1.0.2
h5py==2.6.0
heapdict==1.0.0
html5lib==0.9999999
idna==2.6
intervaltree==2.1.0
ipykernel==4.8.2
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.2
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.2
jupyter-core==4.4.0
jupyterhub==0.8.1
jupyterlab==0.31.8
jupyterlab-launcher==0.10.4
Keras==2.0.9
llvmlite==0.16.0
locket==0.2.0
Logbook==1.2.1
lru-dict==1.1.6
lxml==4.1.1
Mako==1.0.7
Markdown==2.6.9
MarkupSafe==1.0
matplotlib==2.0.2
mistune==0.8.3
mock==2.0.0
msgpack-python==0.5.1
multipledispatch==0.5.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==1.11
notebook==5.2.2
numba==0.31.0
numexpr==2.6.4
numpy==1.14.1
olefile==0.45.1
pamela==0.3.0
pandas==0.18.1
pandas-datareader==0.5.0
pandocfilters==1.4.1
parso==0.1.1
partd==0.3.8
patsy==0.5.0
pbr==3.1.1
pexpect==4.4.0
pickleshare==0.7.4
Pillow==4.2.1
prompt-toolkit==1.0.15
protobuf==3.5.1
psutil==5.4.0
ptyprocess==0.5.2
pycosat==0.6.3
pycparser==2.18
pyfolio==0.8.0+124.g6fa3a30
Pygments==2.2.0
pygpu==0.7.5
pyOpenSSL==17.4.0
pyparsing==2.2.0
PySocks==1.6.8
python-dateutil==2.6.1
python-editor==1.0.3
python-oauth2==1.0.1
pytz==2018.3
PyYAML==3.12
pyzmq==17.0.0
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
ruamel-yaml==0.11.14
scikit-image==0.12.3
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.7.1
simplegeneric==0.8.1
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.4
statsmodels==0.8.0
sympy==1.0
TA-Lib==0.4.17
tables==3.4.2
tblib==1.3.2
tensorboard==1.6.0
tensorflow==1.3.0
terminado==0.8.1
testpath==0.3.1
Theano==1.0.1
toolz==0.9.0
tornado==4.5.3
traitlets==4.3.2
urllib3==1.22
vincent==0.4.4
wcwidth==0.1.7
webencodings==0.5
Werkzeug==0.14.1
widgetsnbextension==3.1.4
wrapt==1.10.11
xlrd==1.1.0
zict==0.1.3
zipline==1.1.1+258.gbd24e0d

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
The same algo (https://www.quantopian.com/posts/why-the-same-algo-in-quantopian-and-local-zipline-has-a-big-gap-in-the-consuming-time-of-backtest) in zipline consumed much more time than the one in quantopian.
quantopian cost a few seconds, no more than 1 minute, but zipline cost more than 10 minutes.

* What did you expect to happen?

The time shouldn't have such large gap.

* What happened instead?

Here is how you can reproduce this issue on your machine:
run the algo with cli or jupyter
https://www.quantopian.com/posts/why-the-same-algo-in-quantopian-and-local-zipline-has-a-big-gap-in-the-consuming-time-of-backtest

```
from zipline import run_algorithm
capital_base = 10000
start = pd.Timestamp('2017-12-01', tz='UTC')
end   = pd.Timestamp('2018-02-01', tz='UTC')
print(start,end,capital_base,initialize,handle_data)
%time perf = run_algorithm(start=start,end=end,capital_base=capital_base,initialize=initialize, handle_data=handle_data)
```

## Reproduction Steps

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by h55nick** [comment]
This is a strange finding for me. My local backtests run orders of magnitude faster than quantopian.com. Only shortcoming is that I find the quandl data bundle not cleaned like the data quantopian must be using so it has a couple days/sec that error out if there is no adjustment

**Comment by fawce** [comment]
Sorry for the long delay. The forum post has an algorithm that references Q1500, which is only available on Quantopian. Perhaps you are running a different version locally? I'm going to close because we are doing a big triage of the zipline issue backlog and closing stale issues. If you can share the locally run algorithm, please re-open.
