### ISSUE TITLE
Update to support Pandas 0.22

### ISSUE THREAD

**Issue by YongBeomKim** [quantopian/zipline#2132]
Dear Zipline Maintainers,
# Environment
* Operating System: (ubuntu mate 17.04)
* Python Version: 3.6.4
* How did you install Zipline: `pip`,

# Description of Issue
https://github.com/quantopian/zipline/issues/2043 [link](https://github.com/quantopian/zipline/issues/2043)
@nateGeorge  is fixed  to use in Pandas 0.22 (New Version)
please chack & update on your Source

**Comment by mickeydonkey** [comment]
there is a branch updating the pandas and other relevant packages, but it has been dominant for several weeks.

**Comment by freddiev4** [comment]
Hi @YongBeomKim thanks for opening the issue. There is a branch open that's a WIP for supporting a newer pandas version. It'll take some time to finish as the remaining work is for the Pipeline API.

**Comment by richafrank** [comment]
Linking to previous PR and ongoing discussion: https://github.com/quantopian/zipline/pull/2086#issuecomment-370858680

**Comment by twiecki** [comment]
Pandas 0.23.0 is the most recent.

**Comment by richafrank** [comment]
Closing - See https://github.com/quantopian/zipline/pull/2194 and https://github.com/quantopian/zipline/issues/2243
