### ISSUE TITLE
Missing methods in zipline.api

### ISSUE THREAD

**Issue by weironglue** [quantopian/zipline#2146]
Dear Zipline Maintainers,

Having installed the zipline through Anaconda, I encounter error message in my first line of python code, as shown below.  The python could not find order_target, record, and symbol in zipline.api.  I was using zipline v1.1.1 and python 3.4.  Do you know how to fix it?

from zipline.api import order_target, record, symbol

Thanks,

Wei

**Comment by freddiev4** [comment]
Hi @weironglue I'm not sure how to reproduce your issue; can you install the latest version of Zipline, 1.2.0 (which is recommended), and if this issue still exists, then fill out the [issue template](https://github.com/quantopian/zipline/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by weironglue** [comment]
I just create the issue template because after installing the zipline 1.2.0 with Python 3.5.5 I still see the same problem.

**Comment by freddiev4** [comment]
Going to close this b/c it's a bit of an older issue, but if you're still having problems, please open a new issue with the [issue template](https://github.com/quantopian/zipline/blob/master/.github/ISSUE_TEMPLATE.md) filled out.

Thanks!
