### ISSUE TITLE
No module named 'lru'

### ISSUE THREAD

**Issue by jhoodbossb** [quantopian/zipline#2148]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: Python 3.6.5
* How did you install Zipline: conda install -c Quantopian zipline

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? 

Hi, I downloaded Zipline Quantopian through Anaconda prompt in the virtual environment I have created. This worked, but now the exercise asks me to run the following code:

from datetime import datetime, timezone
from zipline.api import record, symbol, order
from zipline import run_algorithm

When I run it, I receive the following message:

  File "C:\Users\Me\Anaconda3\envs\myvirtualenvironment\Lib\site-packages\zipline\utils\calendars\trading_calendar.py", line 16, in <module>
    from lru import LRU

ModuleNotFoundError: No module named 'lru'

I went through trading_calendar's line 15 and 16 to see what they say:

line 15: from abc import ABCMeta, abstractproperty
line 16: from lru import LRU

abc is located in C:\Users\Me\Anaconda3\pkgs\python-2.7.14-h4a10d90_31\Lib
lru is located in: C:\Users\Me\Anaconda3\pkgs\zict-0.1.3-py36h2d8e73e_0\Lib\site-packages\zict

I guess it finds ABCMeta, but why does it not find lru?

Regards,

Nick

**Comment by ryanwcyin** [comment]
Have you try conda update Iru?

**Comment by freddiev4** [comment]
Hi @jhoodbossb going to close this b/c it's an older issue, but I also can't tell if you're using Zipline in a Py27 / Py35 env. We don't yet test / build packages for Python 3.6.

Can you try installing using the [docs](http://www.zipline.io/install.html#installing-with-conda) and open a new issue if you still have problems?

Thanks,
Freddie
