### ISSUE TITLE
UnicodeDecodeError when opening dma.csv

### ISSUE THREAD

**Issue by nomadcreator** [quantopian/zipline#2149]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

Windows 10
Python 3.6.4
Installation: using pip (since there was an error doing conda installation),

Python package: 
alembic==0.9.9
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2018.4.16
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.28.2
decorator==4.3.0
empyrical==0.4.2
idna==2.6
intervaltree==2.1.0
Logbook==1.3.3
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
multipledispatch==0.5.0
networkx==1.11
numexpr==2.6.4
numpy==1.14.2
pandas==0.18.1
pandas-datareader==0.5.0
patsy==0.5.0
python-dateutil==2.7.2
python-editor==1.0.3
pytz==2018.4
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
scipy==1.0.1
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.6
statsmodels==0.8.0
tables==3.4.2
toolz==0.9.0
urllib3==1.22
zipline==1.2.0

# Description of Issue

After installing zipine, I have set the key and executed following commands. 

<python code>   - just copied and pasted from the instruction

from zipline.api import order_target, record, symbol

def initialize(context):
    context.i = 0
    context.asset = symbol('AAPL')

def handle_data(context, data):
    # Skip first 300 days to get full windows
    context.i += 1
    if context.i < 300:
        return

    # Compute averages
    # data.history() has to be called with the same params
    # from above and returns a pandas dataframe.
    short_mavg = data.history(context.asset, 'price', bar_count=100, frequency="1d").mean()
    long_mavg = data.history(context.asset, 'price', bar_count=300, frequency="1d").mean()

    # Trading logic
    if short_mavg > long_mavg:
        # order_target orders as many shares as needed to
        # achieve the desired number of shares.
        order_target(context.asset, 100)
    elif short_mavg < long_mavg:
        order_target(context.asset, 0)

    # Save values for later inspection
    record(AAPL=data.current(context.asset, 'price'),
           short_mavg=short_mavg,
           long_mavg=long_mavg)

<Command Line>
>zipline ingest -b quandl
>zipline run -f dual_moving_average.py --start 2014-1-1 --end 2018-1-1 -o dma.csv

after that, I tried to open the dataframe in a py file as below

import pandas
df  =pandas.read_csv('dma.csv')
print(df)

Then I have following error and cannot proceed. 

File "pandas/parser.pyx", line 520, in pandas.parser.TextReader.__cinit__ (pandas\parser.c:5129)
File "pandas/parser.pyx", line 699, in pandas.parser.TextReader._get_header (pandas\parser.c:7634)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

How can I solve this problem?

**Comment by nomadcreator** [comment]
Thank you for your quick response. 

I saw following messages when I tried to install via conda. 

(venv) XXX >conda install -c Quantopian zipline
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - menuinst
  - zipline
Use "conda info <package>" to see the dependencies for each package.


I will try 3.5 version. Is that possible to give some hints to how to? I am not knowledgeable about how to temporary downgrade Python.

**Comment by nomadcreator** [comment]
I have set Conda with Python 3.5.   Then another error comes.

When I tried to ingest as below:

>zipline ingest -b quandl



I got following error message: 

 from pandas.core.reshape import (pivot_simple as pivot, get_dummies,
ImportError: cannot import name 'pivot_simple'

**Comment by freddiev4** [comment]
You can create a new conda env using:
```
conda create -n env_zipline python=3.5
source activate env_zipline
```

And then run `pip install zipline`.

If you want to run `zipline ingest -b quandl` you need to prepend an API key `QUANDL_API_KEY=<yourkey> zipline ingest -b quandl`

**Comment by nomadcreator** [comment]
Thank you. I think I have already create new conda and set API key already, and still have the error mentioned above.

**Comment by freddiev4** [comment]
Hmm...interesting. Haven't seen that error before.

Can you show the output of running:

```
conda info
```

**Comment by nomadcreator** [comment]
active environment : Python35
    active env location : C:\Users\XXX\Miniconda3\envs\Python35
            shell level : 1
       user config file : C:\Users\XXX\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : C:\Users\XXX\Miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\XXX\Miniconda3\pkgs
                          C:\Users\XXX\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\XXX\Miniconda3\envs
                          C:\Users\XXXl\AppData\Local\conda\conda\envs
                          C:\Users\XXX\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : C:\Users\XXX/.netrc
           offline mode : False

**Comment by freddiev4** [comment]
Hmm..ok. And how about if you run: `conda list`

**Comment by nomadcreator** [comment]
>conda list
# packages in environment at C:\Users\livel\Miniconda3\envs\Python35:
#
# Name                    Version                   Build  Channel
alembic                   0.7.7                    py35_0    Quantopian
asn1crypto                0.24.0                   py35_0
bcolz                     0.12.1              np111py35_0    Quantopian
bottleneck                1.2.1            py35h8a3671c_0
bzip2                     1.0.6                hbe05fcf_4
ca-certificates           2018.03.07                    0
certifi                   2018.1.18                py35_0
cffi                      1.11.5           py35h945400d_0
chardet                   3.0.4            py35h177e1b7_1
click                     6.7              py35h10df73f_0
contextlib2               0.5.5            py35h0a97e54_0
cryptography              2.2.2            py35hfa6e2cd_0
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.2           py35hfa6e2cd_0
decorator                 4.3.0                    py35_0
empyrical                 0.4.2                    py35_0    Quantopian
hdf5                      1.10.1               h98b8871_1
icc_rt                    2017.0.4             h97af966_0
idna                      2.6              py35h8dcb9ae_1
intel-openmp              2018.0.0                      8
intervaltree              2.1.0                    py35_0    Quantopian
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
lzo                       2.10                 h6df0209_2
mako                      1.0.7            py35ha146b58_0
markupsafe                1.0              py35hc253e08_1
mkl                       2018.0.2                      1
multipledispatch          0.5.0                    py35_0
networkx                  1.11             py35h097edc8_0
numexpr                   2.6.4            py35hb78e28a_0
numpy                     1.14.2                    <pip>
numpy                     1.11.3           py35h4a99626_4
openssl                   1.0.2o               h8ea7d77_0
pandas                    0.18.1              np111py35_0
pandas                    0.22.0                    <pip>
pandas-datareader         0.5.0                    py35_0
patsy                     0.5.0                    py35_0
pip                       9.0.3                    py35_0
pycparser                 2.18             py35h15a15da_1
pyopenssl                 17.5.0           py35h75c5b16_0
pysocks                   1.6.8                    py35_0
pytables                  3.4.2            py35h9e98cc6_2
python                    3.5.5                h0c2934d_2
python-dateutil           2.7.2                    py35_0
python-dateutil           2.7.2                     <pip>
pytz                      2018.4                    <pip>
pytz                      2018.4                   py35_0
requests                  2.18.4           py35h54a615f_1
requests-file             1.4.1                    py35_0
requests-ftp              0.3.1                    py35_0
scipy                     1.0.1            py35hce232c7_0
setuptools                39.0.1                   py35_0
six                       1.11.0           py35hc1da2df_1
six                       1.11.0                    <pip>
sortedcontainers          1.5.9                    py35_0
sqlalchemy                1.2.6            py35hfa6e2cd_0
statsmodels               0.8.0            py35hfa6034c_0
toolz                     0.9.0                    py35_0
urllib3                   1.22             py35h8cc84eb_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wheel                     0.31.0                   py35_0
win_inet_pton             1.0.1            py35hbef1270_1
wincertstore              0.2              py35hfebbdb8_0
zipline                   1.2.0               np111py35_0    Quantopian
zlib                      1.2.11               h8395fce_2

**Comment by nomadcreator** [comment]
The above is the conda list. Is there any hit you can think about?

**Comment by freddiev4** [comment]
Coming back to this now; I just noticed you're assuming that the output of the algorithm is `.csv` file; in fact it is actually a [pickle](https://docs.python.org/3/library/pickle.html) file.

You need to read the file using:
```
import pandas
df = pandas.read_pickle('dma.pickle')
print(df)
```

**Comment by freddiev4** [comment]
Going to close this due to no follow-up from OP. Feel free to re-open if you're still having issues @nomadcreator
