### ISSUE TITLE
Add Google Finance as intraday DataReader

### ISSUE THREAD

**Issue by c0indev3l** [quantopian/zipline#215]
Hello,

Adding Google Finance as intraday DataReader will be nice.

A sample
https://www.google.com/finance/getprices?q=MSFT&i=60
EXCHANGE%3DNASDAQ
MARKET_OPEN_MINUTE=570
MARKET_CLOSE_MINUTE=960
INTERVAL=60
COLUMNS=DATE,CLOSE,HIGH,LOW,OPEN,VOLUME
DATA=
TIMEZONE_OFFSET=-240
a1376074620,32.67,32.69,32.67,32.68,21748
1,32.65,32.68,32.645,32.67,107914
2,32.665,32.67,32.65,32.655,23613
3,32.6662,32.67,32.66,32.6699,16970
4,32.66,32.67,32.66,32.66,47771
...
81,33.155,33.18,33.15,33.18,0
82,33.145,33.17,33.14,33.155,0
83,33.13,33.155,33.13,33.155,0
84,33.1,33.14,33.095,33.13,0
85,33.115,33.129,33.1,33.1,0
86,33.14,33.14,33.11,33.115,0

Some details about Google's Undocumented Finance API
http://www.networkerror.org/component/content/article/1-technical-wootness/44-googles-undocumented-finance-api.html

Some Python code
http://trading.cheno.net/downloading-google-intraday-historical-data-with-python/
http://trading.cheno.net/wp-content/uploads/2011/12/google_intraday.py

Some R code
http://quantmaster.in/Blog/2013/07/Download-NSE-Intraday-Data-using-R.aspx

Thanks

**Comment by Excaliburst** [comment]
I definitely also support the implementation of intraday info in pd.datareader.

A great suggestion. Thanks for the idea.

**Comment by gliptak** [comment]
This was added to https://github.com/pydata/pandas-datareader/ with https://github.com/pydata/pandas-datareader/pull/177

**Comment by femtotrader** [comment]
Sorry @gliptak but Google Quote is not (historical) intraday data.

**Comment by gliptak** [comment]
@femtotrader I see, misread the description.

**Comment by llllllllll** [comment]
Something like this could now be implemented as a user defined data portal. I think that it is probably best to not include too many data bundles and instead allow users to choose the data source that works best for them.  by default we will be shipping with the quandl WIKI eod pricing data set.
