### ISSUE TITLE
Wrong calculations in returns with zipline 1.2.0

### ISSUE THREAD

**Issue by frosk1** [quantopian/zipline#2150]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux 4.15.12-201.fc26.x86_64 (Fedora kernal 26)
* Python Version: python 3.6.4
* Python Bitness: 64bit
* How did you install Zipline: pip
* Python packages: 
alembic==0.9.9
backcall==0.1.0
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2018.4.16
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.28.2
decorator==4.3.0
empyrical==0.4.2
idna==2.6
intervaltree==2.1.0
ipython==6.3.1
ipython-genutils==0.2.0
jedi==0.12.0
kiwisolver==1.0.1
Logbook==1.3.3
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.2
multipledispatch==0.5.0
networkx==1.11
numexpr==2.6.4
numpy==1.14.2
pandas==0.18.1
pandas-datareader==0.5.0
parso==0.2.0
patsy==0.5.0
pexpect==4.5.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.7.2
python-editor==1.0.3
pytz==2018.4
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
scikit-learn==0.19.1
scipy==1.0.1
seaborn==0.8.1
simplegeneric==0.8.1
six==1.11.0
sklearn==0.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.6
statsmodels==0.8.0
tables==3.4.2
toolz==0.9.0
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
xlrd==1.1.0
zipline==1.2.0

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I am testing the new zipline version 1.2.0 . I ran an identical simple algorithm described below on zipline version 1.1.1 under the exact same conditions: Equal data-bundle, equal commision model, equal slippage model. But i got different returns calculated. The price data and position data is correct with both version, but the returns are calculated differently. So is this an issue or are there new regulations in the calculations with version 1.2.0 which i did not find in the **whatsnew** file.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Define Algorithm:
```python
from zipline.api import symbol, order, record, set_commission, set_slippage

def initialize(context):
    
    set_commission(commission.PerShare(cost=.005, min_trade_cost=1.0))
    set_slippage(slippage.FixedSlippage(spread=0.00))

def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data[symbol('AAPL')].price)
```

2. Run on 1.1.1 and on 1.1.2

3. Check returns sheet
...

## What steps have you taken to resolve this already?

...

# So is there a new mechanism in the calculation ? The returns are slightly different.
...

Sincerely,
frosk

**Comment by abhijeetkalyan** [comment]
Thanks for the report @frosk1. This may be related to the [changes to risk and performance metrics](https://github.com/quantopian/zipline/blob/master/docs/source/whatsnew/1.2.0.txt#L10) we made in Zipline 1.2.0. This is on our list to investigate, although it's a very busy time and we may not get to it during the next week. 

Can you add the actual returns values of the algo you ran - both with zipline 1.1.1 and 1.2.0 - to the ticket as well?

**Comment by llllllllll** [comment]
I can no longer run backtests on 1.1.1 because of the change in benchmark data provider. Can you post the returns from both 1.1.1 and 1.2.0?

**Comment by freddiev4** [comment]
Going to close this as there hasn't been follow up from OP here, but feel free to re-open if you still have issues!
