### ISSUE TITLE
No module named 'zipline.research'

### ISSUE THREAD

**Issue by kaoboyandy** [quantopian/zipline#2151]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
python 3.6
* Operating System: (Windows Version or `$ uname --all`)
OS X El Captain
* Python Version: `$ python --version`
Python 3.6
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
pip install zipline
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I ran from `zipline.research import run_pipeline` and got
No module named 'zipline.research'

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by freddiev4** [comment]
Hi @kaoboyandy thanks for opening this issue. Couple of things to address here

- It looks like you're trying to convert Quantopian-specific code to Zipline code; `quantopian.research` is only available on Quantopian, and there isn't a Zipline equivalent submodule
- If you want to use Pipeline, you'd have to use `attach_pipeline`; see this Momentum example [here](https://github.com/quantopian/zipline/blob/59f12df7c83ae39c67b5abc12fb7b48db94de036/zipline/examples/momentum_pipeline.py)
- We also don't test / build packages for Python 3.6 yet, so if you plan on continuing to use Zipline, I'd recommend a Python 2.7 or Python 3.5 virtualenv

**Comment by freddiev4** [comment]
Going to close this due to no follow-up from OP.
