### ISSUE TITLE
Unable to ingest default data bundle

### ISSUE THREAD

**Issue by niklay14** [quantopian/zipline#2156]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: macOS 10.13.4
* Python Version:  3.5
* How did you install Zipline: Conda
* Python packages: 

Now that you know a little about me, let me tell you about the issue I am
having:

After installing zipline I tried to ingest the default data bundle by typing `zipline ingest -b quandl `(also tried it with my API key). However, I always get the following terminal output.

> (py35) MBP-von-Niklas:~ niklasamslgruber$ zipline ingest -b quandl
> Downloading WIKI metadata:   [------------------------------------]
> Traceback (most recent call last):
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/utils/cache.py", line 234, in __getitem__
>     with open(self._keypath(key), 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/niklasamslgruber/.zipline/data/quandl/.cache/metadata-page-1'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/quandl.py", line 33, in _fetch_raw_metadata
>     raw = cache[key]
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/utils/cache.py", line 239, in __getitem__
>     raise KeyError(key)
> KeyError: 'metadata-page-1'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/bin/zipline", line 11, in <module>
>     load_entry_point('zipline==1.1.1', 'console_scripts', 'zipline')()
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/__main__.py", line 312, in ingest
>     show_progress,
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/core.py", line 451, in ingest
>     pth.data_path([name, timestr], environ=environ),
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/quandl.py", line 295, in quandl_bundle
>     show_progress=show_progress,
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/quandl.py", line 117, in fetch_symbol_metadata_frame
>     data = pd.concat(blocks, ignore_index=True).rename(columns={
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/tools/merge.py", line 845, in concat
>     copy=copy)
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/tools/merge.py", line 875, in __init__
>     objs = list(objs)
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/_termui_impl.py", line 259, in next
>     rv = next(self.iter)
>   File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/quandl.py", line 61, in _fetch_raw_metadata
>     ' attempts.' % (page_number, retries),
> ValueError: Failed to download metadata page 1 after 5 attempts.

Sincerely,
Niklas

**Comment by freddiev4** [comment]
Based off some of the errors there it looks like you're [missing xcode](https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path) and can't actually compile any of the files.

**Comment by niklay14** [comment]
That's it, thank you @freddiev4
