### ISSUE TITLE
Consider using pandas CustomBusinessDay for offset in trading days index.

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#216]
There is a CustomBusinessDay object now available in pandas.tseries.offsets, (however, a caveat, it is labeled as experimental.)

Consider using the CDay as the offset for trading_days DatetimeIndex, so that logic that adds a day etc. can be expressed more clearly than the current need to have a wrapper that searches for the index of the date to which the delta is to be added.

**Comment by richafrank** [comment]
Done in https://github.com/quantopian/zipline/commit/43b85cffb06bfb90db48bbc9ac9f3ea242a01ef1#diff-c3eb37366a67e056eb79907f3330e925R252, by you @ehebert !
