### ISSUE TITLE
zipline fails to install with conda

### ISSUE THREAD

**Issue by wxprofessor** [quantopian/zipline#2176]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
Windows 10

* Python Version: `$ python --version`
(base) C:\WINDOWS\system32>python --version
Python 3.6.5

* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
(base) C:\WINDOWS\system32>python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))
64

* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)

I tried to install with conda... note:
(base) C:\WINDOWS\system32>conda install -c Quantopian zipline
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.6
  - zipline -> bcolz[version='>=0.12.1,<1'] -> numpy=1.10 -> python=2.7

* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
zipline fails to install with conda :(

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by freddiev4** [comment]
Hi @wxprofessor we don't have packages / test for Python 3.6; please try making a Python 3.5 conda env and then install. You can read more in the [Install Docs](http://www.zipline.io/install.html)

**Comment by freddiev4** [comment]
Going to close this due to no follow-up from OP. Feel free to re-open if you're still having issue.
