### ISSUE TITLE
Trading Calendars

### ISSUE THREAD

**Issue by mrahmadt** [quantopian/zipline#2183]
Hello Everyone,

I'm a little bit confused about why I need to define trading calendar, if someone can help me with below issue.

So basically my market trading calendar from 10 am to 4 pm on Sun, Mon, Tue, Wed, and Thu since 2010, before 2010 it was Sat, Sun, Mon, Tue and Wed (9 am to 3 pm) and holidays are not really on a fixed date.

Can I just define my calendar to be from 7 am to 5 pm 24/7 and just import the market data? what will be the impact of doing such thing?

Thanks

**Comment by freddiev4** [comment]
Hi @mrahmadt sorry for the delayed response here. the purpose of defining a trading calendar is to match up the dates in which your assets can be traded in the real world (in the context of a backtest), and the dates on which Zipline will want to actually place trades.

e.g. if I hard-coded a date that I wanted to trade on, and my calendar indicates that the market is closed at that time, the trade wouldn't go through. Also, the same can be said about your data bundle in that if you have pricing data on `1-1-2018` and your calendar does not have `1-1-2018` as a trading day, then there will be a mismatch (and then an error thrown).
