### ISSUE TITLE
Split trading calendars into separate repo

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#2187]
The trading calendars are very useful independently of all the functionality in zipline. If they were in a separate project they could be used much simpler (because the dependencies would be much lighter than zipline) by other projects.

**Comment by richafrank** [comment]
Thanks @twiecki . This is currently planned as part of upcoming changes for global markets.

**Comment by twiecki** [comment]
Great to hear! Feel free to close if it's a duplicate.

**Comment by richafrank** [comment]
Thanks - I didn't find another issue either.

**Comment by freddiev4** [comment]
@twiecki we have https://github.com/quantopian/trading_calendars; I think we can close this?
