### ISSUE TITLE
ImportError: No module named 'zipline.utils.calendars._calendar_helpers'

### ISSUE THREAD

**Issue by yadongcao** [quantopian/zipline#2193]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by umitanuki** [comment]
I hit the same issue.  Looks like you need to build pyx.

**Comment by umitanuki** [comment]
I was able to load zipline after this.
```
import pyximport
import numpy as np
pyximport.install(setup_args={'include_dirs': np.get_include()})
```

**Comment by umitanuki** [comment]
This builds .so files in the same source directory
```
$ python setup.py build_ext --inplace
```

**Comment by freddiev4** [comment]
Hi @yadongcao sorry for the late response here. Going to close this b/c of no follow-up but if you still have issues, please open a new issue with the template completely filled out.

Thanks,
Freddie
