### ISSUE TITLE
Conda build zipline 1.2 on OSX

### ISSUE THREAD

**Issue by waldren** [quantopian/zipline#2215]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System:  OSX 10.13.5
* Python Version: 3.6
* Python Bitness: 64
* How did you install Zipline: trying to use conda build
* Python packages: 
# Name                    Version                   Build  Channel
alabaster                 0.7.10           py27h9dd7d6e_0  
alembic                   0.7.7                    py27_0    Quantopian
anaconda                  custom           py27h2cfa9e9_0  
anaconda-client           1.6.14                   py27_0  
anaconda-project          0.8.2            py27h2dc806c_0  
appnope                   0.1.0            py27hb466136_0  
appscript                 1.0.1            py27h451298e_1  
asn1crypto                0.24.0                   py27_0  
astroid                   1.6.5                    py27_0  
astropy                   2.0.7            py27h917ab60_1  
atomicwrites              1.1.5                    py27_0  
attrs                     18.1.0                   py27_0  
babel                     2.6.0                    py27_0  
backcall                  0.1.0                    py27_0  
backports                 1.0              py27hb4f9756_1  
backports.functools_lru_cache 1.5                      py27_1  
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2  
backports_abc             0.5              py27h6972548_0  
bcolz                     0.12.1          np111py27h98fbfb4_0    Quantopian
beautifulsoup4            4.6.0            py27h9416283_1  
bitarray                  0.8.2            py27h1de35cc_0  
bkcharts                  0.2              py27haafc882_0  
blas                      1.0                         mkl  
blaze                     0.11.3           py27hb49378a_0  
bleach                    2.1.3                    py27_0  
blosc                     1.14.3               hd9629dc_0  
bokeh                     0.12.16                  py27_0  
boto                      2.48.0           py27hacdd0fd_1  
bottleneck                1.2.1            py27h71f98a3_0  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
certifi                   2018.4.16                py27_0  
cffi                      1.11.5           py27h342bebf_0  
chardet                   3.0.4            py27h2842e91_1  
chest                     0.2.3                    py27_0  
click                     6.7              py27h2b86a94_0  
cloudpickle               0.5.3                    py27_0  
clyent                    1.2.2            py27hc0ae608_0  
colorama                  0.3.9            py27hbbe92b6_0  
conda                     4.5.4                    py27_0  
conda-build               3.10.9                   py27_0  
conda-env                 2.6.0                h36134e3_0  
conda-verify              2.0.0            py27hbebe81d_0  
configparser              3.5.0            py27hc7edf1b_0  
contextlib2               0.5.5            py27h9cb85f4_0  
cryptography              2.2.2            py27h1de35cc_0  
curl                      7.60.0               ha441bb4_0  
cycler                    0.10.0           py27hfc73c78_0  
cyordereddict             0.2.2                    py27_0    Quantopian
cython                    0.28.3           py27h1de35cc_0  
cytoolz                   0.9.0.1          py27h1de35cc_0  
dask                      0.13.0                   py27_0  
dask-core                 0.17.5                   py27_0  
datashape                 0.5.4            py27hd6a1745_0  
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py27_0  
distributed               1.21.8                   py27_0  
docutils                  0.14             py27h0befae3_0  
empyrical                 0.4.3                     <pip>
entrypoints               0.2.3            py27hd680fb1_2  
enum34                    1.1.6            py27hf475452_1  
et_xmlfile                1.0.1            py27hc42f929_0  
expat                     2.2.5                hb8e80ba_0  
fastcache                 1.0.2            py27h1de35cc_2  
filelock                  3.0.4                    py27_0  
flask                     1.0.2                    py27_1  
flask-cors                3.0.4                    py27_0  
freetype                  2.8                  h12048fb_1  
funcsigs                  1.0.2            py27hb9f6266_0  
functools32               3.2.3.2          py27h8ceab06_1  
futures                   3.2.0            py27h1b80678_0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.1               h35bc53a_0  
glob2                     0.6              py27h55c9705_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py27h4bc979a_2  
greenlet                  0.4.13           py27h1de35cc_0  
h5py                      2.8.0            py27ha8ecd60_0  
hdf5                      1.10.2               hfa1e0ec_1  
heapdict                  1.0.0                    py27_2  
html5lib                  1.0.1            py27h5233db4_0  
icu                       58.2                 h4b95b61_1  
idna                      2.6              py27hedea723_1  
imageio                   2.3.0                    py27_0  
imagesize                 1.0.0                    py27_0  
inflection                0.3.1                    py27_0  
intel-openmp              2018.0.0                      8  
intervaltree              2.1.0                     <pip>
intervaltree              2.1.0                    py27_0    Quantopian
ipaddress                 1.0.22                   py27_0  
ipykernel                 4.8.2                    py27_0  
ipython                   5.7.0                    py27_0  
ipython_genutils          0.2.0            py27h8b9a179_0  
ipywidgets                7.2.1                    py27_0  
isort                     4.3.4                    py27_0  
itsdangerous              0.24             py27h3948ded_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4                      py27_0  
jedi                      0.12.0                   py27_1  
jinja2                    2.10             py27h70b8dc5_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py27hd9b497e_0  
jupyter                   1.0.0                    py27_4  
jupyter_client            5.2.3                    py27_0  
jupyter_console           5.2.0            py27h9702a86_1  
jupyter_core              4.4.0            py27h5ea6ba4_0  
jupyterlab                0.32.1                   py27_0  
jupyterlab_launcher       0.10.5                   py27_0  
kiwisolver                1.0.1            py27h9856860_0  
lazy-object-proxy         1.3.1            py27h712ce3f_0  
libcurl                   7.60.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                hcb84e12_1  
libxml2                   2.9.8                hab757c2_1  
libxslt                   1.1.32               hb819dd2_0  
linecache2                1.0.0            py27hdcabdf0_0  
llvmlite                  0.23.1           py27hc454e04_0  
locket                    0.2.0            py27ha10513d_1  
logbook                   0.12.5                   py27_0    Quantopian
lru-dict                  1.1.4                    py27_0    Quantopian
lxml                      4.2.1            py27h7166777_0  
lzo                       2.10                 h362108e_2  
mako                      1.0.7            py27h07f8f8b_0  
markupsafe                1.0              py27hd3c86fa_1  
matplotlib                2.2.2            py27ha7267d0_0  
mccabe                    0.6.1            py27h1f69e8d_0  
mistune                   0.8.3            py27h1de35cc_1  
mkl                       2018.0.2                      1  
mkl-service               1.1.2            py27hcba3029_4  
mkl_fft                   1.0.1            py27h917ab60_0  
mkl_random                1.0.1            py27h78cc56f_0  
more-itertools            4.2.0                    py27_0  
mpc                       1.0.3                h7a72875_5  
mpfr                      3.1.5                h711e7fd_2  
mpmath                    1.0.0            py27h6b0eff6_2  
msgpack-python            0.5.6            py27h04f5b5a_0  
multipledispatch          0.5.0                    py27_0  
nbconvert                 5.3.1            py27h6455e4c_0  
nbformat                  4.4.0            py27hddc86d0_0  
ncurses                   6.1                  h0a44026_0  
ndg-httpsclient           0.5.0                    py27_0  
networkx                  2.1                      py27_0  
nltk                      3.3.0                    py27_0  
nose                      1.3.7            py27h2ee3cb8_2  
notebook                  5.5.0                    py27_0  
numba                     0.38.0           py27h1702cab_0  
numexpr                   2.6.5            py27h057f876_0  
numpy                     1.11.3           py27h8a80b8c_4  
numpy-base                1.14.3           py27ha9ae307_2  
numpydoc                  0.8.0                    py27_0  
odo                       0.5.1            py27h992a9f7_0  
olefile                   0.45.1                   py27_0  
openpyxl                  2.5.4                    py27_0  
openssl                   1.0.2o               h26aff7b_0  
packaging                 17.1                     py27_0  
pandas                    0.18.1              np111py27_0  
pandas-datareader         0.5.0                    py27_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py27hed78c4e_1  
parso                     0.2.1                    py27_0  
partd                     0.3.8            py27h7560dbf_0  
path.py                   11.0.1                   py27_0  
pathlib2                  2.3.2                    py27_0  
patsy                     0.5.0                    py27_0  
pcre                      8.42                 h378b8a2_0  
pep8                      1.7.1                    py27_0  
pexpect                   4.6.0                    py27_0  
pickleshare               0.7.4            py27h37e3d41_0  
pillow                    5.1.0            py27hfcce615_0  
pip                       10.0.1                   py27_0  
pkginfo                   1.4.2                    py27_1  
pluggy                    0.6.0            py27had36429_0  
ply                       3.11                     py27_0  
prompt_toolkit            1.0.15           py27h4a7b9c2_0  
psutil                    5.4.6            py27h1de35cc_0  
ptyprocess                0.5.2            py27h70f6364_0  
py                        1.5.3                    py27_0  
pyasn1                    0.4.3                    py27_0  
pycodestyle               2.4.0                    py27_0  
pycosat                   0.6.3            py27h6c51c7e_0  
pycparser                 2.18             py27h0d28d88_1  
pycrypto                  2.6.1            py27h1de35cc_8  
pycurl                    7.43.0.2         py27hdbc3d79_0  
pyflakes                  2.0.0                    py27_0  
pygments                  2.2.0            py27h1a556bb_0  
pylint                    1.9.2                    py27_0  
pyodbc                    4.0.23           py27h0a44026_0  
pyopenssl                 18.0.0                   py27_0  
pyparsing                 2.2.0            py27h5bb6aaf_0  
pyqt                      5.9.2            py27h11d3b92_0  
pysocks                   1.6.8                    py27_0  
pytables                  3.4.3            py27h5ca999c_2  
pytest                    3.6.1                    py27_0  
pytest-arraydiff          0.2                      py27_0  
pytest-astropy            0.4.0                    py27_0  
pytest-doctestplus        0.1.3                    py27_0  
pytest-openfiles          0.3.0                    py27_0  
pytest-remotedata         0.3.0                    py27_0  
python                    2.7.15               h138c1fe_0  
python-dateutil           2.7.3                    py27_0  
python.app                2                py27hf2d5e94_7  
pytz                      2018.4                   py27_0  
pywavelets                0.5.2            py27hd99e88a_0  
pyyaml                    3.12             py27ha7932d0_1  
pyzmq                     17.0.0           py27h1de35cc_1  
qt                        5.9.5                h02808f3_0  
qtawesome                 0.4.4            py27hdeb2f59_0  
qtconsole                 4.3.1            py27hdc90b4f_0  
qtpy                      1.4.2                    py27_0  
quandl                    3.3.0                    py27_0  
readline                  7.0                  hc1231fa_4  
requests                  2.18.4           py27h9b2b37c_1  
requests-file             1.4.3                    py27_0  
requests-ftp              0.3.1                    py27_0  
rope                      0.10.7           py27hffa1879_0  
ruamel_yaml               0.15.37          py27h1de35cc_2  
scandir                   1.7              py27h1de35cc_0  
scikit-image              0.13.1           py27h1de35cc_1  
scikit-learn              0.19.1           py27h9788993_0  
scipy                     1.1.0            py27hcaad992_0  
seaborn                   0.8.1            py27h6bd0ddc_0  
send2trash                1.5.0                    py27_0  
setuptools                39.2.0                   py27_0  
simplegeneric             0.8.1                    py27_2  
singledispatch            3.4.0.3          py27he22c18d_0  
sip                       4.19.8           py27h0a44026_0  
six                       1.11.0           py27h7252ba3_1  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.2.1            py27h68ac032_0  
sortedcollections         0.6.1                    py27_0  
sortedcontainers          1.4.4                    py27_0    Quantopian
sphinx                    1.7.5                    py27_0  
sphinxcontrib             1.0              py27hd2ed746_1  
sphinxcontrib-websupport  1.1.0                    py27_1  
spyder                    3.2.8                    py27_0  
sqlalchemy                1.2.8            py27h1de35cc_0  
sqlite                    3.23.1               hf1716c9_0  
statsmodels               0.9.0            py27h917ab60_0  
subprocess32              3.5.2            py27h1de35cc_0  
sympy                     1.1.1            py27hce55102_0  
tblib                     1.3.2            py27ha684fc4_0  
terminado                 0.8.1                    py27_1  
testpath                  0.3.1            py27h72d81a5_0  
tk                        8.6.7                h35a86e2_3  
toolz                     0.9.0                    py27_0  
tornado                   5.0.2                    py27_0  
traceback2                1.4.0            py27hece0a87_0  
traitlets                 4.3.2            py27hcf08151_0  
typing                    3.6.4                    py27_0  
unicodecsv                0.14.1           py27h170f95c_0  
unittest2                 1.1.0            py27hf661856_0  
unixodbc                  2.3.6                h3efe00b_0  
urllib3                   1.22             py27hc3787e9_0  
wcwidth                   0.1.7            py27h817c265_0  
webencodings              0.5.1            py27h19a9f58_1  
werkzeug                  0.14.1                   py27_0  
wheel                     0.31.1                   py27_0  
widgetsnbextension        3.2.1                    py27_0  
wrapt                     1.10.11          py27hd341262_0  
xlrd                      1.1.0            py27hbd41ed1_1  
xlsxwriter                1.0.5                    py27_0  
xlwings                   0.11.8                   py27_0  
xlwt                      1.2.0            py27hbeec4ae_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h378b8a2_0  
zict                      0.1.3            py27h5fff8b1_0  
zlib                      1.2.11               hf3cbc9b_2 

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I am trying to build zipline 1.2. I am able to run conda build on ta-lib, logbook, and cyordereddict. When I try conda build zipline. I can an error of unresolved dependences (empyrical, intervaltree, lru-dict). I got the github repos and ran build and install with setup.py and then pip installed them. I still get the same dependency error. According to conda list I have the needed versions. 

Anyone successfully build zipline 1.2 on OSX? If so, any pointers?

#Conda build log
(stock_env) ohd:conda swaldren$ conda build zipline
Cloning into '/anaconda3/conda-bld/zipline_1529242498642/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

commit de893303b49eb70eb250b4832f1e1718178c7dd8
Merge: 13b64e8 98bd011
Author: Vikram Narayan <vnarayan@quantopian.com>
Date:   Fri Jun 15 12:34:00 2018 -0400

    Merge pull request #2213 from quantopian/add-license-year
    
    MAINT: add year/name to license

==> git describe --tags --dirty <==

1.2.0-58-gde89330

==> git status <==

On branch _conda_cache_origin_head
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
nothing to commit, working directory clean

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for zipline
INFO:conda_build.metadata:Attempting to finalize metadata for zipline
Solving environment: ...working... done
Solving environment: ...working... done
BUILD START: ['zipline-1.2.0-np111py36_58_gde89330.tar.bz2']
Solving environment: ...working... done
Solving environment: ...working... failed
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant

Leaving build/test directories:
  Work:
 /anaconda3/conda-bld/work 
  Test:
 /anaconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /anaconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac 
  Build:
source activate  /anaconda3/conda-bld/_build_env 

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/conda_build/environ.py", line 710, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 541, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 505, in solve_for_transaction
    force_remove, force_reinstall)
  File "/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 438, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 318, in solve_final_state
    conflicting_specs = r.get_conflicting_specs(tuple(final_environment_specs))
  File "/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 705, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 254, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 172, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - empyrical[version='>=0.4.3']
  - lru-dict[version='>=1.1.4']
  - intervaltree[version='>=2.1.0']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 2168, in build_tree
    notest=notest,
  File "/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1325, in build
    raise e
  File "/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1316, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/anaconda3/lib/python3.6/site-packages/conda_build/environ.py", line 712, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {"empyrical[version='>=0.4.3']", "lru-dict[version='>=1.1.4']", "intervaltree[version='>=2.1.0']"}

# Anything else?
P.S. In zipline/conda/ta-lib/build.sh, it would be nice to detect OSX and use 'curl' on line 2 instead of 'wget' which is not installed by default and requires a build of openssl and wget from source.

Sincerely and thank you,
Steven

**Comment by richafrank** [comment]
Hi @waldren , it looks like you haven't told conda-build where to find these dependencies, which don't come with the standard anaconda package. If you want to use packages from Quantopian's main channel, then you should run `conda build zipline -c quantopian`, like [we do on zipline CI](https://github.com/quantopian/zipline/blob/fa8b6ed46e73e38801c45f450daf356df70bf1c5/.travis.yml#L73).

**Comment by waldren** [comment]
Quantopian channel does not have Zipline 1.2. 

I did run conda build on those depenences. Had to run with --no-test for empyrical due to panda-reader issue.

Seems to work now. Thanks

**Comment by richafrank** [comment]
Oh, thanks for the heads up about zipline 1.2 for OSX. We don't have automated CI for OSX yet... 

I built/uploaded the recent OSX packages (zipline, empyrical) just now, which includes a fix for the pandas-datareader issue.
