### ISSUE TITLE
Utilize ta-lib pandas.DataFrame support

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#222]
With this commit, https://github.com/mrjbq7/ta-lib/commit/9ddcfe7625af1feeb03d1ca63ef19703465953fe, the ta-lib library now supports using a DataFrame directly.

Our internal support for the ta-lib wrapper should migrate to using this directly, instead of creating a dictionary to pass along to the ta-lib module.

**Comment by llllllllll** [comment]
we no longer have talib wrapper

**Comment by femtotrader** [comment]
I'd be please to know how you support technical analysis indicators ?
Is it pure Pandas now ?

**Comment by llllllllll** [comment]
We removed the idea of transforms so zipline does not use talib at all. Users have the option of passing the results of `data.history` (formerly `zipline.api.history`) to any of the talib functions and using the results like normal. A project we are ironing out now with the hope of working on at our PyCon sprint is adding technical analysis features to the pipeline api.
