### ISSUE TITLE
zipline NYSE calendar date issue - 2015-12-24 is missing

### ISSUE THREAD

**Issue by ayxemma** [quantopian/zipline#2227]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux 4.4.0-112-generic # 135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 3.5.5 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: `$ pip freeze` or `$ conda list`
# Name                    Version                   Build  Channel
alembic                   0.9.9                     <pip>
backcall                  0.1.0                     <pip>
backcall                  0.1.0                    py35_0
bcolz                     0.12.1                    <pip>
bleach                    2.1.3                    py35_0
Bottleneck                1.2.1                     <pip>
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py35_0
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.28.3                    <pip>
dbus                      1.13.2               h714fa37_1
decorator                 4.3.0                    py35_0
decorator                 4.3.0                     <pip>
empyrical                 0.5.0                     <pip>
entrypoints               0.2.3            py35h48174a2_2
et-xmlfile                1.0.1                     <pip>
expat                     2.2.5                he0dffb1_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_0
glib                      2.56.1               h000015b_0
gmp                       6.1.2                h6c8ec71_1
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
h5py                      2.8.0                     <pip>
html5lib                  1.0.1            py35h2f9c1c0_0
icu                       58.2                 h9c2bf20_1
idna                      2.7                       <pip>
intel-openmp              2018.0.3                      0
intervaltree              2.1.0                     <pip>
ipykernel                 4.8.2                    py35_0
ipython                   6.4.0                    py35_0
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0            py35hc9e07d0_0
ipywidgets                7.2.1                    py35_0
jdcal                     1.4                       <pip>
jedi                      0.12.0                    <pip>
jedi                      0.12.0                   py35_1
jinja2                    2.10             py35h480ab6d_0
joblib                    0.11                      <pip>
jpeg                      9b                   h024ee3a_2
jsonschema                2.6.0            py35h4395190_0
jupyter                   1.0.0                    py35_4
jupyter_client            5.2.3                    py35_0
jupyter_console           5.2.0            py35h4044a63_1
jupyter_core              4.4.0            py35ha89e94b_0
kiwisolver                1.0.1                     <pip>
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 7.2.0                hdf63c60_3
libpng                    1.6.34               hb9fc6fc_0
libsodium                 1.0.16               h1bed415_0
libstdcxx-ng              7.2.0                hdf63c60_3
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.8                h26e45fe_1
Logbook                   1.4.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
markupsafe                1.0              py35h4f4fcf6_1
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2                     <pip>
mistune                   0.8.3            py35h14c3975_1
mkl                       2018.0.3                      1
mkl-service               1.1.2            py35h0fc7090_4
multipledispatch          0.5.0                     <pip>
nbconvert                 5.3.1            py35hc5194e3_0
nbformat                  4.4.0            py35h12e6e07_0
ncurses                   6.1                  hf484d3e_0
networkx                  1.11                      <pip>
notebook                  5.5.0                    py35_0
numexpr                   2.6.5                     <pip>
numpy                     1.14.5                    <pip>
openpyxl                  2.5.4                     <pip>
openssl                   1.0.2o               h20670df_0
pandas                    0.19.1                    <pip>
pandas-datareader         0.5.0                     <pip>
pandoc                    1.19.2.1             hea2e7c5_1
pandocfilters             1.4.2            py35h1565a15_1
parso                     0.2.1                    py35_0
patsy                     0.5.0                     <pip>
pcre                      8.42                 h439df22_0
pexpect                   4.6.0                    py35_0
pickleshare               0.7.4                     <pip>
pickleshare               0.7.4            py35hd57304d_0
pip                       10.0.1                   py35_0
prompt-toolkit            1.0.15                    <pip>
prompt_toolkit            1.0.15           py35hc09de7a_0
ptyprocess                0.5.2                     <pip>
ptyprocess                0.5.2            py35h38ce0a3_0
pyfolio                   0.8.0                     <pip>
pygments                  2.2.0            py35h0f41973_0
Pygments                  2.2.0                     <pip>
pymc3                     3.4.1                     <pip>
pyparsing                 2.2.0                     <pip>
pyqt                      5.9.2            py35h751905a_0
python                    3.5.5                hc3d631a_4
python-dateutil           2.7.3                    py35_0
python-editor             1.0.3                     <pip>
pytz                      2018.4                    <pip>
pyzmq                     17.0.0           py35h14c3975_0
qt                        5.9.6                h52aff34_0
qtconsole                 4.3.1            py35h4626a06_0
readline                  7.0                  ha6073c6_4
requests                  2.19.1                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
scikit-learn              0.19.1                    <pip>
scipy                     1.1.0                     <pip>
seaborn                   0.8.1                     <pip>
send2trash                1.5.0                    py35_0
setuptools                39.2.0                   py35_0
simplegeneric             0.8.1                    py35_2
simplegeneric             0.8.1                     <pip>
sip                       4.19.8           py35hf484d3e_0
six                       1.11.0                    <pip>
six                       1.11.0           py35h423b573_1
sortedcontainers          2.0.4                     <pip>
SQLAlchemy                1.2.8                     <pip>
sqlite                    3.24.0               h84994c4_0
statsmodels               0.9.0                     <pip>
tables                    3.4.4                     <pip>
terminado                 0.8.1                    py35_1
testpath                  0.3.1            py35had42eaf_0
Theano                    1.0.2                     <pip>
tk                        8.6.7                hc745277_3
toolz                     0.9.0                     <pip>
tornado                   5.0.2                    py35_0
tqdm                      4.23.4                    <pip>
traitlets                 4.3.2                     <pip>
traitlets                 4.3.2            py35ha522a97_0
urllib3                   1.23                      <pip>
wcwidth                   0.1.7            py35hcd08066_0
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1            py35hb6cf162_1
wheel                     0.31.1                   py35_0
widgetsnbextension        3.2.1                    py35_0
xlrd                      1.1.0                     <pip>
xz                        5.2.4                h14c3975_4
zeromq                    4.2.5                h439df22_0
zipline                   1.2.0                     <pip>
zlib                      1.2.11               ha838bed_2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
i use `context.tday=get_datetime().date()` to get the backtest date when run backtest as of each date under function `def before_trading(context, data):` and record `context.tday` by running:
```
def record_vars(context, data):
    """
    This function is called at the end of each day and plots certain variables.
    """
    record(leverage=context.account.leverage, dailypos=context.portfolio.positions, tday=context.tday)

```
it is supposed that the variable records each trading day under NYSE calendar (the calendar i set in TradingAlgorithm as:
```
    perf = TradingAlgorithm(
        env=env,
        trading_calendar=get_calendar("NYSE"),
        sim_params=create_simulation_parameters(
            start=start,
            end=end,
            capital_base=CAPITAL_BASE,
            trading_calendar=get_calendar("NYSE"),
            data_frequency='daily'
        ),
        **{
            'initialize': initialize,
            'handle_data': handle_data,
#            'before_trading_start': before_trading,
            'analyze': analyze,
        }
    ).run(data, overwrite_sim_params=False)
```
* What happened instead?
but for date 2015-12-24   0:00:00, it returns 2015-12-23, which is not right:

  | tday
-- | --
2015-12-17   0:00:00 | 2015-12-17
2015-12-18   0:00:00 | 2015-12-18
2015-12-21   0:00:00 | 2015-12-21
2015-12-22   0:00:00 | 2015-12-22
2015-12-23   0:00:00 | 2015-12-23
2015-12-24   0:00:00 | 2015-12-23
2015-12-28   0:00:00 | 2015-12-28
2015-12-29   0:00:00 | 2015-12-29
2015-12-30   0:00:00 | 2015-12-30
2015-12-31   0:00:00 | 2015-12-31

--

--

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

just create an algo where at each day you record the date as above.
...

## What steps have you taken to resolve this already?
i tried placing an order on 12/23/2015, since i use daily data, the order is executed on 12/24/2015, so it means the date does exsit i think, just somehow when using the function to get it `context.tday=get_datetime().date()` it does not reflect correctly.
...

...

Sincerely,
ccbttn

**Comment by ssanderson** [comment]
hi @ayxemma!

I can't reproduce this issue on master with the following script:

```python
# repro.py

import pandas as pd

from zipline import run_algorithm
from zipline.api import get_datetime, record


def initialize(context):
    pass


def before_trading_start(context, data):
    record(tday=get_datetime())


result = run_algorithm(
    start=pd.Timestamp('2014-12-01', tz='UTC'),
    end=pd.Timestamp('2015-01-02', tz='UTC'),
    initialize=initialize,
    capital_base=10000,
    before_trading_start=before_trading_start,
    bundle='quandl',
)

print result.tday
```

(Note I ran this after running `zipline ingest -b quandl` with an API key exported.)

For me, running this script produces the following:

```
$ python repro.py
2014-12-01 21:00:00+00:00   2014-12-01 13:45:00+00:00
2014-12-02 21:00:00+00:00   2014-12-02 13:45:00+00:00
2014-12-03 21:00:00+00:00   2014-12-03 13:45:00+00:00
2014-12-04 21:00:00+00:00   2014-12-04 13:45:00+00:00
2014-12-05 21:00:00+00:00   2014-12-05 13:45:00+00:00
2014-12-08 21:00:00+00:00   2014-12-08 13:45:00+00:00
2014-12-09 21:00:00+00:00   2014-12-09 13:45:00+00:00
2014-12-10 21:00:00+00:00   2014-12-10 13:45:00+00:00
2014-12-11 21:00:00+00:00   2014-12-11 13:45:00+00:00
2014-12-12 21:00:00+00:00   2014-12-12 13:45:00+00:00
2014-12-15 21:00:00+00:00   2014-12-15 13:45:00+00:00
2014-12-16 21:00:00+00:00   2014-12-16 13:45:00+00:00
2014-12-17 21:00:00+00:00   2014-12-17 13:45:00+00:00
2014-12-18 21:00:00+00:00   2014-12-18 13:45:00+00:00
2014-12-19 21:00:00+00:00   2014-12-19 13:45:00+00:00
2014-12-22 21:00:00+00:00   2014-12-22 13:45:00+00:00
2014-12-23 21:00:00+00:00   2014-12-23 13:45:00+00:00
2014-12-24 18:00:00+00:00   2014-12-24 13:45:00+00:00
2014-12-26 21:00:00+00:00   2014-12-26 13:45:00+00:00
2014-12-29 21:00:00+00:00   2014-12-29 13:45:00+00:00
2014-12-30 21:00:00+00:00   2014-12-30 13:45:00+00:00
2014-12-31 21:00:00+00:00   2014-12-31 13:45:00+00:00
2015-01-02 21:00:00+00:00   2015-01-02 13:45:00+00:00
Name: tday, dtype: datetime64[ns, UTC]
```

You'll notice that the recorded variable entry for 2014-12-24 shows up with a timestamp that's 3 hours earlier than the other days, because the day before christmas is a half day, but otherwise that day works just like a normal trading day.

Are you by any chance using `schedule_function` to schedule your `record` calls? If so, are you passing `half_days=False`? That would cause your function to not run on the 24th, which would cause us to forward-fill the recorded values from the previous day when reporting results.
