### ISSUE TITLE
No price data after 2018-03-27 on different computer

### ISSUE THREAD

**Issue by BenjiKCF** [quantopian/zipline#2238]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Windows 10
* Python Version: `python 3.5`
* Python Bitness: `64`
* How did you install Zipline: (`conda`)
* Python packages: `
#
# Name                    Version                   Build  Channel
alembic                   0.7.7                    py35_0    Quantopian
asn1crypto                0.24.0                   py35_0
backcall                  0.1.0                    py35_0
bcolz                     0.12.1              np111py35_0    Quantopian
bleach                    2.1.3                    py35_0
blosc                     1.14.3               he51fdeb_0
bottleneck                1.2.1            py35h8a3671c_0
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py35_0
cffi                      1.11.5           py35h945400d_0
chardet                   3.0.4            py35h177e1b7_1
click                     6.7              py35h10df73f_0
colorama                  0.3.9            py35h32a752f_0
contextlib2               0.5.5            py35h0a97e54_0
cryptography              2.2.2            py35hfa6e2cd_0
cycler                    0.10.0           py35hcc71164_0
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.3           py35hfa6e2cd_0
decorator                 4.3.0                    py35_0
empyrical                 0.4.3                    py35_0    Quantopian
entrypoints               0.2.3            py35hb91ced9_2
freetype                  2.8                  h51f8f2c_1
hdf5                      1.10.2               hac2f561_1
html5lib                  1.0.1            py35h047fa9f_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py35_0
intel-openmp              2018.0.3                      0
intervaltree              2.1.0                    py35_0    Quantopian
ipykernel                 4.8.2                    py35_0
ipython                   6.4.0                    py35_0
ipython_genutils          0.2.0            py35ha709e79_0
ipywidgets                7.2.1                    py35_0
jedi                      0.12.0                   py35_1
jinja2                    2.10             py35hdf652bb_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py35h27d56d3_0
jupyter                   1.0.0                    py35_4
jupyter_client            5.2.3                    py35_0
jupyter_console           5.2.0            py35hf76c22e_1
jupyter_core              4.4.0            py35h629ba7f_0
kiwisolver                1.0.1            py35hc605aed_0
libpng                    1.6.34               h79bbb47_0
libsodium                 1.0.16               h9d3ae62_0
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.0.7            py35ha146b58_0
markupsafe                1.0              py35hc253e08_1
matplotlib                2.2.2            py35h153e9ff_1
mistune                   0.8.3            py35hfa6e2cd_1
mkl                       2018.0.3                      1
msys2-conda-epoch         20160418                      1
multipledispatch          0.5.0                    py35_0
nbconvert                 5.3.1            py35h98d6c46_0
nbformat                  4.4.0            py35h908c9d9_0
networkx                  1.11             py35h097edc8_0
notebook                  5.5.0                    py35_0
numexpr                   2.6.5            py35hcd2f87e_0
numpy                     1.11.3           py35h4a99626_4
openssl                   1.0.2o               h8ea7d77_0
pandas                    0.18.1              np111py35_0
pandas-datareader         0.5.0                    py35_0
pandoc                    2.2.1                h1a437c5_0
pandocfilters             1.4.2            py35h978f723_1
parso                     0.2.1                    py35_0
patsy                     0.5.0                    py35_0
pickleshare               0.7.4            py35h2f9f535_0
pip                       10.0.1                   py35_0
prompt_toolkit            1.0.15           py35h89c7cb4_0
pycparser                 2.18             py35h15a15da_1
pygments                  2.2.0            py35h24c0941_0
pyopenssl                 18.0.0                   py35_0
pyparsing                 2.2.0            py35hcabcaab_1
pyqt                      5.9.2            py35h1aa27d4_0
pysocks                   1.6.8                    py35_0
pytables                  3.4.4            py35he6f6034_0
python                    3.5.5                h0c2934d_2
python-dateutil           2.7.3                    py35_0
pytz                      2018.5                   py35_0
pywinpty                  0.5.4                    py35_0
pyzmq                     17.0.0           py35hfa6e2cd_1
qt                        5.9.6            vc14h62aca36_0
qtconsole                 4.3.1            py35hc47b0dd_0
requests                  2.19.1                   py35_0
requests-file             1.4.3                    py35_0
requests-ftp              0.3.1                    py35_0
scipy                     1.1.0            py35h672f292_0
send2trash                1.5.0                    py35_0
setuptools                39.2.0                   py35_0
simplegeneric             0.8.1                    py35_2
sip                       4.19.8           py35h6538335_0
six                       1.11.0           py35hc1da2df_1
snappy                    1.1.7                h777316e_3
sortedcontainers          1.4.4                    py35_0    Quantopian
sqlalchemy                1.2.8            py35hfa6e2cd_0
sqlite                    3.24.0               h7602738_0
statsmodels               0.9.0            py35h452e1ab_0
terminado                 0.8.1                    py35_1
testpath                  0.3.1            py35h06cf69e_0
toolz                     0.9.0                    py35_0
tornado                   5.0.2                    py35_0
traitlets                 4.3.2            py35h09b975b_0
urllib3                   1.23                     py35_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7            py35h6e80d8a_0
webencodings              0.5.1            py35h5d527fb_1
wheel                     0.31.1                   py35_0
widgetsnbextension        3.2.1                    py35_0
win_inet_pton             1.0.1            py35hbef1270_1
win_unicode_console       0.5              py35h56988b5_0
wincertstore              0.2              py35hfebbdb8_0
winpty                    0.4.3                         4
zeromq                    4.2.5                hc6251cf_0
zipline                   1.2.0               np111py35_0    Quantopian
zlib                      1.2.11               h8395fce_2
`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?
After I use zipline ingest, I run the tutorial code for jupyter notebook, it ran well except the price data after 2018-03-27 are all Nan. I have tried to install zipline on different computers but the problem persists.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps
I have the following cells in the jupyter notebook and this happens
```
%load_ext zipline
from zipline.api import order, record, symbol, sid
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style

def initialize(context):
    pass


def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data.current(symbol('AAPL'), 'price'))

%zipline --start 2017-7-1 --end 2018-7-9 -o backtest.pickle
backtest_df = pd.read_pickle("backtest.pickle")
backtest_df.AAPL.dropna(axis=0, inplace=True)
backtest_df.AAPL.tail()
```
`2018-03-21 20:00:00+00:00    171.270
2018-03-22 20:00:00+00:00    168.845
2018-03-23 20:00:00+00:00    164.940
2018-03-26 20:00:00+00:00    172.770
2018-03-27 20:00:00+00:00    168.340
Name: AAPL, dtype: float64
`

...

## What steps have you taken to resolve this already?
I have tried it on different computer and the problem appears again. I have tried it on quantopian but the data on quantopian seems to be working fine.
...

# Anything else?
Thank you so much

...

Sincerely,
`$ whoami`

**Comment by freddiev4** [comment]
Hi @BenjiKCF this is expected behavior as Quandl stopped updating their bundle, so if you need more pricing data then you're going to need to write your own bundle until we have the opportunity / time to build a new default bundle; see https://github.com/quantopian/zipline/issues/2145

The amount of pricing data available already, I believe, is plenty of data to do in / out-of-sample backtesting.

Going to close this issue as well.
