### ISSUE TITLE
is it passible to backtest other frequency data such as 3minutes, 5minutes frequency

### ISSUE THREAD

**Issue by studyquant** [quantopian/zipline#2271]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python 3.5
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`) pip install zipline ==1.2.0
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
is it passible to backtest other frequency data such as 3minutes, 5minutes frequency?
* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...
## What steps have you taken to resolve this already?
...
# Anything else?
...
Sincerely,
`$ whoami`

**Comment by freddiev4** [comment]
Hey @studyquant there was some discussion about that here https://github.com/quantopian/zipline/issues/1960; going to close this issue and defer conversation to the one I linked.
