### ISSUE TITLE
Unable to import zipline ; pandas error 'Index must be monotonic increasing or decreasing'

### ISSUE THREAD

**Issue by FrostyKirin** [quantopian/zipline#2276]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Ubuntu 18.04
* Python Version:  python 3.6
* Python Bitness: 64bits
* How did you install Zipline: pip, then conda, then locally
* Python packages: 

<details>
alembic==0.7.7
asn1crypto==0.24.0
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2018.8.13
cffi==1.11.5
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cryptography==2.3
cryptography-vectors==2.3
cvxopt==1.2.0
cyordereddict==0.2.2
Cython==0.28.5
decorator==4.3.0
empyrical==0.5.0
idna==2.7
intervaltree==2.1.0
Logbook==0.12.5
lru-dict==1.1.4
lxml==4.2.4
Mako==1.0.7
MarkupSafe==1.0
multipledispatch==0.6.0
networkx==1.11
numexpr==2.6.1
numpy==1.14.2
pandas==0.22.0
pandas-datareader==0.6.0
patsy==0.5.0
pycparser==2.18
pyOpenSSL==18.0.0
PySocks==1.6.8
python-dateutil==2.7.3
pytz==2018.5
requests==2.19.1
requests-file==1.4.3
requests-ftp==0.3.1
scipy==1.1.0
six==1.11.0
sortedcontainers==1.4.4
SQLAlchemy==1.2.10
statsmodels==0.9.0
tables==3.4.4
toolz==0.9.0
trading-calendars==1.0.1
urllib3==1.23
wrapt==1.10.11
zipline==1.3.0

</details>

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# I am unable to import zipline ; whenever I try to import zipline or any of its packages, I get an error

* What did you expect to happen?

That the package would be imported

* What happened instead?

I got an error, coming from pandas : "Index must be monotonic increasing or decreasing"

Here's the whole error stack :

 <details>

ValueError                                Traceback (most recent call last)
<ipython-input-28-e2fb147858eb> in <module>()
----> 4 import zipline
      5 
      6 from zipline.api import (history)

/opt/anaconda/anaconda3/lib/python3.6/site-packages/zipline/__init__.py in <module>()
     27 from .utils.numpy_utils import numpy_version
     28 from .utils.pandas_utils import new_pandas
---> 29 from .utils.run_algo import run_algorithm
     30 from ._version import get_versions
     31 

/opt/anaconda/anaconda3/lib/python3.6/site-packages/zipline/utils/run_algo.py in <module>()
     18 from zipline.data import bundles
     19 from zipline.data.data_portal import DataPortal
---> 20 from zipline.finance import metrics
     21 from zipline.finance.trading import TradingEnvironment
     22 from zipline.pipeline.data import USEquityPricing

/opt/anaconda/anaconda3/lib/python3.6/site-packages/zipline/finance/metrics/__init__.py in <module>()
     41     _ClassicRiskMetrics,
     42 )
---> 43 from .tracker import MetricsTracker
     44 
     45 

/opt/anaconda/anaconda3/lib/python3.6/site-packages/zipline/finance/metrics/tracker.py in <module>()
     17 import logbook
     18 
---> 19 from ..ledger import Ledger
     20 from zipline.utils.exploding_object import NamedExplodingObject
     21 

/opt/anaconda/anaconda3/lib/python3.6/site-packages/zipline/finance/ledger.py in <module>()
     26 
     27 from zipline.assets import Future
---> 28 from zipline.finance.transaction import Transaction
     29 import zipline.protocol as zp
     30 from zipline.utils.sentinel import sentinel

/opt/anaconda/anaconda3/lib/python3.6/site-packages/zipline/finance/transaction.py in <module>()
     18 
     19 from zipline.assets import Asset
---> 20 from zipline.protocol import DATASOURCE_TYPE
     21 from zipline.utils.input_validation import expect_types
     22 

/opt/anaconda/anaconda3/lib/python3.6/site-packages/zipline/protocol.py in <module>()
     18 
     19 from .assets import Asset
---> 20 from .utils.enum import enum
     21 from ._protocol import BarData, InnerPosition  # noqa
     22 

/opt/anaconda/anaconda3/lib/python3.6/site-packages/zipline/utils/enum.py in <module>()
     41     pd.Series(_inttypes_map).reindex(
     42         range(max(_inttypes_map.keys())),
---> 43         method='bfill',
     44     ),
     45 )

/opt/anaconda/anaconda3/lib/python3.6/site-packages/pandas/core/series.py in reindex(self, index, **kwargs)

/opt/anaconda/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   3683 
   3684         Parameters
-> 3685         ----------
   3686         inplace : boolean, default False
   3687             If False return new object, otherwise modify existing object

/opt/anaconda/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   3696         else:
   3697             f = lambda: self._data.consolidate()
-> 3698             cons_data = self._protect_consolidate(f)
   3699             return self._constructor(cons_data).__finalize__(self)
   3700 

/opt/anaconda/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in reindex(self, target, method, level, limit, tolerance)
   3603             if isinstance(slc, np.ndarray):
   3604                 raise KeyError("Cannot get %s slice bound for non-unique "
-> 3605                                "label: %r" % (side, original_label))
   3606 
   3607         if isinstance(slc, slice):

/opt/anaconda/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_indexer(self, target, method, limit, tolerance)
   3231 
   3232         left_idx, right_idx = _get_join_indexers([self._values],
-> 3233                                                  [other._values], how=how,
   3234                                                  sort=True)
   3235 

/opt/anaconda/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in _get_fill_indexer(self, target, method, limit, tolerance)
   3261         def _get_leaf_sorter(labels):
   3262             """
-> 3263             returns sorter for the inner most level while preserving the
   3264             order of higher levels
   3265             """

/opt/anaconda/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in _get_fill_indexer_searchsorted(self, target, method, limit)
   3283 
   3284         if isinstance(self, MultiIndex) and isinstance(other, MultiIndex):
-> 3285             raise TypeError('Join on level between two MultiIndex objects '
   3286                             'is ambiguous')
   3287 

/opt/anaconda/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in _searchsorted_monotonic(self, label, side)
   4181     See Also
   4182     --------
-> 4183     _ensure_index_from_sequences
   4184     """
   4185     if isinstance(index_like, Index):

ValueError: index must be monotonic increasing or decreasing`

</details>

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Import zipline
2. That's all folks

## What steps have you taken to resolve this already?

I tried to install zipline with conda (`conda install -c Quantopian zipline`) and through a little hack with jupyter (`import sys
!{sys.executable} -m pip install zipline`), but nothing worked although the packages got properly installed. 

I completely wiped anaconda and reinstalled it, without effect.

I also tried to import only one function out of the library, but I get the exact same error. No one else on the internet seems to have encountered the same problem, and to be honest, I'm out of ideas to solve this one

# The End

Thank you for your work on this very nice library, I hope we can solve this problem :)

Sincerely,

Frost

**Comment by freddiev4** [comment]
Hi @FrostyKirin, have you tried installing in a [Py35 conda env](http://www.zipline.io/install.html#installing-with-conda)? We don't yet build packages for Python 3.6
