### ISSUE TITLE
Adding a Zipline Binder?

### ISSUE THREAD

**Issue by freddiev4** [quantopian/zipline#2277]
I was just looking through some JupyterLab repos (among others) and was reminded of [Binder](https://mybinder.org/). I think it'd be pretty cool to have a Binder in the README for people to play around with Zipline's beginner tutorial before they decide whether or not they'd like to install it. 

![image](https://user-images.githubusercontent.com/8339018/44535485-16bdaf00-a6c8-11e8-9326-29a8501087aa.png)

![image](https://user-images.githubusercontent.com/8339018/44535529-3523aa80-a6c8-11e8-8670-8d8311061b10.png)

Thoughts @richafrank @ssanderson @llllllllll?

**Comment by fawce** [comment]
closing because:
- zipline is very data intensive and not a great fit for ephemeral notebooks
- quantopian is free hosted zipline :)
