### ISSUE TITLE
Error with $ zipline run --help (macOS)

### ISSUE THREAD

**Issue by github1github2** [quantopian/zipline#2280]
Dear Zipline Maintainers,

# Environment

macOS High Sierra
Python 3.7.0
64
pip3
$ pip3 freeze:
certifi==2018.8.24
pipenv==2018.7.1
virtualenv==16.0.0
virtualenv-clone==0.3.0

</details>
Installed zipline with:
$ brew install freetype pkg-config gcc openssl

here are the results after running the command a second time (it looks good from what I see):

Warning: freetype 2.9.1 is already installed and up-to-date
To reinstall 2.9.1, run `brew reinstall freetype`
Warning: pkg-config 0.29.2 is already installed and up-to-date
To reinstall 0.29.2, run `brew reinstall pkg-config`
Warning: gcc 8.2.0 is already installed and up-to-date
To reinstall 8.2.0, run `brew reinstall gcc`
Warning: openssl 1.0.2p is already installed and up-to-date
To reinstall 1.0.2p, run `brew reinstall openssl`

The issue:

$ zipline run --help
-bash: $: command not found

I tried running this, per another closed issue #1495 :

python -m zipline
/usr/bin/python: No module named zipline

It appears zipline wasn't installed. 

Any thoughts on how to get zipline run -- help running?

Sincerely,
github1github2

**Comment by freddiev4** [comment]
Also, it looks like you didn't actually install Zipline. Hmebrew only gets you the C dependencies you need; it does not install Zipline. You need to run `pip install zipline`.

**Comment by github1github2** [comment]
Hi @freddiev4.  Sorry, I missed a couple steps i forgot to mention.  Here is what I get with:

$ pip install zipline
-bash: pip: command not found

So, I tried this:

**Comment by github1github2** [comment]
just an update, homebrew installed 

$ python3 --version
Python 3.7.0
$ pip --version
-bash: pip: command not found
$ pip3 --version
pip 18.0 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

Do you, by chance, know which version of pip is supported? I suspect this may be causing an issue since i have both Python 2.7 and 3.7 installed.

**Comment by github1github2** [comment]
I solved my own issue.  Here is a reference for anyone else that runs into the same problem.  My macbook pro came with python 2.7, but didn't have pip.  So, even though pip3 was within python3, it wasn't running the zipline install because i assume (as mentioned above) python3.7 isn't currently supported.  So, download the pip standalone using:

$ easy_install pip

or if you are restricted:

$ sudo easy_install pip

and then 

$ pip install zipline 

will work.
