### ISSUE TITLE
Docstring error

### ISSUE THREAD

**Issue by marketneutral** [quantopian/zipline#2297]
This is super tiny, but the docstring is wrong here:

https://github.com/quantopian/zipline/blob/master/zipline/finance/slippage.py#L346

`self._get_window_data` (correctly) returns the volatility of daily **returns**, not volume.

**Comment by freddiev4** [comment]
That sounds / looks right to me. Opened a PR: https://github.com/quantopian/zipline/pull/2318

**Comment by freddiev4** [comment]
Just merged :)

**Comment by tapaswenipathak** [comment]
Hey folks: Can I PR? I think the ticket has a PR.

**Comment by fawce** [comment]
Code is fixed, closing despite a lack of a release.
