### ISSUE TITLE
NameError: global name 'add_history' is not defined

### ISSUE THREAD

**Issue by ahmedalkordy** [quantopian/zipline#2310]
i have this error and I want to solve it 
https://www.quantopian.com/algorithms/5bae46412b5091004497ef1b

import pandas as pd

def initialize(context):  
    context.i = 0  
    context.window = 5
    context.csi_hist = {}
    url = 'https://raw.githubusercontent.com/solverf/QuantEx/master/csi300_data.csv'  
    fetch_csv(url, mask=False, symbol='CSI300') 
    # Since you are fetching a non-security field, the universe
    # will be empty without specifying a symbol. As a result, your
    # handle data will never be called. Here, I work around this bug
    # by setting the benchmark to SPY.
    set_benchmark(symbol('SPY'))
    add_history(4, '1d', 'high')  
    add_history(4, '1d', 'low')
    
def handle_data(context, data):
    
 
    # history only applies to trade bars we supply.
    # here i'm accumulating a history of csi in a dict
    if 'CSI300' in data:
        context.csi_hist[get_datetime()] = \
            {'high':data['CSI300']['high'], 'low':data['CSI300']['low']}
    # Skip first 4 days to get full windows
    context.i += 1  
    if context.i < context.window:  
        return
    
    # make a dataframe of the csi300
    csi_df = pd.DataFrame.from_dict(context.csi_hist, orient='index')
    # merge the fields from the csi_df into the trade history
    # the result will mask the csi df with the history window
    high_hist = history(4, '1d', 'high')
    high_hist['CSI300'] = csi_df['high']
    log.info("\n {h}".format(h=high_hist))
    low_hist = history(4, '1d', 'low')
    low_hist['CSI300'] = csi_df['low']
    
    
    # delete the oldest date from the csi history
    # to prevent monotonic growth in the dict
    earliest_date = low_hist.index[0]
    del context.csi_hist[earliest_date]

**Comment by richafrank** [comment]
Hi @ahmedalkordy , take a look at the discussion in https://github.com/quantopian/zipline/issues/1286  - hopefully that has enough info.

**Comment by ahmedalkordy** [comment]
thanks @richafrank
