### ISSUE TITLE
No where to change benchmark? 

### ISSUE THREAD

**Issue by liyi-1989** [quantopian/zipline#2311]
Say, I am using v1.3.0 and trying to use `zipline.run_algorithm()` to run the algorithm. If I do not change the source code, I cannot find a way to change the benchmark.

1. In the [run_algo() source code](https://github.com/quantopian/zipline/blob/v1.3.0/zipline/utils/run_algo.py#L206), it essentially creates a `TradingAlgorithm` object by inputing an `env` variable.

2. This `env` variable, [defined in the function body](https://github.com/quantopian/zipline/blob/v1.3.0/zipline/utils/run_algo.py#L154-L160), is created without explicitly giving the `bm_symbol` argument.

3. Based on [the definition of the `TradingEnvironment` class](https://github.com/quantopian/zipline/blob/v1.3.0/zipline/finance/trading.py#L77), the `env` has the `bm_symbol` always equals to `SPY` by default (and `load` variable always equals to `None`).

4. In this way, [the `env.benchmark_return` property is thus (always) created](https://github.com/quantopian/zipline/blob/v1.3.0/zipline/finance/trading.py#L100-L104) by `bm_symbol='SPY'`. 

5. Thus, [when `TradingAlgorithm` uses it (env)](https://github.com/quantopian/zipline/blob/v1.3.0/zipline/algorithm.py#L557), it always uses the `benchmark_return` created by `SPY`.

(6. btw, adding `context.set_benchmark(symbol('XXX')) ` in the `initialize()` function is not useful, since it runs after the above environment process.)

So, it looks like the only way to change the benchmark from `SPY` to something else is to:
- change the code of `TradingEnvironment` class, the default of `bm_symbol`
- or, when creating the `env` variable in [run_algorithm() source code](https://github.com/quantopian/zipline/blob/v1.3.0/zipline/utils/run_algo.py#L206), explicitly add the `bm_symbol` argument. (and probably add a `bm_symbol` argument for the `run_algo` function)

(in either way, we have to change the source code)
Am I right?

**Comment by marketwiz** [comment]
Yes

**Comment by ssanderson** [comment]
Apologies for the slow reply to this issue. On Zipline master, you can now pass `benchmark_returns` or `benchmark_sid` to `TradingAlgorithm`. There's still no good way, however, to control the benchmark when running via the Zipline CLI. I'm tracking that issue in https://github.com/quantopian/zipline/issues/2627.
