### ISSUE TITLE
Error when installing with pip

### ISSUE THREAD

**Issue by morizmartiner** [quantopian/zipline#2314]
# Environment

<details>

* Operating System: OSX 10.13.6
* Python Version: 3.7.0
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages:

alpha-vantage==2.1.0
appnope==0.1.0
backcall==0.1.0
blosc==1.5.1
Bottleneck==1.2.1
certifi==2018.8.24
chardet==3.0.4
configparser==3.5.0
cycler==0.10.0
Cython==0.28.5
decorator==4.3.0
dill==0.2.8.2
empyrical==0.5.0
et-xmlfile==1.0.1
findatapy==0.5
fxcmpy==1.1.28
idna==2.7
inflection==0.3.1
ipython==7.0.1
ipython-genutils==0.2.0
jdcal==1.4
jedi==0.12.1
kiwisolver==1.0.1
llvmlite==0.25.0
lxml==4.2.5
matplotlib==3.0.0
more-itertools==4.3.0
multiprocess==0.70.6.1
multiprocessing-on-dill==3.5.0a4
numba==0.40.0
numpy==1.15.2
oauthlib==2.1.0
openpyxl==2.5.8
pandas==0.23.4
pandas-datareader==0.7.0
parso==0.3.1
pathos==0.2.2.1
patsy==0.5.0
pexpect==4.6.0
pickleshare==0.7.5
pox==0.2.4
ppft==1.6.4.8
prompt-toolkit==2.0.5
ptyprocess==0.6.0
pyfolio==0.9.0
Pygments==2.2.0
pyparsing==2.2.2
python-dateutil==2.7.3
pytz==2018.5
Quandl==3.4.2
redis==2.10.6
requests==2.19.1
requests-oauthlib==1.0.0
scikit-learn==0.20.0
scipy==1.1.0
seaborn==0.9.0
simplegeneric==0.8.1
six==1.11.0
socketIO-client==0.7.2
statsmodels==0.9.0
TA-Lib==0.4.17
traitlets==4.3.2
twython==3.7.0
urllib3==1.23
wcwidth==0.1.7
websocket-client==0.53.0
wrapt==1.10.11

</details>

# Description of Issue

I am trying to install zipline with pip and I get the following error:

> Command "/Users/morizmartiner/Developer/Investing/Heijin/venv/bin/python -m pip install --ignore-installed --no-user --prefix /private/var/folders/p2/kngflz9j4wx6v7mry04trxwc0000gn/T/pip-build-env-tf725kve --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython "numpy==1.9.3; python_version=='3.5'" "numpy==1.12.1; python_version=='3.6'" "numpy==1.13.1; python_version>='3.7'"" failed with error code 1 in None

## Reproduction Steps

1. pip install biplane

## What steps have you taken to resolve this already?

brew install freetype pkg-config gcc openssl
pip install numpy cython

Sincerely,
Moriz Martiner

**Comment by freddiev4** [comment]
Hi @morizmartiner we don't yet build packages / test for Python 3.7, so you'll need to install in a Python 3.5 or Py27 virtualenv

**Comment by morizmartiner** [comment]
@freddiev4 Thank you, I changed version and it worked!
