### ISSUE TITLE
TWS Client Error - 509: Exception caught while reading socket - Not enough space

### ISSUE THREAD

**Issue by alexf321** [quantopian/zipline#2317]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

Windows 10 64-bit
Python 2.7.8
Python Bitness: 32
How did you install Zipline: egg, zipline-0.7.0-py2.7.egg
  - not the conventional way to install, but I have two other programs using this zipline package with no issues

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I expected all of my strategies to run but I am getting a Memory Error.
I am running multiple strategies, classes extended from `zipline.algorithm.TradingAlgorithm`, using `zipline.algorithm.TradingAlgorithm.run(datapanel)`. After completing the first one and in the middle of running the second one I get an error saying

"TWS Client Error - 509: Exception caught while reading socket - Not enough space"

Here is how you can reproduce this issue on your machine:

## Reproduction Steps
I can't give away the exact code as it's proprietary. 
1. Create n classes, each with own trading algorithm, inheriting from `zipline.algorithm.TradingAlgorithm` and extend the following methods:
  - initialize 
  - set_parameter 
  - handle_data
2. For each strategy, call `.run` concurrently with no code executed in between
3. Error will appear on second or later strategy run
...

## What steps have you taken to resolve this already?
I have spoken to a TWS API support tech extensively on this issue who said they didn't have any reference of this error nor how to solve it. We tried changing the API configurations settings for the TWS Desktop Client to no avail.

Of my n strategies, I have tested running each individually and they all execute correctly. It is only when running in succession are there issues.
...

# Anything else?
Stack trace from the console regarding the error:

`  TWS Client Error - 509: Exception caught while reading socket - Not enough space

  Traceback (most recent call last):

  File "C:\Users\Alex\Program\strategy.py", line 462, in Click_Good_Prices
    self.Run_Strategies()

  File "C:\Users\Alex\Program\strategy.py", line 482, in Run_Strategies
    self.calculate_strategies(self.strategies, self.datapanel)

  File "C:\Users\Alex\Program\strategy.py", line 535, in calculate_strategies
    result[name] = strat.run(datapanel)

  File "C:\Python27\lib\site-packages\zipline-0.7.0-py2.7.egg\zipline\algorithm.py", line 423, in run
    for perf in self.gen:

  File "C:\Python27\lib\site-packages\zipline-0.7.0-py2.7.egg\zipline\gens\tradesimulation.py", line 127, in transform
    self.algo.instant_fill,

  File "C:\Python27\lib\site-packages\zipline-0.7.0-py2.7.egg\zipline\gens\tradesimulation.py", line 227, in _process_snapshot
    return self.get_message(dt)

  File "C:\Python27\lib\site-packages\zipline-0.7.0-py2.7.egg\zipline\gens\tradesimulation.py", line 248, in get_message
    self.algo.perf_tracker.handle_market_close_daily()

  File "C:\Python27\lib\site-packages\zipline-0.7.0-py2.7.egg\zipline\finance\performance\tracker.py", line 423, in handle_market_close_daily
    daily_update = self.to_dict()

  File "C:\Python27\lib\site-packages\zipline-0.7.0-py2.7.egg\zipline\finance\performance\tracker.py", line 252, in to_dict
    _dict.update({'daily_perf': self.todays_performance.to_dict()})

  File "C:\Python27\lib\site-packages\zipline-0.7.0-py2.7.egg\zipline\finance\performance\period.py", line 378, in to_dict
    orders = [x.to_dict() for x in itervalues(self.orders_by_id)]

  File "C:\Python27\lib\site-packages\zipline-0.7.0-py2.7.egg\zipline\finance\blotter.py", line 228, in to_dict
    py = copy(self.__dict__)

  File "C:\Python27\lib\copy.py", line 76, in copy
    return copier(x)

  File "C:\Python27\lib\copy.py", line 114, in _copy_with_constructor
    return type(x)(x)

  MemoryError`
...

**Comment by freddiev4** [comment]
Hey @damianialex I'm not sure if any of the other maintainers have any thoughts, but we don't have anything built in to Zipline to connect to IB (TWS API), so it looks like you've written some code that wraps Zipline and connects to the API. It's hard to help debug without knowing what code you've added.

**Comment by freddiev4** [comment]
Also, I just noticed you're using Zipline 0.7. I'm not familiar with that early of a version of Zipline, so combining that with whatever proprietary code you wrote (and can't share) also makes helping debug here slightly harder.

FWIW, on my machine I have the following setup:

Zipline 1.3.0
Py2.7.10 and Py3.5 (virtualenvs)
8GB RAM

**Comment by damianialex** [comment]
@freddiev4 thanks a bunch for both responses. The reason I am using the old `TradingAlgorithm.run()` and an older version of zipline is due to this being legacy code written by my predecessor. Do you mind giving me an example of a replacement using the CLI like you mentioned?

I spoke to the TWS API tech rep for ~2 hours and he assured me it wasn't a TWS API issue as we went through every possible configuration he could think that could cause the issue. 

I also tried running the program on another PC with 200GB of memory free and 32GB of RAM and got the same issue unfortunately. Given I don't believe the memory issue concerns the PC itself, but some configuration setting in either Python or zipline. I have also tried installing the most recent version of Python 2.7 and rerunnning the program, but the issue was the same. 

Going off the stack trace though, it seems the issue resides with the zipline package. I am reluctant to upgrade as it means rewriting the code and I haven't been able to find good examples online detailing how to migrate code written using older versions of zipline to newer versions.

Here's a pared-down version of one of the strategies. 

    from zipline.algorithm import TradingAlgorithm
    from zipline.finance import commission
    from zipline.transforms import batch_transform
    from zipline.transforms import MovingAverage
    import pdb

    class StrategyA(TradingAlgorithm):

        '''
        The GoodWater implementation 
        '''

        def initialize(self, window_length=6, EPS= 1):
            self.stocks = ['XXX', 'XXX'] # changed
            self.window_length = window_length
            self.init = True
            self.days = 0
            self.add_transform(
                MovingAverage, 'kernel', ['price'], window_length=self.window_length)
            self._lambda = 1.0


        def set_parameter(self, dictionary):
            for k,v in dictionary.iteritems():
                setattr(self, k, v)

        def handle_data(self, data):

            if self.init:
                self.rebalance_portfolio(self.b_t)
                self.init = False
                return

            ''' calculations for positions and weights '''

            self.write_positions()

        def rebalance_portfolio(self, b):
            '''
            recalculating positions
            '''
            pass

        def write_positions(self):
            try:
                global_var.my_messenger.write(
                    "StrategyA", self.portfolio.positions, self.portfolio.portfolio_value)
            except NameError, e:
                print("Strategy can't catch my_messenger")
                pdb.set_trace()

**Comment by alexf321** [comment]
@freddiev4 if you could provide any additional help I'd really appreciate it.

**Comment by freddiev4** [comment]
@alexf321 I'll see if I can take a look this weekend

**Comment by freddiev4** [comment]
@alexf321 forgot to say: looked around that old version of Zipline a bit and nothing there convinces me that it's a Zipline issue. Also, the `TWS Client Error - 509:` is an error coming _from_ the TWS API, so I think that they're the only ones that can help you there. Could be a bug that they haven't yet discovered
