### ISSUE TITLE
Unused variables in several methods

### ISSUE THREAD

**Issue by willianpaixao** [quantopian/zipline#2321]
Dear Zipline Maintainers,

while working on a non-related issue, I stumbled upon several functions that have an unused argument. Is that for some backward compatibility? Is it safe to remove? Follow some examples:

`zipline/data/bundles/core.py:`
``` python
def adjustment_db_relative(bundle_name, timestr, environ=None):
    return bundle_name, timestr, 'adjustments.sqlite'

def adjustment_db_relative(bundle_name, timestr, environ=None):
    return bundle_name, timestr, 'adjustments.sqlite'
```

Here the variable `environ` will never be used.

**Comment by willianpaixao** [comment]
@freddiev4 any feedback?

**Comment by richafrank** [comment]
Hi @willianpaixao , great question. Sorry for the delayed response.

I agree - Those params do look to be unnecessary and safe to remove (updating the call sites as well). From looking at the [PR](https://github.com/quantopian/zipline/pull/1282) that added that code, I believe other changes there were all that were really necessary at the time, but we didn't notice.
