### ISSUE TITLE
c programming

### ISSUE THREAD

**Issue by ahmedalkordy** [quantopian/zipline#2330]
i have some issues in this code and I need to solve please I need help

#include <stdio.h>
#include <ctype.h>
int charClass;
char lexeme [100];
char nextChar;
int lexLen;
int token;
int nextToken;
FILE *in_fp, *fopen();
/* Function declarations */
void addChar();
void getChar();
void getNonBlank();
int lex();
/* Character classes */
#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99
/* Token codes */
#define INT_LIT 10
#define IDENT 11
#define ASSIGN 20
#define PLUS 21
#define MINUS 22
#define TIMES 23
#define DIV 24
#define LPAREN 25
#define RPAREN 26
void factor();
void term();
void stmt();
/* main driver */
main() {
/* Open the input data file and process its contents */
if ((in_fp = fopen("front.in", "r")) == NULL)
printf("ERROR - cannot open front.in \n");
else {
getChar();
do {
lex();
} while (nextToken != EOF);
}
}
/* lookup - a function to lookup operators and parentheses
and return the token */
int lookup(char ch) {
switch (ch) {
case '(':
addChar();
nextToken = LPAREN;
break;
case ')':
addChar();
nextToken = RPAREN;
break;
case '+':
addChar();
nextToken = PLUS;
break;
case '-':
addChar();
nextToken = MINUS;
break;
case '*':
addChar();
nextToken = TIMES;
break;
case '/':
addChar();
nextToken = DIV;
break;
default:
addChar();
nextToken = EOF;
break;
}
return nextToken;
}
/* addChar - a function to add nextChar to lexeme */
void addChar() {
if (lexLen <= 98) {
lexeme[lexLen++] = nextChar;
lexeme[lexLen] = 0;
}
else
printf("Error - lexeme is too long \n");
}
/* getChar - a function to get the next character of
input and determine its character class */
void getChar() {
if ((nextChar = getc(in_fp)) != EOF) {
if (isalpha(nextChar))
charClass = LETTER;
else if (isdigit(nextChar))
charClass = DIGIT;
else charClass = UNKNOWN;
}
else
charClass = EOF;
}
/* getNonBlank - a function to call getChar until it
returns a non-whitespace character */
void getNonBlank() {
while (isspace(nextChar))
getChar();
}
/* lex - a simple lexical analyzer for arithmetic
expressions */
int lex() {
lexLen = 0;
getNonBlank();
switch (charClass) {
/* Parse identifiers */
case LETTER:
addChar();
getChar();
while (charClass == LETTER || charClass == DIGIT) {
addChar();
getChar();
}
nextToken = IDENT;
break;
/* Parse integer literals */
case DIGIT:
addChar();
getChar();
while (charClass == DIGIT) {
addChar();
getChar();
}
nextToken = INT_LIT;
break;
/* Parentheses and operators */
case UNKNOWN:
lookup(nextChar);
getChar();
break;
/* EOF */
case EOF:
nextToken = EOF;
lexeme[0] = 'E';
lexeme[1] = 'O';
lexeme[2] = 'F';
lexeme[3] = 0;
break;
} /* End of switch */
printf("Next token is: %d, Next lexeme is %s\n",
nextToken, lexeme);
return nextToken;
} /* End of function lex */

/* term
Parses strings in the language generated by the rule:
<term> -> <factor> {(* | /) <factor>)
*/
void term() {
printf("Enter <term>\n");
/* Parse the first factor */
factor();
/* As long as the next token is * or /, get the
next token and parse the next factor */
while (nextToken == TIMES || nextToken == DIV) {
lex();
factor();
}
printf("Exit <term>\n");
} /* End of function term */

/* factor
Parses strings in the language generated by the rule:
<factor> -> id | int_constant | ( <expr )
*/
void factor() {
printf("Enter <factor>\n");
/* Determine which RHS */
if (nextToken == IDENT || nextToken == INT_LIT)
/* Get the next token */
lex();
/* If the RHS is ( <expr>), call lex to pass over the
left parenthesis, call expr, and check for the right
parenthesis */
else {
if (nextToken == LPAREN) {
lex();
expr();
if (nextToken == RPAREN)
lex();
else
error();
} /* End of if (nextToken == ... */
/* It was not an id, an integer literal, or a left
parenthesis */
else
error();
} /* End of else */
printf("Exit <factor>\n");;
} /* End of function factor */

/* stmt
Parses strings in the language generated by the rule:
<stmt> -> <term> {(+ | -) <term>}
*/
void stmt() {
printf("Enter <stmt>\n");
/* Parse the first term */
term();
/* As long as the next token is + or -, get
the next token and parse the next term */
while (nextToken == PLUS || nextToken == MINUS) {
lex();
term();
}
printf("Exit <stmt>\n");
} /* End of function expr */

**Comment by freddiev4** [comment]
Hey @ahmedalkordy considering this is unrelated to Zipline, and also looks like a homework question about building a parser (?), I'm going to go ahead and close this issue.



P.S., on a personal note I just finished a CS course in May about Programming Languages so... I understand your struggle

**Comment by ahmedalkordy** [comment]
it is a homework to implement a scanner and a parser for this simple language I need to solve it or find a suitable code
