### ISSUE TITLE
Zipline Tutorial - Cannot run sample algorithm - ValueError: SQLite file '...assets-6.sqlite' doesn't exist.

### ISSUE THREAD

**Issue by Tobiasniklasbecker** [quantopian/zipline#2335]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (MacOS)
* Python Version: `Python 3.5.6 : Anaconda, Inc.`
* Python Bitness:
* How did you install Zipline: conda
* Python packages:

# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py35_0  
alabaster                 0.7.11                   py35_0  
alembic                   0.7.7                    py35_0    Quantopian
anaconda-client           1.7.2                    py35_0  
anaconda-navigator        1.9.2                    py35_0  
anaconda-project          0.8.2                    py35_0  
appdirs                   1.4.3            py35h28b3542_0  
appnope                   0.1.0            py35hd172556_0  
appscript                 1.0.1            py35h1de35cc_1  
asn1crypto                0.24.0                   py35_0  
astroid                   2.0.4                    py35_0  
astropy                   3.0.4            py35h1de35cc_0  
atomicwrites              1.2.1                    py35_0  
attrs                     18.2.0           py35h28b3542_0  
automat                   0.7.0                    py35_0  
babel                     2.6.0                    py35_0  
backcall                  0.1.0                    py35_0  
backports                 1.0                      py35_1  
backports.shutil_get_terminal_size 1.0.0                    py35_2  
bcolz                     0.12.1              np114py35_0    Quantopian
beautifulsoup4            4.6.3                    py35_0  
bitarray                  0.8.3            py35h1de35cc_0  
bkcharts                  0.2              py35h18a45e2_0  
blas                      1.0                         mkl  
blaze                     0.11.3                   py35_0  
bleach                    2.1.4                    py35_0  
blosc                     1.14.4               hd9629dc_0  
bokeh                     0.13.0                   py35_0  
boto                      2.49.0                   py35_0  
bottleneck                1.2.1            py35h1d22016_1  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
certifi                   2018.8.24                py35_1  
cffi                      1.11.5           py35h6174b99_1  
chardet                   3.0.4                    py35_1  
click                     6.7              py35hcc65ea6_0  
cloudpickle               0.5.5                    py35_0  
clyent                    1.2.2                    py35_1  
colorama                  0.3.9            py35h1d66b2b_0  
conda                     4.5.11                   py35_0  
conda-build               3.15.1                   py35_0  
conda-env                 2.6.0                         1  
constantly                15.1.0           py35h28b3542_0  
contextlib2               0.5.5            py35hc2c67b4_0  
cryptography              2.3.1            py35hdbc3d79_0  
curl                      7.61.0               ha441bb4_0  
cycler                    0.10.0           py35hb89929e_0  
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.5           py35h0a44026_0  
cytoolz                   0.9.0.1          py35h1de35cc_1  
dask                      0.19.2                   py35_0  
dask-core                 0.19.2                   py35_0  
datashape                 0.5.4                    py35_1  
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py35_0  
defusedxml                0.5.0                    py35_1  
distributed               1.23.2                   py35_0  
docutils                  0.14             py35hb13dbd9_0  
empyrical                 0.5.0                    py35_0    Quantopian
entrypoints               0.2.3                    py35_2  
et_xmlfile                1.0.1            py35h40eb147_0  
expat                     2.2.6                h0a44026_0  
fastcache                 1.0.2            py35h1de35cc_2  
filelock                  3.0.8                    py35_0  
flask                     1.0.2                    py35_1  
flask-cors                3.0.6                    py35_0  
freetype                  2.9.1                hb4e5f40_0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
glob2                     0.6              py35hdef87b6_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py35h212fb8a_2  
greenlet                  0.4.15           py35h1de35cc_0  
h5py                      2.8.0            py35h878fce3_3  
hdf5                      1.10.2               hfa1e0ec_1  
heapdict                  1.0.0                    py35_2  
html5lib                  1.0.1                    py35_0  
hyperlink                 18.0.0                   py35_0  
icu                       58.2                 h4b95b61_1  
idna                      2.7                      py35_0  
imageio                   2.4.1                    py35_0  
imagesize                 1.1.0                    py35_0  
incremental               17.5.0                   py35_0  
inflection                0.3.1                    py35_1  
intel-openmp              2019.0                      118  
intervaltree              2.1.0                    py35_0    Quantopian
ipykernel                 4.10.0                   py35_0  
ipython                   6.5.0                    py35_0  
ipython_genutils          0.2.0            py35hf129286_0  
ipywidgets                7.4.1                    py35_0  
isort                     4.3.4                    py35_0  
itsdangerous              0.24                     py35_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4                      py35_0  
jedi                      0.12.1                   py35_0  
jinja2                    2.10                     py35_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py35h2dd9e4b_0  
jupyter                   1.0.0                    py35_7  
jupyter_client            5.2.3                    py35_0  
jupyter_console           5.2.0            py35hd2aa692_1  
jupyter_core              4.4.0                    py35_0  
jupyterlab                0.34.9                   py35_0  
jupyterlab_launcher       0.13.1                   py35_0  
keyring                   13.2.1                   py35_0  
kiwisolver                1.0.1            py35h219a9d8_0  
lazy-object-proxy         1.3.1            py35h1de35cc_2  
libcurl                   7.61.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                hcb84e12_2  
libxml2                   2.9.8                hab757c2_1  
libxslt                   1.1.32               hb819dd2_0  
llvmlite                  0.24.0           py35hc454e04_0  
locket                    0.2.0            py35h58cf053_1  
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
lxml                      4.2.5            py35hef8c89e_0  
lzo                       2.10                 h362108e_2  
mako                      1.0.7                    py35_0  
markupsafe                1.0              py35h1de35cc_1  
matplotlib                3.0.0            py35h54f8f79_0  
mccabe                    0.6.1            py35h3f6a9a1_0  
mistune                   0.8.3            py35h1de35cc_1  
mkl                       2019.0                      118  
mkl-service               1.1.2            py35h6b9c3cc_5  
mkl_fft                   1.0.6            py35hb8a8100_0  
mkl_random                1.0.1            py35h5d10147_1  
more-itertools            4.3.0                    py35_0  
mpc                       1.0.3                h7a72875_5  
mpfr                      3.1.5                h711e7fd_2  
mpmath                    1.0.0                    py35_2  
msgpack-python            0.5.6            py35h04f5b5a_1  
multipledispatch          0.6.0                    py35_0  
navigator-updater         0.2.1                    py35_0  
nbconvert                 5.4.0                    py35_1  
nbformat                  4.4.0            py35h41c2038_0  
ncurses                   6.1                  h0a44026_0  
networkx                  1.11                     py35_1  
nltk                      3.3.0                    py35_0  
nose                      1.3.7                    py35_2  
notebook                  5.6.0                    py35_0  
numba                     0.39.0           py35h6440ff4_0  
numexpr                   2.6.1               np114py35_0    Quantopian
numpy                     1.14.6           py35h648b28d_4  
numpy-base                1.14.6           py35h8a80b8c_4  
numpydoc                  0.8.0                    py35_0  
odo                       0.5.1            py35h7f7a387_0  
olefile                   0.46                     py35_0  
openpyxl                  2.5.6                    py35_0  
openssl                   1.0.2p               h1de35cc_0  
packaging                 17.1                     py35_0  
pandas                    0.22.0           py35h0a44026_0  
pandas-datareader         0.6.0                    py35_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2                    py35_1  
parso                     0.3.1                    py35_0  
partd                     0.3.8            py35h6fadee7_0  
path.py                   11.1.0                   py35_0  
pathlib2                  2.3.2                    py35_0  
patsy                     0.5.0                    py35_0  
pcre                      8.42                 h378b8a2_0  
pep8                      1.7.1                    py35_0  
pexpect                   4.6.0                    py35_0  
pickleshare               0.7.4            py35h9517181_0  
pillow                    5.2.0            py35hb68e598_0  
pip                       10.0.1                   py35_0  
pkginfo                   1.4.2                    py35_1  
pluggy                    0.7.1            py35h28b3542_0  
ply                       3.11                     py35_0  
prometheus_client         0.3.1            py35h28b3542_0  
prompt_toolkit            1.0.15           py35h93950c5_0  
psutil                    5.4.7            py35h1de35cc_0  
ptyprocess                0.6.0                    py35_0  
py                        1.6.0                    py35_0  
pyasn1                    0.4.4            py35h28b3542_0  
pyasn1-modules            0.2.2                    py35_0  
pycodestyle               2.4.0                    py35_0  
pycosat                   0.6.3            py35h745f8c1_0  
pycparser                 2.19                     py35_0  
pycrypto                  2.6.1            py35h1de35cc_8  
pycurl                    7.43.0.2         py35hdbc3d79_0  
pyflakes                  2.0.0                    py35_0  
pygments                  2.2.0            py35h392a662_0  
pylint                    2.1.1                    py35_0  
pyodbc                    4.0.24           py35h0a44026_0  
pyopenssl                 18.0.0                   py35_0  
pyparsing                 2.2.1                    py35_0  
pyqt                      5.9.2            py35h655552a_2  
pysocks                   1.6.8                    py35_0  
pytables                  3.4.4            py35h13cba08_0  
pytest                    3.8.1                    py35_0  
pytest-arraydiff          0.2              py35h39e3cac_0  
pytest-astropy            0.4.0                    py35_0  
pytest-doctestplus        0.1.3                    py35_0  
pytest-openfiles          0.3.0                    py35_0  
pytest-remotedata         0.3.0                    py35_0  
python                    3.5.6                hc167b69_0  
python-dateutil           2.7.3                    py35_0  
python.app                2                        py35_9  
pytz                      2018.5                   py35_0  
pywavelets                1.0.0            py35h1d22016_0  
pyyaml                    3.13             py35h1de35cc_0  
pyzmq                     17.1.2           py35h1de35cc_0  
qt                        5.9.6                h45cd832_2  
qtawesome                 0.4.4            py35h21e61ad_0  
qtconsole                 4.4.1                    py35_0  
qtpy                      1.5.0                    py35_0  
quandl                    3.4.2                    py35_0  
readline                  7.0                  h1de35cc_5  
requests                  2.19.1                   py35_0  
requests-file             1.4.3                    py35_0  
requests-ftp              0.3.1                    py35_0  
rope                      0.11.0                   py35_0  
ruamel_yaml               0.15.46          py35h1de35cc_0  
scikit-image              0.14.0           py35h0a44026_1  
scikit-learn              0.20.0           py35h4f467ca_1  
scipy                     1.1.0            py35hcaad992_0  
seaborn                   0.9.0                    py35_0  
send2trash                1.5.0                    py35_0  
service_identity          17.0.0           py35h28b3542_0  
setuptools                40.2.0                   py35_0  
simplegeneric             0.8.1                    py35_2  
singledispatch            3.4.0.3          py35h0acf360_0  
sip                       4.19.8           py35h0a44026_0  
six                       1.11.0                   py35_1  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.2.1            py35hbb7be01_0  
sortedcollections         1.0.1                    py35_0  
sortedcontainers          2.0.5                    py35_0  
sphinx                    1.7.9                    py35_0  
sphinxcontrib             1.0                      py35_1  
sphinxcontrib-websupport  1.1.0                    py35_1  
spyder                    3.3.1                    py35_1  
spyder-kernels            0.2.6                    py35_0  
sqlalchemy                1.2.11           py35h1de35cc_0  
sqlite                    3.24.0               ha441bb4_0  
statsmodels               0.9.0            py35h917ab60_0  
sympy                     1.2                      py35_0  
ta-lib                    0.4.9               np114py35_0    quantopian
tblib                     1.3.2            py35h1b9c5fd_0  
terminado                 0.8.1                    py35_1  
testpath                  0.3.1            py35hf8009f4_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.9.0                    py35_0  
tornado                   5.1.1            py35h1de35cc_0  
tqdm                      4.26.0           py35h28b3542_0  
trading-calendars         1.0.1                    py35_0    Quantopian
traitlets                 4.3.2            py35hd3d1486_0  
twisted                   17.5.0                   py35_0  
typed-ast                 1.1.0            py35h6952a12_0  
unicodecsv                0.14.1           py35h2154ad0_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.23                     py35_0  
wcwidth                   0.1.7            py35hdd0c235_0  
webencodings              0.5.1                    py35_1  
werkzeug                  0.14.1                   py35_0  
wheel                     0.31.1                   py35_0  
widgetsnbextension        3.4.1                    py35_0  
wrapt                     1.10.11          py35h1de35cc_2  
xlrd                      1.1.0                    py35_1  
xlsxwriter                1.1.1                    py35_0  
xlwings                   0.11.8                   py35_0  
xlwt                      1.2.0            py35hf70d7fa_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h0a44026_1  
zict                      0.1.3                    py35_0  
zipline                   1.3.0               np114py35_0    Quantopian
zlib                      1.2.11               hf3cbc9b_2  
zope                      1.0                      py35_1  
zope.interface            4.5.0            py35h1de35cc_0

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

After having zipline installed, wanted to run "My first Algorithm" in zipline beginner tutorial.
After entering '$ zipline run -f /anaconda3/lib/python3.5/site-packages/zipline/examples/buyapple.py --start 2016-1-1 --end 2018-1-1 -o buyapple_out.pickle', it stops here:

'.....
File "/anaconda3/lib/python3.5/site-packages/zipline/utils/sqlite_utils.py", line 35, in verify_sqlite_path_exists
    raise ValueError("SQLite file {!r} doesn't exist.".format(path))
ValueError: SQLite file '/Users/Tobias/.zipline/data/quandl/2018-10-20T16;43;04.775904/assets-6.sqlite' doesn't exist.'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

I checked line 35 in my file (File "/anaconda3/lib/python3.5/site-packages/zipline/utils/sqlite_utils.py").

It says: 
def verify_sqlite_path_exists(path):
    if path != ':memory:' and not os.path.exists(path):
        raise ValueError("SQLite file {!r} doesn't exist.".format(path))

However, I don't know what to do with this information.

And when I look up the path "/Users/Tobias/.zipline/data/quandl/2018-10-20T16;43;04.775904/" I can only find an empty folder.

# Anything else?

I'd really appreciate any help. Getting to run the algorithm is crucial for me because I need this for my Master Thesis but I am running out of time. Thank you.

Sincerely,
Tobias

**Comment by Tobiasniklasbecker** [comment]
maybe this is related to [#2222](url)

I am not sure.

Here is the information about my notebook:

 Model Name:	MacBook Pro
 Model Identifier:	MacBookPro12,1
 Processor Name:	Intel Core i5
 Processor Speed:	2,7 GHz
 Number of Processors:	1  
Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB

**Comment by Tobiasniklasbecker** [comment]
case can be closed.

Something went wrong with the ingestion of quandl. I did the ingestion yesterday a few times but each time there was only an empty folder created.

Today, I tried it again, with the same code. But today it worked.

I set up my quandl account and immediately tried the ingestion. Maybe you have to wait a bit. I don't know.

**Comment by smartevin** [comment]
I met the same problem
