### ISSUE TITLE
Install Zipline with pip/Pycharm

### ISSUE THREAD

**Issue by swardsam** [quantopian/zipline#2368]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Windows 10
* Python Version: 3.7 ( I have installed 3.5 but i don't know if I have to do something more )

* How did you install Zipline: That's my issue :)
* Python packages: 
![image](https://user-images.githubusercontent.com/45229023/48833560-ee535880-ed7b-11e8-8957-5f3cba207b0f.png)

# Description of Issue

Tried to install zipline using pip, failed with this error:
![image](https://user-images.githubusercontent.com/45229023/48833774-6e79be00-ed7c-11e8-98a1-f4a326fb436d.png)

 Tried using Pycharm and failed too with this error:
![image](https://user-images.githubusercontent.com/45229023/48833853-99fca880-ed7c-11e8-92b6-4c799b8e427d.png)

I am really bad at installing things ( consider myself as a newbie), I have tried conda aswell it failed too.

Thank you very much for people taking time for this

Sincerely,

**Comment by freddiev4** [comment]
Hey @swardsam thanks opening the issue. Based off your errors above, it looks like you're installing Zipline _with_ Python 3.7, which we don't build packages for or test.

I would recommend you read about [virtualenv](https://virtualenv.readthedocs.io/en/latest/), which you can use to install an isolated set of packages, and run Python 3.5. 

Once you've installed virtualenv, the set of commands you'd run in the Command Prompt are:

```
$ cd your_algorithm_project
$ pip install virtualenv
```

Within your project:

```
$ virtualenv zip35 -p path/to/your/Python35-installation
```

Activate your virtualenv; on Windows, virtualenv creates a batch file

```
\zip35\Scripts\activate.bat
```

To activate virtualenv on Windows, the activate script is in the Scripts folder:

```
# Example:
$ C:\Users\'Username'\zip35\Scripts\activate.bat
```

Let me know if any of that is unclear or if I can help you further.

**Comment by swardsam** [comment]
Thanks a lot for your answer, I understand virtualenv now but I am facing another error:
![image](https://user-images.githubusercontent.com/45229023/48917864-3dd37a80-ee89-11e8-8787-9f8670593746.png)

if it can help:
![image](https://user-images.githubusercontent.com/45229023/48917903-7d9a6200-ee89-11e8-94f6-258947a2ddc2.png)

I have tried to upgrade my setuptools but I does not help:
![image](https://user-images.githubusercontent.com/45229023/48917929-b9cdc280-ee89-11e8-89ba-5b7045fa2670.png)

python packages:
![image](https://user-images.githubusercontent.com/45229023/48917981-fef1f480-ee89-11e8-9243-26ac63330b70.png)

Sincerely,

**Comment by swardsam** [comment]
I think I have made it ! ( i used conda )
![image](https://user-images.githubusercontent.com/45229023/48953815-60c46400-ef47-11e8-8e29-b1f33897557f.png)

Thank you very much for your help  💯
