### ISSUE TITLE
record function not working

### ISSUE THREAD

**Issue by studyquant** [quantopian/zipline#2374]
Dear Zipline Maintainers,
  strategy unable to record data by record api.  It is wired that my zipline environment unable to record data while my catalyst environment able to record.    While last time,  catalyst environment unable to record data, then zipline environment able to record data. 

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --3.5.2version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`) pip 
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by freddiev4** [comment]
Hi @studyquant two things:

1. Can you provide some code that works / does not work when you try to use the record function?
2. I can't help you much with catalyst as I have not looked at the library and would guess it's heavily modified for Enigma's use-cases (just as an FYI in the case that a separate, but related issue exists in that library)

**Comment by studyquant** [comment]
hi, @freddiev4  ,do u know ？  How can I see the sources code of record function ?
