### ISSUE TITLE
Make alternative markets like the London stock exchange fully supported again

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#238]
With changes to the tradingcalendar and environment to support half-days and specific minutes, the LSE support has lagged.

Temporarily skipping tests that cover LSE behavior, with the intent to add them back in when LSE has the same the same full support as the US markets.
i.e. that they will understand half-days, be able to populate minutes per day, etc.

**Comment by freddiev4** [comment]
Going to close this as users can create their own custom trading calendars and pass those via `--trading-calendar` as well as ingest csv data for them.
