### ISSUE TITLE
How to handle special holiday

### ISSUE THREAD

**Issue by scubamut** [quantopian/zipline#2408]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: LinuxMint 19
* Python Version: 3.6.7
* Python Bitness: 
* How did you install Zipline: 1.3.0 (pip)
* Python packages: ``

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

`

    import pandas_datareader as pdr
    import xarray as xr
    from datetime import datetime, timezone
    import pytz
    import zipline
    from zipline.algorithm import TradingAlgorithm
    from zipline.api import order, record, symbol, order_target_percent, get_datetime

    symbols = ['SPY','BND']

    start = datetime(2011, 1, 1, 0, 0, 0, 0, pytz.utc)
    end = datetime.today().replace(tzinfo=timezone.utc)

    data = pdr.DataReader(symbols, 'yahoo',start,end)

    Attributes = data.columns.levels[0].astype(str).str.lower()
    Symbols = data.columns.levels[1]
    Date = data.index

    da = xr.DataArray(data.values.transpose().reshape(len(Attributes),len(Symbols),len(Date)), 
                 coords=[Attributes, Symbols, Date], 
                 dims=['Attributes', 'Symbols', 'Date'])

    def initialize(self):
            self.has_ordered = False

    def handle_data(self, data):

        if not self.has_ordered:
            for stock in data:
                self.order(stock, 100)
            self.has_ordered = True

    my_algo = TradingAlgorithm(initialize=initialize,handle_data=handle_data)
    results = my_algo.run(da.to_pandas().transpose(1,2,0))
    results.portfolio_value
`

* What did you expect to happen?
Run Algo
* What happened instead?
Runs with error

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Run Algo with `end = datetime(2013, 1, 1, 0, 0, 0, 0, pytz.utc)` NO ERRORS
2. Run Algo with `end = datetime.today().replace(tzinfo=timezone.utc)`
3. Error Output (partial) `KeyError: 'the label [2018-12-05 00:00:00+00:00] is not in the [index]`

...

## What steps have you taken to resolve this already?

...
The problem is the special memorial day for George W. Bush - NYSE closed. But I need help to solve it.
# Anything else?

...
None
Sincerely,
`Dave`

**Comment by freddiev4** [comment]
Hi @scubamut you should install the latest version of (trading-calendars)[https://github.com/quantopian/trading_calendars ] using `pip install -U trading-calendars`.

Whenever we do a new Zipline release, the latest version will be automatically installed.

**Comment by scubamut** [comment]
Solved.

Cheers
