### ISSUE TITLE
Zipline Installation on Python v3.5 or Python v3.4

### ISSUE THREAD

**Issue by alphabeingnow** [quantopian/zipline#2436]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version 10)
* Python Version: This issue applies to both python version 3.5 & python version 3.4.
* Python Bitness: NA
* How did you install Zipline: conda install -c Quantopian zipline
* Python packages: Packages shown below are based on the command, conda list
# Name                    Version                   Build  Channel
alembic                   0.7.7                    py35_0    Quantopian
asn1crypto                0.24.0                   py35_0
backcall                  0.1.0                     <pip>
bcolz                     0.12.1              np114py35_0    Quantopian
blas                      1.0                         mkl
blosc                     1.15.0               h7bd577a_0
bottleneck                1.2.1            py35h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.1.23                     0
certifi                   2018.8.24                py35_1
cffi                      1.11.5           py35h74b6da3_1
chardet                   3.0.4                    py35_1
click                     6.7              py35h10df73f_0
colorama                  0.4.1                     <pip>
contextlib2               0.5.5            py35h0a97e54_0
cryptography              2.3.1            py35h74b6da3_0
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.5           py35h6538335_0
decorator                 4.3.0                    py35_0
empyrical                 0.5.0                    py35_0    Quantopian
hdf5                      1.10.2               hac2f561_1
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.7                      py35_0
intel-openmp              2019.1                      144
intervaltree              2.1.0                    py35_0    Quantopian
ipykernel                 5.1.0                     <pip>
ipython                   7.3.0                     <pip>
ipython-genutils          0.2.0                     <pip>
jedi                      0.13.3                    <pip>
jupyter-client            5.2.4                     <pip>
jupyter-core              4.4.0                     <pip>
libiconv                  1.15                 h1df5818_7
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
lxml                      4.2.5            py35hef2cd61_0
lzo                       2.10                 h6df0209_2
mako                      1.0.7                    py35_0
markupsafe                1.0              py35hfa6e2cd_1
mkl                       2018.0.3                      1
mkl_fft                   1.0.6            py35hdbbee80_0
mkl_random                1.0.1            py35h77b88f5_1
multipledispatch          0.6.0                    py35_0
networkx                  1.11                     py35_1
numexpr                   2.6.1               np114py35_0    Quantopian
numpy                     1.14.6           py35hc27ee41_4
numpy-base                1.14.6           py35h8128ebf_4
openssl                   1.0.2r               he774522_0
pandas                    0.22.0           py35h6538335_0
pandas-datareader         0.6.0                    py35_0
parso                     0.3.4                     <pip>
patsy                     0.5.0                    py35_0
pickleshare               0.7.5                     <pip>
pip                       10.0.1                   py35_0
prompt-toolkit            2.0.9                     <pip>
pycparser                 2.19                     py35_0
Pygments                  2.3.1                     <pip>
pyopenssl                 18.0.0                   py35_0
pysocks                   1.6.8                    py35_0
pytables                  3.4.4            py35he6f6034_0
python                    3.5.6                he025d50_0
python-dateutil           2.7.3                    py35_0
pytz                      2018.5                   py35_0
pyzmq                     18.0.0                    <pip>
requests                  2.20.1                   py35_0    Quantopian
requests-file             1.4.3                    py35_0
requests-ftp              0.3.1                    py35_0
scipy                     1.1.0            py35hc28095f_0
setuptools                40.2.0                   py35_0
six                       1.11.0                   py35_1
snappy                    1.1.7                h777316e_3
sortedcontainers          1.4.4                    py35_0    Quantopian
sqlalchemy                1.2.11           py35hfa6e2cd_0
statsmodels               0.9.0            py35h452e1ab_0
toolz                     0.9.0                    py35_0
tornado                   5.1.1                     <pip>
trading-calendars         1.6.1                    py35_0    Quantopian
traitlets                 4.3.2                     <pip>
urllib3                   1.23                     py35_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                     <pip>
wheel                     0.31.1                   py35_0
win-unicode-console       0.5                       <pip>
win_inet_pton             1.0.1                    py35_1
wincertstore              0.2              py35hfebbdb8_0
wrapt                     1.10.11          py35hfa6e2cd_2
zipline                   1.3.0               np114py35_0    Quantopian
zlib                      1.2.11               h62dcd97_3

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? I am trying to download zipline into the latest available python as of 1st March 2019. Based on what I have read and seen online, the latest python available from Anaconda Navigator is Python 3.7 whereas zipline only works on Python 3.5 or earlier version. So I downloaded Anaconda 2018.12 for Windows Installer which has Python v3.7, then create a virtual environment called snakes for python 3.5 and then installed zipline from conda using that virtual environment. After all these, I opened Anaconda Navigator, switched to the virtual environment called snakes, and tried to launch Jupyter Notebook but the launch button was replaced by the install button. So I click install. 

* What happened instead? Halfway throughout the installation, a small window appears, saying that "jupyterlab==0.35.3 cannot be installed in this environment. Do you want to install the package in an existing environment or create a new environment? "

So I chose another environment and the next message that appears is shown below.  

UnsatisfiableError: The following specifications were found to be in conflict:
- jupyterlab==0.35.3 -> jupyterlab_server[version='>=0.2.0, python[version='>=3.6, - python=3.4
Use "conda info " to see the dependencies for each package.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.install latest anaconda with the latest python at Anaconda website. Anaconda 2018.12 for Windows Installer, Python 3.7 version, 64 bit. 

2. command prompt > conda create --name snakes python=3.5

3. command prompt > activate snakes

4. command prompt > conda install -c Quantopian zipline

5. Open Anaconda Navigator 

6. Switch to the newly created virtual environment, snakes

7) Attempt to launch Jupyter Notebook from the virtual environment 

## What steps have you taken to resolve this already?

... NA

# Anything else?

... This issue applies to both Python v3.5 and Python v3.4, and on both Jupyter Notebook and Spyder. 

Sincerely,
Zipline Installer

**Comment by Swalloow** [comment]
It seems anaconda version issue.
Have you tried update conda?

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

**Comment by alphabeingnow** [comment]
Hi Swalloow, 

Thanks for your reply. updating conda via this command <conda update --all> resolves the above problem. 

However, a new problem surfaces. 

When I install python 3.5, zipline-1.3.0 will be removed. 

When I install zipline 1.3.0, python 3.5 will be downgraded to python 2.7

It seems that python 3.5 and zipline -1.3.0 are incompatible with each other. 

How do I get zipline to work with the most latest compatible python? 

Below are the sequence of commands that i have used. 

1) install latest anaconda with the latest python
2) key in this command <conda create --name snakes python=3.5>
3) key in this command <activate snakes>
4) key in this command <conda update --all>
5) key in this command <conda install -c Quantopian zipline>

**Comment by alphabeingnow** [comment]
Hi Swalloow, 

Thanks for your reply. updating conda via this command <conda update --all> resolves the above problem. 

However, a new problem surfaces. 

When I install python 3.5, zipline-1.3.0 will be removed. 

When I install zipline 1.3.0, python 3.5 will be downgraded to python 2.7

It seems that python 3.5 and zipline -1.3.0 are incompatible with each other. 

How do I get zipline to work with python 3.5?  

Below are the sequence of commands that i have used. 

1) install latest anaconda with the latest python

2) key in this command <conda create --name snakes python=3.5> 

3) activate the newly created environment, snakes

4) key in this command <conda update --all>

5) key in this command <conda install -c Quantopian zipline>

**Comment by alphabeingnow** [comment]
anyone can provide a solution here?

**Comment by riddhesh007** [comment]
Same problem faced by me too

**Comment by antal0** [comment]
Conclusion - there is no way for backtesting online crypto tick data like at QuantConnect with the Lean?

**Comment by robertungvari** [comment]
For me these steps solved the issue with Anaconda 3:

conda create -n env_zipline python=3.5

activate env_zipline

conda install -c Quantopian zipline

conda install ipykernel

python -m ipykernel install --user --name env_zipline --display-name "Python (zipline)"

jupyter notebook

**Comment by ssanderson** [comment]
3.5 has been supported for a while. The general problem of "support relatively modern python versions" is now tracked by https://github.com/quantopian/zipline/issues/2616.

**Comment by SrinivasPT** [comment]
> For me these steps solved the issue with Anaconda 3:
> 
> conda create -n env_zipline python=3.5
> 
> activate env_zipline
> 
> conda install -c Quantopian zipline
> 
> conda install ipykernel
> 
> python -m ipykernel install --user --name env_zipline --display-name "Python (zipline)"
> 
> jupyter notebook

Step i missed was adding the ipkernal after installing zipline. Struggled to import zipline and was getting "ImportError: No module named zipline". Finally your steps helped in figuring out that I misssed adding ipkernal. Thanks...

**Comment by SrinivasPT** [comment]
Step i missed was adding the ipkernal after installing zipline. Struggled to import zipline and was getting "ImportError: No module named zipline". Finally your steps helped in figuring out that I misssed adding ipkernal. Thanks...
