### ISSUE TITLE
is zipline has OHLC data dependency?

### ISSUE THREAD

**Issue by subhashdamodaran-synechron** [quantopian/zipline#2442]
Dear Zipline Maintainers,

Do we have OHLC data dependency with zipline library ?  

Sincerely,
`$ whoami`

**Comment by ssanderson** [comment]
hey @subhashdamodaran-synechron. Apologies for the long delay replying here. Zipline does indeed require you to provide OHLCV data (either daily or minutely). You can find more documentation for getting your data into zipline here: https://www.zipline.io/bundles
