### ISSUE TITLE
Argument 'arr' has incorrect type (expected numpy.ndarray, got DatetimeIndex)

### ISSUE THREAD

**Issue by Sundetaly** [quantopian/zipline#2451]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
Python 3.5.6 :: Anaconda, Inc.
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
 conda create -n env_zipline python=3.5
activate env_zipline
(env_zipline) $ conda install -c Quantopian zipline
* Python packages: `$ pip freeze` or `$ conda list`
# Name                    Version                   Build  Channel
alembic                   0.7.7                    py35_0    Quantopian
appdirs                   1.4.3            py35h28b3542_0    anaconda
asn1crypto                0.24.0                   py35_0
attrs                     19.1.0                     py_0    anaconda
automat                   0.7.0                    py35_0    anaconda
backcall                  0.1.0                    py35_0    anaconda
bcolz                     0.12.1              np114py35_0    Quantopian
blas                      1.0                         mkl
bleach                    2.1.4                    py35_0    anaconda
blosc                     1.15.0               h7bd577a_0
bottleneck                1.2.1            py35h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.1.23                     0    anaconda
certifi                   2018.8.24                py35_1    anaconda
cffi                      1.11.5           py35h74b6da3_1
chardet                   3.0.4                    py35_1
click                     6.7              py35h10df73f_0
colorama                  0.3.9            py35h32a752f_0    anaconda
constantly                15.1.0           py35h28b3542_0    anaconda
contextlib2               0.5.5            py35h0a97e54_0
cryptography              2.3.1            py35h74b6da3_0
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.5           py35h6538335_0
decorator                 4.4.0                      py_0
defusedxml                0.5.0                    py35_1    anaconda
empyrical                 0.5.0                    py35_0    Quantopian
entrypoints               0.2.3                    py35_2    anaconda
hdf5                      1.10.2               hac2f561_1
html5lib                  1.0.1                    py35_0    anaconda
hyperlink                 18.0.0                   py35_0    anaconda
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1    anaconda
idna                      2.7                      py35_0
incremental               17.5.0                   py35_0    anaconda
intel-openmp              2019.3                      203
intervaltree              2.1.0                    py35_0    Quantopian
ipykernel                 4.10.0                   py35_0    anaconda
ipython                   6.5.0                    py35_0    anaconda
ipython_genutils          0.2.0            py35ha709e79_0    anaconda
ipywidgets                7.4.1                    py35_0    anaconda
jedi                      0.12.1                   py35_0    anaconda
jinja2                    2.10                     py35_0    anaconda
jpeg                      9b                   hb83a4c4_2    anaconda
jsonschema                2.6.0            py35h27d56d3_0    anaconda
jupyter                   1.0.0                    py35_7    anaconda
jupyter_client            5.2.3                    py35_0    anaconda
jupyter_console           5.2.0                    py35_1    anaconda
jupyter_core              4.4.0                    py35_0    anaconda
libiconv                  1.15                 h1df5818_7
libpng                    1.6.36               h2a8f88b_0    anaconda
libsodium                 1.0.16               h9d3ae62_0    anaconda
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
lxml                      4.2.5            py35hef2cd61_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.0.7                    pypi_0    pypi
markupsafe                1.0              py35hfa6e2cd_1
mistune                   0.8.3            py35hfa6e2cd_1    anaconda
mkl                       2018.0.3                      1
mkl_fft                   1.0.6            py35hdbbee80_0
mkl_random                1.0.1            py35h77b88f5_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py35_0
nbconvert                 5.4.1                      py_2    anaconda
nbformat                  4.4.0            py35h908c9d9_0    anaconda
networkx                  1.11                     py35_1
notebook                  5.6.0                    py35_0    anaconda
numexpr                   2.6.1               np114py35_0    Quantopian
numpy                     1.14.6           py35hc27ee41_4
numpy-base                1.14.6           py35h8128ebf_4
openssl                   1.0.2r               he774522_0    anaconda
pandas                    0.18.0                   pypi_0    pypi
pandas-datareader         0.6.0                    py35_0
pandoc                    2.2.3.2                       0    anaconda
pandocfilters             1.4.2                    py35_1    anaconda
parso                     0.3.1                    py35_0    anaconda
patsy                     0.5.0                    py35_0
pickleshare               0.7.4            py35h2f9f535_0    anaconda
pip                       19.0.3                   pypi_0    pypi
prometheus_client         0.3.1            py35h28b3542_0    anaconda
prompt_toolkit            1.0.15           py35h89c7cb4_0    anaconda
pyasn1                    0.4.5                      py_0    anaconda
pyasn1-modules            0.2.2                    py35_0    anaconda
pycparser                 2.19                     py35_0
pygments                  2.2.0            py35h24c0941_0    anaconda
pyhamcrest                1.9.0                    pypi_0    pypi
pyopenssl                 18.0.0                   py35_0
pyqt                      5.9.2            py35ha878b3d_0    anaconda
pysocks                   1.6.8                    py35_0
pytables                  3.4.4            py35he6f6034_0
python                    3.5.6                he025d50_0
python-dateutil           2.7.3                    py35_0
pytz                      2018.5                   py35_0
pywin32                   223              py35hfa6e2cd_1    anaconda
pywinpty                  0.5.4                    py35_0    anaconda
pyzmq                     17.1.2           py35hfa6e2cd_0    anaconda
qt                        5.9.6            vc14h1e9a669_2
qtconsole                 4.4.1                    py35_0    anaconda
requests                  2.20.1                   py35_0    Quantopian
requests-file             1.4.3                    py35_0
requests-ftp              0.3.1                    py35_0
scipy                     1.1.0            py35hc28095f_0
send2trash                1.5.0                    py35_0    anaconda
service_identity          17.0.0           py35h28b3542_0    anaconda
setuptools                40.2.0                   py35_0
simplegeneric             0.8.1                    py35_2    anaconda
sip                       4.19.12          py35h6538335_0    anaconda
six                       1.11.0                   py35_1
snappy                    1.1.7                h777316e_3
sortedcontainers          1.4.4                    py35_0    Quantopian
sqlalchemy                1.2.11           py35hfa6e2cd_0
sqlite                    3.27.2               he774522_0    anaconda
statsmodels               0.9.0            py35h452e1ab_0
ta-lib                    0.4.9               np114py35_0    quantopian
terminado                 0.8.1                    py35_1    anaconda
testpath                  0.3.1            py35h06cf69e_0    anaconda
toolz                     0.9.0                    py35_0
tornado                   5.1.1            py35hfa6e2cd_0    anaconda
trading-calendars         1.6.1                    py35_0    Quantopian
traitlets                 4.3.2            py35h09b975b_0    anaconda
twisted                   18.7.0           py35hfa6e2cd_1    anaconda
urllib3                   1.23                     py35_0
vc                        14.1                 h21ff451_3    anaconda
vs2015_runtime            15.5.2                        3    anaconda
wcwidth                   0.1.7            py35h6e80d8a_0    anaconda
webencodings              0.5.1                    py35_1    anaconda
wheel                     0.31.1                   py35_0
widgetsnbextension        3.4.1                    py35_0    anaconda
win_inet_pton             1.0.1                    py35_1
win_unicode_console       0.5              py35h56988b5_0    anaconda
wincertstore              0.2              py35hfebbdb8_0
winpty                    0.4.3                         4    anaconda
wrapt                     1.10.11          py35hfa6e2cd_2
zeromq                    4.2.5                he025d50_1    anaconda
zipline                   1.3.0               np114py35_0    Quantopian
zlib                      1.2.11               h62dcd97_3
zope                      1.0                      py35_1    anaconda
zope.interface            4.5.0            py35hfa6e2cd_0    anaconda
</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
when i run command 
> %zipline --bundle quantopian-quandl --start 2008-1-1 --end 2012-1-1 -o dma.pickle, I have problem TypeError: Argument 'arr' has incorrect type (expected numpy.ndarray, got DatetimeIndex)

TypeError: Argument 'arr' has incorrect type (expected numpy.ndarray, got DatetimeIndex)
* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`
### ****

**Comment by steviesteveston** [comment]
How did you fix this?
