### ISSUE TITLE
# Build the Cython extensions in place.  python3 setup.py build_ext --inplace

### ISSUE THREAD

**Issue by Shahroon900** [quantopian/zipline#2469]
Hello ll..

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10
* Python Version: `$ python --version 3.7.3`
 
I have installed python on path 
C:\Users\Admin\AppData\Local\Programs\Python\Python37-32

And I installed darkflow in this directory by using the tutorial

https://appliedmachinelearning.blog/2018/05/27/running-yolo-v2-for-real-time-object-detection-on-videos-images-via-darkflow/#respond

The problem occurs at this command

python3 setup.py build_ext --inplace

Error

C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\darkflow>python3 setup.py build_ext --inplace
'python3' is not recognized as an internal or external command,
operable program or batch file.

So i when I run the command python3 setup.py build_ext --inplace i find error

I also tried it from the folder where it is unable to find the setup.py file
C:\Users\Admin\AppData\Local\Programs\Python\Python37-32>python3 setup.py build_ext --inplace

I did everything mentioned in the turorial but as this does not work, I am unable to run the command which detects object in images which is

./flow –model cfg/yolov2.cfg –load bin/yolov2.weights –imgdir sample_img –gpu 0.9

So i get the error which is listed below with the command itself

C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\darkflow\darkflow\dark>./flow -model cfg/yolov2.cfg -load bin/yolov2.weights -imgdir sample_img -gpu 0.9
'.' is not recognized as an internal or external command,
operable program or batch file.

Please help in running and sorting out the issue. 

Thanks alot.

**Comment by Jaffarali123** [comment]
Hello,
Have you solved the problem? If yes, then pls share the solution.

> Hello ll..
> 
> Before I tell you about my issue, let me describe my environment:
> 
> # Environment
> * Operating System: (Windows 10
> * Python Version: `$ python --version 3.7.3`
> 
> I have installed python on path
> C:\Users\Admin\AppData\Local\Programs\Python\Python37-32
> 
> And I installed darkflow in this directory by using the tutorial
> 
> https://appliedmachinelearning.blog/2018/05/27/running-yolo-v2-for-real-time-object-detection-on-videos-images-via-darkflow/#respond
> 
> The problem occurs at this command
> 
> python3 setup.py build_ext --inplace
> 
> Error
> 
> C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\darkflow>python3 setup.py build_ext --inplace
> 'python3' is not recognized as an internal or external command,
> operable program or batch file.
> 
> So i when I run the command python3 setup.py build_ext --inplace i find error
> 
> I also tried it from the folder where it is unable to find the setup.py file
> C:\Users\Admin\AppData\Local\Programs\Python\Python37-32>python3 setup.py build_ext --inplace
> 
> I did everything mentioned in the turorial but as this does not work, I am unable to run the command which detects object in images which is
> 
> ./flow –model cfg/yolov2.cfg –load bin/yolov2.weights –imgdir sample_img –gpu 0.9
> 
> So i get the error which is listed below with the command itself
> 
> C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\darkflow\darkflow\dark>./flow -model cfg/yolov2.cfg -load bin/yolov2.weights -imgdir sample_img -gpu 0.9
> '.' is not recognized as an internal or external command,
> operable program or batch file.
> 
> Please help in running and sorting out the issue.
> 
> Thanks alot.

**Comment by richafrank** [comment]
Hi @Shahroon900 , 

Sounds like this is an issue building [darkflow](https://github.com/thtrieu/darkflow), as opposed to zipline (this project). I'm going to close this, but feel free to re-open with more info, if it is in fact a problem with zipline!
