### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by stocktrader8888** [quantopian/zipline#2479]
Dear Zipline Maintainers,

Python 3.5 is not receiving any bug fixes, only security fixes.  This happened Aug 2017. 
Python 3.6 is not receiving any bug fixes, only security fixes.   This happened at the end of 2018.

I'm playing with some new libraries that have only be designed for use with Python 3.7, so am finding this a little frustrating.

What needs to happen to support Python 3.7?

**Comment by alb7** [comment]
Probably a strong enough demand, so thanks stocktrader8888 for opening this request.
Given the differences between python 3.5 and 3.7, I suspect the effort necessary to support 3.7 is minimal but Quantopian must feel that the need for it is less than minimal. 
I personally won't consider seriously using zipline or contributing in the Quantopian community until they start supporting the latest versions of python and pandas.

**Comment by Peque** [comment]
Related: https://github.com/quantopian/zipline/pull/2512 (maybe a step-by-step approach is more likely to be merged)

**Comment by stocktrader8888** [comment]
Python 3.8 is out now

**Comment by apoptosis66** [comment]
I just spent days trying to get zipline to work right in anaconda, and it kind of works until you start hitting bugs that have been solved in other libraries for a while now but you can't upgrade.  Seriously this project needs to be updated or admit that its so far behind its no longer supported.

**Comment by joshsackos** [comment]
It would be great if zipline was compatible with Python 3.7 and 3.8.

**Comment by ssanderson** [comment]
I've written up a summary issue on working toward support for newer language/library versions here: https://github.com/quantopian/zipline/issues/2616.

Closing this as a dupe of the above in the interest of consolidating. Feel free to comment there with any other info relevant to adding support for newer Pythons.
