### ISSUE TITLE
Use static data for unit tests

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#256]
Instead of using Yahoo! data for unit tests, use hardcoded/static data, so that there is not a network dependency for unit tests.

When we do this two things to keep in mind:

- Should create fresh/faked data, instead of copying over the data from Yahoo! so as to avoid any Terms of Service issues.
- We should have some separate automated job that checks whether a backtest can be run using the Yahoo! data to help detect problems due to connecting to Yahoo!, problems with the trading calendar, etc.

**Comment by llllllllll** [comment]
There is now a `zipline/tests/resources/example_data` which is used to run the examples. The data comes from the quandl WIKI dataset which is public domain
