### ISSUE TITLE
Make tradingcalendar specific to the TradingEnvironment

### ISSUE THREAD

**Issue by mtrovo** [quantopian/zipline#257]
I'm trying to run some backtests against Brazilian stocks and I'm running through some problems related to the calendar used by zipline by default. 
Some of the trading days don't match between the Brazilian trading calendar and the american one and I'm not seeing any easy way to override the calendar without changing the tradingcalendar imports on the zipline internal files (e.g finance/performance/tracker.py).

I'm already overriding the default benchmark using the TradingEnvironment object and it's working fine, my idea is to make the tradingcalendar an attribute of the TradingEnvironment object set at initialization and when not given defaults to the US tradingcalendar that comes by default.

**Comment by llllllllll** [comment]
@ehebert I think we now have support for passing in calendars, correct?

**Comment by ehebert** [comment]
@llllllllll correct https://github.com/quantopian/zipline/blob/master/zipline/finance/trading.py#L72

**Comment by llllllllll** [comment]
kk, can we close this?

**Comment by ehebert** [comment]
I believe so.

**Comment by jpspfaria** [comment]
Nice, i will test this for BM&FBovespa!
