### ISSUE TITLE
No module named 'zipline.api'; 'zipline' is not a package when debugging in VS, VS Code, Pycharm

### ISSUE THREAD

**Issue by Sutyke** [quantopian/zipline#2575]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

* Operating System: (Windows Version 10)
* Python Version: `$ python --version 3.5`
* How did you install Zipline: (`conda`)
* Python packages:  All required as zipline conda environment works excellent with ipython/jupyter notebook, but don't work with debuggers

Now that you know a little about me, let me tell you about the issue I am
having:

Zipline conda environment works fine with VS Code interactive interpretter / Jupyter notebook / VS Interactive interpretter(Ipython or command line works well)

When I run debugger in VS Code / VS  / Pycharm , `import zipline` works, 

When I run debugger in VS Code / VS  / Pycharm , `from zimpline.api import symbol` or `from zipline import run_algorithm` I'm receiving error message `No module named 'zipline.api'; 'zipline' is not a package`

# Description of Issue

* What did you expect to happen?
When run in editor `from zipline.api import symbol, order, record` no error during debugging
* What happened instead?
When run in editor debugger error message `No module named 'zipline.api'; 'zipline' is not a package`

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Write to editor `from zipline.api import symbol, order, record`
2. in VS or VS code, pycharm press debug
3. Error message: `No module named 'zipline.api'; 'zipline' is not a package`
...

## What steps have you taken to resolve this already?
I have checked in VS Code terminal that debugger use correct environment, below is terminal output: 
`
(env_zipline) g:\Google Drive\FI\02_Research\zipline>cd "g:\Google Drive\FI\02_Research\zipline" && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\Users\sutyke\Anaconda3\envs\env_zipline\python.exe c:\Users\sutyke\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 59017 "g:\Google Drive\FI\02_Research\zipline\zipline.py" "
`...

What else:
From command line in env_zipline `python -c "import zipline;print(zipline.__version__)"` i get v1.3.0
From command line in env_zipline `python -c "from zipline.api import symbol, order, record" `no error msg all works fine

Below is error message from pycharm, when I press Run>file.py or Shift+F10: I get error message below:

```
C:\Users\sutyke\Anaconda3\envs\env_zipline\python.exe "G:/Google Drive/FI/02_Research/zipline/zipline.py"
Traceback (most recent call last):
  File "G:/Google Drive/FI/02_Research/zipline/zipline.py", line 3, in <module>
    import zipline
  File "G:\Google Drive\FI\02_Research\zipline\zipline.py", line 5, in <module>
    from zipline.api import symbol, order, record
ImportError: No module named 'zipline.api'; 'zipline' is not a package

Process finished with exit code 1
```

Or if I write in pycharm editor `from zipline import run_algorithm` and run Shift+F10 

```
C:\Users\sutyke\Anaconda3\envs\env_zipline\python.exe "G:/Google Drive/FI/02_Research/zipline/zipline.py"
Traceback (most recent call last):
  File "G:/Google Drive/FI/02_Research/zipline/zipline.py", line 3, in <module>
    from zipline import run_algorithm
  File "G:\Google Drive\FI\02_Research\zipline\zipline.py", line 3, in <module>
    from zipline import run_algorithm
ImportError: cannot import name 'run_algorithm'


Process finished with exit code 1
```

Sincerely,
`$ whoami`

**Comment by willianpaixao** [comment]
I just replicated those steps and worked fine for me.
I'm using the latest version of conda and Pycharm.

**Comment by bhit** [comment]
Curiously, I experience the same issue in Atom with the Hydrogen plugin but not in the command line

**Comment by mariope** [comment]
https://stackoverflow.com/questions/43207427/using-anaconda-environment-in-atom <https://stackoverflow.com/questions/43207427/using-anaconda-environment-in-atom>

**Comment by taliarhodes** [comment]
Closing as this appears to be an issue with certain IDE's environments and recognition of the installation, not an issue specific to Zipline.
