### ISSUE TITLE
IEX's API changed, it's not able to fetch the SPY benchmark data

### ISSUE THREAD

**Issue by yesme** [quantopian/zipline#2577]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Ubuntu 18.04.3

<details>

* Operating System: Linux shareit-gpu-01 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 3.6.8
* Python Bitness: 64
* How did you install Zipline: PIP3
* Python packages:
alembic==1.2.1
alphalens==0.3.6
attrs==19.3.0
backcall==0.1.0
bcolz==0.12.1
bleach==3.1.0
Bottleneck==1.2.1
certifi==2019.9.11
cffi==1.13.1
chardet==3.0.4
Click==7.0
contextlib2==0.6.0.post1
cryptography==2.8
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.29.13
datashape==0.5.2
decorator==4.4.0
defusedxml==0.6.0
empyrical==0.5.3
entrypoints==0.3
ffn==0.3.4
filelock==3.0.12
future==0.18.1
idna==2.8
importlib-metadata==0.23
intervaltree==3.0.2
ipdb==0.12.2
ipykernel==5.1.3
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.0
jsonschema==3.1.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
kiwisolver==1.1.0
Logbook==1.5.3
lru-dict==1.1.6
lxml==4.4.1
Mako==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.1
metautils==0.1.2
mistune==0.8.4
more-itertools==7.2.0
multipledispatch==0.6.0
nbconvert==5.6.1
nbformat==4.4.0
networkx==1.11
notebook==6.0.1
numexpr==2.7.0
numpy==1.17.3
odo==0.5.0
packaging==19.2
pandas==0.22.0
pandas-datareader==0.8.1
pandocfilters==1.4.2
parso==0.5.1
patsy==0.5.1
pexpect==4.7.0
pgcontents==0.5.3
pickleshare==0.7.5
pkg-resources==0.0.0
pluggy==0.13.0
prometheus-client==0.7.1
prompt-toolkit==2.0.10
psycopg2==2.8.4
ptyprocess==0.6.0
py==1.8.0
pycparser==2.19
pyfolio==0.9.2
Pygments==2.4.2
pyparsing==2.4.2
pyrsistent==0.15.4
python-dateutil==2.8.0
python-editor==1.0.4
pytz==2019.3
PyYAML==5.1.2
pyzmq==18.1.0
qgrid==1.1.1
qrisk==0.1.6
qtconsole==4.5.5
requests==2.22.0
requests-file==1.4.3
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
six==1.12.0
sortedcontainers==2.1.0
SQLAlchemy==1.3.10
statsmodels==0.10.1
tables==3.6.0
tabulate==0.8.5
terminado==0.8.2
testpath==0.4.2
toml==0.10.0
toolz==0.10.0
tornado==6.0.3
tox==3.14.0
trading-calendars==1.11.0
traitlets==4.3.3
urllib3==1.25.6
virtualenv==16.7.7
warp-prism==0.1.1
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1
zipline==1.3.0
zipp==0.6.0

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# IEX (https://iextrading.com/) API changed, it's not able to fetch the SPY benchmark data

* Run the buyaapl.py sample in the tutorial.
* SPY benchmark data can't be fetched.

## What steps have you taken to resolve this already?

I changed the code in zipline/data/benchmarks.py accordingly. A pull request will be submitted soon.
...

Sincerely,
Jacky

**Comment by MichalFoksa** [comment]
@yesme Thank you for you effort I have the same issue.

On to of fixing the issue with benchmark API (which I very much appreciate), I think it would be useful to have a option to completely disable default benchmark.

Cause, in order to run any test, according to #2578, I need to have a API key for iextrading.com but I might not need o have that benchmark.

**Comment by yesme** [comment]
@MichalFoksa Totally understood. I'm quite new to Zipline so it may take me some time to dig deeper into the framework to turn off the benchmark completely without side effect. Please feel free to use my PR #2578 as the quick fix for now so it won't block you. :)

**Comment by bernino** [comment]
I had the same problem and changed benchmarks.py to:

+ import json

and in def get_benchmark... all + and got rid of old requests.get :

    IEX_TOKEN = '...'
    r = requests.get(
        'https://cloud.iexapis.com/stable/stock/{}/chart/5y?token={}'.format(symbol, IEX_TOKEN)
     )
    data = json.loads(r.text)

And SPY downloads with no more trouble.

Are the official maintainers quickly changing this bug for official release?

**Comment by stocktrader8888** [comment]
This is a poor solution.  

There should be no dependency on any particular data vendor.  Consider a user in Asia - IEX has no relevance whatsoever.

A far better solution would be to accept a benchmark from the bundle ingested.

**Comment by timkpaine** [comment]
IEX has international end of day. That being said, the default benchmark for zipline is SPY regardless of region.

**Comment by ssanderson** [comment]
Hi all. I'm going through and consolidating the various issues related to the broken benchmark dependency. I've opened https://github.com/quantopian/zipline/issues/2627 as a single place to track this issue. Feel free to comment there if there's information from this thread that's not captured in that writeup.
