### ISSUE TITLE
Please simplify zipline installation process

### ISSUE THREAD

**Issue by sabirjana** [quantopian/zipline#2618]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by ernestoeperez88** [comment]
Hello @sabirjana . Could you please provide some details about your environment, and what are some of the install steps that are giving you the most trouble.

**Comment by sabirjana** [comment]
Hi @ernestoeperez88, thank you for your response. I am trying to install on window 10 laptop. please find below details
Operating System: Windows 10
Python Version: Python 3.7.3
Python Bitness: 64
1. conda create -n env_zipline python=3.7
2. source activate env_zipline
3. conda install -c Quantopian zipline
If fails at #3

**Comment by sabirjana** [comment]
I could able to resolve the issue for zipline however now facing problem for pyfolio
#########################################
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sabirj\.conda\envs\env_zipline\lib\site-packages\pyfolio\__init__.py", line 4, in <module>
    from . import timeseries
  File "C:\Users\sabirj\.conda\envs\env_zipline\lib\site-packages\pyfolio\timeseries.py", line 25, in <module>
    from sklearn import linear_model
  File "C:\Users\sabirj\.conda\envs\env_zipline\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "C:\Users\sabirj\.conda\envs\env_zipline\lib\site-packages\sklearn\base.py", line 20, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\sabirj\.conda\envs\env_zipline\lib\site-packages\sklearn\utils\__init__.py", line 22, in <module>
    from .murmurhash import murmurhash3_32
  File "__init__.pxd", line 918, in init sklearn.utils.murmurhash
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by samatix** [comment]
Hi @sabirjana, zipline is only supported for python 3.5

**Comment by sabirjana** [comment]
Thank you! As I mentioned I realized that and installed zipline on 3.5 env and its working. However now pyfolio doesn't work in same env.

**Comment by samatix** [comment]
@sabirjana, what's the issue you see when you use pyfolio ? It's supposed to work with zipline

**Comment by sabirjana** [comment]
It finally worked.
Thanks
Sabir
