### ISSUE TITLE
Zipline install fail: "testing is not defined"

### ISSUE THREAD

**Issue by SockPastaRock** [quantopian/zipline#2632]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Linux raspberrypi 4.19.95-v7l+ #1292 SMP Thu Jan 16 15:50:13 GMT 2020 armv7l GNU/Linux
* Python Version: 3.5.6
* Python Bitness: 32
* How did you install Zipline: pip
I have installed dependencies: 
sudo apt-get install libatlas-base-dev python-dev gfortran pkg-config libfreetype6-dev

Then: 

$ pip install cython
$ pip install -U setuptools
$ pip install numpy
$ pip install zipline
----------------------------
Also attempted just installing zipline (these are each in separate virtual envs)
$ pip install zipline

* Python packages:
Cython==0.29.14
numpy==1.18.1

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I run 
$ pip install zipline
and receive an error message

* What did you expect to happen?
Zipline installs successfully

* What happened instead?
I receive the following error:

ERROR: Command errored out with exit status 1:
     command: /home/pi/venvs/py3.5/quant/bin/python3.5 /home/pi/venvs/py3.5/quant/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp0b2ni_jg
         cwd: /tmp/pip-install-muvzoap8/scipy
    Complete output (22 lines):
    setup.py:420: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-wsfuscxq'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Traceback (most recent call last):
      File "/home/pi/venvs/py3.5/quant/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/home/pi/venvs/py3.5/quant/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/pi/venvs/py3.5/quant/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-dnn3clp7/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-dnn3clp7/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 243, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-dnn3clp7/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 540, in <module>
        setup_package()
      File "setup.py", line 516, in setup_package
        from numpy.distutils.core import setup
      File "/tmp/pip-build-env-dnn3clp7/overlay/lib/python3.5/site-packages/numpy/__init__.py", line 152, in <module>
        test = testing.nosetester._numpy_tester().test
    NameError: name 'testing' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/venvs/py3.5/quant/bin/python3.5 /home/pi/venvs/py3.5/quant/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp0b2ni_jg Check the logs for full command output.

Here is how you can reproduce this issue on your machine:

$ cd /usr/src
$ wget https://www.python.org/ftp/python/3.5.6/Python-3.5.6.tgz
$ sudo tar xzf Python-3.5.6.tgz
$ cd Python-3.5.6
$ sudo ./configure --enable-optimizations
$ sudo make altinstall

Edit /home/username/.bashrc to include:
alias python="python3.5"
alias python3="python3.5"
Save and open new terminal

$ python -m venv quant
$ source ./quant/bin/activate

$ sudo apt-get install libatlas-base-dev python-dev gfortran pkg-config libfreetype6-dev

$ pip install cython
$ pip install -U setuptools
$ pip install numpy
$ pip install zipline

I would put the logs here if relevant but idk where zipline writes logs to.

Any help greatly appreciated

**Comment by SockPastaRock** [comment]
I've discovered that this issue is likely related to some compatibility issues with raspberry pi 4 architecture and scipy. Some more info can be found here:

https://raspberrypi.stackexchange.com/questions/8308/how-to-install-latest-scipy-version-on-raspberry-pi/107587#107587

Following the steps from the solution posted there still hasn't resolved my issue. May be some differences for raspberry pi 4 since that solution was posted some time ago. Will keep looking for a way to get this running locally.

**Comment by ssanderson** [comment]
It looks to me like you're failing to install scipy, which is a dependency of Zipline. Since it doesn't look like this is an issue specific to Zipline, I'm going to close this issue for now. Feel free to reopen if you think there's a zipline-specific problem here.
