### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Surfkat** [quantopian/zipline#2648]
Can't get Zipline to run in Python35...this is the most un user-friendly application around...

AttributeError                            Traceback (most recent call last)
<ipython-input-2-ab8bff6e5ffb> in <module>()
----> 1 import zipline

~\Anaconda\lib\site-packages\zipline\__init__.py in <module>()
     21 from trading_calendars import get_calendar
     22 
---> 23 from . import data
     24 from . import finance
     25 from . import gens

~\Anaconda\lib\site-packages\zipline\data\__init__.py in <module>()
----> 1 from . import loader
      2 from .loader import (
      3     load_prices_from_csv,
      4     load_prices_from_csv_folder,
      5 )

~\Anaconda\lib\site-packages\zipline\data\loader.py in <module>()
     28 
     29 
---> 30 logger = logbook.Logger('Loader')
     31 
     32 # Mapping from index symbol to appropriate bond data

AttributeError: module 'logbook' has no attribute 'Logger'

**Comment by richafrank** [comment]
Hi @Surfkat , Sorry for the delayed response. 

What versions of zipline and Logbook do you have installed? `logbook.Logger` should exist (see [their docs](https://logbook.readthedocs.io/en/stable/api/base.html#logbook.Logger)). Are you able to import that attribute yourself with something like `from logbook import Logger`, or is zipline's the only code that fails to import it?

**Comment by Surfcat888** [comment]
tried that...this is the result:

AttributeError: module 'logbook' has no attribute 'Logger'

**Comment by richafrank** [comment]
> whoever built this must really hate Windows ;)

Haha, yea - hard to say the issue without knowing versions and installation steps, but definitely sounds like something is wrong with your Logbook module...

**Comment by richafrank** [comment]
Can you try to reinstall Logbook, maybe from a source distribution?

**Comment by Surfcat888** [comment]
whats the best way to do that?

**Comment by richafrank** [comment]
Sounds like you should first uninstall it with the package manager you used to install it. Once it's re-installed, you can try that import again, even before worrying about zipline.

**Comment by Surfcat888** [comment]
I'll give it a try...

**Comment by richafrank** [comment]
👍
