### ISSUE TITLE
How is the graph generated from the Python source code ?

### ISSUE THREAD

**Issue by ijean** [quantopian/zipline#2662]
Hello,

I want to use Zipline in a personal project and I was wondering how are you constructing the pipeline graph from the Python source code ? It seems that in the end you are parsing strings that represent expressions, but I don't understand how are you creating the expressions. (I wasn't able to find where you are parsing the actual source code into expressions) I would appreciate a hint on where to look in the Zipline code.

Thanks,
Jean

**Comment by ssanderson** [comment]
There isn't any string parsing that happens to render pipelines as graphs. The basic way that code works is that we convert your Pipeline object into a [`TermGraph`](https://github.com/quantopian/zipline/blob/master/zipline/pipeline/graph.py#L26) objject via `Pipeline.to_simple_graph`, and then we convert that into a displayable graph using [GraphViz](https://www.graphviz.org/) (which has to be separately installed) in [`zipline.pipeline.visualize`](https://github.com/quantopian/zipline/blob/master/zipline/pipeline/visualize.py#L152-L168). The code there is loosely modeled on [similar code from Dask](https://github.com/dask/dask/blob/master/dask/dot.py).

**Comment by ijean** [comment]
Thanks, but my question was on how are you generating the expressions graph (not on how you draw it). Specifically, I'm interested in how you get from the Python code to the expressions depending on x_0, x_1 ... and so on.

**Comment by ssanderson** [comment]
The code that converts from Pipeline API objects into a graph representation is the `TermGraph` class linked above. Each term has references to all its dependencies, so to build the graph we just start from the pipeline's output terms and recursively traverse their dependencies. 

The text that shows up in the graph nodes is determined by each term's [`graph_repr`](https://github.com/quantopian/zipline/blob/master/zipline/pipeline/visualize.py#L177) method.  The base class implementation of that method just prodcues name of the term's type, but various subclasses override the method to produce more useful information.

The terms whose reprs look like `x_0 + x_1`, etc are all subclasses of the `NumericalExpression` type, which is what's returned by most of the binary operators defined on `Factor`. The methods that actually produce NumericalExpressions are all basically the same, so they're actually dynamically generated and appended onto the `Factor` and `Filter` classes. The code that does that dynamic generation is [here](https://github.com/quantopian/zipline/blob/master/zipline/pipeline/factors/factor.py#L162-L238), and it gets used [here](https://github.com/quantopian/zipline/blob/master/zipline/pipeline/factors/factor.py#L421-L457).
