### ISSUE TITLE
Cant ingest quandl bundle

### ISSUE THREAD

**Issue by Matma724427** [quantopian/zipline#2683]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Mac OS 10.14.6)
* Python Version: `$ python 3.5`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`conda`)
* Python packages: `$ pip freeze` or `$ conda list`

</details>
Hello,

I am trying to ingest the quandl bundle through bash using a variety of prompts;

$ export QUANDL_API_KEY="my_api_key"
$ zipline ingest -b quandl

Settin the API key appears to work, or rather it does not produce an error, but then when I follow with "zipline ingest -b quandl" I get "command not found."

Please help!

Thanks,
Mark

**Comment by richafrank** [comment]
Hi @Matma724427 ,

Sorry for the trouble. Quandl's WIKI Prices data set is no longer maintained, so this integration unfortunately doesn't work anymore (see https://github.com/quantopian/zipline/issues/2603).

Separately, it sounds like `zipline` is not in your path. Either you haven't installed it in your environment, or you haven't activated the conda env in which you did install it.

**Comment by Matma724427** [comment]
AhhI see. Ok, thanks for your help.

Cheers,
Mark
