### ISSUE TITLE
Termux HiddenEye IndexError: Replacement index 3 out of range for positional args tuple

### ISSUE THREAD

**Issue by worsthacker** [quantopian/zipline#2690]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version 2.7`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? 
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by richafrank** [comment]
Hi @worsthacker , 

From the title of this issue, it sounds unrelated to this project (zipline), but hard to tell from the title alone. Feel free to reopen this with more information, if there's something about zipline that's affecting you.

**Comment by worsthacker** [comment]
Okay bro I'm trying to re install HiddenEye tool in termux , and there is one user name and password asking ,which one I provide ?
