### ISSUE TITLE
Support forward testing

### ISSUE THREAD

**Issue by daraul** [quantopian/zipline#2693]
I love zipline, but I want to be able to forward test (paper trade) my algorithms using it, with some (or no) broker. 
There is [zipline-live](https://github.com/zipline-live/zipline), but that doesn't seem actively supported and hasn't been updated since [August, 2019](https://github.com/zipline-live/zipline/commit/de038dbf584980af4f30822f8e5d306bac2a44cb). Could that be because no *zipline* release has been made since? 
If zipline will not be supporting forward testing itself, is there any other recommendation that should work?

**Comment by samatix** [comment]
There are multiple tentatives for paper trading ([pylivetrader by Alpaca](https://github.com/alpacahq/pylivetrader/issues) is the most recent one)

Zipline is a backtester and supports running scenarios in walk forward mode in the past. From my perspective, supporting paper trading falls outside of its functional scope and deserves to be an outside initiative. 

**Disclaimer** I would recommend being careful when using any live or paper trading solution. Usually, the available packages are not clear enough about the risks involved.

**Comment by daraul** [comment]
I agree forward testing/paper trading should be an outside initiative, but I was unable to find one that seemed reliable or even actively supported that worked with zipline, leading me to believe the way forward (for me) was the either fork zipline to do that, or ask you guys for help :smile: 

I can't find any [mention of pylivetrader in the zipline docs](https://www.zipline.io/search.html?q=pylivetrader&check_keywords=yes&area=default), maybe it could be added as a recommendation for those wanting to paper trade their strategies? 

I'll close this, now, as my my problem is solved at least.

**Comment by samatix** [comment]
@daraul , I think for the same reasons that you mentioned before on packages not being maintained and taking into account the risks involved in paper or live trading, endorsing a package doesn't serve Zipline's community.
