### ISSUE TITLE
Custom Data Bundles raising assertion error:

### ISSUE THREAD

**Issue by jmaslek** [quantopian/zipline#2707]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: macOS
* Python Version: 3.6
* Python Bitness: 64 probably
* How did you install Zipline: pip3 install zipline
* Python packages: relevant: pandas==0.22.0
,zipline==1.3.0,  pandas-datareader==0.8.1

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I was trying to ingest a custom bundle Of 1000+ csv files.
* What happened instead?

```
> AssertionError: Got 83 rows for daily bars table with first day=2020-01-06, last day=2020-05-13, expected 90 rows.
> Missing sessions: [Timestamp('2020-01-10 00:00:00+0000', tz='UTC'), Timestamp('2020-01-17 00:00:00+0000', tz='UTC'), Timestamp('2020-01-24 00:00:00+0000', tz='UTC'), Timestamp('2020-01-31 00:00:00+0000', tz='UTC'), Timestamp('2020-02-07 00:00:00+0000', tz='UTC'), Timestamp('2020-02-14 00:00:00+0000', tz='UTC'), Timestamp('2020-02-21 00:00:00+0000', tz='UTC')]
> Extra sessions: []
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.  Ingest with custom bundle, but take out some days out of one csv file.
...

## What steps have you taken to resolve this already?
I am going through my script to create the csv to try and make sure they are all the same size.
...

# Anything else?
I am curious if there is any way that I can just tell the ingest to ignore that, or fill with nan values.
...

Sincerely,
James

**Comment by cemal95** [comment]
I got the same problem, i compared by index dates with NYSE trading calendar from pandas, all most all csv have the dame time index, bjt zipline doesnt except it
