### ISSUE TITLE
Benchmark troubles

### ISSUE THREAD

**Issue by RayVR** [quantopian/zipline#271]
Perhaps I'm just missing where this is documented. How do I turn off any attempt to access Yahoo? I have no interest in their data, and even if I did, I am not able to access it.

**Comment by FreddieV4** [comment]
x-ref #1812

**Comment by FreddieV4** [comment]
Going to close this as I believe Eddie has answered this question, and also because we don't use Yahoo for benchmarking anymore.

**Comment by cyniphile** [comment]
Getting this issue, seems to be because google is not returning the proper data.  The following code only returns pricing back to 2016-9-15

```
import pandas_datareader.data as pd_reader
import datetime as dt

pd_reader.DataReader(
        'SPY',
        'google',
        dt.datetime(2009,1,1),
        dt.datetime(2017,1,1),
    )

```
Would be helpful to have a better error...took awhile to debug this.
