### ISSUE TITLE
JSONDecodeError while running First Example

### ISSUE THREAD

**Issue by kulchidambar** [quantopian/zipline#2712]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

My Environment is Python 3.5 with Windows-10 operating system. 

When I try to run example "buyapple.py" from IPython Jupiter Notebook. I am getting following error ""

* Operating System: (Windows Version or `Windows-10`)
* Python Version: `$ python --version 3.5`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`conda`,conda install -c Quantopian zipline `)
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

#When I try to run example "buyapple.py" from IPython Jupiter Notebook. I am getting following error "JSONDecodeError "

* It was expected to see a Plot of Symbol "AAPL for date range. 
* But I get error message as below
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Use code `from zipline.api import order, record, symbol
from zipline.finance import commission, slippage
from zipline import run_algorithm

def initialize(context):
    context.asset = symbol('AAPL')

    # Explicitly set the commission/slippage to the "old" value until we can
    # rebuild example data.
    # github.com/quantopian/zipline/blob/master/tests/resources/
    # rebuild_example_data#L105
    context.set_commission(commission.PerShare(cost=.0075, min_trade_cost=1.0))
    context.set_slippage(slippage.VolumeShareSlippage())

def handle_data(context, data):
    order(context.asset, 10)
    record(AAPL=data.current(context.asset, 'price'))

# Note: this function can be removed if running
# this algorithm on quantopian.com
def analyze(context=None, results=None):
    import matplotlib.pyplot as plt
    # Plot the portfolio and asset data.
    ax1 = plt.subplot(211)
    results.portfolio_value.plot(ax=ax1)
    ax1.set_ylabel('Portfolio value (USD)')
    ax2 = plt.subplot(212, sharex=ax1)
    results.AAPL.plot(ax=ax2)
    ax2.set_ylabel('AAPL price (USD)')

    # Show the plot.
    plt.gcf().set_size_inches(18, 8)
    plt.show()

results= run_algorithm(start= '2019-1-1', end='2020-5-15', initialize=initialize, capital_base=100000, handle_data=handle_data, analyze=analyze)`
2. Set Quandl API Key and Ingest Data from Quandl
3. Run the cell with code
...

## What steps have you taken to resolve this already?
 I have tried to look for error on Github. But I did not find solution for this error.

# Anything else?

...

Sincerely,
`Chidambar Kulkarni`

**Comment by richafrank** [comment]
Hi @kulchidambar , I can't tell definitively without a traceback, but I think this is probably the same as https://github.com/quantopian/zipline/issues/2607. I'm going to close this in favor of https://github.com/quantopian/zipline/issues/2627 as well, but let us know if this is actually different.
