### ISSUE TITLE
csv bundle ingestion error

### ISSUE THREAD

**Issue by burak-premind** [quantopian/zipline#2719]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
<details>
* Operating System: macOS Catalina
* Python Version: Python 3.5.6 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: alabaster==0.7.12
alembic==0.7.7
anaconda-client==1.7.2
appnope==0.1.0
asn1crypto==0.24.0
astroid==1.6.5
Babel==2.8.0
backcall==0.1.0
bcolz==0.12.1
bleach==3.1.0
Bottleneck==1.2.1
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
Click==7.0
cloudpickle==1.4.1
clyent==1.2.2
contextlib2==0.6.0.post1
cryptography==2.3.1
cycler==0.10.0
cyordereddict==0.2.2
Cython==0.28.5
decorator==4.4.1
defusedxml==0.6.0
docutils==0.14
empyrical==0.5.0
entrypoints==0.2.3
idna==2.7
imagesize==1.2.0
intervaltree==2.1.0
ipykernel==4.10.0
ipython==6.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.1
isort==4.3.4
jedi==0.12.1
Jinja2==2.10.3
joblib==0.14.1
jsonschema==2.6.0
jupyter-client==5.3.3
jupyter-core==4.5.0
keyring==13.2.1
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
Logbook==0.12.5
lru-dict==1.1.4
lxml==4.2.5
Mako==1.1.0
MarkupSafe==1.0
matplotlib==3.0.0
mccabe==0.6.1
mistune==0.8.3
mkl-fft==1.0.6
mkl-random==1.0.1
multipledispatch==0.6.0
nb-anacondacloud==1.4.0
nb-conda==2.2.1
nb-conda-kernels==2.1.0
nbconvert==5.5.0
nbformat==5.0.4
nbpresent==3.0.2
networkx==1.11
notebook==5.6.0
numexpr==2.6.1
numpy==1.14.6
numpydoc==0.9.2
packaging==20.3
pandas==0.22.0
pandas-datareader==0.8.1
pandocfilters==1.4.2
parso==0.6.0
patsy==0.5.0
pexpect==4.6.0
pickleshare==0.7.4
prometheus-client==0.7.1
prompt-toolkit==1.0.15
psutil==5.4.7
ptyprocess==0.6.0
pycodestyle==2.6.0
pycparser==2.19
pyflakes==2.2.0
pyfolio==0.9.2
Pygments==2.5.2
pylint==1.9.2
pyOpenSSL==18.0.0
pyparsing==2.4.6
PySocks==1.6.8
python-dateutil==2.8.1
pytz==2019.3
PyYAML==3.13
pyzmq==17.1.2
QtAwesome==0.7.0
qtconsole==4.7.4
QtPy==1.9.0
requests==2.20.1
requests-file==1.4.3
rope==0.17.0
scikit-learn==0.22.1
scipy==1.1.0
seaborn==0.9.1
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==2.0.0
sortedcontainers==2.0.5
Sphinx==3.0.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
spyder==3.3.1
spyder-kernels==0.2.6
SQLAlchemy==1.2.11
statsmodels==0.9.0
tables==3.4.4
TBB==0.1
terminado==0.8.1
testpath==0.4.4
toolz==0.10.0
tornado==5.1.1
trading-calendars==1.11.1
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.1
wrapt==1.10.11
zipline==1.3.0

</details>

Now that you know a little about me, let me tell you about the issue I am having:

# Description of Issue

* What did you expect to happen? I downloaded daily OHLC volume, dividend, split data from Alpha Vantage and tried to ingest the data into Zipline as a 'csv' file. To do so, I added the following lines of code into extensions.py and expected to run this command (zipline ingest -b custom-csvdir-bundle) in Terminal to create my bundle.

#----------------------------------------------------------------------
import pandas as pd

from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities

start_session = pd.Timestamp('2020-1-7', tz='utc')
end_session = pd.Timestamp('2020-5-29', tz='utc')
path = '/Users/burakozkan/Google Drive (burak@premind.ai)/Premind_Light/MarketData/Daily/ALL/'

register(
    'custom-csvdir-bundle',
    csvdir_equities(
        ['daily'],
        path,
    ),
    calendar_name='NYSE', # US equities
    start_session=start_session,
    end_session=end_session
)
#----------------------------------------------------------------------
* What happened instead? It errorred out with the following traceback message

Traceback (most recent call last):
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.3.0', 'console_scripts', 'zipline')()
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/lib/python3.5/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/lib/python3.5/site-packages/zipline/__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 27, in <module>
    from zipline.algorithm import TradingAlgorithm
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/lib/python3.5/site-packages/zipline/algorithm.py", line 68, in <module>
    from zipline.finance.blotter import SimulationBlotter
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/lib/python3.5/site-packages/zipline/finance/blotter/__init__.py", line 16, in <module>
    from .simulation_blotter import SimulationBlotter
  File "/Users/burakozkan/anaconda3/envs/Backtesting_Zip/lib/python3.5/site-packages/zipline/finance/blotter/simulation_blotter.py", line 43, in <module>
    class SimulationBlotter(Blotter):
TypeError: 'str' object is not callable

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. add the code above into extensions.py
2. use one of the csv files attacted as a sample OHLC/Vol/Div/Split
3. run the same terminal command 
...

## What steps have you taken to resolve this already?
Read the blogposts and other issues raised.
...

# Anything else?
Nope!
[AAPL.csv.zip](https://github.com/quantopian/zipline/files/4708062/AAPL.csv.zip)

...

Sincerely,
Burak Ozkan

**Comment by cemal95** [comment]
Try reduce your path to '/path/to/data/daily', it seems like you have extra directories that shouldnt be there according to the documentation. Look again at the csvdir.py

**Comment by mariope** [comment]
The csvdir.py script appends the minute a daily folders by default. So, the main path shouldn’t includes this names. In addition your data must be inside these folders.

————-
Mario

**Comment by burak-premind** [comment]
I'm a bit confused. My data is in the folder specified in the code. Do I need to abide by a specific folder naming convention? I don't think the folder structure I use in my local harddrive has anything to do with this error message "TypeError: 'str' object is not callable"? Any thoughts?

**Comment by cemal95** [comment]
Did you try the exact way the documentation describes?  My daily folder consists of all the data csv files. Also check your path, is says it can read strings in your path

**Comment by burak-premind** [comment]
The documentation is also confusing imho. (https://www.zipline.io/bundles.html#ingesting-data-from-csv-files). It tells you to edit extension.py in folder "~/.zipline/extension.py". But there's no such file. Instead, I found extension**s**.py and I've been tinkering with that to see what happens. Are you referring to another document?

**Comment by cemal95** [comment]
Yes thats the one you need, you have to register it there. Look at the screenshot I posted earlier. If you register and your path is correct, then it should be fine.

**Comment by burak-premind** [comment]
Thanks so much, Cemal. Much appreciated. It worked:))

**Comment by cemal95** [comment]
no worries :)
