### ISSUE TITLE
Assertion error : Got 1510 rows for daily bars table with first day=2010-01-04, last day=2015-12-31, expected 0 rows.

### ISSUE THREAD

**Issue by learqt** [quantopian/zipline#2724]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Windows 10
* How did you install Zipline: Conda

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I want to ingest a CSV corresponding to Apple for five years.
* What happened instead?

<img width="947" alt="pb_zipline" src="https://user-images.githubusercontent.com/63244380/84765916-3e35e800-afd0-11ea-8fd2-c88f195df08c.PNG">

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Download data from Quandl or Yahoo
2. register(
    'eu_stocks',  # name we select for the bundle
    csvdir_equities(
        # name of the directory as specified above (named after data frequency)
        ['daily'],
        # path to directory containing the
        'path',
    ),
    calendar_name='NYSE',  # Euronext Paris
    start_session=start_session,
    end_session=end_session
)
3. Try to ingest the bundle
...

## What steps have you taken to resolve this already?
Reindexing with NYSE calendar + try others stocks + upgrade Trading Calendar
...

# Anything else?

...

Sincerely,
`$ lea`

**Comment by cemal95** [comment]
Hi Lea, I believe I have the same issue, #2700

**Comment by cemal95** [comment]
@learqt  Did you solve it?

**Comment by cemal95** [comment]
Hi Richard, @richafrank , I also have this issue. It is similar to the previous issue I tagged you in
