### ISSUE TITLE
corrupted core.py incorrect size & No module

### ISSUE THREAD

**Issue by daandaandot** [quantopian/zipline#2737]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Ubuntu20
* Python Version: Python 3.5.6 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Zipline: conda
* Python packages: 
[package_python_list.txt](https://github.com/quantopian/zipline/files/4941796/package_python_list.txt)

Hey. I'm trying to use zipline and run backtest with it but I get into problem.
Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
run it and using it.
* What happened instead?
problem with using it.
when I imported zipline and run it it said :
No module named 'zipline.data.adjustments'
![Screenshot from 2020-07-18 18-35-49](https://user-images.githubusercontent.com/63190166/87854209-8d4f9f80-c925-11ea-9c7c-9898a9a9aec6.png)
when I was installing it , it gave this problem at the end :
![Screenshot from 2020-07-18 18-37-20](https://user-images.githubusercontent.com/63190166/87854231-bec86b00-c925-11ea-9b8f-6cc487705be6.png)
so maybe there is something wrong with that.
attached the core.py text into a txt file for you to see:
[core.txt](https://github.com/quantopian/zipline/files/4941789/core.txt)

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

completely removed the env. the reinstalled it again and it's happening again.

# Anything else?

...

Sincerely,
`dan`

**Comment by KrishnaRachh** [comment]
same issues 
if anyone has  a solution pls help
