### ISSUE TITLE
Buy and sell orders 

### ISSUE THREAD

**Issue by Monsieurvishal** [quantopian/zipline#2745]
How can I specifically buy and sell an asset?

I am creating an algorithm which generates buy and sell signal from technical analysis. I want to go long and short trade using my analyzed signal.

How to proceed?

Sincerely,
Vishal

**Comment by cemal95** [comment]
The way I did it was for a pairs trading strategy for my thesis.

if signal for position:
order_target_percent(stock1, weight)
order_target_percent(stock2, -weight)

the minus sign tells the algo to go short

**Comment by Monsieurvishal** [comment]
@cemal95 
I want to do go short and long for the same stock.

**Comment by cemal95** [comment]
Then apply it to the above, you can also use order(stock, quantitiy) or order_target(stock, %) and mess around with these. But, why go long and short the same stock? could you not use the net value of you positions to either go long or short once?

**Comment by Monsieurvishal** [comment]
@cemal95 
I am using a sma crossover to go either long or short on the same stock.

**Comment by Monsieurvishal** [comment]
@cemal95
Thanks a lot it helped.
