### ISSUE TITLE
zipline 1.4.0 install issue?

### ISSUE THREAD

**Issue by marlowequart** [quantopian/zipline#2751]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Mac
* Python Version: 3.5.6

</details>

I just updated from zipline 1.3.0 to 1.4.0. I don't know if I did something wrong, but I am trying to ingest some data and got an error and noticed that the executable zipline.exe in my environment folder still lists zipline as 1.3.0. here is the executable file:

```
#!/opt/anaconda3/envs/zipline/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'zipline==1.3.0','console_scripts','zipline'
__requires__ = 'zipline==1.3.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('zipline==1.3.0', 'console_scripts', 'zipline')()
    )
```

Did I do something wrong when I updated? when I run Conda list it shows I am still 1.3.0, but I know that when I ran "conda update zipline -c quantopian" it went in and updated some of the files because I lost my constants in constants.py

**Comment by marlowequart** [comment]
I created a new environment and installed zipline using Conda install, and it installs version 1.3.0. Is this right? When I run the Conda update after install it still shows that its installing 1.3.0. Am I doing something dumb?

**Comment by richafrank** [comment]
Hi @marlowequart ,

Thanks for the issue! The osx conda build isn't currently automated, and we forgot to build the packages for the 1.4.0 release! 

I just uploaded them. Hopefully that solves this for you.

**Comment by marlowequart** [comment]
Thanks for the help! When I ran the "conda update zipline -c quantopian", it updated two packages, empyrical to 0.5.0 and trading-calendars to 1.11.1. It still shows my version as 1.3.0

When I create a new environment and install with "Conda install zipline=1.4.0 -c Quantopian" it lists my version of zipline as 1.4.0

**Comment by richafrank** [comment]
Hmm, that's pretty odd, since zipline 1.3.0 already required "empyrical>=0.5.0", and 0.5.0 for osx/py35 was published 2 years ago. Not sure what was messed up about your first environment, but sounds like your new environment is updated to the latest?

**Comment by marlowequart** [comment]
I created a new environment where I installed zipline 1.4.0 and its working fine so I am just going to use that now, seems to be working good so far.
