### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by marlowequart** [quantopian/zipline#2752]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: osx
* Python Version: 3.5.6
* Python Bitness: 64
* How did you install Zipline: Conda
* Python packages:
zipline version: 1.4.0
pandas version: 0.22.0
matplotlib version: 2.2.2
numpy version: 1.14.6
scipy version: 1.1.0
pyfolio version: 0.9.2
pytz version 2019.3
ipython version: 7.9.0

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

Trying to run a basic script in the new 1.4.0 that I had working before in 1.3.0, any idea what I am doing wrong or how I might trouble shoot this?

Here is the error I am getting:

> | => python basic_zipline.py
> Traceback (most recent call last):
>   File "basic_zipline.py", line 105, in <module>
>     bundle='quantopian-quandl')
>   File "/opt/anaconda3/envs/zipline14/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 407, in run_algorithm
>     benchmark_spec=benchmark_spec,
>   File "/opt/anaconda3/envs/zipline14/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 203, in _run
>     data_frequency=data_frequency,
>   File "/opt/anaconda3/envs/zipline14/lib/python3.5/site-packages/zipline/finance/trading.py", line 38, in __init__
>     assert type(start_session) == pd.Timestamp
>   AssertionError

Here is my code:
```
# Import Zipline functions that we need
from zipline import run_algorithm
from zipline.api import order_target_percent, symbol

# Import date and time zone libraries
from datetime import datetime
import pytz

# Import visualization
import matplotlib.pyplot as plt


def initialize(context):
    context.set_benchmark(symbol('AAPL'))
    # Which stock to trade
    context.stock = symbol('MSFT')
    
    # Moving average window
    context.index_average_window = 100
    
def handle_data(context, data):
    # Request history for the stock
    equities_hist = data.history(context.stock, "close", 
                                 context.index_average_window, "1d")
    
    # Check if price is above moving average
    if equities_hist[-1] > equities_hist.mean():
        stock_weight = 1.0
    else:
        stock_weight = 0.0
    
    # Place order
    order_target_percent(context.stock, stock_weight)


def analyze(context, perf):
    print('outputting plots')
    fig = plt.figure(figsize=(12, 8))
    
    # First chart
    ax = fig.add_subplot(311)
    ax.set_title('Strategy Results')
    ax.semilogy(perf['portfolio_value'], linestyle='-', 
                label='Equity Curve', linewidth=3.0)
    ax.legend()
    ax.grid(False)
    
    # Second chart
    ax = fig.add_subplot(312)
    ax.plot(perf['gross_leverage'], 
            label='Exposure', linestyle='-', linewidth=1.0)
    ax.legend()
    ax.grid(True)

    # Third chart
    ax = fig.add_subplot(313)
    ax.plot(perf['returns'], label='Returns', linestyle='-.', linewidth=1.0)
    ax.legend()
    ax.grid(True)
    plt.show()

# Set start and end date
start_date = datetime(1996, 1, 1, tzinfo=pytz.UTC)
end_date = datetime(2018, 1, 31, tzinfo=pytz.UTC)

# Fire off the backtest
results = run_algorithm(
    start=start_date, 
    end=end_date, 
    initialize=initialize, 
    analyze=analyze, 
    handle_data=handle_data,
    metrics_set=None,
    capital_base=10000, 
    data_frequency = 'daily',
    bundle='quantopian-quandl')

```
...

Sincerely,
`$ whoami`

**Comment by marlowequart** [comment]
I didn't do a very good job searching this one out, I found the answer here: https://stackoverflow.com/questions/61513097/how-to-solve-assertionerror-when-running-backtest-on-zipline

I don't really understand why this fixes it, but it does.

**Comment by vagaram** [comment]
I'm facing the same issue. The above StackOverflow link is not helping though. I have installed the latest release of Zipline1.4.1 with python 3.6

**Comment by jpaniagua26** [comment]
I am having the same issue. @vagaram let me know if you find a solution. I will too.

**Comment by rahold** [comment]
For me the stackoverflow link did work. I replaced the block "# Set start and end date" with the code under Solution [1] and now the backtest runs without any error.

**Comment by baslia** [comment]
I am having the same error, when using the code: 
```
start = pd.Timestamp('2015', tz='utc')
end = pd.Timestamp('2018', tz='utc')
```

I am getting a new error: `AttributeError: 'datetime.timezone' object has no attribute 'zone'`

**Comment by Katya047** [comment]
@baslia I am getting the opposite error with this solution :)

`ValueError: Parameter start received with timezone defined as 'UTC' although a Date must be timezone naive.
`
