### ISSUE TITLE
Issue loading data with DataFrameLoader

### ISSUE THREAD

**Issue by rcardinaux** [quantopian/zipline#2754]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Windows 10 Version 1909
* Python Version: python 3.5.6
* How did you install Zipline: conda

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I am willing to switch from quantopian.com to offline in order to use a Database I have been building on my computer. As far as I could see, my best option to import my data into the zipline environment is to use the loader DataFrameLoader, considering I am not working with csv files.

I found a very simple example on how to use the DataFrameLoader in the issue #911 , which I thought could be good to start with. Below the code I am working with:

```
from zipline.data import bundles
from zipline.pipeline import Pipeline
from zipline.pipeline.data import USEquityPricing
from zipline.pipeline.data import Column  
from zipline.pipeline.data import DataSet
from zipline.pipeline.engine import SimplePipelineEngine
from zipline.pipeline.filters import StaticAssets
from zipline.pipeline.loaders import USEquityPricingLoader
from zipline.pipeline.loaders.frame import DataFrameLoader
from zipline.utils.calendars import get_calendar

import numpy as np
import pandas as pd

trading_calendar = get_calendar('NYSE')
bundle_data = bundles.load('quantopian-quandl')

# Set up Custom Data Source for two sids for DataFrameLoader
class MyDataSet(DataSet):  
    column_A = Column(dtype=float)
    column_B = Column(dtype=bool) 

#RC: added tz='UTC' as recommended in issue
dates = pd.date_range('2014-01-01', '2017-01-01', tz='UTC')
assets = bundle_data.asset_finder.lookup_symbols(['A', 'AAL'], as_of_date=None)
sids = pd.Int64Index([asset.sid for asset in assets])

# The values for Column A will just be a 2D array of numbers ranging from 1 -> N.  
column_A_frame = pd.DataFrame(  
    data=np.arange(len(dates)*len(assets), dtype=float).reshape(len(dates), len(assets)),  
    index=dates,
    columns=sids,
)

# Column B will always provide True for 0 and False for 1.
column_B_frame = pd.DataFrame(data={sids[0]: True, sids[1]: False}, index=dates)

loaders = {  
    MyDataSet.column_A: DataFrameLoader(MyDataSet.column_A, column_A_frame),  
    MyDataSet.column_B: DataFrameLoader(MyDataSet.column_B, column_B_frame),  
}

def my_dispatcher(column):
    return loaders[column]

# Set up pipeline engine

# Loader for pricing
#RC: added without_fx
pipeline_loader = USEquityPricingLoader.without_fx(
    bundle_data.equity_daily_bar_reader,
    bundle_data.adjustment_reader
)

def choose_loader(column):
    if column in USEquityPricing.columns:
        return pipeline_loader
    return my_dispatcher(column)

engine = SimplePipelineEngine(
    get_loader=choose_loader,
    #RC: removed calendar from arguments
    #calendar=trading_calendar.all_sessions,
    asset_finder=bundle_data.asset_finder,
)

p = Pipeline(
    columns={
        'price': USEquityPricing.close.latest,
        'col_A': MyDataSet.column_A.latest,
        #'col_B': MyDataSet.column_B.latest
    },
    screen=StaticAssets(assets)
)

df = engine.run_pipeline(
    p,
    pd.Timestamp('2016-01-05', tz='utc'),
    pd.Timestamp('2016-01-07', tz='utc')
)

print(df)
```
Please note the two following remarks:

1. I have had to go through the procedure described in the issue #2517, which in essence implied setting manually the country_code to 'US' in the 'exchanges' table of my quandl bundle, since I was getting the following error message: 
`ValueError: Failed to find any assets with country_code 'US'`

2. The comments in the code above preceded by the letters 'RC', indicates changes I have had to do on the code published in the issue #911 . I assume these changes were required because of some changes in the zipline library committed since the issue was published.

* What did you expect to happen?
I am expecting the print to display the following DataFrame:
![image](https://user-images.githubusercontent.com/49291917/90198556-5066b380-ddd2-11ea-930f-b163b2633d28.png)

* What happened instead?
Instead I get the following error message:
`KeyError: MyDataSet<US>.column_A::float64`

Here is how you can reproduce this issue on your machine:
I assume that running the code above, in the same environment and following the procedure describes above should get you the same results.

## What steps have you taken to resolve this already?
I looked for the error I obtain online, but could not find any relevant information to help me solve it. The reference to 'US' in the error message hints at an issue related to manual adjustement described above in my first remark (issue #2517), but it is just a guess. I tried changing the value of the country_code, but then got again the error message `ValueError: Failed to find any assets with country_code 'US'`.

# Anything else?
Any help would be more than welcome, as this issue is really preventing me from moving forward in my project, and from getting to know better and testing the zipline library.

Sincerely,
Raphaël

**Comment by cecini** [comment]
You should change to 
```
class MyDataSet(DataSet):  
    column_A = Column(dtype=float)
    column_B = Column(dtype=bool) 
    domain= US_EQUITIES
```
```
engine = SimplePipelineEngine(
    get_loader=choose_loader,
    asset_finder=bundle_data.asset_finder,
    default_domain=US_EQUITIES,
)
```
and No need fix the issue about ValueError: Failed to find any assets with country_code 'US'.

**Comment by rcardinaux** [comment]
Hi Cecini,

Thanks for the heads up. It worked out 

> You should change to
> 
> ```
> class MyDataSet(DataSet):  
>     column_A = Column(dtype=float)
>     column_B = Column(dtype=bool) 
>     domain= US_EQUITIES
> ```
> 
> ```
> engine = SimplePipelineEngine(
>     get_loader=choose_loader,
>     asset_finder=bundle_data.asset_finder,
>     default_domain=US_EQUITIES,
> )
> ```
> 
> and No need fix the issue about ValueError: Failed to find any assets with country_code 'US'.

**Comment by rcardinaux** [comment]
Hi Cecini,

Thanks for the heads up. It worked out with the domain set to US_EQUITIES.

I tried to revert the change applied to correct the error message `ValueError: Failed to find any assets with country_code 'US'` , but still got the message and did not manage to get the code running.

Cheers,
Raphaël

**Comment by cecini** [comment]
on zipline 1.4 master, there is no this issue. Maybe you can specify the default bundle quantopian-bundle,not the quandl.

**Comment by rcardinaux** [comment]
I am using the default bundle quantopian-quandl, and zipline 1.4. 

Not sure why I get this error message, but it's not blocking for me at the moment since the workaround mentioned above does the trick. So, as far as I am concerned, this issue can be closed.

Thanks @cecini for the support.
