### ISSUE TITLE
 Issue (and solution) for running run_algorithm without benchmark_returns

### ISSUE THREAD

**Issue by ghost** [quantopian/zipline#2761]
Dear Zipline Maintainers,

Running run_algorithm without benchmark_returns raises the following NoBenchmark exception:

NoBenchmark: Must specify either benchmark_sid or benchmark_returns.

The issue can be resolved by fixing a bug/removing 'not' in  the from_returns method of the BenchmarkSpec class:

    @classmethod
    def from_returns(cls, benchmark_returns):
        return cls(
            benchmark_returns=benchmark_returns,
            benchmark_file=None,
            benchmark_sid=None,
            benchmark_symbol=None,
            no_benchmark=benchmark_returns is not None,
        )

Sincerely,
Flounder

**Comment by flounderhost** [comment]
Great, glad to hear.

**Comment by arisliang** [comment]
In which version the bug is fixed? I'm running zipline 1.4.1, and still got this error from the beginner tutorial https://www.zipline.io/beginner-tutorial.html.
