### ISSUE TITLE
KeyError: 'TURKEY'

### ISSUE THREAD

**Issue by BibiTheLamb** [quantopian/zipline#2843]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Ubuntu 18.04 LTS)
* Python Version: 3.8.14
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages:
alabaster==0.7.8
alembic==1.8.1
apturl==0.5.2
asn1crypto==0.24.0
astroid==1.6.0
Babel==2.4.0
bcolz-zipline==1.2.4
bleach==2.1.2
Bottleneck==1.3.5
Brlapi==0.6.6
certifi==2018.1.18
chardet==3.0.4
charset-normalizer==2.1.1
click==6.7
cloudpickle==0.5.2
colorama==0.3.7
command-not-found==0.3
cryptography==2.1.4
cupshelpers==1.0
Cython==0.29.32
decorator==4.1.2
defer==1.0.6
devscripts===2.17.12ubuntu1.1
distro-info===0.18ubuntu0.18.04.1
docutils==0.14
empyrical-reloaded==0.5.8
entrypoints==0.2.3.post1
exchange-calendars==3.3
gpg==1.10.0
greenlet==1.1.3
h5py==3.7.0
html5lib==0.999999999
httplib2==0.9.2
idna==2.6
imagesize==0.7.1
importlib-metadata==4.12.0
importlib-resources==5.9.0
intervaltree==3.1.0
ipykernel==4.8.2
ipython==5.5.0
ipython_genutils==0.2.0
iso3166==2.1.1
iso4217==1.11.20220401
isort==4.3.4
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.2
jupyter-core==4.4.0
keyring==10.6.0
keyrings.alt==3.0
korean-lunar-calendar==0.3.1
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
lazy-object-proxy==1.3.1
Logbook==1.5.3
logilab-common==1.4.1
louis==3.5.0
lru-dict==1.1.8
lxml==4.9.1
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.0
mccabe==0.6.1
mistune==0.8.3
multipledispatch==0.6.0
multitasking==0.0.11
mysql-connector-python==2.1.6
nbconvert==5.3.1
nbformat==4.4.0
netifaces==0.10.4
networkx==2.8.6
numexpr==2.8.3
numpy==1.23.3
numpydoc==0.7.0
oauth==1.0.1
olefile==0.45.1
packaging==21.3
pandas==1.4.4
pandas-datareader==0.10.0
pandocfilters==1.4.2
parso==0.1.1
patsy==0.5.2
pexpect==4.2.1
pickleshare==0.7.4
Pillow==5.1.0
pkg_resources==0.0.0
prompt-toolkit==1.0.15
protobuf==3.0.0
psutil==5.4.2
pycairo==1.16.2
pycodestyle==2.3.1
pycrypto==2.6.1
pycups==1.9.73
pyflakes==1.6.0
Pygments==2.2.0
PyGObject==3.26.1
pylint==1.8.3
pyluach==2.0.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyparsing==3.0.9
pyRFC3339==1.0
python-apt==1.6.5+ubuntu0.7
python-dateutil==2.8.2
python-debian==0.1.32
python-interface==1.6.1
python-magic==0.4.16
python-xapp==1.0.0
python-xlib==0.20
pytz==2022.2.1
pyxdg==0.25
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
reportlab==3.4.0
requests==2.28.1
requests-unixsocket==0.1.5
roman==2.0.0
rope==0.10.5
scipy==1.9.1
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
setproctitle==1.1.10
simplegeneric==0.8.1
simplejson==3.13.2
six==1.11.0
sortedcontainers==2.4.0
Sphinx==1.6.7
spyder==3.2.6
SQLAlchemy==1.4.41
statsmodels==0.13.2
system-service==0.3
systemd-python==234
TA-Lib==0.4.25
tables==3.7.0
testpath==0.3.1
toolz==0.12.0
tornado==4.5.3
trading-calendars==2.1.1
traitlets==4.3.2
ubuntu-advantage-tools==27.10
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
unidiff==0.5.4
urllib3==1.22
usb-creator==0.3.3
vboxapi==1.0
virtualenv==15.1.0
wadllib==1.3.2
wcwidth==0.1.7
webencodings==0.5
wrapt==1.9.0
xkit==0.0.0
yfinance==0.1.74
zipline-reloaded==2.2.0
zipp==3.8.1
zope.interface==4.3.2

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

After I managed to finally install successfully zipline in a venv environment, I wanted to test it and ran:

(zipL-py381-croco) sa6@sa6-HP-Z820-Workstation:~$ python
Python 3.8.14 (default, Sep  8 2022, 00:02:10) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zipline.api import order_target, record, symbol

I expected to be able to input new lines of code.

Instead I got this:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/utils/run_algo.py", line 24, in <module>
    from zipline.pipeline.data import USEquityPricing
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/pipeline/__init__.py", line 1, in <module>
    from .classifiers import Classifier, CustomClassifier
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/pipeline/classifiers/__init__.py", line 1, in <module>
    from .classifier import (
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/pipeline/classifiers/classifier.py", line 22, in <module>
    from zipline.pipeline.term import ComputableTerm
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/pipeline/term.py", line 45, in <module>
    from .domain import Domain, GENERIC, infer_domain
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/pipeline/domain.py", line 27, in <module>
    from zipline.country import CountryCode
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/country.py", line 10, in <module>
    class CountryCode(object):
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/country.py", line 55, in CountryCode
    TURKEY = code('TURKEY')
  File "/home/sa6/ML/zipL-py381-croco/lib/python3.8/site-packages/zipline/country.py", line 7, in code
    return countries_by_name[name].alpha2
KeyError: 'TURKEY'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
The Lamb

**Comment by BibiTheLamb** [comment]
issue solved with
pip install iso3166==2.0.2

**Comment by whuHXWang** [comment]
Really thank you, you saved my day!
