### ISSUE TITLE
Figure out why test_transforms:TestTALib.test_talib_with_default_params always has an empty length

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#316]
The commit, 64b2a7377c52cc0a7b8c393cb3f1e4cc28f91392, added a skip of this particular test. (See commit message for fuller details.)

This test should probably be re-enabled, but disabling for now while it has no teeth, so that it does not eat up time spent in tests.

**Comment by freddiev4** [comment]
Looks like this test was removed at some point
