### ISSUE TITLE
NaN volume causes ValueError in slippage.py

### ISSUE THREAD

**Issue by vonbirdie** [quantopian/zipline#321]
I have plugged in a custom datasource that is missing some data. What is causing me problems right now is that the volume is missing on a few places and this causes `ValueError: cannot convert float NaN to integer` in zipline/finance/slippage.py#L217 due to `event.volume` being `NaN` a few rows above.

I'm just wondering if this is expected or if the NaN should have been handled earlier?

**Comment by cwse89** [comment]
I am having this same error. Tried filtering out the NaNs (Fillna, dropna, etc). Nothing seems to fix it. Further more I cant actually see any NaNs in the data I sampled! Any Ideas?
