### ISSUE TITLE
Make treasury curve used by cumulative risk metrics configurable

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#324]
We currently use the 10-year curve for all cumulative risk metrics.

However, whether this is the appropriate curve could be open to debate.

Rather than switch the default, depending on the current leading consensus; the risk rate could be made configurable.

i.e. the should be some way (not sure if we should use a config file, env variables, or configuration in the Python script running the algorithm.) to change the default curve for all of the cumulative, as well as to tune the curve used for the alpha and sortino metrics.

**Comment by richafrank** [comment]
https://github.com/quantopian/zipline/pull/2626 removed the dependency on treasury curves.
