### ISSUE TITLE
Inconsistent data from Yahoo causes crash on simulation

### ISSUE THREAD

**Issue by diegopdomingos** [quantopian/zipline#388]
When running Zipline with ^BVSP benchmark (a simulation with start in 2008-4-1 and end in 2008-5-1), zipline crashs with the following error:

raise LinAlgError("Array must not contain infs or NaNs") numpy.linalg.linalg.LinAlgError: Array must not contain infs or NaNs

This is due a incosistence in Yahoo benchmark data. In Brazil, Tiradentes Holiday is in April 21, but this date is in Yahoo data as zero return.
When running the algorithm, the function handle_market_close() misaligns his "todays_date" with all_benchmark_returns, and RiskMetricsCumulative finally gets "NaN" as valid benchmark returns.

**Comment by pdiffley12** [comment]
I am having the exact same issue. Is anyone able to run zipline without this problem?

**Comment by twiecki** [comment]
It's also reported here: https://github.com/quantopian/zipline/issues/473 with the US benchmark. Can someone try running the buy apple example with the same parameters as in #473?

**Comment by mosesmc52** [comment]
Hi I downloaded zipline to my computer and tried running the apple example on m computer and I am having the same problem.

**Comment by ssanderson** [comment]
@pdiffley12 @mosesmc52 I haven't been able to repro this locally.  My best guess would be that your benchmark data cache somehow acquired bad data.  On Unix-ey operating systems, zipline downloads that data to ~/.zipline/data/.  I'm not sure where it goes on Windows.  Can you try clearing the contents of that directory and running the tutorial example again?

**Comment by twiecki** [comment]
I have tried that but unfortunately without success.

**Comment by mosesmc52** [comment]
I tried clearing my zipline cache and no success as well.

**Comment by jetheurer** [comment]
I'm seeing the same problem.

Python venv includes on Ubuntu 14.04 LTS:
argparse (1.2.1)
backports.ssl-match-hostname (3.4.0.2)
certifi (14.05.14)
docutils (0.12)
ipython (2.4.1)
Jinja2 (2.7.3)
Logbook (0.9.0)
MarkupSafe (0.23)
matplotlib (1.4.2)
mock (1.0.1)
nose (1.3.4)
numpy (1.9.1)
pandas (0.15.2)
pip (1.5.4)
Pygments (2.0.2)
pyparsing (2.0.3)
python-dateutil (2.4.0)
pytz (2014.10)
pyzmq (14.5.0)
requests (2.5.1)
setuptools (2.2)
six (1.9.0)
Sphinx (1.2.3)
tornado (4.1)
wsgiref (0.1.2)
zipline (0.7.0)

**Comment by twiecki** [comment]
Glad that it works, thanks for reporting.
