### ISSUE TITLE
CLI is not creating .pickle file

### ISSUE THREAD

**Issue by aprasad1993** [quantopian/zipline#403]
I tried the basic Moving Average example - http://nbviewer.ipython.org/github/quantopian/zipline/blob/master/docs/tutorial.ipynb

When I try to run the Algorithm I am getting no output. Infact when I try executing: 

run_algo.py --help

I get nothing on my Command Line. Instead it becomes ready to execute the next set of commands!

**Comment by llllllllll** [comment]
The tutorial and cli have been reworked. I imagine this is no longer an issue.
