### ISSUE TITLE
Can zipline use min or sec frequency data?

### ISSUE THREAD

**Issue by cosnis** [quantopian/zipline#407]
hi, dear all

i'm a new zipline user, for now, i have some seconds level OHLC datas in one day.

but when i use zipline to backtest, i get this report:

[2014-10-05 10:49] INFO: Performance: Simulated 1 trading days out of 1.

i tried code like that:

``` python
    algo = TradingAlgorithm(initialize=initialize, handle_data=handle_date)
    algo.run(datas)
```

so, please help me....

**Comment by balut91** [comment]
Hi @freddiev4 ,
When we use minute data the performance results are coming in daily basis.
Could you please help how can we get the perf result on minute basis?
