### ISSUE TITLE
Add ability to define additional variables to run_algo.py script

### ISSUE THREAD

**Issue by hahnicity** [quantopian/zipline#421]
It doesn't have to be anything fancy but it would be nice to be able to specify additional variables from the CLI like

```
run_algo -f path/to/my/algo.py --extra-vars foo=bar baz=bin
```

An environment variable would also suffice

```
ZIPLINE_CONFIG=path/to/my/config.py
run_algo.py -f path/to/my/algo.py
```

**Comment by twiecki** [comment]
This provides the ground work for this to happen: https://github.com/quantopian/zipline/pull/456

**Comment by llllllllll** [comment]
The new cli in 1.0.0 can do this by passing `-Da=b` on the command line. This will make the name `a` have the value `b` in the algoscript.

**Comment by twiecki** [comment]
:+1:
