### ISSUE TITLE
api import magic breaks direct import

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#440]
Without `import zipline`, you can't do `from zipline.api import price` because those functions are not registered yet.

**Comment by laurlaur** [comment]
I cannot use 'from zipline.api import whatever' even if I do 'import zipline' first. Any ideas where I might be going wrong? 

I installed zipline using 'conda install -c Quantopian zipline'.
Thanks

**Comment by twiecki** [comment]
What's the error message?

**Comment by laurlaur** [comment]
>>>import zipline
>>>from zipline.api import history
Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
ImportError: No module named api

**Comment by twiecki** [comment]
Can you print zipline.__version__?

**Comment by laurlaur** [comment]
I haven't used Anaconda before so cannot explain what is going on.. but

I can do it in Anaconda command prompt:

Added C:\Anaconda and C:\Anaconda\Scripts to PATH.

C:\Anaconda>python
Python 2.7.8 |Anaconda 2.1.0 (32-bit)| (default, Jul  2 2014, 15:13:35) [MSC v.1
500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import zipline
>>> print zipline.__version__
0.7.0

I cannot do it using the Windows command prompt:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Laur>python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipline
>>> print zipline.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
>>>

Hope you can help

**Comment by laurlaur** [comment]
got it sorted by manually downloading and installing using python setup.py install.

Thank you anyway!

**Comment by richafrank** [comment]
@twiecki Since `zipline/__init__.py` imports TradingAlgorithm, I think this *should* work, and it does work for me:
```python
In [1]: from zipline.api import symbol
```
```python
In [2]: from zipline.api import price
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-0fb9877edb87> in <module>()
----> 1 from zipline.api import price

ImportError: cannot import name price
```
though importing `price` doesn't because there's no "price" `api_method`.

Is that unexpected?

**Comment by twiecki** [comment]
TBH, I don't remember how this came about or why I thought this should work but I agree with everything you said.
