### ISSUE TITLE
Allow external setting of variables in TradingAlgorithm

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#455]
Currently `TradingAlgorithm.__init__()` calls the user-defined `initialize()` function.

This is problematic as sometimes one would like to set a variable of the algorithm externally. For example during parameter optimization. I think currently it's impossible to do parameter optimization if the parameters need to be accessed from inside `initialize` (e.g. window length).

There's a few ways, these I can think of from the top of my head:
1. Allow passing of `*args` and `**kwargs` to `__init__` which get forwarded to `initialize`.
2. Move the call of `initialize()` from `__init__()` to `.run()`. This way we can create the `TradingAlgorithm` object and set variables which can then get accessed from inside `initialize` and `handle_data`.

CC @ssanderson @ehebert.

**Comment by dalejung** [comment]
Personally, I don't like the algoscript/function api. However, subclassing TradingAlgorithm is messy because it does a lot. Any reason we don't support a simple object api like so?

```python
class AwesomeAlgo:
    def __init__(self, bottom=99, top=100, lag=3):
        self.bottom = bottom
        self.top = top
        self.lag = lag

    def initialize(self):
        set_universe(DollarUniverse(bottom, top))

    def handle_data(self, context, data):
        #do stuff
```

**Comment by llllllllll** [comment]
couldn't you just do:
```python
a = AwesomeAlgo()
algo = TradingAlgorithm(initialize=a.initialize, handle_data=a.handle_data)
```

**Comment by dalejung** [comment]
Sure, I generally work with a wrapper like that. I hate putting code in strings. But this is issue is about first order support as parameter sweeping can already be done via wrappers. 

Conceptually, it feels cleaner if TradingAlgorithm was split up as it's a harness to itself.

**Comment by twiecki** [comment]
@dalejung The algoscript is for use with the ipython magic. The rest of the interface is mainly to get compatibility with Quantopian so that code does not have be rewritten.

But we already have 2 ways of writing algos and I don't think the right solution is a 3rd way :).

**Comment by dalejung** [comment]
@twiecki 1 -> 2 is 100%. but 2 -> 3 is only 50%!  And they get cheaper as we go

**Comment by twiecki** [comment]
@dalejung I don't follow. But the 3rd way is already supported as @llllllllll points out but that's not great UX.

Devs can of course figure out different ways but I think we want something that's more userfriendly.

**Comment by dalejung** [comment]
ah, nm. Was making a joke.

On a more serious note, the simple class based approach can superset the handle_data/initialize approach. Having the user defined strategy completely separate from the harness/sim params is cleaner. It's surprising that the TradingAlgorithm class itself is passed around as the context. In quantopian proper the context object is a attrdict like object with access to portfolio and account.

**Comment by llllllllll** [comment]
We have deprecated the subclassing api a while ago and now have `zipline.run_algorithm` as the top level entry point for running backtests. This will let us change the implementation of TradingAlgorithm  as needed without breaking user code. For the parameter optimization use case, one may just define their functions as closures and then pass them to run_algorithm
