### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by femtotrader** [quantopian/zipline#462]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with zipline. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable zipline on @Sourcegraph by going to https://sourcegraph.com/github.com/quantopian/zipline and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by twiecki** [comment]
Should be enabled now. Build is still queued.
