### ISSUE TITLE
conda win-32 zipline 0.7.0 out of step with master branch

### ISSUE THREAD

**Issue by scubamut** [quantopian/zipline#481]
Comparing [conda win-32 zipline package](win-32\zipline-0.7.0-np18py27_0.tar.bz2) with zipline 0.7.0 from github, it appears that the conda package is not up to date.

For example, utils files events.py, algo_instance.py, argcheck.py are missing....

**Comment by twiecki** [comment]
Yes, 0.7.0 is a bit outdated and we should release a new version soon.

**Comment by llllllllll** [comment]
We are still working on getting the project ready for our 0.8.0 release. Currently I would suggest installing from github with pip to use the most up to date features. We should be releasing soon. Moving forward, we will try to keep our pypi and conda packages more up to date.
