### ISSUE TITLE
get historical prices from command line args.

### ISSUE THREAD

**Issue by karolestrada** [quantopian/zipline#489]
Hi,
Would it be possible to have a better way to handle historical prices in zipline? If I understand correctly, right now one has to manually check if the days that one is looking back in history have already passed by before actually running the ``` history(72, '1d', 'price') ``` code. The suggested code to do so in handle_data is:
```
    context.i += 1
    if context.i < 72:
        return
```
But this wouldn't work if for example one wants to use minute mode. It would be better if one could download from command line the historical prices. Needless to say, these kind of issues do not appear when code is run in quantopian.

Thanks

Karol

**Comment by lestatega** [comment]
Agree with Karol I am exactly having same problem

**Comment by ssanderson** [comment]
@karolestrada is your goal just to work with the raw pricing data without running a backtest at all?  Or are you looking to implement the same backfilling logic that's applied on Quantopian?

w/r/t the former issue, you can use the utils in `zipline.data.loader` to load the same data that's used by default in Zipline's CLI (specifically, it uses `load_data_yahoo` and `load_bar_from_yahoo`.  You might also take a look at `pandas.io.data` (https://github.com/pydata/pandas/blob/master/pandas/io/data.py), which supports querying data from a whole host of remote sources.

w/r/t the latter issue, agreed that the need to skip over the first N bars is a kludge, though I'm not sure I understand how running in minute mode makes a difference.  The reason backfilling isn't built into zipline is that zipline can work with arbitrary user-supplied data sources, and we can't necessarily backfill from before the beginning of your test.

**Comment by karolestrada** [comment]
I'm trying to run my quantopian scripts directly in zipline. But I want to continue using quantopian as my "editor mode". So far it has been frustratingly painful to make the same script that worked fine in quantopian to work directly on zipline. 

So, I want to run my code in minute mode, and I want to lookback 72 days in the past. 
When I run minute mode on quantopian, the handle_data function is called every minute, so the hack to use a counter to check if the number of days has passed wouldn't work. 

Furthermore, now I'm realizing that zipline is not calling handle_data every minute but every day.  So how am I supposed to work in minute mode data in zipline?

I added to the cmd line: ```  --data_frequency minute```  and then when I try to do ``` add_history(43200, '1m', 'price')``` it complains and says: 

``` File "/home/ubuntu/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/history/history.py", line 275, in __init__
    data_frequency=data_frequency,
zipline.errors.IncompatibleHistoryFrequency: Requested history at frequency 'm' cannot be created with data```

Is there a working minute mode zipline script with history() calls that I can have a look at?

**Comment by ssanderson** [comment]
@karolestrada I believe the required keyword argument for the CLI is `data-frequency`, not `data_frequency`.  Unfortunately, however, I don't think that will do you any good.  While Zipline can be configured to use your own arbitrary data sources, the CLI only knows how to pull Yahoo's free daily data (yahoo doesn't provide free data at minutely resolution), and from my reading of the code in https://github.com/quantopian/zipline/blob/master/zipline/utils/cli.py#L161, it silently ignores the data-frequency argument. 

As may be apparent by now, the CLI isn't especially well-maintained; it was built as a simple prototype to allow people to try out zipline with a simple data source in daily mode, but for most serious use-cases you still have to work directly with the zipline internals.  If you don't already have your own minutely data, I'd recommend working in Quantopian for now :(.

**Comment by karolestrada** [comment]
Thanks for you answer.
