### ISSUE TITLE
Adjusted and Unadjusted close prices in history()

### ISSUE THREAD

**Issue by karolestrada** [quantopian/zipline#490]
Hi, 
I'm running the same code in quantopian and zipline, and have found some significant differences in the results. So far, I believe that the major difference is in what is considered a close price in both platforms when data is retrieved via history(). 
It seems that quantopian is using unadjusted close price when one uses 'price' or 'close_price' .

Here just a quick sample looking at the close price for EDV stored in the cache file 
`EDV-2010-10-19\ 00-00-00+00-00-2011-02-28\ 00-00-00+00-00.csv`

| Date | zipline.Close | zipline.Adj Close (this is the one reported as 'price') | quantopian.close_price |
| --- | --- | --- | --- |
| 2010-10-19 | 91.17 | 73.34 | 91.166 |
| 2010-10-20 | 91.8 | 73.84 | 91.798 |
| 2010-10-21 | 90.68 | 72.94 | 90.680 |

As you can see, quantopian's close_price corresponds pretty close to the value stored in the cache file of zipline corresponding to regular close and not the adjusted close price. The adjusted close price  is the one used in zipline code.

Further, when I try to use 'close_price' on zipline it returns NaN. 
Could you place a handler to use unadjusted close prices in zipline and/or to use adjusted close prices in quantopian? 

Thanks

Karol

**Comment by twiecki** [comment]
I'm not an expert on the adjustment process but Quantopian does explicitly handle splits, mergers and dividends. There's thus no need to adjust the price which is basically just a hack. That information is not available in yahoo finance though so if you don't want crazy jumps in price during a split you'll have to use the adjusted price. But yes, the difference between Quantopian and yahoo data in that regard is a bit unfortunate as it makes comparing and porting more difficult. I'm not sure there's a good solution though.

I do agree though that `close_price` should work for history, not sure why it doesn't.

**Comment by karolestrada** [comment]
I see, that's going to make my debugging quite hard.. I have an algo with a 30% difference in total return when run in quantopian vs zipline, with exactly the same equities, time frames, and code. In some way these differences in how prices are handled have compounded in huge differences in the final return. Have you experienced something like that in a 2 year-range algo?

**Comment by twiecki** [comment]
One easy thing to try is to switch the column names of adjusted and close price in the data panel so that zipline thinks its using adjusted while it's actually the close.

**Comment by jbredeche** [comment]
Hi @karolestrada, we've recently completely rewritten how Zipline adjusts prices and lookback windows.

Now, all prices and lookback windows are adjusted as of the lookback date (= the algorithm's simulation date).  If you'd like, you can pass in datasource that represents the adjustments (splits, mergers, etc) and Zipline will use that to apply adjustments on the fly.  We haven't made this very easy yet, so it's on our roadmap to simplify that for Zipline users.

There's more information here: https://www.quantopian.com/quantopian2/adjustments.  (That page is Quantopian specific, but Quantopian and Zipline behave identically now).

Hope that helps!
