### ISSUE TITLE
Test Broker Blotter with Serialization

### ISSUE THREAD

**Issue by CaptainKanuk** [quantopian/zipline#515]
In the current tests I don't believe that we check how a broker blotter would behave (just a zipline blotter). We should have someone who knows that code look it over and also try serializing an algo actually connected to IB before we turn serialization on for any important algos.

**Comment by CaptainKanuk** [comment]
@jdricklefs

**Comment by jdricklefs** [comment]
Think this belongs in our internal bug tracker.
