### ISSUE TITLE
Cannot run tests from a source tarball

### ISSUE THREAD

**Issue by cournape** [quantopian/zipline#519]
Looks like the file `risk-answer-key-checksums` is missing from the tarball (0.7.0).

**Comment by richafrank** [comment]
I just downloaded and unzipped zipline-master.zip from the Download ZIP link at https://github.com/quantopian/zipline.  I see 

```bash
$ ls -l ~/Downloads/zipline-master/tests/risk/risk-answer-key-checksums 
-rwxr-xr-x@ 1 rich  staff  528 Mar 29 19:26 /Users/rich/Downloads/zipline-master/tests/risk/risk-answer-key-checksums
```
so seems like that file is there now.

I haven't tried running tests from outside a git clone, so it's possible there are further issues.  Feel free to re-open if you find that to be the case.
