### ISSUE TITLE
Add support for bid/ask specification.

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#52]
Currently zipline requires a price (and volume) field to be present for each sid. From this price we calculate the bid/ask spread when orders are placed.

The order function should be adapted so that when an bid and ask field are present it uses those as the price.

**Comment by femtotrader** [comment]
This is a quite old issue. What is current status?

**Comment by MarikoKujo** [comment]
Is there any chance that this feature will be supported in the near future?
I am currently working on a project which may need this one, but I cannot find any clue apart from some feature request posts like this.

**Comment by dmichalowicz** [comment]
Sorry for the silence here; this is likely a feature that will not be supported soon, but we are currently working on sorting through requests like these.

**Comment by ssanderson** [comment]
I'm closing this for the time being since I don't think we have any near or medium term plans to work on this.
