### ISSUE TITLE
Cython in setup.py

### ISSUE THREAD

**Issue by llllllllll** [quantopian/zipline#536]
Because we import Cython in setup.py, this is now an implicit dependency and must be installed prior to calling setup.py

We should resolve this by making it do a try import and then download cython or something.

**Comment by twiecki** [comment]
I don't think it's worth the added complexity in `setup.py`. Instead, we could add the `.c` output files to the build and defer to them if cython is not installed.

**Comment by llllllllll** [comment]
I feel like putting generated files into source control is an anti-pattern because it means that we need to manually keep the source and the output in sync. This is an issue that pandas also has; we can try to use the same method they do.

**Comment by twiecki** [comment]
Yeah, I meant to put it into the packaged version, not the source. That's how pandas does it.

**Comment by llllllllll** [comment]
Ah, so you mean before we push to pypi?

**Comment by twiecki** [comment]
Yeah.

**Comment by llllllllll** [comment]
We now use the LazyCythonizingList to get around this issue.
