### ISSUE TITLE
SID/Symbol/Asset management

### ISSUE THREAD

**Issue by dalejung** [quantopian/zipline#537]
Now that zipline has `Asset` objects, there needs to be some way of managing it and also defining when a numeric sid is acceptable vs object. Take for instance `BarData`, for parity with quantopian it should be keyed by some Asset object, but data sources will most definitely come in keyed to some numeric. There has to be a translation layer or something that converts these into objects when necessary/available. 

@jfkirk @ehebert

**Comment by ssanderson** [comment]
Seems like we probably need to port some version of `SecurityFinder` to Zipline?  Possibly associating it with TradingEnvironment?

**Comment by jfkirk** [comment]
@dalejung Within Zipline, it will be important within the perf tracker that the sids are Asset objects, so the logic can be pivoted on the asset_type. Alternatively, the perf tracker could treat all non-Asset sids as asset_type 1 (Equity).

@ssanderson That sounds right to me, but I'm not familiar with the SecurityFinder. Would there be any major dependencies?

**Comment by dalejung** [comment]
Yeah it just needs to be defined and also exposed to zipline. For me, I have an instance where I want to pre-warm the BarData object with SIDData objects, but on the zipline side there's no concept of a sid => SID translation. I suppose one could say that the switch occurs on the datasource level, so if the datasource doesn't know about Asset objects, then the entire system should not. That's yuck though.

It doesn't even have to be the Security finder per se, just an api that Security finder hooks into.

**Comment by ehebert** [comment]
What would the input/output of that API be? Something like the following?

```
def get_asset(sid):
   asset = ...# Get Security, Future, etc.
   return asset
```

To be used as the following?

```
assets = [get_asset(sid) for sid in universe]
bar_data.index = assets
```

**Comment by dalejung** [comment]
at a base level with some caching. the instrument management is a much bigger thing once you add point in time and matching on multiple identifiers. but that's all out of scope for zipline. 




btw. too late to rename asset to instrument ?



—

**Comment by llllllllll** [comment]
We have ported the asset finder to zipline and zipline now uses Asset objects where possible. We are trying to finish cleaning up the last of the int/asset issues.

**Comment by VitalyErmilov** [comment]
Hi, I have the following problem. Is it possible to convert a string like 'Equity(42 [AMD])' to Asset object?
