### ISSUE TITLE
set_benchmark not available in zipline?

### ISSUE THREAD

**Issue by karolestrada** [quantopian/zipline#548]
Is there a way to change the default benchmark in zipline? at Quantopian this works by doing set_benchmark() which doesn't seem to be available here.

**Comment by fretchen** [comment]
Same problem here.

**Comment by warren-oneill** [comment]
You could write your own load_market_data function and pass it to the TradingEnvironment. The default load_market_data looks for data in yahoo.

**Comment by richafrank** [comment]
I think is in the works with #858!

**Comment by richafrank** [comment]
This should be available on master now, as of https://github.com/quantopian/zipline/pull/1105.
