### ISSUE TITLE
Tried to implement my own commission model but got UnsupportedCommissionModel error

### ISSUE THREAD

**Issue by sebnil** [quantopian/zipline#553]
I wanted to implement a commission model based on my bank. Why is this something that is not favored in zipline.algorithm.py?

        def set_commission(self, commission):
            if not isinstance(commission, (PerShare, PerTrade, PerDollar)):
                raise UnsupportedCommissionModel()

**Comment by twiecki** [comment]
You're right, that should be supported.

**Comment by richafrank** [comment]
The requirement has now been [relaxed] (https://github.com/quantopian/zipline/pull/1213/files#diff-710b8bff6f1b5d930511d643b73c6987L1499) to any CommissionModel instance, e.g. even a custom subclass.
