### ISSUE TITLE
Paper trading

### ISSUE THREAD

**Issue by karolestrada** [quantopian/zipline#567]
Is there a way to test an algo in paper trading using zipline and yahoo delayed feed?

**Comment by twiecki** [comment]
That should be possible if you write a data source that queries the yahoo feed and yields the results. But that data source does not exist yet. If you decide to write one (shouldn't be too hard), please consider making a pull request.

**Comment by freddiev4** [comment]
Going to close this as it's not been touched for a while. There's https://github.com/zipline-live/zipline which is built on top of zipline and supports live trading.

**Comment by daraul** [comment]
zipline-live hasn't been updated since August, 2019, is it still the recommended way to paper/live trade with zipline?
