### ISSUE TITLE
"test_history_add_field_10 (zipline_tests.test_history.TestHistoryContainerResize)" Reporting RuntimeWarning

### ISSUE THREAD

**Issue by jikamens** [quantopian/zipline#576]
test_history_add_field_10 (zipline_tests.test_history.TestHistoryContainerResize) ... /home/qexec/virtual_envs/qexec/local/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:220: RuntimeWarning: All-NaN axis encountered
      warnings.warn("All-NaN axis encountered", RuntimeWarning)
    ok

Can we make the runtime warning go away? I don't understand this test well enough to know what the right thing to do to fix it is.

**Comment by jikamens** [comment]
As shown in the commit above, I've worked around this for the time being by suppressing user warnings on one line of this test, but we really should fix it properly rather than relying on this suppression.

**Comment by richafrank** [comment]
This test looks to have been removed, and test_history.py doesn't suppress any warnings.  Closing.
