### ISSUE TITLE
Moving Average Transforms in Minutes

### ISSUE THREAD

**Issue by athenawisdoms** [quantopian/zipline#607]
Is it possible to use window lengths in the order of minutes for the transforms? If we use `short_window=0.5`, it gives an error about only accepting integer values.

    def initialize(self, short_window=0.5, long_window=5):
        self.add_transform(zp.transforms.MovingAverage, 'short_mavg', ['price'], window_length=short_window)
        self.add_transform(zp.transforms.MovingAverage, 'long_mavg', ['price'], window_length=long_window)
        self.invested = False

**Comment by ssanderson** [comment]
@athenawisdoms `zp.transforms.MovingAverage` only accepts integer arguments, which are interpreted as days. This is mostly for legacy compatibility reasons.  If you want to compute a moving average in a new algorithm, you're probably better off using `history()` instead.

**Comment by athenawisdoms** [comment]
@ssanderson Tried your suggestion of using `history()` and `add_history()`, but I am encountering an error `AttributeError: 'NoneType' object has no attribute 'add_history'`. Do you know where did I go wrong?



	%matplotlib inline
	import matplotlib.pyplot as plt

	import numpy as np
	import pandas as pd
	import pytz
	from datetime import datetime
	import zipline as zp
	from zipline.utils.factory import load_bars_from_yahoo





	# Load data manually from Yahoo! finance
	start = datetime(2000, 1, 1, 0, 0, 0, 0, pytz.utc)
	end = datetime(2012, 1, 1, 0, 0, 0, 0, pytz.utc)
	data = load_bars_from_yahoo(stocks=['AAPL'], start=start,
	                            end=end)
	 




	 class DualMovingAverage(zp.TradingAlgorithm):
	    
	    def initialize(context):
	        add_history(100, '1d', 'price')
	        add_history(300, '1d', 'price')
	        
	        context.i = 0
	        
	    def handle_data(context, data):
	        # Skip first 300 days to get full window
	        context.i += 1
	        if context.i < 300:
	            return
	        
	        # Compute averages
	        short_mavg = history(100, '1d', 'price')
	        long_mavg = history(300, '1d', 'price')
	        
	        # Trading logic
	        if short_mavg[0] > long_mavg[0]:
	            order_target(symbol('AAPL'), 100)
	        elif short_mavg[0] < long_mavg[0]:
	            order_target(symbol['AAPL'], 0)
	            
	        # Save values for later inspection
	        record(AAPL=data[symbol('AAPL')].price,
	               short_mavg=short_mavg[0],
	               long_mavg=long_mavg[0])
	        
	    def analyze(context, perf):
	        fig = plt.figure()
	        ax1 = fig.add_subplot(211)
	        perf.portfolio_value.plot(ax=ax1)
	        ax1.set_ylabel('portfolio value in $')
	        
	        ax2 = fig.add_subplot(212)
	        perf['AAPL'].plot(ax=ax2)
	        perf[['short_mavg','long_mavg']].plot(ax=ax2)
	        ax2.set_ylabel('price in $')
	        plt.legend(loc=0)
	        plt.show()





	dma = DualMovingAverage()
	dma.run()



Here is the traceback in iPython

	---------------------------------------------------------------------------
	AttributeError                            Traceback (most recent call last)
	<ipython-input-24-67d050ec63d5> in <module>()
	----> 1 dma = DualMovingAverage()
	      2 dma.run()

	/Users/athena/anaconda/envs/zipline/lib/python2.7/site-packages/zipline/algorithm.pyc in __init__(self, *args, **kwargs)
	    208         # is manually set to False.
	    209         self.initialized = False
	--> 210         self.initialize(*args, **kwargs)
	    211         if self.AUTO_INITIALIZE:
	    212             self.initialized = True

	<ipython-input-23-c3675585cb3c> in initialize(context)
	      2 
	      3     def initialize(context):
	----> 4         add_history(100, '1d', 'price')
	      5         add_history(300, '1d', 'price')
	      6 

	/Users/athena/anaconda/envs/zipline/lib/python2.7/site-packages/zipline/utils/api_support.pyc in wrapped(*args, **kwargs)
	     58     def wrapped(*args, **kwargs):
	     59         # Get the instance and call the method
	---> 60         return getattr(get_algo_instance(), f.__name__)(*args, **kwargs)
	     61     # Add functor to zipline.api
	     62     setattr(zipline.api, f.__name__, wrapped)

	AttributeError: 'NoneType' object has no attribute 'add_history'

**Comment by ssanderson** [comment]
@athenawisdoms I think the error you're seeing there should be fixed on the latest master, but I should also point out that the idiom of "Subclass TradingAlgorithm and override `initialize` and `handle_data` is deprecated".  What you want to do instead is something like:

```
%matplotlib inline
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
import pytz
from datetime import datetime
import zipline as zp
from zipline.utils.factory import load_bars_from_yahoo

# Load data manually from Yahoo! finance
start = datetime(2000, 1, 1, 0, 0, 0, 0, pytz.utc)
end = datetime(2012, 1, 1, 0, 0, 0, 0, pytz.utc)
data = load_bars_from_yahoo(stocks=['AAPL'], start=start,
                            end=end)

def initialize(context):
    add_history(100, '1d', 'price')
    add_history(300, '1d', 'price')

    context.i = 0

def handle_data(context, data):
    # Skip first 300 days to get full window
    context.i += 1
    if context.i < 300:
        return

    # Compute averages
    short_mavg = history(100, '1d', 'price')
    long_mavg = history(300, '1d', 'price')

    # Trading logic
    if short_mavg[0] > long_mavg[0]:
        order_target(symbol('AAPL'), 100)
    elif short_mavg[0] < long_mavg[0]:
        order_target(symbol['AAPL'], 0)

    # Save values for later inspection
    record(AAPL=data[symbol('AAPL')].price,
           short_mavg=short_mavg[0],
           long_mavg=long_mavg[0])

def analyze(context, perf):
    fig = plt.figure()
    ax1 = fig.add_subplot(211)
    perf.portfolio_value.plot(ax=ax1)
    ax1.set_ylabel('portfolio value in $')

    ax2 = fig.add_subplot(212)
    perf['AAPL'].plot(ax=ax2)
    perf[['short_mavg','long_mavg']].plot(ax=ax2)
    ax2.set_ylabel('price in $')
    plt.legend(loc=0)
    plt.show()

algo = TradingAlgorithm(initialize=initialize, handle_data=handle_data, analyze=analyze)
algo.run(source=data)
```

Can you let me know if the above works for you?

**Comment by athenawisdoms** [comment]
Yes it works now!

However `algo.run(source=data)` only prints out the `perf` DataFrame, it does not appear to run `analyze` as no plot is drawn.

**Comment by ssanderson** [comment]
> However algo.run(source=data) only prints out the perf DataFrame, it does not appear to run analyze as no plot is drawn.

What context are you running from?  Plots will only show up if you're in IPython Notebook or the IPython QtConsole.

**Comment by athenawisdoms** [comment]
@ssanderson I am running in IPython Notebook and included `%matplotlib inline` at the top of the notebook and the plots does not appear when doing `algo.run(source=data)`

However if I use `%%zipline --start 2010-1-1 --end 2012-1-1 --symbols AAPL -o perf_dma`, the 2 plots does show up. But I'll still like to use `algo.run` instead of IPython magic.
