### ISSUE TITLE
Price column in Data source

### ISSUE THREAD

**Issue by vertangelx** [quantopian/zipline#611]
Hi all,

I have tick data on local storage that I will like to load into Zipline. So I resampled the original data using `pandas.resample` into a DataFrame containing the 4 OHLC columns and a DataFrame with a `volume` column.

However when loading `AAPL` data from Yahoo! finance, I notice that the DataFrame contains a `price` column, which is not found in my resampled DataFrame.

![image](https://cloud.githubusercontent.com/assets/8826684/8212263/b4248554-14e8-11e5-8244-c076c3105117.png)

 How is the `price` column calculated?  Is it simply the same value as in the `close` column?

**Comment by ssanderson** [comment]
@vertangelx yep, `price` is just an alias of `close`.  You can copy it over.  I think Zipline should run just fine if you only have OHLCV with no price column, though I'm not 100% sure on that.

**Comment by vertangelx** [comment]
And a follow up question:

I am getting an error `IndexError: index out of bounds` when running the `TradingAlgorithm` using custom data resampled by pandas and under IPython notebook.

	def initialize(context):
	    add_history(1, '1d', 'price')
	    add_history(5, '1d', 'price')

	    context.i = 0
	    
	    
	def handle_data(context, data):
	    
	    sym = symbol('ABC')
	    print context.i
	    
	    context.i += 1
	    if context.i < 7:
	        return

	    
	    short_mavg = history(1, '1d', 'price').mean()
	    long_mavg = history(5, '1d', 'price').mean()
	    

	    if short_mavg[sym] > long_mavg[sym]:
	        order_target(sym, 1)
	    elif short_mavg[sym] < long_mavg[sym]:
	        order_target(sym, 0)
	        
	    record(ABC=data[sym].price,
	           short_mavg=short_mavg[sym],
	           long_mavg=long_mavg[sym])


	data = pd.Panel({'ABC': ohlcv})
	algo = zp.TradingAlgorithm(initialize=initialize, handle_data=handle_data, analyze=analyze)
	perf = algo.run(data)

**Comment by ssanderson** [comment]
@vertangelx can you post the traceback for the error you're seeing?

**Comment by vertangelx** [comment]
0
	1
	2
	3
	4
	5
	6
	---------------------------------------------------------------------------
	IndexError                                Traceback (most recent call last)
	<ipython-input-5-c03d9f28c52a> in <module>()
	      4 # Run
	      5 algo = zp.TradingAlgorithm(initialize=initialize, handle_data=handle_data, analyze=analyze)

	----> 6 perf = algo.run(data)

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/zipline/algorithm.pyc in run(self, source, overwrite_sim_params, benchmark_return_source)
	    421             # perf dictionary
	    422             perfs = []
	--> 423             for perf in self.gen:
	    424                 perfs.append(perf)
	    425 

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/zipline/gens/tradesimulation.pyc in transform(self, stream_in)
	    125                         date,
	    126                         snapshot,
	--> 127                         self.algo.instant_fill,
	    128                     )
	    129                     # Perf messages are only emitted if the snapshot contained

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/zipline/gens/tradesimulation.pyc in _process_snapshot(self, dt, snapshot, instant_fill)
	    212 
	    213         if any_trade_occurred:
	--> 214             new_orders = self._call_handle_data()
	    215             for order in new_orders:
	    216                 self.algo.perf_tracker.process_event(order)

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/zipline/gens/tradesimulation.pyc in _call_handle_data(self)
	    234         during the call.
	    235         """
	--> 236         self.algo.handle_data(self.current_data)
	    237         orders = self.algo.blotter.new_orders
	    238         self.algo.blotter.new_orders = []

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/zipline/algorithm.pyc in handle_data(self, data)
	    224             self.history_container.update(data, self.datetime)
	    225 
	--> 226         self._handle_data(self, data)
	    227 
	    228     def analyze(self, perf):

	<ipython-input-4-79cf35da143b> in handle_data(context, data)
	     25 
	     26     # Compute averages
	---> 27     short_mavg = history(1, '1d', 'price').mean()
	     28     long_mavg = history(5, '1d', 'price').mean()
	     29 

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/zipline/utils/api_support.pyc in wrapped(*args, **kwargs)
	     58     def wrapped(*args, **kwargs):
	     59         # Get the instance and call the method
	---> 60         return getattr(get_algo_instance(), f.__name__)(*args, **kwargs)
	     61     # Add functor to zipline.api
	     62     setattr(zipline.api, f.__name__, wrapped)

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/zipline/algorithm.pyc in history(self, bar_count, frequency, field, ffill)
	    846             bar_count, frequency, field, ffill)
	    847         history_spec = self.history_specs[spec_key_str]
	--> 848         return self.history_container.get_history(history_spec, self.datetime)
	    849 
	    850     ####################

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/zipline/history/history_container.pyc in get_history(self, history_spec, algo_dt)
	    464                 buffer_frame,
	    465                 digest_frame,
	--> 466                 self.last_known_prior_values,
	    467             )
	    468 

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/zipline/history/history_container.pyc in ffill_buffer_from_prior_values(field, buffer_frame, digest_frame, pre_digest_values)
	     42 
	     43     # Get values which are NaN at the beginning of the period.
	---> 44     first_bar = buffer_frame.iloc[0]
	     45 
	     46     def iter_nan_sids():

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/pandas/core/indexing.pyc in __getitem__(self, key)
	   1142             return self._getitem_tuple(key)
	   1143         else:
	-> 1144             return self._getitem_axis(key, axis=0)
	   1145 
	   1146     def _getitem_axis(self, key, axis=0, validate_iterable=False):

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/pandas/core/indexing.pyc in _getitem_axis(self, key, axis, validate_iterable)
	   1415                 self._is_valid_integer(key, axis)
	   1416 
	-> 1417             return self._get_loc(key, axis=axis)
	   1418 
	   1419     def _convert_to_indexer(self, obj, axis=0, is_setter=False):

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/pandas/core/indexing.pyc in _get_loc(self, key, axis)
	     88 
	     89     def _get_loc(self, key, axis=0):
	---> 90         return self.obj._ixs(key, axis=axis)
	     91 
	     92     def _slice(self, obj, axis=0, typ=None):

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/pandas/core/frame.pyc in _ixs(self, i, axis)
	   1600                 return self[i]
	   1601             else:
	-> 1602                 label = self.index[i]
	   1603                 if isinstance(label, Index):
	   1604                     # a location index by definition

	/Users/vertangelx/anaconda/envs/test/lib/python2.7/site-packages/pandas/tseries/index.pyc in __getitem__(self, key)
	   1372         arr_idx = self.view(np.ndarray)
	   1373         if np.isscalar(key):
	-> 1374             val = arr_idx[key]
	   1375             return Timestamp(val, offset=self.offset, tz=self.tz)
	   1376         else:

	IndexError: index out of bounds

**Comment by vertangelx** [comment]
@ssanderson I think this error is due to some timezone settings? 

Here's the complete code and CSV data for you to reproduce the problem


	import pandas as pd
	import zipline as zp
	from zipline.api import order_target, record, symbol, history, add_history
	from StringIO import StringIO


	# Load CSV data set
	CSV = StringIO("""Date,open,high,low,close,volume,price
	2015-04-30 00:00:00+00:00,238.562,240.9,236.75,238.55,1057.999764759998,238.55
	2015-05-01 00:00:00+00:00,238.55,238.799,232.6,232.826,5571.780883030158,232.826
	2015-05-02 00:00:00+00:00,232.826,243.0,232.66,242.1,5248.548124790254,242.1
	2015-05-03 00:00:00+00:00,242.16299999999998,243.989,239.00099999999998,241.477,5676.511356750245,241.477
	2015-05-04 00:00:00+00:00,241.43400000000003,242.898,235.0,236.0,7261.460645310007,236.0
	2015-05-05 00:00:00+00:00,236.0,239.0,232.722,235.09,5535.097640390021,235.09
	2015-05-06 00:00:00+00:00,235.321,237.38,230.1,231.92,7939.87403392013,231.92
	2015-05-07 00:00:00+00:00,230.933,239.945,230.502,237.00099999999998,9827.88230409027,237.00099999999998
	2015-05-08 00:00:00+00:00,237.0,247.99900000000002,237.0,246.6,9441.443625220327,246.6
	2015-05-09 00:00:00+00:00,246.271,247.0,238.75,241.10299999999998,5434.345944310029,241.10299999999998
	2015-05-10 00:00:00+00:00,241.0,245.196,239.3,240.859,5347.909005330071,240.859
	2015-05-11 00:00:00+00:00,240.859,243.84400000000002,238.79,241.019,7142.361329230143,241.019
	2015-05-12 00:00:00+00:00,240.89,243.75,240.0,242.34799999999998,6270.16734212027,242.34799999999998
	2015-05-13 00:00:00+00:00,242.34799999999998,243.55,235.13099999999997,235.99900000000002,9069.02121746034,235.99900000000002
	2015-05-14 00:00:00+00:00,235.833,239.077,233.354,236.75599999999997,7692.901582780324,236.75599999999997
	2015-05-15 00:00:00+00:00,236.926,239.34,235.0,236.81599999999997,5826.34219158019,236.81599999999997
	2015-05-16 00:00:00+00:00,236.81599999999997,237.99,235.05700000000002,237.0,3363.910114550028,237.0
	2015-05-17 00:00:00+00:00,236.7,238.104,235.04,235.87599999999998,4373.577924750004,235.87599999999998
	""")

	df = pd.read_csv(CSV, parse_dates=['Date']).set_index('Date')
	df.index = df.index.tz_localize('UTC')

	def initialize(context):
	    add_history(1, '1d', 'price')
	    add_history(5, '1d', 'price')

	    context.i = 0

	    
	def handle_data(context, data):
	    
	    sym = symbol('XYZ')
	    
	    # Skip first 5 days to get full window
	    context.i += 1
	    if context.i < 5:
	        return

	    # Compute averages
	    short_mavg = history(1, '1d', 'price').mean()
	    long_mavg = history(5, '1d', 'price').mean()


	data = pd.Panel({'XYZ': df})
	dma = zp.TradingAlgorithm(initialize=initialize, handle_data=handle_data)
	perf = dma.run(source=data)

**Comment by ssanderson** [comment]
@vertangelx did you figure out what the issue was here?
