### ISSUE TITLE
Pass Parameter into Initialize()

### ISSUE THREAD

**Issue by athenawisdoms** [quantopian/zipline#618]
I'm running the simulation using `TradingAlgorithm(initialize=initialize, handle_data=handle_data)`. How can I pass additional parameters into `initialize` and `handle_data`?

    short_window = 3
    long_window = 5
    TradingAlgorithm(initialize=initialize, handle_data=handle_data)    # how can short_window, long_window be passed inside?

**Comment by twiecki** [comment]
I think you _should_ be able to do:
`TradingAlgorithm(initialize=initialize, handle_data=handle_data, short_window=short_window, long_window=long_window)`

and then have:
```
def initialize(short_window=5, long_window=10)
```

**Comment by llllllllll** [comment]
Confirming that you can pass this to the constructor of your trading algo as @twiecki showed. This might not be in 0.7.0 though. If you still need this feature, you might want to consider installing from github. We are working on releasing 0.8.0 soon which will support this.

**Comment by ucals** [comment]
Just run into the problem of passing parameters to `initialize`, but wanted to do it using `run_algorithm`, without using `TradingAlgorithm`. Here's a solution:
```
def custom_initialize(sym='AAPL'):
    def initialize(context):
        context.sym = symbol(sym)

    return initialize
```

Then, you can run:
```
df = run_algorithm(start=pd.Timestamp('2011', tz='utc'),
                   end=pd.Timestamp('2017', tz='utc'),
                   initialize=custom_initialize('NKE'),
                   capital_base=1e7,
                   handle_data=handle_data)
```
