### ISSUE TITLE
TradingAlgorithm.initialize accepts and silently ignores *args and **kwargs.

### ISSUE THREAD

**Issue by ssanderson** [quantopian/zipline#634]
c.f. https://github.com/quantopian/zipline/blob/master/zipline/algorithm.py#L285

These either shouldn't be accepted or should be forwarded to `_initialize`.

cc @jfkirk

**Comment by jfkirk** [comment]
@ssanderson My understanding was that the *args and **kwargs are accepted because extensions of TradingAlgorithm that override TradingAlgorithm.initialize may accept other args. Is this not the case?

**Comment by ssanderson** [comment]
@jfkirk if a subclass overrides `TradingAlgorithm.initialize`, then it doesn't matter if the base class accepts additional args, because the base class function isn't being being called.

**Comment by jfkirk** [comment]
![](http://st.depositphotos.com/2602289/4400/i/950/depositphotos_44001039-Man-slapping-hand-on-head-to-say-duh.jpg)

Makes sense. Thanks!

**Comment by richafrank** [comment]
Is this all set with #687 ?

**Comment by twiecki** [comment]
Yes.
