### ISSUE TITLE
Need to do new PyPI zipline release

### ISSUE THREAD

**Issue by jikamens** [quantopian/zipline#675]
It's been over a year since a new release of zipline was posted to PyPI. Can we do a new release?

**Comment by ssanderson** [comment]
@jfkirk @krubin we should talk about what pieces of our current feature work would make sense as stopping points for a 0.8.0 release.

**Comment by ssanderson** [comment]
**@KarenRubin**  sorry @krubin, whoever you are...

**Comment by KarenRubin** [comment]
Am I correct in thinking that the two big questions are futures and FFC and if they should be included?

**Comment by ssanderson** [comment]
@KarenRubin more or less.  The real question is: at what point are those features complete/useful/stable enough in Zipline to make a public release?  We also probably need to clean up some of our broken examples before we ship.

**Comment by jfkirk** [comment]
On the Markets trello board, I have a few milestones for a .8 release:

1. Zipline buy-Apple example may be broken
2. Symbol look-up should be use a static date
3. Remove update_asset_finder

There are certainly plenty more goals for a .8, mostly from FFC and Futures, but those are just a few others worth noting.

**Comment by richafrank** [comment]
Did it!

**Comment by jfkirk** [comment]
:+1: :yum: :moneybag:
