### ISSUE TITLE
Support Batched Loading Of Assets

### ISSUE THREAD

**Issue by ssanderson** [quantopian/zipline#688]
When loading ~8000 stocks, loading with a query like "SELECT * FROM <table> WHERE table in (...)" is 3x faster than doing the same number of queries serially:

    from zipline.assets import AssetFinder

#Pure Iteration Time

    %%timeit -n1 -r1 "f = AssetFinder(create_table=False, db_path='chroot/findata/assets/2015-08-20/assets.db')"
    [i for i in range(8401)]

    1 loops, best of 1: 479 µs per loop

    def load_8000_assets(f): 
        assets = []
        i = 0
        while i < 23000:
            i += 1
            try:
                assets.append(f.retrieve_asset(i))
            except:
                pass
        return assets

#All Cache Misses

    %%timeit -n1 -r1 f = AssetFinder(create_table=False, db_path='chroot/findata/assets/2015-08-20/assets.db')
    
    print len(f._asset_cache)
    load_8000_assets(f)
    print len(f._asset_cache)

    0
    23000
    1 loops, best of 1: 367 ms per loop

#All Cache Hits

    %%timeit -n1 -r1 f = AssetFinder(create_table=False, db_path='chroot/findata/assets/2015-08-20/assets.db'); load_8000_assets(f)
    
    print len(f._asset_cache)
    load_8000_assets(f)
    print len(f._asset_cache)

    23000
    23000
    1 loops, best of 1: 25.3 ms per loop

#Batched vs. Serial Queries

    finder = AssetFinder(create_table=False, db_path='chroot/findata/assets/2015-08-20/assets.db')
    assets = load_8000_assets(finder)

##Serial

    %%timeit -n1 -r1 f = AssetFinder(create_table=False, db_path='chroot/findata/assets/2015-08-20/assets.db'); assets = map(int, load_8000_assets(f))
    conn = f.conn
    result = []
    for asset in assets:
        result.append(conn.execute("SELECT * from equities where sid=?", (asset,)).fetchall()[0])
    print len(result)

    8401
    1 loops, best of 1: 62.6 ms per loop

##Batched

    %%timeit -n1 -r1 f = AssetFinder(create_table=False, db_path='chroot/findata/assets/2015-08-20/assets.db'); assets = map(int, load_8000_assets(f))
    
    conn = f.conn
    result = conn.execute(
        'SELECT * FROM equities WHERE sid in ({0})'.format(
            ', '.join('?' for _ in assets)
        ), 
        map(int, assets)
    ).fetchall()
    print len(result)

    8401
    1 loops, best of 1: 24.4 ms per loop

**Comment by ehebert** [comment]
:+1:

**Comment by richafrank** [comment]
@ssanderson I think this done with your merge of #817 !
