### ISSUE TITLE
Irrelevant sid filtering test

### ISSUE THREAD

**Issue by warren-oneill** [quantopian/zipline#696]
In an earlier version of Zipline it was possible to pass sids to the `DataFrameSource` and these would be used as filters. In the newest version this functionality seems to be removed but the test is still there. It still passing though since df is only composed of data with sid=0.

```
def test_df_sid_filtering(self):
        _, df = factory.create_test_df_source()
        source = DataFrameSource(df)
        assert 1 not in [event.sid for event in source], \
            "DataFrameSource should only stream selected sid 0, not sid 1."
```

Should this be removed our is it planned to re-implement this functionality?

**Comment by freddiev4** [comment]
Grepped through some Zipline code and I don't think this is here anymore.
