### ISSUE TITLE
Risk metrics not returning as series

### ISSUE THREAD

**Issue by jfkirk** [quantopian/zipline#703]
Reported by @KarenRubin.

Previously, the metrics in a Zipline algo were coming back in such a format that a user could call '.plot' and receive a timestamped plot of the algorithm returns. Now, the metrics appear to be coming back as an array and are not plottable.

Here is an example code snippet that is no longer working:

```
#: Plot the graph
benchmark_bt.risk.benchmark_period_return.plot(label="SPY")
my_algo.perf_tracker.cumulative_risk_metrics.algorithm_cumulative_returns.plot(label="Fortune 1000 Women-Led Companies")
ax1.set_ylabel('% Cumulative Return', fontsize=20)
ax1.set_title("Cumulative Return", fontsize=20)
ax1.legend(loc='best')
fig.tight_layout()
pyplot.show()
```

Issue appears related to https://github.com/quantopian/zipline/pull/631, but that is a guess.

@ehebert Do you know at-a-glance why this would be failing?

**Comment by ssanderson** [comment]
IMO, the real fix for this is to port the `BacktestResult` object from Q research to Zipline, and have that be the return value of `TradingAlgorithm.run`.

**Comment by ssanderson** [comment]
This expression is reaching **deep** into Zipline implementation internals:

> `my_algo.perf_tracker.cumulative_risk_metrics.algorithm_cumulative_returns.plot`

This isn't a public interface, so I don't think it's a bug that we broke this.  Are the cumulative risk metrics not available in the final output of `TradingAlgorithm.run` right now?

**Comment by ehebert** [comment]
We did change the datatype of the internal metrics to arrays for both speed and memory.

I did not consider/remember how that would affect the `run` method. (Do we have a test covering whether `run` succeeds? I think we have coverage of some examples, but perhaps not all?)

**Comment by llllllllll** [comment]
What is the status of this issue? @ehebert @jfkirk @ssanderson

**Comment by jfkirk** [comment]
Probably a non-issue
I'd recommend closing
