### ISSUE TITLE
Conda install does not work as advertised

### ISSUE THREAD

**Issue by typeless** [quantopian/zipline#706]
```
$ uname -a
Darwin muras-MacBook-Air.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```
```
$ conda install -c Quantopian zipline
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|#####################################################################################################| 100%

Hint: the following packages conflict with each other:
  - zipline
  - python 3.4*
```

**Comment by ssanderson** [comment]
This is happening because we're not distributing a conda package for 3.4 I think.

@twiecki given that Python 3.5 just came out, we should probably have a build up for 3.4.  Do you think you could take a look at getting that running since you're the most regular user of conda of the Zipline dev team?

**Comment by twiecki** [comment]
I can upload the binaries for windows and linux, not osx (but it's pretty straight forward to build). What's the current plan for a 0.8 release? Maybe it's better to do it just once. The work-around is probably to just run with python 2.7 or use pip install.

**Comment by AnthonyFJGarner** [comment]
typeless
my advice would be not to waste your time with zipline 0.7.0 It seems to be missing some of the elements present on Quantopian and hence it will be impossible to port between the two. You will get zipline 0.7.0 fine if you revert to python 2.7 but it is not worth it. Either wait for .08 to be released or load in the develop environment or at least direct from github if you don't need it to be editable. This is a nightmare process all round but hopefully worth it in the end.

**Comment by typeless** [comment]
OK. I am looking forward to the next release.

**Comment by llllllllll** [comment]
We are working on releasing a new version soon. We will try to have up to date conda packages when this happens. Sorry about this. In the interim, I would suggest using pip to install from github.
