### ISSUE TITLE
Converting asset fields may be broken

### ISSUE THREAD

**Issue by jfkirk** [quantopian/zipline#740]
From @ssanderson : 

Oof.  Thanks for the catch.  We're currently doing:

```
def _convert_asset_timestamp_fields(dict):
    """
    Takes in a dict of Asset init args and converts dates to pd.Timestamps
    """
    for key, value in dict.items():
        if (key in _asset_timestamp_fields) and (value is not None):
            dict[key] = pd.Timestamp(value, tz='UTC')
```
when we pull an entry out of the database.  Both for efficiency and correctness, this loop should probably be:

```
def _convert_asset_timestamp_fields(dict):
    """
    Takes in a dict of Asset init args and converts dates to pd.Timestamps
    """
    for key in _asset_timestamp_fields:
        value = dict[key]
        if value is not None:
            dict[key] = pd.Timestamp(value, tz='UTC')
```

 `_convert_asset_str_fields` is also almost certainly broken.

```
# A set of fields that need to be converted to strings before building an
# Asset to avoid unicode fields
_asset_str_fields = frozenset({
    'symbol',
    'asset_name',
    'exchange',
})

def _convert_asset_str_fields(dict):
    """
    Takes in a dict of Asset init args and converts from unicode to string
    where applicable
    """
    for key, value in dict.items():
        if key in _asset_str_fields:
            dict[key] = str(value)
```

This will return `bytes` in Python 2 and `unicode` in Python 3.  The statement "converts from unicode to string" is not meaningful in a Python 2/3 compat library.

**Comment by jfkirk** [comment]
@StewartDouglas Could you tackle these fixes at your earliest opportunity?

**Comment by StewartDouglas** [comment]
ACK looking now

**Comment by ssanderson** [comment]
Adding to AssetFinder bugs noticed while looking at this: **we're no longer correctly testing for duplicate symbol resolution in `test_lookup_generic`**.  The code that builds the test cases for that method currently uses these two assets:

```
            {
                'sid': 0,
                'symbol': 'duplicated_0',
                'start_date': dupe_0_start.value,
                'end_date': dupe_0_end.value,
                'exchange': '',
            },
            {
                'sid': 1,
                'symbol': 'duplicated_1',
                'start_date': dupe_1_start.value,
                'end_date': dupe_1_end.value,
                'exchange': '',
            }
```
We then query for `'duplicated_0'` and `'duplicated_1'`, but
the intent of this test is to ensure that if we have **two different assets that share a symbol**, then we correctly resolve them based on a provided symbol resolution date.  The test was originally written like this:

```
            {
                'sid': 0,
                'file_name':  'duplicated',
                'company_name': 'duplicated_0',
                'start_date_nano': dupe_0_start.value,
                'end_date_nano': dupe_0_end.value,
                'exchange': '',
            },
            {
                'sid': 1,
                'file_name':  'duplicated',
                'company_name': 'duplicated_1',
                'start_date_nano': dupe_1_start.value,
                'end_date_nano': dupe_1_end.value,
                'exchange': '',
            },
```

**Comment by StewartDouglas** [comment]
@ssanderson I think your following proposal will raise a KeyError when run with equities:

```
def _convert_asset_timestamp_fields(dict):
    """
    Takes in a dict of Asset init args and converts dates to pd.Timestamps
    """
    for key in _asset_timestamp_fields:
        value = dict[key]
        if value is not None:
            dict[key] = pd.Timestamp(value, tz='UTC')
```

Since keys such as `expiration_date` are not defined for equities, hence the existing `if (key in _asset_timestamp_fields)` check. As an alternative we could use `try...catch` or define two different methods to handle equites and futures.

**Comment by ssanderson** [comment]
`dict.get(key)` is probably what you want then.

**Comment by StewartDouglas** [comment]
`_convert_asset_str_fields` may not be necessary at all, as all tests currently pass for me for both python 2.7 and 3.3, including the tests which we'd expect to complain: test_repr and test_root_symbols in tests_assets.py.

**Comment by richafrank** [comment]
@StewartDouglas If you leave the timestamp code intact, I'll update it with my performance changes.

**Comment by StewartDouglas** [comment]
@richafrank sure, made a commit for it but will just delete it.

**Comment by richafrank** [comment]
Ok, thanks.

**Comment by StewartDouglas** [comment]
@jfkirk I think this issue can be closed now since:
- `_convert_asset_timestamp_fields` has been refactored.
- `_convert_asset_str_fields` has been removed.
- `test_lookup_generic` now correctly tests for duplicates.

**Comment by richafrank** [comment]
([Link] (https://github.com/quantopian/zipline/commit/c8c83a9f2bf52806178b9cd4d0a0aa7d6845e399#diff-e38a95b451336da451f69f2b60840da6L67) to the `_convert_asset_timestamp_fields` refactoring.)
