### ISSUE TITLE
Problem building bleeding edge version

### ISSUE THREAD

**Issue by bpajusco** [quantopian/zipline#766]
After building the development version (in order to comply with pyfolio requirements) I run into a name error when loading the library in the name space. The build seems to work fine (I've used pip install with git) but when I try to use the library I get the following error: ImportError: cannot import name Event. Here is the full traceback:

/home/bruno/anaconda/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/pkg_resources/__init__.py:1256: UserWarning: /home/bruno/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bruno/anaconda/lib/python2.7/site-packages/zipline/__init__.py", line 29, in <module>
    from . import transforms
  File "/home/bruno/anaconda/lib/python2.7/site-packages/zipline/transforms/__init__.py", line 16, in <module>
    from . batch_transform import BatchTransform, batch_transform
  File "/home/bruno/anaconda/lib/python2.7/site-packages/zipline/transforms/batch_transform.py", line 37, in <module>
    from zipline.protocol import Event
  File "/home/bruno/anaconda/lib/python2.7/site-packages/zipline/protocol.py", line 25, in <module>
    from zipline.utils.algo_instance import get_algo_instance
  File "/home/bruno/anaconda/lib/python2.7/site-packages/zipline/zipline/__init__.py", line 29, in <module>
    from . import transforms
  File "/home/bruno/anaconda/lib/python2.7/site-packages/zipline/zipline/transforms/__init__.py", line 16, in <module>
    from . batch_transform import BatchTransform, batch_transform
  File "/home/bruno/anaconda/lib/python2.7/site-packages/zipline/zipline/transforms/batch_transform.py", line 37, in <module>
    from zipline.protocol import Event
ImportError: cannot import name Event

**Comment by ssanderson** [comment]
@bpajusco I can't reproduce this with a fresh install:

```
[~]$ mkvirtualenv test
New python executable in test/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/ssanderson/.virtualenvs/test/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/ssanderson/.virtualenvs/test/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/ssanderson/.virtualenvs/test/bin/preactivate
virtualenvwrapper.user_scripts creating /home/ssanderson/.virtualenvs/test/bin/postactivate
virtualenvwrapper.user_scripts creating /home/ssanderson/.virtualenvs/test/bin/get_env_details
(test)[~]$ pip freeze
wheel==0.24.0
(test)[~]$ pip install git+https://github.com/quantopian/zipline.git
...
Running setup.py install for zipline
Successfully installed Logbook-0.10.0 bcolz-0.10.0 bottleneck-1.0.0 click-4.0 contextlib2-0.4.0 cyordereddict-0.2.2 decorator-4.0.4 networkx-1.9.1 numexpr-2.4.3 pandas-0.16.1 patsy-0.4.0 python-dateutil-2.4.2 pytz-2015.4 requests-2.7.0 scipy-0.15.1 six-1.9.0 sqlalchemy-1.0.8 statsmodels-0.6.1 toolz-0.7.2 zipline-0.8.0rc1
(test)[~]$ python
Python 2.7.10 (default, Jun 30 2015, 15:30:23)
>>> import zipline
>>> zipline.protocol.Event
<class 'zipline.protocol.Event'>
```

**Comment by bpajusco** [comment]
There is something wrong in my setup then but I can't figure out what it could be since my environment is a standard anaconda

**Comment by llllllllll** [comment]
Were you able to get your build working? If not, can you show the commands you ran to install the package?

**Comment by richafrank** [comment]
Let us know if there's something for us to do here!  Closing in the meantime.
