### ISSUE TITLE
datetools.py has no attribute 'relativedelta'

### ISSUE THREAD

**Issue by ever4cyth** [quantopian/zipline#771]
Both 
python run_algo.py -f olmar.py --start 2004-1-1 --end 2008-1-1 --symbols 'AMD,CERN,COST,DELL,GPS,INTC,MMM'
and
python run_algo.py -f dual_moving_average.py --symbols AAPL --start 2011-1-1 --end 2012-1-1 -o dma.pickle
gave the same error
.......
/usr/local/lib/python2.7/site-packages/zipline-0.8.0rc1-py2.7-linux-x86_64.egg/zipline/utils/tradingcalendar.py", line 26, in <module>
    end = end_base + pd.datetools.relativedelta(years=1)
AttributeError: 'module' object has no attribute 'relativedelta'

**Comment by twiecki** [comment]
This is related to pandas `0.17`.
