### ISSUE TITLE
no backtesting data show before 1990

### ISSUE THREAD

**Issue by leoleolam** [quantopian/zipline#777]
get the following if i input data which is all prior than 1990
AssertionError: Period end falls before the first known trading day. 

i did some narrow down and see it is hardcode 
start = pd.Timestamp('1990-01-01', tz='UTC') in tradingcalendar

is there anyway I can see backtesting result prior to 1990? is there any workaround for the release 0.7

**Comment by llllllllll** [comment]
hmm, it looks like this date was just chosen based on the data we commonly work with. Currently there is some work that modifies the trading calendar; however, it is not yet completed. This work is a more long term solution as it would allow the user to specify their start date. You can track this progress here: #556. As a temporary workaround, I think you might be able to patch out the start date from the module. For example:

```python
from zipline.uitls import tradingcalendar
tradingcalendar.start = pd.Timestamp('1980-01-01')  # set a new start date.
```

__note__: This is not supported behavior but it might solve the immediate problem that you have. This will likely break in future versions of zipline.

Another problem with this is that we do not mark all holidays before 1990, so the simulation might be incorrect.

**Comment by leoleolam** [comment]
thanks, i did some hack for the current release version and it worked. i also needed to do some patch on the benchmark data, treasury . 

agree that it is not a proper way, please let me know if there are some updates for the latest release regarding this soon.

**Comment by FreddieV4** [comment]
Going to close this as it looks like the OP had figured out a solution. Feel free to re-open if you come across a similar issue 🙂
