### ISSUE TITLE
update_last_sale fails when instant_fill=False for asset type Future

### ISSUE THREAD

**Issue by dhexus** [quantopian/zipline#778]
Hi. When running zipline TestAlgorithm for EEX Futures using instant_fill=False, update_last_sale in position_tracker fails because _position_payout_multipliers is not defined for given sid. As a workaround, I call 

```
self.perf_tracker.position_tracker._update_asset(self.asset.sid)
```

in handle_data method of class TestAlgorithm. This should not be necessary.

cc @warren-oneill

**Comment by warren-oneill** [comment]
@dhexus looks like you resolved this will I was away. Can we close the issue?

**Comment by jfkirk** [comment]
Is this issue still relevant? Possibly related to https://github.com/quantopian/zipline/issues/783?

If not, go ahead and close it.

**Comment by freddiev4** [comment]
Going to close this issue considering `instant_fill` looks like it was removed + this is an old issue.
