### ISSUE TITLE
zipline installs numpy 1.9.2

### ISSUE THREAD

**Issue by joequant** [quantopian/zipline#823]
The requirements file in zipline should be upgraded to allow installs with numpy 1.10

**Comment by llllllllll** [comment]
The requirements file specifies the tested and supported versions for zipline. We try to use exact version numbers instead of lower bounds to minimize the combinations of libraries that we support. With that said, I will see if the tests pass and performance stays the same with the newest version of numpy.

**Comment by richafrank** [comment]
What do you think about pinning the versions in the requirements file, but not in the `install_requires`?  https://packaging.python.org/en/latest/requirements/#install-requires-vs-requirements-files

I imagine we could generate the `install_requires` minimums from the requirements, with a facility to override the output, if we found, for example, that numpy 1.10 actually broke zipline.

**Comment by joequant** [comment]
The basic issue that I ran into is....

1) I install numpy 1.10
2) I do a pip install of zipline
3) zipline pulls in numpy 1.9.2 from requirements
4) at that point the other modules which were built on 1.10 fail because of
binary incompatbilities with 1.9.2

So I don't care much what version of numpy is used by zipline.  The more
serious problem is that installing zipline with a fixed numpy can cause
other modules to break.

**Comment by richafrank** [comment]
@joequant The HEAD of zipline master now allows for newer versions of its requirements.  How does that work for you?

**Comment by joequant** [comment]
That should be good enough.
