### ISSUE TITLE
Add a way to update benchmark data 

### ISSUE THREAD

**Issue by ehebert** [quantopian/zipline#83]
Currently, the only way to update benchmark data is to delete the benchmark file contained in "$HOME/.zipline", so that the code that detects missing data pulls in the full data set up to the most recently available data. 

One solution is to just check the latest date in the file and fill in the attempt to fill the data if it's not the previous market day.

Or we could add an utility script that can be run to update the data.

**Comment by llllllllll** [comment]
this is being updated now
