### ISSUE TITLE
Late data from the Fed can cause slowdowns.

### ISSUE THREAD

**Issue by ssanderson** [quantopian/zipline#839]
We try to download historical treasury rates from the Fed to use in Sharpe calculations, among other things.  The logic for that download tries to be fairly conservative about when we think data should be available for a given day, but there are cases where data isn't available when we think it should be, which causes tests, among other things, to run very slowly because they download the same stale treasury data over and over.

For example, on today (November 13th, 2015), we are expecting that data should be available for November 12th, 2015.  The data from the fed, however, only reaches November 11th, which means every test in the suite is trying to redownload the old data.  Our best guess is that this is somehow related to Veteran's day on the 11th, which isn't a market holiday, but **is** a federal holiday.

Two thoughts here:

1. Should we provide a switch (maybe via an environment variable?) to disable remote data downloading?
2. Should we add logic to prevent repeated download attempts?  For example, we could store the last time we tried to download and always wait at least an hour before trying again.

**Comment by ssanderson** [comment]
Partially addressed by https://github.com/quantopian/zipline/pull/841.  @richafrank is there anything else you think we need to be doing here?

**Comment by richafrank** [comment]
:+1: on #841.  A switch would be a nice general enhancement, but I think you've done enough for this issue of slow downloads, especially for tests.
