### ISSUE TITLE
Is is possible that a python module that wrap a third-party c++ trading communiction libraries can work well with zipline?

### ISSUE THREAD

**Issue by javagg** [quantopian/zipline#843]
I want to use zipline to live-trade against the Chinese stock and future markets. The brokers in those markets have provides some c++ libraries to handle the execution of the orders. The problem is that most of these c++ libs are multithreading and with c++ callbacks. I have read the code of zipline and found that the way that zipline are written will probably make the integration very hard. My question is whether I can use gevent(or eventlet) to wrap these c++ lib to provide synchronize-style functions that work compatiblely with zipline framework?

**Comment by llllllllll** [comment]
Hey, is the library you are working with publicly available. It is hard to make a suggestion without seeing the API you are working with.

**Comment by javagg** [comment]
Yes, It is accessible to the public, the download page is here(http://www.sfit.com.cn/5_2_DocumentDown.htm). This API is written in c++, and is multi-threaded. Some of class methods may be called by a different thread to return the results to user(multi-threading is mentioned in its user manual). I am basicly new to python, so forget about gevent or eventlet here. I just wondered how to handle these callbacks if I want to integrate this c++ libs with zipline framework.

**Comment by richafrank** [comment]
Hi @javagg , I don't know about the compatibility of gevent or eventlet with your c++ lib, but we've been using zipline in a gevented process successfully, so that end of it shouldn't be a blocker.
