### ISSUE TITLE
how to get high or low prices ?

### ISSUE THREAD

**Issue by FayolChang** [quantopian/zipline#845]
from the tutorials, the data are like:
 date                      AAPL GOOG

2010-01-02     10.0     12.0

so I don't know how to get other prices, like high, low, etc.

in the run method of TradingAlgorithm class in the algorithm.py
it says:
     
          If pandas.DataFrame is provided, it must have the
               following structure:
               * column names must be the different asset identifiers
               * index must be DatetimeIndex
               * array contents should be price info.

any ideas?
thanks for advance.

**Comment by richafrank** [comment]
Hi @FayolChang , It looks like the DataFrameSource yields data with only price and volume fields (and it looks like the volume is [hardcoded] (https://github.com/quantopian/zipline/blob/242175350958ed0936aa43461adc4d32d858d4ed/zipline/sources/data_frame_source.py#L86-L86)!).   It does that by ingesting a DataFrame (2D) of prices keyed by sid/datetime.  However, the [DataPanelSource] (https://github.com/quantopian/zipline/blob/242175350958ed0936aa43461adc4d32d858d4ed/zipline/sources/data_frame_source.py#L97-L97) ingests a pandas DataPanel (3D) with more attributes to each data point.  You might take a look at [this test] (https://github.com/quantopian/zipline/blob/dc964a7e7da7e975b22fabfe962d2210704c1d6b/tests/test_sources.py#L67), which uses the DataPanelSource to yield events with OHLCV from yahoo data.

**Comment by FayolChang** [comment]
Thank you very much, @richafrank , problem solved!
