### ISSUE TITLE
Unify risk metrics across zipline and pyfolio

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#855]
Discussion started over here: #853 

With @llllllllll  saying "The main reason for moving this to a new repo would be to make all the risk metrics that we report consistent. We can share implementation and tests for zipline and pyfolio which is great for avoiding duplication and introducing subtle differences. I would want this to be a standalone project because I don't think it makes sense for zipline to be a dependency of pyfolio or for pyfolio to be a dependency of zipline."

One thing to consider is that the data passed into zipline and pyfolio risk metrics is quite different. pyfolio requires arrays and zipline passes in e.g. mean returns. If we rely on separate code paths we might just move that problem somewhere else.

**Comment by ehebert** [comment]
What are the shape/contents of the arrays passed by pyfolio?

It should not be too much work to change Zipline over to using a different array structure since risk modules are already keeping track of the original returns as well.

**Comment by twiecki** [comment]
It takes an array of daily returns and daily treasury returns.

**Comment by twiecki** [comment]
I ported the risk metrics to https://github.com/quantopian/pyrisk so zipline is free to move over.

**Comment by twiecki** [comment]
CC @llllllllll @richafrank

**Comment by ahgnaw** [comment]
Closed by https://github.com/quantopian/zipline/pull/1322 and https://github.com/quantopian/pyfolio/pull/320
