### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by Nickleaton** [quantopian/zipline#857]
When installing zipline I notice it tries to remove scipy version 0.16.0 and replace it with an older version.

ect/requirements.txt specifies scipy==0.15.1

On window's this is a pain, since you then get into window's build problems. Any reason why it has to be 0.15.1?

**Comment by ssanderson** [comment]
@Nickleaton I think this is the same issue as https://github.com/quantopian/zipline/issues/823, which was fixed by https://github.com/quantopian/zipline/pull/825 on master.  @richafrank @llllllllll any ideas when we plan on shipping 0.8.4?

**Comment by Nickleaton** [comment]
Am I right in thinking that its a mess? Particularly if you haven't managed to set up a C++ build set up on windows? ie. Not necessarily a zip line issue.

**Comment by ssanderson** [comment]
> Am I right in thinking that its a mess?

I assume by "it", you mean "installing Zipline one Windows"?  Installing Zipline on Linux and OSX is pretty reliable and straightforward.  Windows is definitely a hairier beast, and none of the core developers are Windows users, so there hasn't been a ton of development effort spent on streamlining that process.

The particular issue linked here, namely that the latest PyPI release is tagged to exact versions of dependencies, affects all platforms equally, but it's fixed on master.

**Comment by richafrank** [comment]
@ssanderson We were thinking about monthly releases, but if there are important changes, we could release sooner.
