### ISSUE TITLE
record() with minute data

### ISSUE THREAD

**Issue by warren-oneill** [quantopian/zipline#865]
when record() used on minute data only one value is recorded per day. Is it possible to record all prices and not just a daily price?

**Comment by richafrank** [comment]
Hi @warren-oneill , `record` stores one value per key (i.e. in a dict), and those values are emitted according to the simulation's emission_rate ('minute' or 'daily').  If you're emitting daily, then to store multiple values in the dict over the course of the simulation day, I think you'll need to aggregate the data yourself, and each aggregate value will overwrite the previous one.

If I have an algo with the following, then I see performance packets with `{'daily_perf': {'recorded_vars': {'test': [0, 1, ..., 389]}}}` emitted each day:

```python
from zipline.api import record

def initialize(context):
    pass

def before_trading_start(context, data):
    context.all_values = []

def handle_data(context, data):
    context.all_values.append(len(context.all_values))
    record(test=context.all_values)  # not actually necessary after the first call
```

**Comment by ssanderson** [comment]
Closing this as nothing to be done.  @warren-oneill if you think there's a change that should be made here, feel free to reopen.
