### ISSUE TITLE
Refactor Data Loader for Alternate Pricing API Use

### ISSUE THREAD

**Issue by cyniphile** [quantopian/zipline#889]
Right now `loader.py` has `DataReader(stock, 'yahoo', start, end)` sprinkled in it, but it would be great to  easily pass a dataloader function to fetch pricing from other APIs. `_load_raw_yahoo_data` becomes `_load_raw_data` with an additional `source` kwarg for passing in a loading function that returns pricing data formatted just like yahoo api data. I've had to implement this already for my own use.

**Comment by ssanderson** [comment]
@cyniphile can you provide an example of another data source you'd like to be able to load from via a reader?

**Comment by cyniphile** [comment]
Any EOD pricing API that is not yahoo; it could be Bloomberg, Barchart, Xignite.

**Comment by michaeljohnbennett** [comment]
You also have CSI and metastock as well.

**Comment by llllllllll** [comment]
There is new API for ingesting data for use in zipline. For information about how to use this api or add your own data, see: http://www.zipline.io/bundles.html
