### ISSUE TITLE
Get daily orders from Daily/Minute algo?

### ISSUE THREAD

**Issue by michaeljohnbennett** [quantopian/zipline#899]
Is it possible to output the orders from the system easily to a log file or similar (or where can I get them from the performance or order manager API's)

Been scratching my head trying to figure out a nice way to get it but I'm stuck, any help would be appreciated.

Thanks

**Comment by twiecki** [comment]
You can check how pyfolio extracts these: https://github.com/quantopian/pyfolio/blob/master/pyfolio/utils.py#L320

**Comment by michaeljohnbennett** [comment]
thanks so much @twiecki :+1:
