### ISSUE TITLE
error pip installing zipline on MacOSX

### ISSUE THREAD

**Issue by jxstanford** [quantopian/zipline#930]
I get the following error when running `pip install zipline`:

```
Collecting bcolz==0.10.0 (from zipline)
  Using cached bcolz-0.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    * Found Cython 0.23.4 package installed.
    .. ERROR:: You need numpy 1.7 or greater to run bcolz!
```

`pip freeze | grep numpy` shows:

```
numpy==1.10.2
```

**Comment by jxstanford** [comment]
I eventually got zipline installed by creating a new virtualenv, and manually pip installing numpy==1.7.

**Comment by richafrank** [comment]
Glad you fixed it!  Looks like bcolz fixed [this bug] (https://github.com/Blosc/bcolz/pull/276) in its numpy version comparison in version 0.12.0.

**Comment by kovek** [comment]
`pip install zipline`  does `Collecting bcolz==0.10.0 (from zipline)`

Maybe then etc/requirements.txt should be modified from 
bcolz==0.10.0 to
bcolz==0.12.0
