### ISSUE TITLE
Passing code as command line argument 

### ISSUE THREAD

**Issue by Immortalin** [quantopian/zipline#945]
Is there a way to run code by passing it to `run_algo.py` as command line arguments?  E.g. for a normal python interpreter you could do something like `python -c "print("hello world")`. This is because the environment which I am running zipline in doesn't allow writing to disk and hence I have to pass generated code etc. via command line arguments.

**Comment by llllllllll** [comment]
You can do this with standard bash syntax for process substitution on the file argument. For example:

```bash
$ run_algo.py -f <(echo "initialize = lambda context: print('test');handle_data = lambda context, data: None")
```

The body of the subshell can be any command. This works by taking the output of the command and writing it to a temporary fifo. The program will see this as `/dev/fd/<n>`.
