### ISSUE TITLE
Performance degradation with pandas 0.17.1 

### ISSUE THREAD

**Issue by ljw2602** [quantopian/zipline#946]
(copied from google group)

Hi,

I installed zipline and tried to run the moving average example codes. However, it takes more than 25 mins to complete it. (and I specified frequency as daily)
I reduced the length of backtesting time window from 14 years to only a couple years, but it didn't affect the total running time much.

Can you explain why it takes so long time?
Is there any way to reduce it? For example, in Quantopian, running algorithm (not full backtesting) is pretty fast, which is good for debugging.

Best,

**Comment by ssanderson** [comment]
@ljw2602 that sounds unusually slow.  Are you running in an environment with a particularly slow internet connection?  By default the examples generally download data from Yahoo Finance and the US Treasury site.  If you're on a slow connection, that can potentially take quite a while.

**Comment by ljw2602** [comment]
(copied from the answer of lsyinubc@gmail.com from google group)

"what was the version of pandas in your environment ?
I upgraded pandas to 0.17 and had the same issue, after I downgraded it to 0.16, everything is fine, the moving average example took ~30 secs."

My pandas version was 0.17.1, and I downgraded to 0.16.2.
I observed two significant improvements
1) zipline installation time decreased to only a few seconds
2) dual moving MA examples (and other ones too) are completed in only a few seconds

So.. I don't know why the lower version of pandas makes everything around 100 times faster, but my problem solved!

**Comment by richafrank** [comment]
Glad you solved your issue @ljw2602.  I'm going leave this open for us to add support for newer versions of pandas without performance degradation, since other people will likely encounter the same issue.

**Comment by SlyOne** [comment]
ZIpline 0.8.3 wont install with pandas 17.1 --- Data reader problem??

**Comment by richafrank** [comment]
Fixed by #969.
