### ISSUE TITLE
short term treasury as an asset

### ISSUE THREAD

**Issue by ljw2602** [quantopian/zipline#952]
I was wondering if there is a way to treat short-term treasury (e.g. 1month or 3month) as an asset. I guess the cached treasury data is used only in calculation of risk metrics (e.g. sharp ratio), but I was wondering if I can use it in trading session too.

For example, when I decrease the portfolio weight to zero (no investment in equities), the portfolio return becomes zero, but I want it to be the return of short-term treasury.

I know there are bond ETFs, but their history is pretty short (~ 10years). I wanted to run backtests for a much longer period.

**Comment by llllllllll** [comment]
Right now we only support Equities and Futures as asset types in your simulation. This is an interesting idea that we could try to support in the future. We would be open to a pull request that adds this feature if you would like to contribute.

**Comment by ljw2602** [comment]
Sounds like a plan. I will work on it.

**Comment by ssanderson** [comment]
I think it's unlikely that we're going to add support for this any time soon.
