### ISSUE TITLE
`test_examples` creates `.pyc` files in zipline source root

### ISSUE THREAD

**Issue by ssanderson** [quantopian/zipline#968]
We call `imp.load_module` (which is deprecated) on the examples to run them as main, which leaves behind .pyc files in the cwd of the tests.

A better way to do this would be to use `runpy.run_path`. https://docs.python.org/2/library/runpy.html

**Comment by richafrank** [comment]
Looks like you did this @ssanderson : https://github.com/quantopian/zipline/commit/5f49fa22cb52bb139a5d5c4ff05f1b12884fe23f#diff-a7c0d292cdfcb6ed3888aba6eaaa50bbR23
