### ISSUE TITLE
Mismatched data/benchmark dates creates an error at the end of simulation

### ISSUE THREAD

**Issue by jlowin** [quantopian/zipline#971]
As described in [loader.py](https://github.com/quantopian/zipline/blob/master/zipline/data/loader.py#L157), benchmark returns are cut off 2 days before the current trading day. But if users run algorithms with a data source that includes the most recent trading days, it creates an error during the risk calculations at the end of the simulation, because the "extra" day will get `nan` for the benchmark return.

It's happening this weekend: `zipline.data.load_from_yahoo()` is returning data through 1/21, but the last benchmark return from `loader.load_market_data` is 1/20.

**Comment by freddiev4** [comment]
The data is filled through the current trading day (x-ref https://github.com/quantopian/zipline/pull/2044) so going to close this; we also don't use `load_from_yahoo()` anymore.
