### ISSUE TITLE
Typo in MANIFEST.in

### ISSUE THREAD

**Issue by peteut** [quantopian/zipline#995]
`README.md` should read `README.rst`. 

```patch
From 3e548a1426935db13db3b72c77232b12c1b32173 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Alain=20P=C3=A9teut?= <alain.peteut@yahoo.com>
Date: Sat, 13 Feb 2016 23:11:31 +0100
Subject: [PATCH] fix README extension

---
 MANIFEST.in | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/MANIFEST.in b/MANIFEST.in
index a4790bd..5b24f45 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -1,4 +1,4 @@
-include README.md
+include README.rst
 include LICENSE
 
 include etc/requirements*.txt
-- 
2.1.4
```

**Comment by richafrank** [comment]
Thanks @peteut !  Did you find the reST file missing from the source distribution?  Looks like setuptools includes it implicitly, so I'm thinking we can just remove this line.

**Comment by peteut** [comment]
No, I just stumbled over it while working on my branch. It should be fine to remove it.

**Comment by richafrank** [comment]
Cool - done in https://github.com/quantopian/zipline/commit/62020f6529b906c14d8ac365ae965ce6bec613c0
